<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process">
  <process:MainProcess xmi:id="_wS6UQIaSEeSMzJufh3GDGA" name="Projet_Validation_Diagram_CORTES_MARTINEZ" version="4.0" author="corteshs" bonitaVersion="6.3.8" bonitaModelVersion="6.3.8-001" configId="ACED000574003750726F6A65745F56616C69646174696F6E5F4469616772616D5F434F525445535F4D415254494E455A362E332E382D303031362E332E38">
    <elements xsi:type="process:Pool" xmi:id="_wS6UQYaSEeSMzJufh3GDGA" name="Projet_Validation_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="4.0">
      <elements xsi:type="process:Lane" xmi:id="_wS6UQoaSEeSMzJufh3GDGA" name="Employé (lane)" actor="_wS68I4aSEeSMzJufh3GDGA">
        <elements xsi:type="process:Task" xmi:id="_wS6UQ4aSEeSMzJufh3GDGA" name="Approve proposal" outgoing="_wS68CoaSEeSMzJufh3GDGA" incoming="_wS679YaSEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_wS6URIaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_wS6URYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_wS6URoaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_wS6UR4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_wS6USIaSEeSMzJufh3GDGA">
            <cardinality xmi:id="_gPx_4JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gPx_4ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <BoundaryIntermediateEvents xsi:type="process:BoundaryTimerEvent" xmi:id="_42oo0IaSEeSMzJufh3GDGA" name="BoundaryTimerEvent" outgoing="_E-B4cIaTEeSMzJufh3GDGA">
            <condition xmi:id="_gPx_7pXdEeSroeU30tgKmw" name="5 Jours 00:00:00" content="432000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long">
              <referencedElements xsi:type="process:Data" xmi:id="_gPx_75XdEeSroeU30tgKmw" name="proposalOK" dataType="_wS68oYaSEeSMzJufh3GDGA"/>
            </condition>
          </BoundaryIntermediateEvents>
          <loopCondition xmi:id="_wS6US4aSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_wS6UTIaSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_wS6UTYaSEeSMzJufh3GDGA" name="ApproveProposal" nLine="3">
            <widgets xsi:type="form:CheckBoxSingleFormField" xmi:id="_wS6UToaSEeSMzJufh3GDGA" name="proposalOK1">
              <widgetLayoutInfo xmi:id="_wS6UT4aSEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gP24cpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gP24c5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gP24dJXdEeSroeU30tgKmw" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xsi:type="process:Data" xmi:id="_gP24dZXdEeSroeU30tgKmw" name="proposalOK" dataType="_wS68oYaSEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gP24dpXdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_wS6UVoaSEeSMzJufh3GDGA">
                <leftOperand xmi:id="_gP3fiJXdEeSroeU30tgKmw" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="process:Data" xmi:id="_gP3fiZXdEeSroeU30tgKmw" name="proposalOK" dataType="_wS68oYaSEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_wS6UWoaSEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_gP3fipXdEeSroeU30tgKmw" name="field_proposalOK1" content="field_proposalOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="form:CheckBoxSingleFormField" xmi:id="_gP3fi5XdEeSroeU30tgKmw" name="proposalOK1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_gP24d5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gP24eJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_gP24eZXdEeSroeU30tgKmw" name="Approved?" content="Approved?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gP24epXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_gP24fJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_gP3fcJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_gP3fcZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_gP3fcpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_gP3fc5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_gP3fdJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_gP3fdZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_wS6UfoaSEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_gP4GgJXdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:id="_gP4GgZXdEeSroeU30tgKmw" name="OK" content="OK" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gP4GgpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_wS6UgoaSEeSMzJufh3GDGA" name="proposal1">
              <widgetLayoutInfo xmi:id="_gP4GjJXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gP4GjZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gP4GjpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gP4Gj5XdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_gP4GkJXdEeSroeU30tgKmw" name="proposal" dataType="_wS68poaSEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gP4GkZXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_gP4GkpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gP4Gk5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gP4GlJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_gP24Y5XdEeSroeU30tgKmw" name="Approve proposal" content="Approve proposal" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_wS6UjoaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_wS6Uj4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:StartEvent" xmi:id="_wS6UkIaSEeSMzJufh3GDGA" name="Proposal made" outgoing="_wS679YaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP4tnpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP4tn5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP4toJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP4toZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_wS6UlYaSEeSMzJufh3GDGA" name="Analyze Impact" outgoing="_wS67-4aSEeSMzJufh3GDGA" incoming="_wS67-IaSEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_wS6UloaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_wS6Ul4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_wS6UmIaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_wS6UmYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_wS6UmoaSEeSMzJufh3GDGA">
            <cardinality xmi:id="_gPx_4pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gPx_45XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_wS6UnYaSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_wS6UnoaSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_wS6Un4aSEeSMzJufh3GDGA" name="AnalyzeImpact" nLine="3">
            <widgets xsi:type="form:TextFormField" xmi:id="_wS6UoIaSEeSMzJufh3GDGA" name="impacts1">
              <widgetLayoutInfo xmi:id="_gP4tppXdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gP4tp5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gP4tqJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gP4tqZXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_gP4tqpXdEeSroeU30tgKmw" name="impacts" dataType="_wS68poaSEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gP4tq5XdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_gP4tsJXdEeSroeU30tgKmw">
                <leftOperand xmi:id="_gP4tsZXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                  <referencedElements xsi:type="process:Data" xmi:id="_gP4tspXdEeSroeU30tgKmw" name="impacts" dataType="_wS68poaSEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_gP4ttZXdEeSroeU30tgKmw" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_gP4ts5XdEeSroeU30tgKmw" name="field_impacts1" content="field_impacts1" type="TYPE_INPUT">
                  <referencedElements xsi:type="form:TextFormField" xmi:id="_gP4ttJXdEeSroeU30tgKmw" name="impacts1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_gP4trJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gP4trZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_gP4trpXdEeSroeU30tgKmw" name="Impact?" content="Impact?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gP4tr5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_gP4ttpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_gP4tt5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_gP4tuJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_gP4tuZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_gP4tupXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_gP4tu5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_gP4tvJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_wS6U0IaSEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_gP4Gg5XdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:id="_gP4GhJXdEeSroeU30tgKmw" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gP4GhZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_wS6U1IaSEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:id="_wS6U1YaSEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <htmlAttributes xmi:id="_wS6U1oaSEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <widgetLayoutInfo xmi:id="_gP4Gl5XdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gP4GmJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gP4GmZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gP4GmpXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_gP4Gm5XdEeSroeU30tgKmw" name="proposal" dataType="_wS68poaSEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gP4GnJXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_gP4GnZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gP4GnpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gP4Gn5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_gP24Z5XdEeSroeU30tgKmw" name="Analyze Impact" content="Analyze Impact" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_wS6U4oaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_wS6U44aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_wS6U5IaSEeSMzJufh3GDGA" name="Validate project" outgoing="_wS68FYaSEeSMzJufh3GDGA" incoming="_wS67-4aSEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_wS6U5YaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_wS6U5oaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_wS6U54aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_wS6U6IaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_wS6U6YaSEeSMzJufh3GDGA">
            <cardinality xmi:id="_gPx_5JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gPx_5ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_wS6U7IaSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_wS6U7YaSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_wS6U7oaSEeSMzJufh3GDGA" name="ValidateProject">
            <widgets xsi:type="form:CheckBoxSingleFormField" xmi:id="_wS6U74aSEeSMzJufh3GDGA" name="projectOK1">
              <widgetLayoutInfo xmi:id="_wS6U8IaSEeSMzJufh3GDGA" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gP3fd5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gP3feJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gP3feZXdEeSroeU30tgKmw" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xsi:type="process:Data" xmi:id="_gP3fepXdEeSroeU30tgKmw" name="projectOK" dataType="_wS68oYaSEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gP3fe5XdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_wS6U94aSEeSMzJufh3GDGA">
                <leftOperand xmi:id="_gP3fjZXdEeSroeU30tgKmw" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="process:Data" xmi:id="_gP3fjpXdEeSroeU30tgKmw" name="projectOK" dataType="_wS68oYaSEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_wS6U-4aSEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_gP3fj5XdEeSroeU30tgKmw" name="field_projectOK1" content="field_projectOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="form:CheckBoxSingleFormField" xmi:id="_gP3fkJXdEeSroeU30tgKmw" name="projectOK1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_gP3ffJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gP3ffZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_gP3ffpXdEeSroeU30tgKmw" name="Approve project?" content="Approve project?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gP3ff5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_gP3fgZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_gP3fgpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_gP3fg5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_gP3fhJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_gP3fhZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_gP3fhpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_gP3fh5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_wS6VH4aSEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_gP4GhpXdEeSroeU30tgKmw" line="3"/>
              <displayLabel xmi:id="_gP4Gh5XdEeSroeU30tgKmw" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gP4GiJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_wS6VI4aSEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:id="_wS6VJIaSEeSMzJufh3GDGA" key="input_css:color" value="purple"/>
              <htmlAttributes xmi:id="_wS6VJYaSEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <htmlAttributes xmi:id="_wS6VJoaSEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <widgetLayoutInfo xmi:id="_gP4Go5XdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gP4GpJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gP4GpZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gP4GppXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_gP4Gp5XdEeSroeU30tgKmw" name="proposal" dataType="_wS68poaSEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gP4GqJXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_gP4GqZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gP4GqpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gP4Gq5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_wS6VMYaSEeSMzJufh3GDGA" name="impacts1">
              <htmlAttributes xmi:id="_wS6VMoaSEeSMzJufh3GDGA" key="input_css:color" value="red"/>
              <htmlAttributes xmi:id="_wS6VM4aSEeSMzJufh3GDGA" key="input_css:font-size" value="18px"/>
              <widgetLayoutInfo xmi:id="_gP4GrpXdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gP4Gr5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gP4GsJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gP4GsZXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_gP4GspXdEeSroeU30tgKmw" name="impacts" dataType="_wS68poaSEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gP4Gs5XdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_gP4GtJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gP4GtZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gP4GtpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_gP24bJXdEeSroeU30tgKmw" name="Validate project" content="Validate project" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_wS6VP4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_wS6VQIaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_wS6VQYaSEeSMzJufh3GDGA" name="Proposal refused" incoming="_wS68BIaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP5UoJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP5UoZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP5UopXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP5Uo5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_wS6VRoaSEeSMzJufh3GDGA" name="Project finished" incoming="_wS68IIaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP5UpJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP5UpZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP5UppXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP5Up5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_wS6VS4aSEeSMzJufh3GDGA" name="Project refused" incoming="_wS68B4aSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP5UqJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP5UqZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP5UqpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP5Uq5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:XORGateway" xmi:id="_wS67UYaSEeSMzJufh3GDGA" name="Project approval?" outgoing="_wS68GIaSEeSMzJufh3GDGA _wS68HYaSEeSMzJufh3GDGA" incoming="_wS68FYaSEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:id="_gP5UsJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP5UsZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP5UspXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP5Us5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:XORGateway" xmi:id="_wS67VoaSEeSMzJufh3GDGA" name="5 days?" outgoing="_wS68DYaSEeSMzJufh3GDGA _wS68EoaSEeSMzJufh3GDGA" incoming="_wS68CoaSEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:id="_gP5UtJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP5UtZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP5UtpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP5Ut5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_wS67W4aSEeSMzJufh3GDGA" name="Notify proposal aproved" outgoing="_wS67-IaSEeSMzJufh3GDGA" incoming="_wS68DYaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP5UuJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP5UuZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP5UupXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP5Uu5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gP5UvJXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gP57sJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gP57sZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gP57spXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gP57s5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_wS67ZYaSEeSMzJufh3GDGA" name="Notify proposal refusal" outgoing="_wS68BIaSEeSMzJufh3GDGA" incoming="_wS68EoaSEeSMzJufh3GDGA _E-B4cIaTEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP57tJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP57tZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP57tpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP57t5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gP57uJXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gP57uZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gP57upXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gP57u5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gP57vJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_wS67b4aSEeSMzJufh3GDGA" name="Notify project refused" outgoing="_wS68B4aSEeSMzJufh3GDGA" incoming="_wS68HYaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP57vZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP57vpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP57v5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP57wJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gP57wZXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gP57wpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gP57w5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gP57xJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gP57xZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_wS67eYaSEeSMzJufh3GDGA" name="Notify project accepted" outgoing="_wS67_oaSEeSMzJufh3GDGA" incoming="_wS68GIaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP57xpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP57x5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP57yJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP57yZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gP57ypXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gP57y5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gP57zJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gP57zZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gP57zpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_wS67g4aSEeSMzJufh3GDGA" name="Notify project delivery" outgoing="_wS68IIaSEeSMzJufh3GDGA" incoming="_wS68AYaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP57z5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP570JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP570ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP570pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gP5705XdEeSroeU30tgKmw">
            <cardinality xmi:id="_gP571JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gP571ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gP571pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gP5715XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:CallActivity" xmi:id="_wS67jYaSEeSMzJufh3GDGA" name="Do project" outgoing="_wS68AYaSEeSMzJufh3GDGA" incoming="_wS67_oaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP572JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP572ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP572pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP5725XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gP573JXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gP573ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gP573pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gP5735XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gP574JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <inputMappings xmi:id="_wS67l4aSEeSMzJufh3GDGA" processSource="_wS67qIaSEeSMzJufh3GDGA" subprocessTarget="sub_proposal"/>
          <inputMappings xmi:id="_wS67mIaSEeSMzJufh3GDGA" processSource="_wS67qoaSEeSMzJufh3GDGA" subprocessTarget="sub_proposalOK"/>
          <inputMappings xmi:id="_wS67mYaSEeSMzJufh3GDGA" processSource="_wS67rIaSEeSMzJufh3GDGA" subprocessTarget="sub_projectOK"/>
          <inputMappings xmi:id="_wS67moaSEeSMzJufh3GDGA" processSource="_wS67roaSEeSMzJufh3GDGA" subprocessTarget="sub_impacts"/>
          <outputMappings xmi:id="_wS67m4aSEeSMzJufh3GDGA" subprocessSource="sub_proposal" processTarget="_wS67qIaSEeSMzJufh3GDGA"/>
          <outputMappings xmi:id="_wS67nIaSEeSMzJufh3GDGA" subprocessSource="sub_proposalOK" processTarget="_wS67qoaSEeSMzJufh3GDGA"/>
          <outputMappings xmi:id="_wS67nYaSEeSMzJufh3GDGA" subprocessSource="sub_projectOK" processTarget="_wS67rIaSEeSMzJufh3GDGA"/>
          <outputMappings xmi:id="_wS67noaSEeSMzJufh3GDGA" subprocessSource="sub_impacts" processTarget="_wS67roaSEeSMzJufh3GDGA"/>
          <calledActivityName xmi:id="_gP576ZXdEeSroeU30tgKmw" name="Do_project_CORTES_MARTINEZ" content="Do_project_CORTES_MARTINEZ" returnTypeFixed="true"/>
          <calledActivityVersion xmi:id="_gP576pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:id="_wXR24IaSEeSMzJufh3GDGA" path="_wS6UQYaSEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:id="_wS67ooaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_wS67o4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_wS67pIaSEeSMzJufh3GDGA" path="_wS6UQYaSEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:id="_wS67pYaSEeSMzJufh3GDGA" path="_wS6UQYaSEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:id="_wS67poaSEeSMzJufh3GDGA" path="_wS6UQYaSEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:id="_wS67p4aSEeSMzJufh3GDGA" path="_wS6UQYaSEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:id="_wS67qIaSEeSMzJufh3GDGA" name="proposal" dataType="_wS68poaSEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gPym8JXdEeSroeU30tgKmw" content=""/>
      </data>
      <data xmi:id="_wS67qoaSEeSMzJufh3GDGA" name="proposalOK" dataType="_wS68oYaSEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gPym8ZXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_wS67rIaSEeSMzJufh3GDGA" name="projectOK" dataType="_wS68oYaSEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gPym8pXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_wS67roaSEeSMzJufh3GDGA" name="impacts" dataType="_wS68poaSEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gPym85XdEeSroeU30tgKmw" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <form xmi:id="_wS67sIaSEeSMzJufh3GDGA" name="Project_Validation_CORTES_MARTINEZ" nLine="3">
        <widgets xsi:type="form:TextFormField" xmi:id="_wS67sYaSEeSMzJufh3GDGA" name="proposal1">
          <widgetLayoutInfo xmi:id="_gP4tvZXdEeSroeU30tgKmw" line="1"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gP4tvpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:id="_gP4tv5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:id="_gP4twJXdEeSroeU30tgKmw" name="" content=""/>
          <afterEventExpression xmi:id="_gP4twZXdEeSroeU30tgKmw" name="" content=""/>
          <action xmi:id="_gP4txpXdEeSroeU30tgKmw">
            <leftOperand xmi:id="_gP4tx5XdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
              <referencedElements xsi:type="process:Data" xmi:id="_gP4tyJXdEeSroeU30tgKmw" name="proposal" dataType="_wS68poaSEeSMzJufh3GDGA"/>
            </leftOperand>
            <operator xmi:id="_gP4ty5XdEeSroeU30tgKmw" type="ASSIGNMENT"/>
            <rightOperand xmi:id="_gP4tyZXdEeSroeU30tgKmw" name="field_proposal1" content="field_proposal1" type="TYPE_INPUT">
              <referencedElements xsi:type="form:TextFormField" xmi:id="_gP4typXdEeSroeU30tgKmw" name="proposal1"/>
            </rightOperand>
          </action>
          <tooltip xmi:id="_gP4twpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:id="_gP4tw5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:id="_gP4txJXdEeSroeU30tgKmw" name="Proposal" content="Proposal" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_gP4txZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <maxNumberOfDuplication xmi:id="_gP4tzJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:id="_gP4tzZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <displayLabelForAdd xmi:id="_gP4tzpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <tooltipForAdd xmi:id="_gP4tz5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabelForRemove xmi:id="_gP4t0JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <tooltipForRemove xmi:id="_gP4t0ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <exampleMessage xmi:id="_gP4t0pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </widgets>
        <widgets xsi:type="form:SubmitFormButton" xmi:id="_wS673YaSEeSMzJufh3GDGA" name="Soumettre1">
          <widgetLayoutInfo xmi:id="_gP4GiZXdEeSroeU30tgKmw" line="2"/>
          <displayLabel xmi:id="_gP4GipXdEeSroeU30tgKmw" name="OK" content="OK" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_gP4Gi5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <widgets xsi:type="form:MessageInfo" xmi:id="_wS674YaSEeSMzJufh3GDGA" name="Enter proposal:">
          <htmlAttributes xmi:id="_wS674oaSEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
          <widgetLayoutInfo xmi:id="_gP4tkZXdEeSroeU30tgKmw"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gP4tkpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:id="_gP4tk5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:id="_gP4tlJXdEeSroeU30tgKmw" name="" content=""/>
          <afterEventExpression xmi:id="_gP4tlZXdEeSroeU30tgKmw" name="" content=""/>
          <action xmi:id="_gP4tmpXdEeSroeU30tgKmw">
            <leftOperand xmi:id="_gP4tm5XdEeSroeU30tgKmw"/>
            <operator xmi:id="_gP4tnZXdEeSroeU30tgKmw" type="ASSIGNMENT" expression="="/>
            <rightOperand xmi:id="_gP4tnJXdEeSroeU30tgKmw"/>
          </action>
          <tooltip xmi:id="_gP4tlpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:id="_gP4tl5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:id="_gP4tmJXdEeSroeU30tgKmw" name="Message1" content="Message1" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_gP4tmZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:id="_gP24cJXdEeSroeU30tgKmw" name="Propose proposal" content="Propose proposal" returnTypeFixed="true"/>
      </form>
      <entryRedirectionURL xmi:id="_wS678YaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_wS678oaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_wS6784aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_wS679IaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS679YaSEeSMzJufh3GDGA" source="_wS6UkIaSEeSMzJufh3GDGA" target="_wS6UQ4aSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS679oaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6iwZXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS67-IaSEeSMzJufh3GDGA" source="_wS67W4aSEeSMzJufh3GDGA" target="_wS6UlYaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS67-YaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6iw5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS67-4aSEeSMzJufh3GDGA" source="_wS6UlYaSEeSMzJufh3GDGA" target="_wS6U5IaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS67_IaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6ixZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS67_oaSEeSMzJufh3GDGA" source="_wS67eYaSEeSMzJufh3GDGA" target="_wS67jYaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS67_4aSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6ix5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68AYaSEeSMzJufh3GDGA" source="_wS67jYaSEeSMzJufh3GDGA" target="_wS67g4aSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68AoaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6iyZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68BIaSEeSMzJufh3GDGA" source="_wS67ZYaSEeSMzJufh3GDGA" target="_wS6VQYaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68BYaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6iy5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68B4aSEeSMzJufh3GDGA" source="_wS67b4aSEeSMzJufh3GDGA" target="_wS6VS4aSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68CIaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6izZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68CoaSEeSMzJufh3GDGA" source="_wS6UQ4aSEeSMzJufh3GDGA" target="_wS67VoaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68C4aSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6iz5XdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68DYaSEeSMzJufh3GDGA" name="Approved" source="_wS67VoaSEeSMzJufh3GDGA" target="_wS67W4aSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68DoaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6i0ZXdEeSroeU30tgKmw" name="proposalOK==true" content="proposalOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xsi:type="process:Data" xmi:id="_gP6i0pXdEeSroeU30tgKmw" name="proposalOK" dataType="_wS68oYaSEeSMzJufh3GDGA"/>
        </condition>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68EoaSEeSMzJufh3GDGA" name="Not Approved" source="_wS67VoaSEeSMzJufh3GDGA" target="_wS67ZYaSEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:id="_wS68E4aSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6i1JXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68FYaSEeSMzJufh3GDGA" source="_wS6U5IaSEeSMzJufh3GDGA" target="_wS67UYaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68FoaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6i1pXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68GIaSEeSMzJufh3GDGA" name="Approved" source="_wS67UYaSEeSMzJufh3GDGA" target="_wS67eYaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68GYaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6i2JXdEeSroeU30tgKmw" name="projectOK==true" content="projectOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xsi:type="process:Data" xmi:id="_gP6i2ZXdEeSroeU30tgKmw" name="projectOK" dataType="_wS68oYaSEeSMzJufh3GDGA"/>
        </condition>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68HYaSEeSMzJufh3GDGA" name="Not approved" source="_wS67UYaSEeSMzJufh3GDGA" target="_wS67b4aSEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:id="_wS68HoaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP6i25XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68IIaSEeSMzJufh3GDGA" source="_wS67g4aSEeSMzJufh3GDGA" target="_wS6VRoaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68IYaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP7J0ZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_E-B4cIaTEeSMzJufh3GDGA" source="_42oo0IaSEeSMzJufh3GDGA" target="_wS67ZYaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_E-CfgIaTEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP7J05XdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:id="_wS68I4aSEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:id="_wS68JIaSEeSMzJufh3GDGA">
        <name xmi:id="_gP7J3pXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gP7J35XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_wS68J4aSEeSMzJufh3GDGA">
        <name xmi:id="_gP7J4JXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gP7J4ZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_wS68KoaSEeSMzJufh3GDGA">
        <name xmi:id="_gP7J4pXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gP7J45XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_wS68LYaSEeSMzJufh3GDGA">
        <name xmi:id="_gP7J5JXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gP7J5ZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_wS68MIaSEeSMzJufh3GDGA">
        <name xmi:id="_gP7J5pXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gP7J55XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xsi:type="process:Pool" xmi:id="_wS68M4aSEeSMzJufh3GDGA" name="Do_project_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="2.0">
      <elements xsi:type="process:Lane" xmi:id="_wS68NIaSEeSMzJufh3GDGA" name="Research and Development" actor="_wS68kYaSEeSMzJufh3GDGA">
        <elements xsi:type="process:Task" xmi:id="_wS68NYaSEeSMzJufh3GDGA" name="Deploy" outgoing="_wS68joaSEeSMzJufh3GDGA" incoming="_wS68i4aSEeSMzJufh3GDGA" actor="_wS68kYaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_wS68NoaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_wS68N4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_wS68OIaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_wS68OYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_wS68OoaSEeSMzJufh3GDGA">
            <cardinality xmi:id="_gPx_5pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gPx_55XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_wS68PYaSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_wS68PoaSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_wS68P4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_wS68QIaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:StartEvent" xmi:id="_wS68QYaSEeSMzJufh3GDGA" name="Start project" outgoing="_wS68goaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP4topXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP4to5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP4tpJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP4tpZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_wS68RoaSEeSMzJufh3GDGA" name="Project finished" incoming="_wS68joaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gP5UrJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gP5UrZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gP5UrpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gP5Ur5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_wS68S4aSEeSMzJufh3GDGA" name="Specify" outgoing="_wS68hYaSEeSMzJufh3GDGA" incoming="_wS68goaSEeSMzJufh3GDGA" actor="_wS68kYaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_wS68TIaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_wS68TYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_wS68ToaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_wS68T4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_wS68UIaSEeSMzJufh3GDGA">
            <cardinality xmi:id="_gPx_6JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gPx_6ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_wS68U4aSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_wS68VIaSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_wS68VYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_wS68VoaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_wS68V4aSEeSMzJufh3GDGA" name="Implement" outgoing="_wS68iIaSEeSMzJufh3GDGA" incoming="_wS68hYaSEeSMzJufh3GDGA" actor="_wS68kYaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_wS68WIaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_wS68WYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_wS68WoaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_wS68W4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_wS68XIaSEeSMzJufh3GDGA">
            <cardinality xmi:id="_gPx_6pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gPx_65XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_wS68X4aSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_wS68YIaSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_wS68YYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_wS68YoaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_wS68Y4aSEeSMzJufh3GDGA" name="Test" outgoing="_wS68i4aSEeSMzJufh3GDGA" incoming="_wS68iIaSEeSMzJufh3GDGA" actor="_wS68kYaSEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_wS68ZIaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_wS68ZYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_wS68ZoaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_wS68Z4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_wS68aIaSEeSMzJufh3GDGA">
            <cardinality xmi:id="_gPx_7JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gPx_7ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_wS68a4aSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_wS68bIaSEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_wS68bYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_wS68boaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:id="_wazE8IaSEeSMzJufh3GDGA" path="_wS68M4aSEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:id="_wS68cIaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_wS68cYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_wS68coaSEeSMzJufh3GDGA" path="_wS68M4aSEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:id="_wS68c4aSEeSMzJufh3GDGA" path="_wS68M4aSEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:id="_wS68dIaSEeSMzJufh3GDGA" path="_wS68M4aSEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:id="_wS68dYaSEeSMzJufh3GDGA" path="_wS68M4aSEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:id="_wS68doaSEeSMzJufh3GDGA" name="sub_proposal" dataType="_wS68poaSEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gPz1EJXdEeSroeU30tgKmw" content=""/>
      </data>
      <data xmi:id="_wS68eIaSEeSMzJufh3GDGA" name="sub_proposalOK" dataType="_wS68oYaSEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gPz1EZXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_wS68eoaSEeSMzJufh3GDGA" name="sub_projectOK" dataType="_wS68oYaSEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gP1DMJXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_wS68fIaSEeSMzJufh3GDGA" name="sub_impacts" dataType="_wS68poaSEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gP2RUJXdEeSroeU30tgKmw" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <entryRedirectionURL xmi:id="_wS68foaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_wS68f4aSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_wS68gIaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_wS68gYaSEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68goaSEeSMzJufh3GDGA" source="_wS68QYaSEeSMzJufh3GDGA" target="_wS68S4aSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68g4aSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP7J1ZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68hYaSEeSMzJufh3GDGA" source="_wS68S4aSEeSMzJufh3GDGA" target="_wS68V4aSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68hoaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP7J15XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68iIaSEeSMzJufh3GDGA" source="_wS68V4aSEeSMzJufh3GDGA" target="_wS68Y4aSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68iYaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP7J2ZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68i4aSEeSMzJufh3GDGA" source="_wS68Y4aSEeSMzJufh3GDGA" target="_wS68NYaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68jIaSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP7J25XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_wS68joaSEeSMzJufh3GDGA" source="_wS68NYaSEeSMzJufh3GDGA" target="_wS68RoaSEeSMzJufh3GDGA">
        <decisionTable xmi:id="_wS68j4aSEeSMzJufh3GDGA"/>
        <condition xmi:id="_gP7J3ZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:id="_wS68kYaSEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:id="_wS68koaSEeSMzJufh3GDGA">
        <name xmi:id="_gP7J6JXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gP7J6ZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_wS68lYaSEeSMzJufh3GDGA">
        <name xmi:id="_gP7J6pXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gP7J65XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_wS68mIaSEeSMzJufh3GDGA">
        <name xmi:id="_gP7J7JXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gP7J7ZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_wS68m4aSEeSMzJufh3GDGA">
        <name xmi:id="_gP7J7pXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gP7J75XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_wS68noaSEeSMzJufh3GDGA">
        <name xmi:id="_gP7J8JXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gP7J8ZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xsi:type="process:BooleanType" xmi:id="_wS68oYaSEeSMzJufh3GDGA" name="Boolean"/>
    <datatypes xsi:type="process:DateType" xmi:id="_wS68ooaSEeSMzJufh3GDGA" name="Date"/>
    <datatypes xsi:type="process:IntegerType" xmi:id="_wS68o4aSEeSMzJufh3GDGA" name="Integer"/>
    <datatypes xsi:type="process:LongType" xmi:id="_wS68pIaSEeSMzJufh3GDGA" name="Long"/>
    <datatypes xsi:type="process:DoubleType" xmi:id="_wS68pYaSEeSMzJufh3GDGA" name="Double"/>
    <datatypes xsi:type="process:StringType" xmi:id="_wS68poaSEeSMzJufh3GDGA" name="Text"/>
    <datatypes xsi:type="process:JavaType" xmi:id="_wS68p4aSEeSMzJufh3GDGA" name="Java_object"/>
    <datatypes xsi:type="process:XMLType" xmi:id="_wS68qIaSEeSMzJufh3GDGA" name="XML"/>
    <datatypes xsi:type="process:BusinessObjectType" xmi:id="_gPqEIJXdEeSroeU30tgKmw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_wS68qYaSEeSMzJufh3GDGA" type="Process" element="_wS6UQIaSEeSMzJufh3GDGA" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:id="_wS68qoaSEeSMzJufh3GDGA" type="2007" element="_wS6UQYaSEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_wS68q4aSEeSMzJufh3GDGA" type="5008" element="_wS6UQYaSEeSMzJufh3GDGA"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_wS68rIaSEeSMzJufh3GDGA" type="7001" element="_wS6UQYaSEeSMzJufh3GDGA">
        <children xmi:id="_gP8_BJXdEeSroeU30tgKmw" type="3007" element="_wS6UQoaSEeSMzJufh3GDGA">
          <children xsi:type="notation:DecorationNode" xmi:id="_wS68roaSEeSMzJufh3GDGA" type="5007" element="_wS6UQoaSEeSMzJufh3GDGA"/>
          <children xsi:type="notation:DecorationNode" xmi:id="_wS68r4aSEeSMzJufh3GDGA" type="7002" element="_wS6UQoaSEeSMzJufh3GDGA">
            <children xsi:type="notation:Shape" xmi:id="_wS68sIaSEeSMzJufh3GDGA" type="3005" element="_wS6UQ4aSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP-0MJXdEeSroeU30tgKmw" type="5005" element="_wS6UQ4aSEeSMzJufh3GDGA"/>
              <children xsi:type="notation:Shape" xmi:id="_42p28IaSEeSMzJufh3GDGA" type="3043" element="_42oo0IaSEeSMzJufh3GDGA" fontName="Sans">
                <children xsi:type="notation:DecorationNode" xmi:id="_gP-0M5XdEeSroeU30tgKmw" type="5055" element="_42oo0IaSEeSMzJufh3GDGA">
                  <layoutConstraint xsi:type="notation:Location" xmi:id="_42p284aSEeSMzJufh3GDGA" y="5"/>
                </children>
                <layoutConstraint xsi:type="notation:Bounds" xmi:id="_42p28YaSEeSMzJufh3GDGA"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS68soaSEeSMzJufh3GDGA" x="119" y="165"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS68s4aSEeSMzJufh3GDGA" type="3002" element="_wS6UkIaSEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP-0NpXdEeSroeU30tgKmw" type="5024" element="_wS6UkIaSEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_wS68tYaSEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS68toaSEeSMzJufh3GDGA" x="40" y="179"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS68t4aSEeSMzJufh3GDGA" type="3005" element="_wS6UlYaSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP-0OZXdEeSroeU30tgKmw" type="5005" element="_wS6UlYaSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS68uYaSEeSMzJufh3GDGA" x="421" y="102"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS68uoaSEeSMzJufh3GDGA" type="3005" element="_wS6U5IaSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bQJXdEeSroeU30tgKmw" type="5005" element="_wS6U5IaSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS68vIaSEeSMzJufh3GDGA" x="556" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS68vYaSEeSMzJufh3GDGA" type="3062" element="_wS6VQYaSEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bQpXdEeSroeU30tgKmw" type="5090" element="_wS6VQYaSEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_wS68v4aSEeSMzJufh3GDGA" x="-1" y="18"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS68wIaSEeSMzJufh3GDGA" x="537" y="197"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS68wYaSEeSMzJufh3GDGA" type="3062" element="_wS6VRoaSEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bRZXdEeSroeU30tgKmw" type="5090" element="_wS6VRoaSEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_wS68w4aSEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS68xIaSEeSMzJufh3GDGA" x="1221" y="136"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS68xYaSEeSMzJufh3GDGA" type="3062" element="_wS6VS4aSEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bSJXdEeSroeU30tgKmw" type="5090" element="_wS6VS4aSEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_wS68x4aSEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS68yIaSEeSMzJufh3GDGA" x="1012" y="226"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS68yYaSEeSMzJufh3GDGA" type="3008" element="_wS67UYaSEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bS5XdEeSroeU30tgKmw" type="5026" element="_wS67UYaSEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_wS68y4aSEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS68zIaSEeSMzJufh3GDGA" x="689" y="105" width="43" height="43"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS68zYaSEeSMzJufh3GDGA" type="3008" element="_wS67VoaSEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bTpXdEeSroeU30tgKmw" type="5026" element="_wS67VoaSEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_wS68z4aSEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS680IaSEeSMzJufh3GDGA" x="230" y="170" width="43" height="43"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS680YaSEeSMzJufh3GDGA" type="3027" element="_wS67W4aSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bUZXdEeSroeU30tgKmw" type="5017" element="_wS67W4aSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS6804aSEeSMzJufh3GDGA" x="271" y="95" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS681IaSEeSMzJufh3GDGA" type="3027" element="_wS67ZYaSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bU5XdEeSroeU30tgKmw" type="5017" element="_wS67ZYaSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS681oaSEeSMzJufh3GDGA" x="347" y="187" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS6814aSEeSMzJufh3GDGA" type="3027" element="_wS67b4aSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bVZXdEeSroeU30tgKmw" type="5017" element="_wS67b4aSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS682YaSEeSMzJufh3GDGA" x="765" y="192" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS682oaSEeSMzJufh3GDGA" type="3027" element="_wS67eYaSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bV5XdEeSroeU30tgKmw" type="5017" element="_wS67eYaSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS683IaSEeSMzJufh3GDGA" x="762" y="96" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS683YaSEeSMzJufh3GDGA" type="3027" element="_wS67g4aSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bWZXdEeSroeU30tgKmw" type="5017" element="_wS67g4aSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS6834aSEeSMzJufh3GDGA" x="1041" y="90" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS684IaSEeSMzJufh3GDGA" type="3063" element="_wS67jYaSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bW5XdEeSroeU30tgKmw" type="5093" element="_wS67jYaSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS684oaSEeSMzJufh3GDGA" x="913" y="125"/>
            </children>
          </children>
          <styles xsi:type="notation:DescriptionStyle" xmi:id="_wS6844aSEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FontStyle" xmi:id="_wS685IaSEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xsi:type="notation:LineStyle" xmi:id="_wS685YaSEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FillStyle" xmi:id="_wS685oaSEeSMzJufh3GDGA"/>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS6854aSEeSMzJufh3GDGA" x="45" y="10" width="1372" height="302"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_wS686IaSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_wS686YaSEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_wS686oaSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_wS6864aSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS687IaSEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_wS687YaSEeSMzJufh3GDGA" type="2007" element="_wS68M4aSEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_wS687oaSEeSMzJufh3GDGA" type="5008" element="_wS68M4aSEeSMzJufh3GDGA"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_wS6874aSEeSMzJufh3GDGA" type="7001" element="_wS68M4aSEeSMzJufh3GDGA">
        <children xmi:id="_gP9mG5XdEeSroeU30tgKmw" type="3007" element="_wS68NIaSEeSMzJufh3GDGA">
          <children xsi:type="notation:DecorationNode" xmi:id="_wS688YaSEeSMzJufh3GDGA" type="5007" element="_wS68NIaSEeSMzJufh3GDGA"/>
          <children xsi:type="notation:DecorationNode" xmi:id="_wS688oaSEeSMzJufh3GDGA" type="7002" element="_wS68NIaSEeSMzJufh3GDGA">
            <children xsi:type="notation:Shape" xmi:id="_wS6884aSEeSMzJufh3GDGA" type="3005" element="_wS68NYaSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bXZXdEeSroeU30tgKmw" type="5005" element="_wS68NYaSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS689YaSEeSMzJufh3GDGA" x="597" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS689oaSEeSMzJufh3GDGA" type="3002" element="_wS68QYaSEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bX5XdEeSroeU30tgKmw" type="5024" element="_wS68QYaSEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_wS68-IaSEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS68-YaSEeSMzJufh3GDGA" x="84" y="110"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS68-oaSEeSMzJufh3GDGA" type="3062" element="_wS68RoaSEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gP_bYpXdEeSroeU30tgKmw" type="5090" element="_wS68RoaSEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_wS68_IaSEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS68_YaSEeSMzJufh3GDGA" x="753" y="110"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS68_oaSEeSMzJufh3GDGA" type="3005" element="_wS68S4aSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gQACUJXdEeSroeU30tgKmw" type="5005" element="_wS68S4aSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69AIaSEeSMzJufh3GDGA" x="160" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS69AYaSEeSMzJufh3GDGA" type="3005" element="_wS68V4aSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gQACUpXdEeSroeU30tgKmw" type="5005" element="_wS68V4aSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69A4aSEeSMzJufh3GDGA" x="294" y="91" width="134" height="67"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_wS69BIaSEeSMzJufh3GDGA" type="3005" element="_wS68Y4aSEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gQACVJXdEeSroeU30tgKmw" type="5005" element="_wS68Y4aSEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69BoaSEeSMzJufh3GDGA" x="464" y="100"/>
            </children>
          </children>
          <styles xsi:type="notation:DescriptionStyle" xmi:id="_wS69B4aSEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FontStyle" xmi:id="_wS69CIaSEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xsi:type="notation:LineStyle" xmi:id="_wS69CYaSEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FillStyle" xmi:id="_wS69CoaSEeSMzJufh3GDGA"/>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69C4aSEeSMzJufh3GDGA" x="231" y="176"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_wS69DIaSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_wS69DYaSEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_wS69DoaSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_wS69D4aSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69EIaSEeSMzJufh3GDGA" width="1454" height="250"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_wS69EYaSEeSMzJufh3GDGA"/>
    <edges xsi:type="notation:Connector" xmi:id="_wS69EoaSEeSMzJufh3GDGA" type="4001" element="_wS679YaSEeSMzJufh3GDGA" source="_wS68s4aSEeSMzJufh3GDGA" target="_wS68sIaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQBQcJXdEeSroeU30tgKmw" type="6001" element="_wS679YaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQBQcZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQBQcpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69FoaSEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69F4aSEeSMzJufh3GDGA" type="4001" element="_wS67-IaSEeSMzJufh3GDGA" source="_wS680YaSEeSMzJufh3GDGA" target="_wS68t4aSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQBQdJXdEeSroeU30tgKmw" type="6001" element="_wS67-IaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQBQdZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQBQdpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69G4aSEeSMzJufh3GDGA" points="[0, 1, -66, -7]$[16, 1, -50, -7]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69HIaSEeSMzJufh3GDGA" id="(1.0,0.55)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69HYaSEeSMzJufh3GDGA" type="4001" element="_wS67-4aSEeSMzJufh3GDGA" source="_wS68t4aSEeSMzJufh3GDGA" target="_wS68uoaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQBQeZXdEeSroeU30tgKmw" type="6001" element="_wS67-4aSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQBQepXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQBQe5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69IYaSEeSMzJufh3GDGA" points="[0, 0, -41, 91]$[-9, -91, -50, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69IoaSEeSMzJufh3GDGA" id="(1.0,0.64)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69I4aSEeSMzJufh3GDGA" type="4001" element="_wS67_oaSEeSMzJufh3GDGA" source="_wS682oaSEeSMzJufh3GDGA" target="_wS684IaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQBQfpXdEeSroeU30tgKmw" type="6001" element="_wS67_oaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQBQf5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQBQgJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69J4aSEeSMzJufh3GDGA" points="[0, 0, -5, -60]$[55, 51, 50, -9]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69KIaSEeSMzJufh3GDGA" id="(1.0,0.5)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69KYaSEeSMzJufh3GDGA" type="4001" element="_wS68AYaSEeSMzJufh3GDGA" source="_wS684IaSEeSMzJufh3GDGA" target="_wS683YaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQBQg5XdEeSroeU30tgKmw" type="6001" element="_wS68AYaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQBQhJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQBQhZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69LYaSEeSMzJufh3GDGA" points="[0, 0, -60, 48]$[65, -35, 5, 13]"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69LoaSEeSMzJufh3GDGA" id="(0.5583333333333333,0.7833333333333333)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69L4aSEeSMzJufh3GDGA" type="4001" element="_wS68BIaSEeSMzJufh3GDGA" source="_wS681IaSEeSMzJufh3GDGA" target="_wS68vYaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQB3gJXdEeSroeU30tgKmw" type="6001" element="_wS68BIaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQB3gZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQB3gpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69M4aSEeSMzJufh3GDGA" points="[0, -8, -85, 2]$[78, 3, -7, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69NIaSEeSMzJufh3GDGA" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69NYaSEeSMzJufh3GDGA" type="4001" element="_wS68B4aSEeSMzJufh3GDGA" source="_wS6814aSEeSMzJufh3GDGA" target="_wS68xYaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQB3hZXdEeSroeU30tgKmw" type="6001" element="_wS68B4aSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQB3hpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQB3h5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69OYaSEeSMzJufh3GDGA" points="[0, 0, -142, -15]$[135, 28, -7, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69OoaSEeSMzJufh3GDGA" id="(1.0,0.5666666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69O4aSEeSMzJufh3GDGA" type="4001" element="_wS68CoaSEeSMzJufh3GDGA" source="_wS68sIaSEeSMzJufh3GDGA" target="_wS68zYaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQB3ipXdEeSroeU30tgKmw" type="6001" element="_wS68CoaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQB3i5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQB3jJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69P4aSEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69QIaSEeSMzJufh3GDGA" type="4001" element="_wS68DYaSEeSMzJufh3GDGA" source="_wS68zYaSEeSMzJufh3GDGA" target="_wS680YaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQB3jpXdEeSroeU30tgKmw" type="6001" element="_wS68DYaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQB3j5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQB3kJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69RIaSEeSMzJufh3GDGA" points="[-11, -22, -51, 47]$[42, -57, 2, 12]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69RYaSEeSMzJufh3GDGA" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69RoaSEeSMzJufh3GDGA" id="(0.5333333333333333,0.8)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69R4aSEeSMzJufh3GDGA" type="4001" element="_wS68EoaSEeSMzJufh3GDGA" source="_wS68zYaSEeSMzJufh3GDGA" target="_wS681IaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQB3lJXdEeSroeU30tgKmw" type="6001" element="_wS68EoaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQB3lZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQB3lpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69S4aSEeSMzJufh3GDGA" points="[-14, 1, -91, 0]$[52, -2, -25, -3]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69TIaSEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69TYaSEeSMzJufh3GDGA" id="(0.20833333333333334,0.45)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69ToaSEeSMzJufh3GDGA" type="4001" element="_wS68FYaSEeSMzJufh3GDGA" source="_wS68uoaSEeSMzJufh3GDGA" target="_wS68yYaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQB3mpXdEeSroeU30tgKmw" type="6001" element="_wS68FYaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQB3m5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQB3nJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69UoaSEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69U4aSEeSMzJufh3GDGA" id="(0.97,0.54)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69VIaSEeSMzJufh3GDGA" type="4001" element="_wS68GIaSEeSMzJufh3GDGA" source="_wS68yYaSEeSMzJufh3GDGA" target="_wS682oaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQCekJXdEeSroeU30tgKmw" type="6001" element="_wS68GIaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQCekZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQCekpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69WIaSEeSMzJufh3GDGA" points="[-11, -3, -65, 0]$[30, -1, -24, 2]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69WYaSEeSMzJufh3GDGA" id="(1.0,0.813953488372093)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69WoaSEeSMzJufh3GDGA" id="(0.025,0.18333333333333332)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69W4aSEeSMzJufh3GDGA" type="4001" element="_wS68HYaSEeSMzJufh3GDGA" source="_wS68yYaSEeSMzJufh3GDGA" target="_wS6814aSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQCelpXdEeSroeU30tgKmw" type="6001" element="_wS68HYaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQCel5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQCemJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69X4aSEeSMzJufh3GDGA" points="[-4, -10, -40, -95]$[33, 84, -3, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69YIaSEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69YYaSEeSMzJufh3GDGA" id="(0.025,0.4166666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69YoaSEeSMzJufh3GDGA" type="4001" element="_wS68IIaSEeSMzJufh3GDGA" source="_wS683YaSEeSMzJufh3GDGA" target="_wS68wYaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQCenJXdEeSroeU30tgKmw" type="6001" element="_wS68IIaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQCenZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQCenpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69ZoaSEeSMzJufh3GDGA" points="[0, 0, -75, -29]$[72, 14, -3, -15]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69Z4aSEeSMzJufh3GDGA" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69aIaSEeSMzJufh3GDGA" type="4001" element="_wS68goaSEeSMzJufh3GDGA" source="_wS689oaSEeSMzJufh3GDGA" target="_wS68_oaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQCeoZXdEeSroeU30tgKmw" type="6001" element="_wS68goaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQCeopXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQCeo5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69bIaSEeSMzJufh3GDGA" points="[-7, -2, -57, 0]$[46, -1, -4, 1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69bYaSEeSMzJufh3GDGA" id="(0.9666666666666667,0.5333333333333333)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69boaSEeSMzJufh3GDGA" id="(0.05,0.5)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69b4aSEeSMzJufh3GDGA" type="4001" element="_wS68hYaSEeSMzJufh3GDGA" source="_wS68_oaSEeSMzJufh3GDGA" target="_wS69AYaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQCep5XdEeSroeU30tgKmw" type="6001" element="_wS68hYaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQCeqJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQCeqZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69c4aSEeSMzJufh3GDGA" points="[0, -5, -35, 0]$[34, -6, -1, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69dIaSEeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69dYaSEeSMzJufh3GDGA" id="(0.007462686567164179,0.4925373134328358)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69doaSEeSMzJufh3GDGA" type="4001" element="_wS68iIaSEeSMzJufh3GDGA" source="_wS69AYaSEeSMzJufh3GDGA" target="_wS69BIaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQCerZXdEeSroeU30tgKmw" type="6001" element="_wS68iIaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQCerpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQDFoJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69eoaSEeSMzJufh3GDGA" points="[0, 1, -36, 0]$[36, 1, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69e4aSEeSMzJufh3GDGA" id="(1.0,0.4626865671641791)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69fIaSEeSMzJufh3GDGA" id="(0.0,0.46)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69fYaSEeSMzJufh3GDGA" type="4001" element="_wS68i4aSEeSMzJufh3GDGA" source="_wS69BIaSEeSMzJufh3GDGA" target="_wS6884aSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQDssJXdEeSroeU30tgKmw" type="6001" element="_wS68i4aSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQDssZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQDsspXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69gYaSEeSMzJufh3GDGA" points="[0, -6, -40, 0]$[33, -7, -7, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69goaSEeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69g4aSEeSMzJufh3GDGA" id="(0.07,0.46)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_wS69hIaSEeSMzJufh3GDGA" type="4001" element="_wS68joaSEeSMzJufh3GDGA" source="_wS6884aSEeSMzJufh3GDGA" target="_wS68-oaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQDstpXdEeSroeU30tgKmw" type="6001" element="_wS68joaSEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQDst5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQDsuJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_wS69iIaSEeSMzJufh3GDGA" points="[0, -3, -59, 0]$[56, -3, -3, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69iYaSEeSMzJufh3GDGA" id="(1.0,0.6)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_wS69ioaSEeSMzJufh3GDGA" id="(0.1,0.5666666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_E-DtoIaTEeSMzJufh3GDGA" type="4001" element="_E-B4cIaTEeSMzJufh3GDGA" source="_42p28IaSEeSMzJufh3GDGA" target="_wS681IaSEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQDsvJXdEeSroeU30tgKmw" type="6001" element="_E-B4cIaTEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gQDsvZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gQDsvpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_E-DtooaTEeSMzJufh3GDGA" points="[0, -1, -194, 0]$[187, 0, -7, 1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_E-Fi0IaTEeSMzJufh3GDGA" id="(1.0,1.0)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_E-Fi0YaTEeSMzJufh3GDGA" id="(0.058333333333333334,0.7333333333333333)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_wS69i4aSEeSMzJufh3GDGA" type="Form" element="_wS67sIaSEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_wS69jIaSEeSMzJufh3GDGA" type="2120" element="_wS67sYaSEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQACVpXdEeSroeU30tgKmw" type="5157" element="_wS67sYaSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69joaSEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_wS69j4aSEeSMzJufh3GDGA" type="2126" element="_wS673YaSEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_wS69kIaSEeSMzJufh3GDGA" type="5160" element="_wS673YaSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_wS69kYaSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_wS69koaSEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_wS69k4aSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69lIaSEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_wS69lYaSEeSMzJufh3GDGA" type="2131" element="_wS674YaSEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQACWJXdEeSroeU30tgKmw" type="5135" element="_wS674YaSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69l4aSEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_wS69mIaSEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_wS69mYaSEeSMzJufh3GDGA" type="Form" element="_wS6UTYaSEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_wS69moaSEeSMzJufh3GDGA" type="2130" element="_wS6UToaSEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQACWpXdEeSroeU30tgKmw" type="5148" element="_wS6UToaSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69nIaSEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_wS69nYaSEeSMzJufh3GDGA" type="2126" element="_wS6UfoaSEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_wS69noaSEeSMzJufh3GDGA" type="5160" element="_wS6UfoaSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_wS69n4aSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_wS69oIaSEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_wS69oYaSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69ooaSEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_wS69o4aSEeSMzJufh3GDGA" type="2131" element="_wS6UgoaSEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQACXJXdEeSroeU30tgKmw" type="5135" element="_wS6UgoaSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69pYaSEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_wS69poaSEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_wS69p4aSEeSMzJufh3GDGA" type="Form" element="_wS6Un4aSEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_wS69qIaSEeSMzJufh3GDGA" type="2120" element="_wS6UoIaSEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQACXpXdEeSroeU30tgKmw" type="5157" element="_wS6UoIaSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69qoaSEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_wS69q4aSEeSMzJufh3GDGA" type="2126" element="_wS6U0IaSEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_wS69rIaSEeSMzJufh3GDGA" type="5160" element="_wS6U0IaSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_wS69rYaSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_wS69roaSEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_wS69r4aSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69sIaSEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_wS69sYaSEeSMzJufh3GDGA" type="2131" element="_wS6U1IaSEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQACYJXdEeSroeU30tgKmw" type="5135" element="_wS6U1IaSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69s4aSEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_wS69tIaSEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_wS69tYaSEeSMzJufh3GDGA" type="Form" element="_wS6U7oaSEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_wS69toaSEeSMzJufh3GDGA" type="2130" element="_wS6U74aSEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQACYpXdEeSroeU30tgKmw" type="5148" element="_wS6U74aSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69uIaSEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_wS69uYaSEeSMzJufh3GDGA" type="2126" element="_wS6VH4aSEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_wS69uoaSEeSMzJufh3GDGA" type="5160" element="_wS6VH4aSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_wS69u4aSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_wS69vIaSEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_wS69vYaSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS69voaSEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_wS69v4aSEeSMzJufh3GDGA" type="2131" element="_wS6VI4aSEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQACZJXdEeSroeU30tgKmw" type="5135" element="_wS6VI4aSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS7iYIaSEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_wS7iYYaSEeSMzJufh3GDGA" type="2131" element="_wS6VMYaSEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQACZpXdEeSroeU30tgKmw" type="5135" element="_wS6VMYaSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS7iY4aSEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_wS7iZIaSEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_wS7iZYaSEeSMzJufh3GDGA" type="Form" measurementUnit="Pixel">
    <children xmi:id="_wS7iZoaSEeSMzJufh3GDGA" type="2126">
      <children xsi:type="notation:DecorationNode" xmi:id="_wS7iZ4aSEeSMzJufh3GDGA" type="5160"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_wS7iaIaSEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_wS7iaYaSEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_wS7iaoaSEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS7ia4aSEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_wS7ibIaSEeSMzJufh3GDGA" type="2131" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gQACaJXdEeSroeU30tgKmw" type="5135"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_wS7iboaSEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_wS7ib4aSEeSMzJufh3GDGA"/>
  </notation:Diagram>
</xmi:XMI>
