<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_AhxLsIaXEeSMzJufh3GDGA" name="Projet_Validation_Diagram_CORTES_MARTINEZ" version="6.0" author="corteshs" bonitaVersion="6.1.1" bonitaModelVersion="6.1.1-001" configId="ACED000574003750726F6A65745F56616C69646174696F6E5F4469616772616D5F434F525445535F4D415254494E455A362E312E312D303031362E312E31">
    <elements xmi:type="process:Pool" xmi:id="_AhxLsYaXEeSMzJufh3GDGA" name="Projet_Validation_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="6.0">
      <elements xmi:type="process:Lane" xmi:id="_AhxLsoaXEeSMzJufh3GDGA" name="Employé (lane)" actor="_AhxzfoaXEeSMzJufh3GDGA">
        <elements xmi:type="process:Task" xmi:id="_AhxLs4aXEeSMzJufh3GDGA" name="Approve proposal" outgoing="_AhxzXIaXEeSMzJufh3GDGA" incoming="_AhxzR4aXEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxLtIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxLtYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxLtoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxLt4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxLuIaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxLuYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxLuoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_AhxLu4aXEeSMzJufh3GDGA" name="BoundaryTimerEvent" outgoing="_AhxzdYaXEeSMzJufh3GDGA">
            <condition xmi:type="expression:Expression" xmi:id="_AhxLvIaXEeSMzJufh3GDGA" name="5 Jours 00:00:00" content="432000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long">
              <referencedElements xmi:type="process:Data" xmi:id="_AhxLvYaXEeSMzJufh3GDGA" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_AhxLvoaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
              </referencedElements>
            </condition>
          </BoundaryIntermediateEvents>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxLv4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AhxLwIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_AhxLwYaXEeSMzJufh3GDGA" name="ApproveProposal" nLine="3">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_AhxLwoaXEeSMzJufh3GDGA" name="proposalOK1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxLw4aXEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxLxIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxLxYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_AhxLxoaXEeSMzJufh3GDGA" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_AhxLx4aXEeSMzJufh3GDGA" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_AhxLyIaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxLyYaXEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_AhxLyoaXEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_AhxLy4aXEeSMzJufh3GDGA" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="_AhxLzIaXEeSMzJufh3GDGA" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_AhxLzYaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                  </referencedElements>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_AhxLzoaXEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_AhxLz4aXEeSMzJufh3GDGA" name="field_proposalOK1" content="field_proposalOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_AhxL0IaXEeSMzJufh3GDGA" name="proposalOK1">
                    <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxL0YaXEeSMzJufh3GDGA" line="1"/>
                    <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxL0oaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxL04aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <inputExpression xmi:type="expression:Expression" xmi:id="_AhxL1IaXEeSMzJufh3GDGA" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                      <referencedElements xmi:type="process:Data" xmi:id="_AhxL1YaXEeSMzJufh3GDGA" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
                        <defaultValue xmi:type="expression:Expression" xmi:id="_AhxL1oaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                      </referencedElements>
                    </inputExpression>
                    <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxL14aXEeSMzJufh3GDGA" name="" content=""/>
                    <action xmi:type="expression:Operation" xmi:id="_AhxL2IaXEeSMzJufh3GDGA">
                      <leftOperand xmi:type="expression:Expression" xmi:id="_AhxL2YaXEeSMzJufh3GDGA"/>
                      <operator xmi:type="expression:Operator" xmi:id="_AhxL2oaXEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                      <rightOperand xmi:type="expression:Expression" xmi:id="_AhxL24aXEeSMzJufh3GDGA"/>
                    </action>
                    <tooltip xmi:type="expression:Expression" xmi:id="_AhxL3IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <helpMessage xmi:type="expression:Expression" xmi:id="_AhxL3YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabel xmi:type="expression:Expression" xmi:id="_AhxL3oaXEeSMzJufh3GDGA" name="proposalOK1" content="proposalOK1" returnTypeFixed="true"/>
                    <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxL34aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxL4IaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxL4YaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_AhxL4oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForAdd xmi:type="expression:Expression" xmi:id="_AhxL44aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_AhxL5IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForRemove xmi:type="expression:Expression" xmi:id="_AhxL5YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <exampleMessage xmi:type="expression:Expression" xmi:id="_AhxL5oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                  </referencedElements>
                </rightOperand>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_AhxL54aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_AhxL6IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_AhxL6YaXEeSMzJufh3GDGA" name="Approved?" content="Approved?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxL6oaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxL64aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxL7IaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_AhxL7YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_AhxL7oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_AhxL74aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_AhxL8IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_AhxL8YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_AhxL8oaXEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxL84aXEeSMzJufh3GDGA" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_AhxL9IaXEeSMzJufh3GDGA" name="OK" content="OK" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxL9YaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_AhxL9oaXEeSMzJufh3GDGA" name="proposal1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxL94aXEeSMzJufh3GDGA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxL-IaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxL-YaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_AhxL-oaXEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_AhxL-4aXEeSMzJufh3GDGA" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_AhxL_IaXEeSMzJufh3GDGA" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxL_YaXEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_AhxL_oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_AhxL_4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxMAIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_AhxMAYaXEeSMzJufh3GDGA" name="Approve proposal" content="Approve proposal" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMAoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_AhxMA4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_AhxMBIaXEeSMzJufh3GDGA" name="Proposal made" outgoing="_AhxzR4aXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMBYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxMBoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxMB4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxMCIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AhxMCYaXEeSMzJufh3GDGA" name="Analyze Impact" outgoing="_AhxzTYaXEeSMzJufh3GDGA" incoming="_AhxzSoaXEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMCoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxMC4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxMDIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxMDYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxMDoaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxMD4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxMEIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxMEYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AhxMEoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_AhxME4aXEeSMzJufh3GDGA" name="AnalyzeImpact" nLine="3">
            <widgets xmi:type="form:TextFormField" xmi:id="_AhxMFIaXEeSMzJufh3GDGA" name="impacts1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxMFYaXEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxMFoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxMF4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_AhxMGIaXEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_AhxMGYaXEeSMzJufh3GDGA" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_AhxMGoaXEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxMG4aXEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_AhxMHIaXEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_AhxMHYaXEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                  <referencedElements xmi:type="process:Data" xmi:id="_AhxMHoaXEeSMzJufh3GDGA" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_AhxMH4aXEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                  </referencedElements>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_AhxMIIaXEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_AhxMIYaXEeSMzJufh3GDGA" name="field_impacts1" content="field_impacts1" type="TYPE_INPUT">
                  <referencedElements xmi:type="form:TextFormField" xmi:id="_AhxMIoaXEeSMzJufh3GDGA" name="impacts1">
                    <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxMI4aXEeSMzJufh3GDGA"/>
                    <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxMJIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxMJYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <inputExpression xmi:type="expression:Expression" xmi:id="_AhxMJoaXEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_AhxMJ4aXEeSMzJufh3GDGA" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                        <defaultValue xmi:type="expression:Expression" xmi:id="_AhxMKIaXEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                      </referencedElements>
                    </inputExpression>
                    <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxMKYaXEeSMzJufh3GDGA" name="" content=""/>
                    <action xmi:type="expression:Operation" xmi:id="_AhxMKoaXEeSMzJufh3GDGA">
                      <leftOperand xmi:type="expression:Expression" xmi:id="_AhxMK4aXEeSMzJufh3GDGA"/>
                      <operator xmi:type="expression:Operator" xmi:id="_AhxMLIaXEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                      <rightOperand xmi:type="expression:Expression" xmi:id="_AhxMLYaXEeSMzJufh3GDGA"/>
                    </action>
                    <tooltip xmi:type="expression:Expression" xmi:id="_AhxMLoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <helpMessage xmi:type="expression:Expression" xmi:id="_AhxML4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabel xmi:type="expression:Expression" xmi:id="_AhxMMIaXEeSMzJufh3GDGA" name="impacts1" content="impacts1" returnTypeFixed="true"/>
                    <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxMMYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxMMoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxMM4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_AhxMNIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForAdd xmi:type="expression:Expression" xmi:id="_AhxMNYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_AhxMNoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForRemove xmi:type="expression:Expression" xmi:id="_AhxMN4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <exampleMessage xmi:type="expression:Expression" xmi:id="_AhxMOIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                  </referencedElements>
                </rightOperand>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_AhxMOYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_AhxMOoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_AhxMO4aXEeSMzJufh3GDGA" name="Impact?" content="Impact?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxMPIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxMPYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxMPoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_AhxMP4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_AhxMQIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_AhxMQYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_AhxMQoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_AhxMQ4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_AhxMRIaXEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxMRYaXEeSMzJufh3GDGA" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_AhxMRoaXEeSMzJufh3GDGA" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxMR4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_AhxMSIaXEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMSYaXEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMSoaXEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxMS4aXEeSMzJufh3GDGA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxMTIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxMTYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_AhxMToaXEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_AhxMT4aXEeSMzJufh3GDGA" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_AhxMUIaXEeSMzJufh3GDGA" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxMUYaXEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_AhxMUoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_AhxMU4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxMVIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_AhxMVYaXEeSMzJufh3GDGA" name="Analyze Impact" content="Analyze Impact" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMVoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_AhxMV4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AhxMWIaXEeSMzJufh3GDGA" name="Validate project" outgoing="_AhxzZ4aXEeSMzJufh3GDGA" incoming="_AhxzTYaXEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMWYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxMWoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxMW4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxMXIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxMXYaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxMXoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxMX4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_AhxMYIaXEeSMzJufh3GDGA" documentation="&#x9;&#x9;&#x9;" name="NonInterruptingBoundaryTimerEvent" outgoing="_AhxzeIaXEeSMzJufh3GDGA">
            <condition xmi:type="expression:Expression" xmi:id="_AhxMYYaXEeSMzJufh3GDGA" name="4 Jours 00:00:00" content="345600000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxMYoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AhxMY4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_AhxMZIaXEeSMzJufh3GDGA" name="ValidateProject">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_AhxMZYaXEeSMzJufh3GDGA" name="projectOK1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxMZoaXEeSMzJufh3GDGA" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxMZ4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxMaIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_AhxMaYaXEeSMzJufh3GDGA" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_AhxMaoaXEeSMzJufh3GDGA" name="projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_AhxMa4aXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxMbIaXEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_AhxMbYaXEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_AhxMboaXEeSMzJufh3GDGA" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="_AhxMb4aXEeSMzJufh3GDGA" name="projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_AhxMcIaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                  </referencedElements>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_AhxMcYaXEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_AhxMcoaXEeSMzJufh3GDGA" name="field_projectOK1" content="field_projectOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_AhxMc4aXEeSMzJufh3GDGA" name="projectOK1">
                    <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxMdIaXEeSMzJufh3GDGA" line="1"/>
                    <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxMdYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxMdoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <inputExpression xmi:type="expression:Expression" xmi:id="_AhxMd4aXEeSMzJufh3GDGA" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                      <referencedElements xmi:type="process:Data" xmi:id="_AhxMeIaXEeSMzJufh3GDGA" name="projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
                        <defaultValue xmi:type="expression:Expression" xmi:id="_AhxMeYaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                      </referencedElements>
                    </inputExpression>
                    <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxMeoaXEeSMzJufh3GDGA" name="" content=""/>
                    <action xmi:type="expression:Operation" xmi:id="_AhxMe4aXEeSMzJufh3GDGA">
                      <leftOperand xmi:type="expression:Expression" xmi:id="_AhxMfIaXEeSMzJufh3GDGA"/>
                      <operator xmi:type="expression:Operator" xmi:id="_AhxMfYaXEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                      <rightOperand xmi:type="expression:Expression" xmi:id="_AhxMfoaXEeSMzJufh3GDGA"/>
                    </action>
                    <tooltip xmi:type="expression:Expression" xmi:id="_AhxMf4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <helpMessage xmi:type="expression:Expression" xmi:id="_AhxMgIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabel xmi:type="expression:Expression" xmi:id="_AhxMgYaXEeSMzJufh3GDGA" name="projectOK1" content="projectOK1" returnTypeFixed="true"/>
                    <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxMgoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxMg4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxMhIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_AhxMhYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForAdd xmi:type="expression:Expression" xmi:id="_AhxMhoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_AhxMh4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForRemove xmi:type="expression:Expression" xmi:id="_AhxMiIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <exampleMessage xmi:type="expression:Expression" xmi:id="_AhxMiYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                  </referencedElements>
                </rightOperand>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_AhxMioaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_AhxMi4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_AhxMjIaXEeSMzJufh3GDGA" name="Approve project?" content="Approve project?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxMjYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxMjoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxMj4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_AhxMkIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_AhxMkYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_AhxMkoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_AhxMk4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_AhxMlIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_AhxMlYaXEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxMloaXEeSMzJufh3GDGA" line="3"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_AhxMl4aXEeSMzJufh3GDGA" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxMmIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_AhxMmYaXEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMmoaXEeSMzJufh3GDGA" key="input_css:color" value="purple"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMm4aXEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMnIaXEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxMnYaXEeSMzJufh3GDGA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxMnoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxMn4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_AhxMoIaXEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_AhxMoYaXEeSMzJufh3GDGA" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_AhxMooaXEeSMzJufh3GDGA" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxMo4aXEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_AhxMpIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_AhxMpYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxMpoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_AhxMp4aXEeSMzJufh3GDGA" name="impacts1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMqIaXEeSMzJufh3GDGA" key="input_css:color" value="red"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMqYaXEeSMzJufh3GDGA" key="input_css:font-size" value="18px"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxMqoaXEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxMq4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxMrIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_AhxMrYaXEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_AhxMroaXEeSMzJufh3GDGA" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_AhxMr4aXEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxMsIaXEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_AhxMsYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_AhxMsoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxMs4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_AhxMtIaXEeSMzJufh3GDGA" name="Validate project" content="Validate project" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMtYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_AhxMtoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_AhxMt4aXEeSMzJufh3GDGA" name="Proposal refused" incoming="_AhxzVoaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMuIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxMuYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxMuoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxMu4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_AhxMvIaXEeSMzJufh3GDGA" name="Project finished" incoming="_AhxzcoaXEeSMzJufh3GDGA _83WS8IaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMvYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxMvoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxMv4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxMwIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_AhxMwYaXEeSMzJufh3GDGA" name="Project refused" incoming="_AhxzWYaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMwoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxMw4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxMxIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxMxYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_AhxMxoaXEeSMzJufh3GDGA" name="Project approval?" outgoing="_AhxzaoaXEeSMzJufh3GDGA _Ahxzb4aXEeSMzJufh3GDGA" incoming="_AhxzZ4aXEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMx4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxMyIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxMyYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxMyoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_AhxMy4aXEeSMzJufh3GDGA" name="5 days?" outgoing="_AhxzX4aXEeSMzJufh3GDGA _AhxzZIaXEeSMzJufh3GDGA" incoming="_AhxzXIaXEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxMzIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxMzYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxMzoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxMz4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxM0IaXEeSMzJufh3GDGA" name="Notify proposal aproved" outgoing="_AhxzSoaXEeSMzJufh3GDGA" incoming="_AhxzX4aXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxM0YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxM0oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxM04aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxM1IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxM1YaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxM1oaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxM14aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxM2IaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AhxM2YaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxM2oaXEeSMzJufh3GDGA" name="Notify proposal refusal" outgoing="_AhxzVoaXEeSMzJufh3GDGA" incoming="_AhxzZIaXEeSMzJufh3GDGA _AhxzdYaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxM24aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxM3IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxM3YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxM3oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxM34aXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxM4IaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxM4YaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxM4oaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AhxM44aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxM5IaXEeSMzJufh3GDGA" name="Notify project refused" outgoing="_AhxzWYaXEeSMzJufh3GDGA" incoming="_Ahxzb4aXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxM5YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxM5oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxM54aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxM6IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxM6YaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxM6oaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxM64aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxM7IaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AhxM7YaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxM7oaXEeSMzJufh3GDGA" name="Notify project accepted" outgoing="_AhxzUIaXEeSMzJufh3GDGA" incoming="_AhxzaoaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxM74aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxM8IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxM8YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxM8oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxM84aXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxM9IaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxM9YaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxM9oaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AhxM94aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxM-IaXEeSMzJufh3GDGA" name="Notify project delivery" outgoing="_AhxzcoaXEeSMzJufh3GDGA" incoming="_AhxzU4aXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxM-YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxM-oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxM-4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxM_IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Ol28EIaYEeSMzJufh3GDGA" name="Send Email on Project Delivery" definitionId="email" event="ON_ENTER" throwErrorEvent="true" namedError="Send email error" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_Ol28EYaYEeSMzJufh3GDGA" definitionId="email" version="1.0.0">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28EoaYEeSMzJufh3GDGA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28E4aYEeSMzJufh3GDGA" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28FIaYEeSMzJufh3GDGA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28FYaYEeSMzJufh3GDGA" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28FoaYEeSMzJufh3GDGA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28F4aYEeSMzJufh3GDGA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28GIaYEeSMzJufh3GDGA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28GYaYEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28GoaYEeSMzJufh3GDGA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28G4aYEeSMzJufh3GDGA" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28HIaYEeSMzJufh3GDGA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28HYaYEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28HoaYEeSMzJufh3GDGA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28H4aYEeSMzJufh3GDGA" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28IIaYEeSMzJufh3GDGA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28IYaYEeSMzJufh3GDGA" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28IoaYEeSMzJufh3GDGA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28I4aYEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28JIaYEeSMzJufh3GDGA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28JYaYEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28JoaYEeSMzJufh3GDGA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28J4aYEeSMzJufh3GDGA" name="Project Delivered " content="Project Delivered " returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28KIaYEeSMzJufh3GDGA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28KYaYEeSMzJufh3GDGA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28KoaYEeSMzJufh3GDGA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28K4aYEeSMzJufh3GDGA" name="&lt;pattern-expression>" content="Bah oui, Project ${proposal} delivered&#xA;Thanks" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_Ol28LIaYEeSMzJufh3GDGA" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_Ol28LYaYEeSMzJufh3GDGA" content=""/>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28LoaYEeSMzJufh3GDGA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_Ol28L4aYEeSMzJufh3GDGA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28MIaYEeSMzJufh3GDGA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28MYaYEeSMzJufh3GDGA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28MoaYEeSMzJufh3GDGA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_Ol28M4aYEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ol28NIaYEeSMzJufh3GDGA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_Ol28NYaYEeSMzJufh3GDGA"/>
              </parameters>
            </configuration>
          </connectors>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxM_YaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxM_oaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxM_4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <BoundaryIntermediateEvents xmi:type="process:IntermediateErrorCatchEvent" xmi:id="_uY4eQIaXEeSMzJufh3GDGA" name="Email Error" outgoing="_3s8qoIaXEeSMzJufh3GDGA" errorCode="Send email error"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxNAIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AhxNAYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_AhxNAoaXEeSMzJufh3GDGA" name="Do project" outgoing="_AhxzU4aXEeSMzJufh3GDGA" incoming="_AhxzUIaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxNA4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxNBIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxNBYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxNBoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxNB4aXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxNCIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxNCYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxNCoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AhxNC4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_AhxNDIaXEeSMzJufh3GDGA" processSource="_Ahxy-oaXEeSMzJufh3GDGA" subprocessTarget="sub_proposal"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_AhxNDYaXEeSMzJufh3GDGA" processSource="_Ahxy_IaXEeSMzJufh3GDGA" subprocessTarget="sub_proposalOK"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_AhxNDoaXEeSMzJufh3GDGA" processSource="_Ahxy_oaXEeSMzJufh3GDGA" subprocessTarget="sub_projectOK"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_AhxND4aXEeSMzJufh3GDGA" processSource="_AhxzAIaXEeSMzJufh3GDGA" subprocessTarget="sub_impacts"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_AhxNEIaXEeSMzJufh3GDGA" subprocessSource="sub_proposal" processTarget="_Ahxy-oaXEeSMzJufh3GDGA"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_AhxNEYaXEeSMzJufh3GDGA" subprocessSource="sub_proposalOK" processTarget="_Ahxy_IaXEeSMzJufh3GDGA"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_AhxNEoaXEeSMzJufh3GDGA" subprocessSource="sub_projectOK" processTarget="_Ahxy_oaXEeSMzJufh3GDGA"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_AhxNE4aXEeSMzJufh3GDGA" subprocessSource="sub_impacts" processTarget="_AhxzAIaXEeSMzJufh3GDGA"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_AhxNFIaXEeSMzJufh3GDGA" name="Do_project_CORTES_MARTINEZ" content="Do_project_CORTES_MARTINEZ" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_AhxNFYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxNFoaXEeSMzJufh3GDGA" name="Notify Delay" outgoing="_Ahxze4aXEeSMzJufh3GDGA" incoming="_AhxzeIaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxNF4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxNGIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxNGYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxywIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_AhxywYaXEeSMzJufh3GDGA" name="Connecteur Mail - Delay" definitionId="email" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_AhxywoaXEeSMzJufh3GDGA" definitionId="email" version="1.0.0">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxyw4aXEeSMzJufh3GDGA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_AhxyxIaXEeSMzJufh3GDGA" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_AhxyxYaXEeSMzJufh3GDGA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_AhxyxoaXEeSMzJufh3GDGA" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxyx4aXEeSMzJufh3GDGA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_AhxyyIaXEeSMzJufh3GDGA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_AhxyyYaXEeSMzJufh3GDGA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_AhxyyoaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxyy4aXEeSMzJufh3GDGA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_AhxyzIaXEeSMzJufh3GDGA" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_AhxyzYaXEeSMzJufh3GDGA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_AhxyzoaXEeSMzJufh3GDGA" name="nbvcxwmlkj" content="nbvcxwmlkj" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxyz4aXEeSMzJufh3GDGA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_Ahxy0IaXEeSMzJufh3GDGA" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxy0YaXEeSMzJufh3GDGA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_Ahxy0oaXEeSMzJufh3GDGA" name="sacortesh@gmail.com" content="sacortesh@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxy04aXEeSMzJufh3GDGA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_Ahxy1IaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxy1YaXEeSMzJufh3GDGA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_Ahxy1oaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxy14aXEeSMzJufh3GDGA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_Ahxy2IaXEeSMzJufh3GDGA" name="Test" content="Test" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxy2YaXEeSMzJufh3GDGA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_Ahxy2oaXEeSMzJufh3GDGA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxy24aXEeSMzJufh3GDGA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_Ahxy3IaXEeSMzJufh3GDGA" name="&lt;pattern-expression>" content="${impacts}&#xA;${proposal}&#xA;Gracias" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_Ahxy3YaXEeSMzJufh3GDGA" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_Ahxy3oaXEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                  </referencedElements>
                  <referencedElements xmi:type="process:Data" xmi:id="_Ahxy34aXEeSMzJufh3GDGA" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_Ahxy4IaXEeSMzJufh3GDGA" content=""/>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxy4YaXEeSMzJufh3GDGA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_Ahxy4oaXEeSMzJufh3GDGA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxy44aXEeSMzJufh3GDGA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_Ahxy5IaXEeSMzJufh3GDGA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxy5YaXEeSMzJufh3GDGA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_Ahxy5oaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ahxy54aXEeSMzJufh3GDGA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_Ahxy6IaXEeSMzJufh3GDGA"/>
              </parameters>
            </configuration>
          </connectors>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_Ahxy6YaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_Ahxy6oaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_Ahxy64aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Ahxy7IaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ahxy7YaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Ahxy7oaXEeSMzJufh3GDGA" name="Notification Done" incoming="_Ahxze4aXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Ahxy74aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ahxy8IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ahxy8YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ahxy8oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4_iT4IaXEeSMzJufh3GDGA" name="Notify project delivery by form" outgoing="_83WS8IaXEeSMzJufh3GDGA" incoming="_3s8qoIaXEeSMzJufh3GDGA" overrideActorsOfTheLane="false" priority="4">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_3s1884aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3s188YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3s188IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3s188oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_3s189oaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_3s1894aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_3s18-IaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3s189IaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3s189YaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_CO9Q0IaYEeSMzJufh3GDGA" name="NotifyProjectDeliveryByForm" nLine="3">
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_CO9Q0YaYEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_CO9Q0oaYEeSMzJufh3GDGA" line="2"/>
              <tooltip xmi:type="expression:Expression" xmi:id="_JbESMIaYEeSMzJufh3GDGA" content=""/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_CO9Q04aYEeSMzJufh3GDGA" name="Ok" content="Ok" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_CO9Q1IaYEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_IIvHoIaYEeSMzJufh3GDGA" name="Message1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IIwVw4aYEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_IIvus4aYEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_IIvutIaYEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_IIvusoaYEeSMzJufh3GDGA" name="Save Yoko Ono, Deliver the message" content="Save Yoko Ono, Deliver the message"/>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_IIvutYaYEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_IIvutoaYEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_IIvut4aYEeSMzJufh3GDGA"/>
                <operator xmi:type="expression:Operator" xmi:id="_IIvuuIaYEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_IIvuuYaYEeSMzJufh3GDGA"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_IIvusYaYEeSMzJufh3GDGA" name="Save Yoko Ono, Deliver the message" content="Save Yoko Ono, Deliver the message" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_IIvusIaYEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_IIvHoYaYEeSMzJufh3GDGA" name="Message1" content="Message1" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_IIvHooaYEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_CO9Q1YaYEeSMzJufh3GDGA" name="Notify project delivery by form" content="Notify project delivery by form" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_4_iT54aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_4_iT6IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_Al-9UIaXEeSMzJufh3GDGA" path="_AhxLsYaXEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_Ahxy9IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_Ahxy9YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxy9oaXEeSMzJufh3GDGA" path="_AhxLsYaXEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxy94aXEeSMzJufh3GDGA" path="_AhxLsYaXEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxy-IaXEeSMzJufh3GDGA" path="_AhxLsYaXEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxy-YaXEeSMzJufh3GDGA" path="_AhxLsYaXEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_Ahxy-oaXEeSMzJufh3GDGA" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Ahxy-4aXEeSMzJufh3GDGA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Ahxy_IaXEeSMzJufh3GDGA" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Ahxy_YaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Ahxy_oaXEeSMzJufh3GDGA" name="projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Ahxy_4aXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_AhxzAIaXEeSMzJufh3GDGA" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_AhxzAYaXEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <form xmi:type="form:Form" xmi:id="_AhxzAoaXEeSMzJufh3GDGA" name="Project_Validation_CORTES_MARTINEZ" nLine="3">
        <widgets xmi:type="form:TextFormField" xmi:id="_AhxzA4aXEeSMzJufh3GDGA" name="proposal1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxzBIaXEeSMzJufh3GDGA" line="1"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxzBYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxzBoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_AhxzB4aXEeSMzJufh3GDGA" name="" content=""/>
          <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxzCIaXEeSMzJufh3GDGA" name="" content=""/>
          <action xmi:type="expression:Operation" xmi:id="_AhxzCYaXEeSMzJufh3GDGA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AhxzCoaXEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_AhxzC4aXEeSMzJufh3GDGA" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_AhxzDIaXEeSMzJufh3GDGA" content=""/>
              </referencedElements>
            </leftOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AhxzDYaXEeSMzJufh3GDGA" type="ASSIGNMENT"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AhxzDoaXEeSMzJufh3GDGA" name="field_proposal1" content="field_proposal1" type="TYPE_INPUT">
              <referencedElements xmi:type="form:TextFormField" xmi:id="_AhxzD4aXEeSMzJufh3GDGA" name="proposal1">
                <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxzEIaXEeSMzJufh3GDGA"/>
                <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxzEYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxzEoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                <inputExpression xmi:type="expression:Expression" xmi:id="_AhxzE4aXEeSMzJufh3GDGA" name="" content=""/>
                <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxzFIaXEeSMzJufh3GDGA" name="" content=""/>
                <action xmi:type="expression:Operation" xmi:id="_AhxzFYaXEeSMzJufh3GDGA">
                  <leftOperand xmi:type="expression:Expression" xmi:id="_AhxzFoaXEeSMzJufh3GDGA"/>
                  <operator xmi:type="expression:Operator" xmi:id="_AhxzF4aXEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                  <rightOperand xmi:type="expression:Expression" xmi:id="_AhxzGIaXEeSMzJufh3GDGA"/>
                </action>
                <tooltip xmi:type="expression:Expression" xmi:id="_AhxzGYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <helpMessage xmi:type="expression:Expression" xmi:id="_AhxzGoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <displayLabel xmi:type="expression:Expression" xmi:id="_AhxzG4aXEeSMzJufh3GDGA" name="proposal1" content="proposal1" returnTypeFixed="true"/>
                <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxzHIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxzHYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxzHoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_AhxzH4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <tooltipForAdd xmi:type="expression:Expression" xmi:id="_AhxzIIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_AhxzIYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <tooltipForRemove xmi:type="expression:Expression" xmi:id="_AhxzIoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <exampleMessage xmi:type="expression:Expression" xmi:id="_AhxzI4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              </referencedElements>
            </rightOperand>
          </action>
          <tooltip xmi:type="expression:Expression" xmi:id="_AhxzJIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:type="expression:Expression" xmi:id="_AhxzJYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_AhxzJoaXEeSMzJufh3GDGA" name="Proposal" content="Proposal" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxzJ4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxzKIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_AhxzKYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_AhxzKoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <tooltipForAdd xmi:type="expression:Expression" xmi:id="_AhxzK4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_AhxzLIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <tooltipForRemove xmi:type="expression:Expression" xmi:id="_AhxzLYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <exampleMessage xmi:type="expression:Expression" xmi:id="_AhxzLoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </widgets>
        <widgets xmi:type="form:SubmitFormButton" xmi:id="_AhxzL4aXEeSMzJufh3GDGA" name="Soumettre1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxzMIaXEeSMzJufh3GDGA" line="2"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_AhxzMYaXEeSMzJufh3GDGA" name="OK" content="OK" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxzMoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <widgets xmi:type="form:MessageInfo" xmi:id="_AhxzM4aXEeSMzJufh3GDGA" name="Enter proposal:">
          <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxzNIaXEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxzNYaXEeSMzJufh3GDGA"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_AhxzNoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_AhxzN4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_AhxzOIaXEeSMzJufh3GDGA" name="" content=""/>
          <afterEventExpression xmi:type="expression:Expression" xmi:id="_AhxzOYaXEeSMzJufh3GDGA" name="" content=""/>
          <action xmi:type="expression:Operation" xmi:id="_AhxzOoaXEeSMzJufh3GDGA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AhxzO4aXEeSMzJufh3GDGA"/>
            <operator xmi:type="expression:Operator" xmi:id="_AhxzPIaXEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AhxzPYaXEeSMzJufh3GDGA"/>
          </action>
          <tooltip xmi:type="expression:Expression" xmi:id="_AhxzPoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:type="expression:Expression" xmi:id="_AhxzP4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_AhxzQIaXEeSMzJufh3GDGA" name="Message1" content="Message1" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_AhxzQYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:type="expression:Expression" xmi:id="_AhxzQoaXEeSMzJufh3GDGA" name="Propose proposal" content="Propose proposal" returnTypeFixed="true"/>
      </form>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxzQ4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_AhxzRIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxzRYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxzRoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzR4aXEeSMzJufh3GDGA" source="_AhxMBIaXEeSMzJufh3GDGA" target="_AhxLs4aXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzSIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzSYaXEeSMzJufh3GDGA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzSoaXEeSMzJufh3GDGA" source="_AhxM0IaXEeSMzJufh3GDGA" target="_AhxMCYaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzS4aXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzTIaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzTYaXEeSMzJufh3GDGA" source="_AhxMCYaXEeSMzJufh3GDGA" target="_AhxMWIaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzToaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzT4aXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzUIaXEeSMzJufh3GDGA" source="_AhxM7oaXEeSMzJufh3GDGA" target="_AhxNAoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzUYaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzUoaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzU4aXEeSMzJufh3GDGA" source="_AhxNAoaXEeSMzJufh3GDGA" target="_AhxM-IaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzVIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzVYaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzVoaXEeSMzJufh3GDGA" source="_AhxM2oaXEeSMzJufh3GDGA" target="_AhxMt4aXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzV4aXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzWIaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzWYaXEeSMzJufh3GDGA" source="_AhxM5IaXEeSMzJufh3GDGA" target="_AhxMwYaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzWoaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzW4aXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzXIaXEeSMzJufh3GDGA" source="_AhxLs4aXEeSMzJufh3GDGA" target="_AhxMy4aXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzXYaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzXoaXEeSMzJufh3GDGA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzX4aXEeSMzJufh3GDGA" name="Approved" source="_AhxMy4aXEeSMzJufh3GDGA" target="_AhxM0IaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzYIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzYYaXEeSMzJufh3GDGA" name="proposalOK==true" content="proposalOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_AhxzYoaXEeSMzJufh3GDGA" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_AhxzY4aXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzZIaXEeSMzJufh3GDGA" name="Not Approved" source="_AhxMy4aXEeSMzJufh3GDGA" target="_AhxM2oaXEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzZYaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzZoaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzZ4aXEeSMzJufh3GDGA" source="_AhxMWIaXEeSMzJufh3GDGA" target="_AhxMxoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzaIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzaYaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzaoaXEeSMzJufh3GDGA" name="Approved" source="_AhxMxoaXEeSMzJufh3GDGA" target="_AhxM7oaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxza4aXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzbIaXEeSMzJufh3GDGA" name="projectOK==true" content="projectOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_AhxzbYaXEeSMzJufh3GDGA" name="projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_AhxzboaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxzb4aXEeSMzJufh3GDGA" name="Not approved" source="_AhxMxoaXEeSMzJufh3GDGA" target="_AhxM5IaXEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzcIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzcYaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzcoaXEeSMzJufh3GDGA" source="_AhxM-IaXEeSMzJufh3GDGA" target="_AhxMvIaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxzc4aXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzdIaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzdYaXEeSMzJufh3GDGA" source="_AhxLu4aXEeSMzJufh3GDGA" target="_AhxM2oaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzdoaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ahxzd4aXEeSMzJufh3GDGA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzeIaXEeSMzJufh3GDGA" source="_AhxMYIaXEeSMzJufh3GDGA" target="_AhxNFoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzeYaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzeoaXEeSMzJufh3GDGA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxze4aXEeSMzJufh3GDGA" source="_AhxNFoaXEeSMzJufh3GDGA" target="_Ahxy7oaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzfIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AhxzfYaXEeSMzJufh3GDGA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3s8qoIaXEeSMzJufh3GDGA" source="_uY4eQIaXEeSMzJufh3GDGA" target="_4_iT4IaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3s8qoYaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_3s8qooaXEeSMzJufh3GDGA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_83WS8IaXEeSMzJufh3GDGA" source="_4_iT4IaXEeSMzJufh3GDGA" target="_AhxMvIaXEeSMzJufh3GDGA">
        <expression xmi:type="expression:Expression" xmi:id="_9BjX0IaXEeSMzJufh3GDGA" content=""/>
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_83WS8YaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_83WS8oaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_AhxzfoaXEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxzf4aXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_AhxzgIaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_AhxzgYaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AhxzgoaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_Ahxzg4aXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_AhxzhIaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AhxzhYaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_AhxzhoaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ahxzh4aXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AhxziIaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_AhxziYaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_AhxzioaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxzi4aXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_AhxzjIaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_AhxzjYaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_AhxzjoaXEeSMzJufh3GDGA" name="Do_project_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="4.0">
      <elements xmi:type="process:Lane" xmi:id="_Ahxzj4aXEeSMzJufh3GDGA" name="Research and Development" actor="_Ahxz7IaXEeSMzJufh3GDGA">
        <elements xmi:type="process:Task" xmi:id="_AhxzkIaXEeSMzJufh3GDGA" name="Deploy" outgoing="_Ahxz6YaXEeSMzJufh3GDGA" incoming="_Ahxz5oaXEeSMzJufh3GDGA" actor="_Ahxz7IaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxzkYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxzkoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ahxzk4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxzlIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxzlYaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxzloaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_Ahxzl4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxzmIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_AhxzmYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxzmoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_Ahxzm4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_AhxznIaXEeSMzJufh3GDGA" name="Start project" outgoing="_Ahxz3YaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxznYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxznoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ahxzn4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxzoIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_AhxzoYaXEeSMzJufh3GDGA" name="Project finished" incoming="_Ahxz6YaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxzooaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ahxzo4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxzpIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxzpYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AhxzpoaXEeSMzJufh3GDGA" name="Specify" outgoing="_Ahxz4IaXEeSMzJufh3GDGA" incoming="_Ahxz3YaXEeSMzJufh3GDGA" actor="_Ahxz7IaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Ahxzp4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxzqIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxzqYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxzqoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_Ahxzq4aXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxzrIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxzrYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxzroaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ahxzr4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxzsIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_AhxzsYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AhxzsoaXEeSMzJufh3GDGA" name="Implement" outgoing="_Ahxz44aXEeSMzJufh3GDGA" incoming="_Ahxz4IaXEeSMzJufh3GDGA" actor="_Ahxz7IaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Ahxzs4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxztIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxztYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxztoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_Ahxzt4aXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxzuIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxzuYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxzuoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ahxzu4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxzvIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_AhxzvYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AhxzvoaXEeSMzJufh3GDGA" name="Test" outgoing="_Ahxz5oaXEeSMzJufh3GDGA" incoming="_Ahxz44aXEeSMzJufh3GDGA" actor="_Ahxz7IaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Ahxzv4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AhxzwIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AhxzwYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AhxzwoaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_Ahxzw4aXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_AhxzxIaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_AhxzxYaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_AhxzxoaXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ahxzx4aXEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_AhxzyIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_AhxzyYaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_AqMu8IaXEeSMzJufh3GDGA" path="_AhxzjoaXEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_Ahxzy4aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_AhxzzIaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_AhxzzYaXEeSMzJufh3GDGA" path="_AhxzjoaXEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_AhxzzoaXEeSMzJufh3GDGA" path="_AhxzjoaXEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxzz4aXEeSMzJufh3GDGA" path="_AhxzjoaXEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxz0IaXEeSMzJufh3GDGA" path="_AhxzjoaXEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_Ahxz0YaXEeSMzJufh3GDGA" name="sub_proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Ahxz0oaXEeSMzJufh3GDGA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Ahxz04aXEeSMzJufh3GDGA" name="sub_proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Ahxz1IaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Ahxz1YaXEeSMzJufh3GDGA" name="sub_projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Ahxz1oaXEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Ahxz14aXEeSMzJufh3GDGA" name="sub_impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Ahxz2IaXEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_Ahxz2YaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_Ahxz2oaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Ahxz24aXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Ahxz3IaXEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxz3YaXEeSMzJufh3GDGA" source="_AhxznIaXEeSMzJufh3GDGA" target="_AhxzpoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxz3oaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ahxz34aXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxz4IaXEeSMzJufh3GDGA" source="_AhxzpoaXEeSMzJufh3GDGA" target="_AhxzsoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxz4YaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ahxz4oaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxz44aXEeSMzJufh3GDGA" source="_AhxzsoaXEeSMzJufh3GDGA" target="_AhxzvoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxz5IaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ahxz5YaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxz5oaXEeSMzJufh3GDGA" source="_AhxzvoaXEeSMzJufh3GDGA" target="_AhxzkIaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxz54aXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ahxz6IaXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxz6YaXEeSMzJufh3GDGA" source="_AhxzkIaXEeSMzJufh3GDGA" target="_AhxzoYaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxz6oaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ahxz64aXEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Ahxz7IaXEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxz7YaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_Ahxz7oaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ahxz74aXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxz8IaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_Ahxz8YaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ahxz8oaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxz84aXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_Ahxz9IaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ahxz9YaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxz9oaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_Ahxz94aXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ahxz-IaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxz-YaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_Ahxz-oaXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ahxz-4aXEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Ahxz_IaXEeSMzJufh3GDGA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Ahxz_YaXEeSMzJufh3GDGA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Ahxz_oaXEeSMzJufh3GDGA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Ahxz_4aXEeSMzJufh3GDGA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Ahx0AIaXEeSMzJufh3GDGA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Ahx0AYaXEeSMzJufh3GDGA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Ahx0AoaXEeSMzJufh3GDGA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Ahx0A4aXEeSMzJufh3GDGA" name="XML"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Ahx0BIaXEeSMzJufh3GDGA" type="Process" element="_AhxLsIaXEeSMzJufh3GDGA" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Ahx0BYaXEeSMzJufh3GDGA" type="2007" element="_AhxLsYaXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0BoaXEeSMzJufh3GDGA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0B4aXEeSMzJufh3GDGA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_Ahx0CIaXEeSMzJufh3GDGA" type="3007" element="_AhxLsoaXEeSMzJufh3GDGA">
          <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0CYaXEeSMzJufh3GDGA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0CoaXEeSMzJufh3GDGA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Ahx0C4aXEeSMzJufh3GDGA" type="3005" element="_AhxLs4aXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0DIaXEeSMzJufh3GDGA" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_Ahx0DYaXEeSMzJufh3GDGA" type="3043" element="_AhxLu4aXEeSMzJufh3GDGA" fontName="Sans">
                <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0DoaXEeSMzJufh3GDGA" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0D4aXEeSMzJufh3GDGA" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0EIaXEeSMzJufh3GDGA"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0EYaXEeSMzJufh3GDGA" x="119" y="165"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0EoaXEeSMzJufh3GDGA" type="3002" element="_AhxMBIaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0E4aXEeSMzJufh3GDGA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0FIaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0FYaXEeSMzJufh3GDGA" x="40" y="179"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0FoaXEeSMzJufh3GDGA" type="3005" element="_AhxMCYaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0F4aXEeSMzJufh3GDGA" type="5005" element="_AhxMCYaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0GIaXEeSMzJufh3GDGA" x="421" y="102"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0GYaXEeSMzJufh3GDGA" type="3005" element="_AhxMWIaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0GoaXEeSMzJufh3GDGA" type="5005" element="_AhxMWIaXEeSMzJufh3GDGA"/>
              <children xmi:type="notation:Shape" xmi:id="_Ahx0G4aXEeSMzJufh3GDGA" type="3064" element="_AhxMYIaXEeSMzJufh3GDGA" fontName="Sans">
                <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0HIaXEeSMzJufh3GDGA" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0HYaXEeSMzJufh3GDGA" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0HoaXEeSMzJufh3GDGA"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0H4aXEeSMzJufh3GDGA" x="556" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0IIaXEeSMzJufh3GDGA" type="3062" element="_AhxMt4aXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0IYaXEeSMzJufh3GDGA" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0IoaXEeSMzJufh3GDGA" x="-1" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0I4aXEeSMzJufh3GDGA" x="508" y="227"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0JIaXEeSMzJufh3GDGA" type="3062" element="_AhxMvIaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0JYaXEeSMzJufh3GDGA" type="5090" element="_AhxMvIaXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0JoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0J4aXEeSMzJufh3GDGA" x="1221" y="136"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0KIaXEeSMzJufh3GDGA" type="3062" element="_AhxMwYaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0KYaXEeSMzJufh3GDGA" type="5090" element="_AhxMwYaXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0KoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0K4aXEeSMzJufh3GDGA" x="1012" y="226"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0LIaXEeSMzJufh3GDGA" type="3008" element="_AhxMxoaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0LYaXEeSMzJufh3GDGA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0LoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0L4aXEeSMzJufh3GDGA" x="689" y="105" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0MIaXEeSMzJufh3GDGA" type="3008" element="_AhxMy4aXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0MYaXEeSMzJufh3GDGA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0MoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0M4aXEeSMzJufh3GDGA" x="230" y="170" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0NIaXEeSMzJufh3GDGA" type="3027" element="_AhxM0IaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0NYaXEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0NoaXEeSMzJufh3GDGA" x="271" y="95" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0N4aXEeSMzJufh3GDGA" type="3027" element="_AhxM2oaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0OIaXEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0OYaXEeSMzJufh3GDGA" x="347" y="187" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0OoaXEeSMzJufh3GDGA" type="3027" element="_AhxM5IaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0O4aXEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0PIaXEeSMzJufh3GDGA" x="765" y="192" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0PYaXEeSMzJufh3GDGA" type="3027" element="_AhxM7oaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0PoaXEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0P4aXEeSMzJufh3GDGA" x="762" y="96" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0QIaXEeSMzJufh3GDGA" type="3027" element="_AhxM-IaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0QYaXEeSMzJufh3GDGA" type="5017"/>
              <children xmi:type="notation:Shape" xmi:id="_uY5sYIaXEeSMzJufh3GDGA" type="3032" element="_uY4eQIaXEeSMzJufh3GDGA" fontName="Sans">
                <children xmi:type="notation:DecorationNode" xmi:id="_uY6TcIaXEeSMzJufh3GDGA" type="5062">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_uY6TcYaXEeSMzJufh3GDGA" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uY5sYYaXEeSMzJufh3GDGA"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0QoaXEeSMzJufh3GDGA" x="1041" y="90" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0Q4aXEeSMzJufh3GDGA" type="3063" element="_AhxNAoaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0RIaXEeSMzJufh3GDGA" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0RYaXEeSMzJufh3GDGA" x="913" y="125"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0RoaXEeSMzJufh3GDGA" type="3027" element="_AhxNFoaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0R4aXEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0SIaXEeSMzJufh3GDGA" x="590" y="192"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0SYaXEeSMzJufh3GDGA" type="3003" element="_Ahxy7oaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0SoaXEeSMzJufh3GDGA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0S4aXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0TIaXEeSMzJufh3GDGA" x="714" y="227"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4_i68IaXEeSMzJufh3GDGA" type="3005" element="_4_iT4IaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4_i68oaXEeSMzJufh3GDGA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4_i68YaXEeSMzJufh3GDGA" x="1107" y="227" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Ahx0TYaXEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Ahx0ToaXEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Ahx0T4aXEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Ahx0UIaXEeSMzJufh3GDGA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0UYaXEeSMzJufh3GDGA" x="45" y="10" width="1383" height="342"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Ahx0UoaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ahx0U4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Ahx0VIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Ahx0VYaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0VoaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_Ahx0V4aXEeSMzJufh3GDGA" type="2007" element="_AhxzjoaXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0WIaXEeSMzJufh3GDGA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0WYaXEeSMzJufh3GDGA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_Ahx0WoaXEeSMzJufh3GDGA" type="3007" element="_Ahxzj4aXEeSMzJufh3GDGA">
          <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0W4aXEeSMzJufh3GDGA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0XIaXEeSMzJufh3GDGA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Ahx0XYaXEeSMzJufh3GDGA" type="3005" element="_AhxzkIaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0XoaXEeSMzJufh3GDGA" type="5005" element="_AhxzkIaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0X4aXEeSMzJufh3GDGA" x="597" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0YIaXEeSMzJufh3GDGA" type="3002" element="_AhxznIaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0YYaXEeSMzJufh3GDGA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0YoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0Y4aXEeSMzJufh3GDGA" x="84" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0ZIaXEeSMzJufh3GDGA" type="3062" element="_AhxzoYaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0ZYaXEeSMzJufh3GDGA" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0ZoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0Z4aXEeSMzJufh3GDGA" x="753" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0aIaXEeSMzJufh3GDGA" type="3005" element="_AhxzpoaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0aYaXEeSMzJufh3GDGA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0aoaXEeSMzJufh3GDGA" x="160" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0a4aXEeSMzJufh3GDGA" type="3005" element="_AhxzsoaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0bIaXEeSMzJufh3GDGA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0bYaXEeSMzJufh3GDGA" x="294" y="91" width="134" height="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0boaXEeSMzJufh3GDGA" type="3005" element="_AhxzvoaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0b4aXEeSMzJufh3GDGA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0cIaXEeSMzJufh3GDGA" x="464" y="100"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Ahx0cYaXEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Ahx0coaXEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Ahx0c4aXEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Ahx0dIaXEeSMzJufh3GDGA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0dYaXEeSMzJufh3GDGA" x="231" y="176"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Ahx0doaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ahx0d4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Ahx0eIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Ahx0eYaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0eoaXEeSMzJufh3GDGA" width="1454" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Ahx0e4aXEeSMzJufh3GDGA"/>
    <edges xmi:type="notation:Connector" xmi:id="_Ahx0fIaXEeSMzJufh3GDGA" type="4001" element="_AhxzR4aXEeSMzJufh3GDGA" source="_Ahx0EoaXEeSMzJufh3GDGA" target="_Ahx0C4aXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0fYaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyZ0IaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyZ0YaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ0oaXEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ04aXEeSMzJufh3GDGA" type="4001" element="_AhxzSoaXEeSMzJufh3GDGA" source="_Ahx0NIaXEeSMzJufh3GDGA" target="_Ahx0FoaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyZ1IaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyZ1YaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyZ1oaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ14aXEeSMzJufh3GDGA" points="[0, 1, -66, -7]$[16, 1, -50, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ2IaXEeSMzJufh3GDGA" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ2YaXEeSMzJufh3GDGA" type="4001" element="_AhxzTYaXEeSMzJufh3GDGA" source="_Ahx0FoaXEeSMzJufh3GDGA" target="_Ahx0GYaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyZ2oaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyZ24aXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyZ3IaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ3YaXEeSMzJufh3GDGA" points="[0, 0, -41, 91]$[-9, -91, -50, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ3oaXEeSMzJufh3GDGA" id="(1.0,0.64)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ34aXEeSMzJufh3GDGA" type="4001" element="_AhxzUIaXEeSMzJufh3GDGA" source="_Ahx0PYaXEeSMzJufh3GDGA" target="_Ahx0Q4aXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyZ4IaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyZ4YaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyZ4oaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ44aXEeSMzJufh3GDGA" points="[0, 0, -5, -60]$[55, 51, 50, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ5IaXEeSMzJufh3GDGA" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ5YaXEeSMzJufh3GDGA" type="4001" element="_AhxzU4aXEeSMzJufh3GDGA" source="_Ahx0Q4aXEeSMzJufh3GDGA" target="_Ahx0QIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyZ5oaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyZ54aXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyZ6IaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ6YaXEeSMzJufh3GDGA" points="[0, 0, -60, 48]$[65, -35, 5, 13]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ6oaXEeSMzJufh3GDGA" id="(0.5583333333333333,0.7833333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ64aXEeSMzJufh3GDGA" type="4001" element="_AhxzVoaXEeSMzJufh3GDGA" source="_Ahx0N4aXEeSMzJufh3GDGA" target="_Ahx0IIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyZ7IaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyZ7YaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyZ7oaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ74aXEeSMzJufh3GDGA" points="[0, -8, -85, 2]$[78, 3, -7, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ8IaXEeSMzJufh3GDGA" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ8YaXEeSMzJufh3GDGA" type="4001" element="_AhxzWYaXEeSMzJufh3GDGA" source="_Ahx0OoaXEeSMzJufh3GDGA" target="_Ahx0KIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyZ8oaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyZ84aXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyZ9IaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ9YaXEeSMzJufh3GDGA" points="[0, 0, -142, -15]$[135, 28, -7, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ9oaXEeSMzJufh3GDGA" id="(1.0,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ94aXEeSMzJufh3GDGA" type="4001" element="_AhxzXIaXEeSMzJufh3GDGA" source="_Ahx0C4aXEeSMzJufh3GDGA" target="_Ahx0MIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyZ-IaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyZ-YaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyZ-oaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ-4aXEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ_IaXEeSMzJufh3GDGA" type="4001" element="_AhxzX4aXEeSMzJufh3GDGA" source="_Ahx0MIaXEeSMzJufh3GDGA" target="_Ahx0NIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyZ_YaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyZ_oaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyZ_4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaAIaXEeSMzJufh3GDGA" points="[-11, -22, -51, 47]$[42, -57, 2, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaAYaXEeSMzJufh3GDGA" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaAoaXEeSMzJufh3GDGA" id="(0.5333333333333333,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaA4aXEeSMzJufh3GDGA" type="4001" element="_AhxzZIaXEeSMzJufh3GDGA" source="_Ahx0MIaXEeSMzJufh3GDGA" target="_Ahx0N4aXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaBIaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaBYaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaBoaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaB4aXEeSMzJufh3GDGA" points="[-14, 1, -91, 0]$[52, -2, -25, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaCIaXEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaCYaXEeSMzJufh3GDGA" id="(0.20833333333333334,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaCoaXEeSMzJufh3GDGA" type="4001" element="_AhxzZ4aXEeSMzJufh3GDGA" source="_Ahx0GYaXEeSMzJufh3GDGA" target="_Ahx0LIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaC4aXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaDIaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaDYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaDoaXEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaD4aXEeSMzJufh3GDGA" id="(0.97,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaEIaXEeSMzJufh3GDGA" type="4001" element="_AhxzaoaXEeSMzJufh3GDGA" source="_Ahx0LIaXEeSMzJufh3GDGA" target="_Ahx0PYaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaEYaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaEoaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaE4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaFIaXEeSMzJufh3GDGA" points="[-11, -3, -65, 0]$[30, -1, -24, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaFYaXEeSMzJufh3GDGA" id="(1.0,0.813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaFoaXEeSMzJufh3GDGA" id="(0.025,0.18333333333333332)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaF4aXEeSMzJufh3GDGA" type="4001" element="_Ahxzb4aXEeSMzJufh3GDGA" source="_Ahx0LIaXEeSMzJufh3GDGA" target="_Ahx0OoaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaGIaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaGYaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaGoaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaG4aXEeSMzJufh3GDGA" points="[-4, -10, -40, -95]$[33, 84, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaHIaXEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaHYaXEeSMzJufh3GDGA" id="(0.025,0.4166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaHoaXEeSMzJufh3GDGA" type="4001" element="_AhxzcoaXEeSMzJufh3GDGA" source="_Ahx0QIaXEeSMzJufh3GDGA" target="_Ahx0JIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaH4aXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaIIaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaIYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaIoaXEeSMzJufh3GDGA" points="[0, 0, -75, -29]$[72, 14, -3, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaI4aXEeSMzJufh3GDGA" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaJIaXEeSMzJufh3GDGA" type="4001" element="_Ahxz3YaXEeSMzJufh3GDGA" source="_Ahx0YIaXEeSMzJufh3GDGA" target="_Ahx0aIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaJYaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaJoaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaJ4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaKIaXEeSMzJufh3GDGA" points="[-7, -2, -57, 0]$[46, -1, -4, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaKYaXEeSMzJufh3GDGA" id="(0.9666666666666667,0.5333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaKoaXEeSMzJufh3GDGA" id="(0.05,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaK4aXEeSMzJufh3GDGA" type="4001" element="_Ahxz4IaXEeSMzJufh3GDGA" source="_Ahx0aIaXEeSMzJufh3GDGA" target="_Ahx0a4aXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaLIaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaLYaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaLoaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaL4aXEeSMzJufh3GDGA" points="[0, -5, -35, 0]$[34, -6, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaMIaXEeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaMYaXEeSMzJufh3GDGA" id="(0.007462686567164179,0.4925373134328358)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaMoaXEeSMzJufh3GDGA" type="4001" element="_Ahxz44aXEeSMzJufh3GDGA" source="_Ahx0a4aXEeSMzJufh3GDGA" target="_Ahx0boaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaM4aXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaNIaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaNYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaNoaXEeSMzJufh3GDGA" points="[0, 1, -36, 0]$[36, 1, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaN4aXEeSMzJufh3GDGA" id="(1.0,0.4626865671641791)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaOIaXEeSMzJufh3GDGA" id="(0.0,0.46)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaOYaXEeSMzJufh3GDGA" type="4001" element="_Ahxz5oaXEeSMzJufh3GDGA" source="_Ahx0boaXEeSMzJufh3GDGA" target="_Ahx0XYaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaOoaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaO4aXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaPIaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaPYaXEeSMzJufh3GDGA" points="[0, -6, -40, 0]$[33, -7, -7, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaPoaXEeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaP4aXEeSMzJufh3GDGA" id="(0.07,0.46)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaQIaXEeSMzJufh3GDGA" type="4001" element="_Ahxz6YaXEeSMzJufh3GDGA" source="_Ahx0XYaXEeSMzJufh3GDGA" target="_Ahx0ZIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaQYaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaQoaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaQ4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaRIaXEeSMzJufh3GDGA" points="[0, -3, -59, 0]$[56, -3, -3, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaRYaXEeSMzJufh3GDGA" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaRoaXEeSMzJufh3GDGA" id="(0.1,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaR4aXEeSMzJufh3GDGA" type="4001" element="_AhxzdYaXEeSMzJufh3GDGA" source="_Ahx0DYaXEeSMzJufh3GDGA" target="_Ahx0N4aXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaSIaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaSYaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaSoaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaS4aXEeSMzJufh3GDGA" points="[0, -1, -194, 0]$[187, 0, -7, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaTIaXEeSMzJufh3GDGA" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaTYaXEeSMzJufh3GDGA" id="(0.058333333333333334,0.7333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaToaXEeSMzJufh3GDGA" type="4001" element="_AhxzeIaXEeSMzJufh3GDGA" source="_Ahx0G4aXEeSMzJufh3GDGA" target="_Ahx0RoaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaT4aXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaUIaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaUYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaUoaXEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaU4aXEeSMzJufh3GDGA" type="4001" element="_Ahxze4aXEeSMzJufh3GDGA" source="_Ahx0RoaXEeSMzJufh3GDGA" target="_Ahx0SYaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaVIaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AhyaVYaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaVoaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaV4aXEeSMzJufh3GDGA" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaWIaXEeSMzJufh3GDGA" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaWYaXEeSMzJufh3GDGA" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3tF0kIaXEeSMzJufh3GDGA" type="4001" element="_3s8qoIaXEeSMzJufh3GDGA" source="_uY5sYIaXEeSMzJufh3GDGA" target="_4_i68IaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3tF0k4aXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3tF0lIaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3tF0kYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3tF0koaXEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_83W6AIaXEeSMzJufh3GDGA" type="4001" element="_83WS8IaXEeSMzJufh3GDGA" source="_4_i68IaXEeSMzJufh3GDGA" target="_Ahx0JIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_83XhEIaXEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_83XhEYaXEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_83W6AYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_83W6AoaXEeSMzJufh3GDGA" points="[-42, -29, -51, 76]$[2, -92, -7, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_83YvMIaXEeSMzJufh3GDGA" id="(1.0,0.48333333333333334)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AhyaWoaXEeSMzJufh3GDGA" type="Form" element="_AhxzAoaXEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_AhyaW4aXEeSMzJufh3GDGA" type="2120" element="_AhxzA4aXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaXIaXEeSMzJufh3GDGA" type="5157"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyaXYaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_AhyaXoaXEeSMzJufh3GDGA" type="2126" element="_AhxzL4aXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaX4aXEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AhyaYIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaYYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AhyaYoaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyaY4aXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyaZIaXEeSMzJufh3GDGA" type="2131" element="_AhxzM4aXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaZYaXEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyaZoaXEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_AhyaZ4aXEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AhyaaIaXEeSMzJufh3GDGA" type="Form" element="_AhxLwYaXEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_AhyaaYaXEeSMzJufh3GDGA" type="2130" element="_AhxLwoaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaaoaXEeSMzJufh3GDGA" type="5148"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahyaa4aXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_AhyabIaXEeSMzJufh3GDGA" type="2126" element="_AhxL8oaXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyabYaXEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AhyaboaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ahyab4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AhyacIaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyacYaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyacoaXEeSMzJufh3GDGA" type="2131" element="_AhxL9oaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahyac4aXEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyadIaXEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_AhyadYaXEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AhyadoaXEeSMzJufh3GDGA" type="Form" element="_AhxME4aXEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_Ahyad4aXEeSMzJufh3GDGA" type="2120" element="_AhxMFIaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaeIaXEeSMzJufh3GDGA" type="5157"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyaeYaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_AhyaeoaXEeSMzJufh3GDGA" type="2126" element="_AhxMRIaXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahyae4aXEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AhyafIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyafYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AhyafoaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahyaf4aXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyagIaXEeSMzJufh3GDGA" type="2131" element="_AhxMSIaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyagYaXEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyagoaXEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Ahyag4aXEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AhyahIaXEeSMzJufh3GDGA" type="Form" element="_AhxMZIaXEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_AhyahYaXEeSMzJufh3GDGA" type="2130" element="_AhxMZYaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyahoaXEeSMzJufh3GDGA" type="5148"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahyah4aXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_AhyaiIaXEeSMzJufh3GDGA" type="2126" element="_AhxMlYaXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaiYaXEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AhyaioaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ahyai4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AhyajIaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyajYaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyajoaXEeSMzJufh3GDGA" type="2131" element="_AhxMmYaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahyaj4aXEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyakIaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyakYaXEeSMzJufh3GDGA" type="2131" element="_AhxMp4aXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyakoaXEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahyak4aXEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_AhyalIaXEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AhyalYaXEeSMzJufh3GDGA" type="Form" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_AhyaloaXEeSMzJufh3GDGA" type="2126">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahyal4aXEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AhyamIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyamYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AhyamoaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahyam4aXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyanIaXEeSMzJufh3GDGA" type="2131" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyanYaXEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyanoaXEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Ahyan4aXEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_CO_tEIaYEeSMzJufh3GDGA" type="Form" element="_CO9Q0IaYEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_CPsQoIaYEeSMzJufh3GDGA" type="2126" element="_CO9Q0YaYEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_CPsQpYaYEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_CPsQoYaYEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_CPsQooaYEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_CPsQo4aYEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CPsQpIaYEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_IIwVwIaYEeSMzJufh3GDGA" type="2131" element="_IIvHoIaYEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_IIwVwoaYEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IIwVwYaYEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_CO_tEYaYEeSMzJufh3GDGA"/>
  </notation:Diagram>
</xmi:XMI>
