<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_bkB8UIaQEeSMzJufh3GDGA" name="Projet_Validation_Diagram_CORTES_MARTINEZ" version="3.0" author="corteshs" bonitaVersion="6.1.1" bonitaModelVersion="6.1.1-001" configId="ACED000574003750726F6A65745F56616C69646174696F6E5F4469616772616D5F434F525445535F4D415254494E455A362E312E312D303031362E312E31">
    <elements xmi:type="process:Pool" xmi:id="_bkB8UYaQEeSMzJufh3GDGA" name="Projet_Validation_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="3.0">
      <elements xmi:type="process:Lane" xmi:id="_bkB8UoaQEeSMzJufh3GDGA" name="Employé (lane)" actor="_bkDx-oaQEeSMzJufh3GDGA">
        <elements xmi:type="process:Task" xmi:id="_bkB8U4aQEeSMzJufh3GDGA" name="Approve proposal" outgoing="_bkDx4YaQEeSMzJufh3GDGA" incoming="_bkDxzIaQEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkB8VIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkB8VYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkB8VoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkB8V4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_bkB8WIaQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_bkB8WYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_bkB8WoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bkB8W4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bkB8XIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_bkB8XYaQEeSMzJufh3GDGA" name="ApproveProposal" nLine="3">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_bkB8XoaQEeSMzJufh3GDGA" name="proposalOK1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkB8X4aQEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkB8YIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkB8YYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_bkB8YoaQEeSMzJufh3GDGA" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_bkB8Y4aQEeSMzJufh3GDGA" name="proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_bkB8ZIaQEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkB8ZYaQEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_bkB8ZoaQEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_bkB8Z4aQEeSMzJufh3GDGA" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="_bkB8aIaQEeSMzJufh3GDGA" name="proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_bkB8aYaQEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                  </referencedElements>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_bkB8aoaQEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_bkB8a4aQEeSMzJufh3GDGA" name="field_proposalOK1" content="field_proposalOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_bkB8bIaQEeSMzJufh3GDGA" name="proposalOK1">
                    <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkB8bYaQEeSMzJufh3GDGA" line="1"/>
                    <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkB8boaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkB8b4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <inputExpression xmi:type="expression:Expression" xmi:id="_bkB8cIaQEeSMzJufh3GDGA" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                      <referencedElements xmi:type="process:Data" xmi:id="_bkB8cYaQEeSMzJufh3GDGA" name="proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
                        <defaultValue xmi:type="expression:Expression" xmi:id="_bkB8coaQEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                      </referencedElements>
                    </inputExpression>
                    <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkB8c4aQEeSMzJufh3GDGA" name="" content=""/>
                    <action xmi:type="expression:Operation" xmi:id="_bkB8dIaQEeSMzJufh3GDGA">
                      <leftOperand xmi:type="expression:Expression" xmi:id="_bkB8dYaQEeSMzJufh3GDGA"/>
                      <operator xmi:type="expression:Operator" xmi:id="_bkB8doaQEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                      <rightOperand xmi:type="expression:Expression" xmi:id="_bkB8d4aQEeSMzJufh3GDGA"/>
                    </action>
                    <tooltip xmi:type="expression:Expression" xmi:id="_bkB8eIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <helpMessage xmi:type="expression:Expression" xmi:id="_bkB8eYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabel xmi:type="expression:Expression" xmi:id="_bkB8eoaQEeSMzJufh3GDGA" name="proposalOK1" content="proposalOK1" returnTypeFixed="true"/>
                    <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkB8e4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkB8fIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkB8fYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_bkB8foaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForAdd xmi:type="expression:Expression" xmi:id="_bkB8f4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_bkB8gIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForRemove xmi:type="expression:Expression" xmi:id="_bkB8gYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <exampleMessage xmi:type="expression:Expression" xmi:id="_bkB8goaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                  </referencedElements>
                </rightOperand>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_bkB8g4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_bkB8hIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_bkB8hYaQEeSMzJufh3GDGA" name="Approved?" content="Approved?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkB8hoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkB8h4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkB8iIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_bkB8iYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_bkB8ioaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_bkB8i4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_bkB8jIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_bkB8jYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_bkB8joaQEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkB8j4aQEeSMzJufh3GDGA" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_bkB8kIaQEeSMzJufh3GDGA" name="OK" content="OK" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkB8kYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_bkB8koaQEeSMzJufh3GDGA" name="proposal1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkB8k4aQEeSMzJufh3GDGA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkB8lIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkB8lYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_bkB8loaQEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_bkB8l4aQEeSMzJufh3GDGA" name="proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_bkB8mIaQEeSMzJufh3GDGA" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkB8mYaQEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_bkB8moaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_bkB8m4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkB8nIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_bkB8nYaQEeSMzJufh3GDGA" name="Approve proposal" content="Approve proposal" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_bkB8noaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_bkB8n4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_bkB8oIaQEeSMzJufh3GDGA" name="Proposal made" outgoing="_bkDxzIaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkB8oYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkB8ooaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkB8o4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkB8pIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_bkB8pYaQEeSMzJufh3GDGA" name="Analyze Impact" outgoing="_bkDx0oaQEeSMzJufh3GDGA" incoming="_bkDxz4aQEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkB8poaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkB8p4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkB8qIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkB8qYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_bkB8qoaQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_bkB8q4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_bkCjYIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bkCjYYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bkCjYoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_bkCjY4aQEeSMzJufh3GDGA" name="AnalyzeImpact" nLine="3">
            <widgets xmi:type="form:TextFormField" xmi:id="_bkCjZIaQEeSMzJufh3GDGA" name="impacts1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkCjZYaQEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkCjZoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkCjZ4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_bkCjaIaQEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_bkCjaYaQEeSMzJufh3GDGA" name="impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_bkCjaoaQEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkCja4aQEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_bkCjbIaQEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_bkCjbYaQEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                  <referencedElements xmi:type="process:Data" xmi:id="_bkCjboaQEeSMzJufh3GDGA" name="impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_bkCjb4aQEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                  </referencedElements>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_bkCjcIaQEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_bkCjcYaQEeSMzJufh3GDGA" name="field_impacts1" content="field_impacts1" type="TYPE_INPUT">
                  <referencedElements xmi:type="form:TextFormField" xmi:id="_bkCjcoaQEeSMzJufh3GDGA" name="impacts1">
                    <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkCjc4aQEeSMzJufh3GDGA"/>
                    <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkCjdIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkCjdYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <inputExpression xmi:type="expression:Expression" xmi:id="_bkCjdoaQEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_bkCjd4aQEeSMzJufh3GDGA" name="impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA">
                        <defaultValue xmi:type="expression:Expression" xmi:id="_bkCjeIaQEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                      </referencedElements>
                    </inputExpression>
                    <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkCjeYaQEeSMzJufh3GDGA" name="" content=""/>
                    <action xmi:type="expression:Operation" xmi:id="_bkCjeoaQEeSMzJufh3GDGA">
                      <leftOperand xmi:type="expression:Expression" xmi:id="_bkCje4aQEeSMzJufh3GDGA"/>
                      <operator xmi:type="expression:Operator" xmi:id="_bkCjfIaQEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                      <rightOperand xmi:type="expression:Expression" xmi:id="_bkCjfYaQEeSMzJufh3GDGA"/>
                    </action>
                    <tooltip xmi:type="expression:Expression" xmi:id="_bkCjfoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <helpMessage xmi:type="expression:Expression" xmi:id="_bkCjf4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabel xmi:type="expression:Expression" xmi:id="_bkCjgIaQEeSMzJufh3GDGA" name="impacts1" content="impacts1" returnTypeFixed="true"/>
                    <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkCjgYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkCjgoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkCjg4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_bkCjhIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForAdd xmi:type="expression:Expression" xmi:id="_bkCjhYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_bkCjhoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForRemove xmi:type="expression:Expression" xmi:id="_bkCjh4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <exampleMessage xmi:type="expression:Expression" xmi:id="_bkCjiIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                  </referencedElements>
                </rightOperand>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_bkCjiYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_bkCjioaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_bkCji4aQEeSMzJufh3GDGA" name="Impact?" content="Impact?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkCjjIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkCjjYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkCjjoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_bkCjj4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_bkCjkIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_bkCjkYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_bkCjkoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_bkCjk4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_bkCjlIaQEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkCjlYaQEeSMzJufh3GDGA" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_bkCjloaQEeSMzJufh3GDGA" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkCjl4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_bkCjmIaQEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_bkCjmYaQEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_bkCjmoaQEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkCjm4aQEeSMzJufh3GDGA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkCjnIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkCjnYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_bkCjnoaQEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_bkCjn4aQEeSMzJufh3GDGA" name="proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_bkCjoIaQEeSMzJufh3GDGA" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkCjoYaQEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_bkCjooaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_bkCjo4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkCjpIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_bkCjpYaQEeSMzJufh3GDGA" name="Analyze Impact" content="Analyze Impact" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_bkCjpoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_bkCjp4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_bkCjyIaQEeSMzJufh3GDGA" name="Validate project" outgoing="_bkDx7IaQEeSMzJufh3GDGA" incoming="_bkDx0oaQEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkCjyYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkCjyoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkCjy4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkCjzIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_bkCjzYaQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_bkCjzoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_bkCjz4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bkCj0IaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bkCj0YaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_bkCj0oaQEeSMzJufh3GDGA" name="ValidateProject">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_bkCj04aQEeSMzJufh3GDGA" name="projectOK1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkCj1IaQEeSMzJufh3GDGA" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkCj1YaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkCj1oaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_bkCj14aQEeSMzJufh3GDGA" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_bkCj2IaQEeSMzJufh3GDGA" name="projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_bkCj2YaQEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkCj2oaQEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_bkCj24aQEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_bkCj3IaQEeSMzJufh3GDGA" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="_bkCj3YaQEeSMzJufh3GDGA" name="projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_bkCj3oaQEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                  </referencedElements>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_bkCj34aQEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_bkCj4IaQEeSMzJufh3GDGA" name="field_projectOK1" content="field_projectOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_bkCj4YaQEeSMzJufh3GDGA" name="projectOK1">
                    <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkCj4oaQEeSMzJufh3GDGA" line="1"/>
                    <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkCj44aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkCj5IaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <inputExpression xmi:type="expression:Expression" xmi:id="_bkCj5YaQEeSMzJufh3GDGA" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                      <referencedElements xmi:type="process:Data" xmi:id="_bkCj5oaQEeSMzJufh3GDGA" name="projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
                        <defaultValue xmi:type="expression:Expression" xmi:id="_bkCj54aQEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                      </referencedElements>
                    </inputExpression>
                    <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkCj6IaQEeSMzJufh3GDGA" name="" content=""/>
                    <action xmi:type="expression:Operation" xmi:id="_bkCj6YaQEeSMzJufh3GDGA">
                      <leftOperand xmi:type="expression:Expression" xmi:id="_bkCj6oaQEeSMzJufh3GDGA"/>
                      <operator xmi:type="expression:Operator" xmi:id="_bkCj64aQEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                      <rightOperand xmi:type="expression:Expression" xmi:id="_bkDKcIaQEeSMzJufh3GDGA"/>
                    </action>
                    <tooltip xmi:type="expression:Expression" xmi:id="_bkDKcYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <helpMessage xmi:type="expression:Expression" xmi:id="_bkDKcoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabel xmi:type="expression:Expression" xmi:id="_bkDKc4aQEeSMzJufh3GDGA" name="projectOK1" content="projectOK1" returnTypeFixed="true"/>
                    <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkDKdIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkDKdYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkDKdoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_bkDKd4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForAdd xmi:type="expression:Expression" xmi:id="_bkDKeIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_bkDKeYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForRemove xmi:type="expression:Expression" xmi:id="_bkDKeoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <exampleMessage xmi:type="expression:Expression" xmi:id="_bkDKe4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                  </referencedElements>
                </rightOperand>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_bkDKfIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_bkDKfYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_bkDKfoaQEeSMzJufh3GDGA" name="Approve project?" content="Approve project?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkDKf4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkDKgIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkDKgYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_bkDKgoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_bkDKg4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_bkDKhIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_bkDKhYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_bkDKhoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_bkDKh4aQEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkDKiIaQEeSMzJufh3GDGA" line="3"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_bkDKiYaQEeSMzJufh3GDGA" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkDKioaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_bkDKi4aQEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_bkDKjIaQEeSMzJufh3GDGA" key="input_css:color" value="purple"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_bkDKjYaQEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_bkDKjoaQEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkDKj4aQEeSMzJufh3GDGA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkDKkIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkDKkYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_bkDKkoaQEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_bkDKk4aQEeSMzJufh3GDGA" name="proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_bkDKlIaQEeSMzJufh3GDGA" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkDKlYaQEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_bkDKloaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_bkDKl4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkDKmIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_bkDKmYaQEeSMzJufh3GDGA" name="impacts1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_bkDKmoaQEeSMzJufh3GDGA" key="input_css:color" value="red"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_bkDKm4aQEeSMzJufh3GDGA" key="input_css:font-size" value="18px"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkDKnIaQEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkDKnYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkDKnoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_bkDKn4aQEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_bkDKoIaQEeSMzJufh3GDGA" name="impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_bkDKoYaQEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkDKooaQEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_bkDKo4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_bkDKpIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkDKpYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_bkDKpoaQEeSMzJufh3GDGA" name="Validate project" content="Validate project" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDKp4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_bkDKqIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_bkDKqYaQEeSMzJufh3GDGA" name="Proposal refused" incoming="_bkDx24aQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDKqoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkDKq4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkDKrIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkDKrYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_bkDKroaQEeSMzJufh3GDGA" name="Project finished" incoming="_bkDx94aQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDKr4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkDKsIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkDKsYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkDKsoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_bkDKs4aQEeSMzJufh3GDGA" name="Project refused" incoming="_bkDx3oaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDKtIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkDKtYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkDKtoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkDKt4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_bkDKuIaQEeSMzJufh3GDGA" name="Project approval?" outgoing="_bkDx74aQEeSMzJufh3GDGA _bkDx9IaQEeSMzJufh3GDGA" incoming="_bkDx7IaQEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDKuYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkDKuoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkDKu4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkDKvIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_bkDKvYaQEeSMzJufh3GDGA" name="Proposal approval?" outgoing="_bkDx5IaQEeSMzJufh3GDGA _bkDx6YaQEeSMzJufh3GDGA" incoming="_bkDx4YaQEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDKvoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkDKv4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkDKwIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkDKwYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_bkDKwoaQEeSMzJufh3GDGA" name="Notify proposal aproved" outgoing="_bkDxz4aQEeSMzJufh3GDGA" incoming="_bkDx5IaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDKw4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkDKxIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkDKxYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkDKxoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_bkDKx4aQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_bkDKyIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_bkDKyYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bkDKyoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bkDKy4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_bkDKzIaQEeSMzJufh3GDGA" name="Notify proposal refusal" outgoing="_bkDx24aQEeSMzJufh3GDGA" incoming="_bkDx6YaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDKzYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkDKzoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkDKz4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkDK0IaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_bkDK0YaQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_bkDK0oaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_bkDK04aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bkDK1IaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bkDK1YaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_bkDK1oaQEeSMzJufh3GDGA" name="Notify project refused" outgoing="_bkDx3oaQEeSMzJufh3GDGA" incoming="_bkDx9IaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDK14aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkDK2IaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkDK2YaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkDK2oaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_bkDK24aQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_bkDK3IaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_bkDK3YaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bkDK3oaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bkDK34aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_bkDK4IaQEeSMzJufh3GDGA" name="Notify project accepted" outgoing="_bkDx1YaQEeSMzJufh3GDGA" incoming="_bkDx74aQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDK4YaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkDK4oaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkDK44aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkDK5IaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_bkDK5YaQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_bkDK5oaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_bkDK54aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bkDK6IaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bkDK6YaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_bkDK6oaQEeSMzJufh3GDGA" name="Notify project delivery" outgoing="_bkDx94aQEeSMzJufh3GDGA" incoming="_bkDx2IaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDK64aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bkDK7IaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bkDK7YaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bkDK7oaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_bkDK74aQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_bkDK8IaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_bkDK8YaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bkDK8oaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bkDK84aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_ebw-cIaQEeSMzJufh3GDGA" name="Do project" outgoing="_bkDx2IaQEeSMzJufh3GDGA" incoming="_bkDx1YaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_ebw-dIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ebw-coaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ebw-cYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ebw-c4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_ebxlgYaQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_ebxlgoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_ebxlg4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ebw-d4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ebxlgIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_edIQYIaQEeSMzJufh3GDGA" processSource="_bkDK-4aQEeSMzJufh3GDGA" subprocessTarget="sub_proposal"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_edI3coaQEeSMzJufh3GDGA" processSource="_bkDxgYaQEeSMzJufh3GDGA" subprocessTarget="sub_proposalOK"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_edI3dYaQEeSMzJufh3GDGA" processSource="_bkDxg4aQEeSMzJufh3GDGA" subprocessTarget="sub_projectOK"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_edI3eIaQEeSMzJufh3GDGA" processSource="_bkDxhYaQEeSMzJufh3GDGA" subprocessTarget="sub_impacts"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_Co8F0IaSEeSMzJufh3GDGA" subprocessSource="sub_proposal" processTarget="_bkDK-4aQEeSMzJufh3GDGA"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_CsskcIaSEeSMzJufh3GDGA" subprocessSource="sub_proposalOK" processTarget="_bkDxgYaQEeSMzJufh3GDGA"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_Cs0gQIaSEeSMzJufh3GDGA" subprocessSource="sub_projectOK" processTarget="_bkDxg4aQEeSMzJufh3GDGA"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_Cs8cEIaSEeSMzJufh3GDGA" subprocessSource="sub_impacts" processTarget="_bkDxhYaQEeSMzJufh3GDGA"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_tgY0MIaQEeSMzJufh3GDGA" name="Do_project_CORTES_MARTINEZ" content="Do_project_CORTES_MARTINEZ" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_ebw-doaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_boflkIaQEeSMzJufh3GDGA" path="_bkB8UYaQEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_bkDK9YaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_bkDK9oaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_bkDK94aQEeSMzJufh3GDGA" path="_bkB8UYaQEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_bkDK-IaQEeSMzJufh3GDGA" path="_bkB8UYaQEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_bkDK-YaQEeSMzJufh3GDGA" path="_bkB8UYaQEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_bkDK-oaQEeSMzJufh3GDGA" path="_bkB8UYaQEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_bkDK-4aQEeSMzJufh3GDGA" name="proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_bkDxgIaQEeSMzJufh3GDGA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_bkDxgYaQEeSMzJufh3GDGA" name="proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_bkDxgoaQEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_bkDxg4aQEeSMzJufh3GDGA" name="projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_bkDxhIaQEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_bkDxhYaQEeSMzJufh3GDGA" name="impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_bkDxhoaQEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <form xmi:type="form:Form" xmi:id="_bkDxh4aQEeSMzJufh3GDGA" name="Project_Validation_CORTES_MARTINEZ" nLine="3">
        <widgets xmi:type="form:TextFormField" xmi:id="_bkDxiIaQEeSMzJufh3GDGA" name="proposal1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkDxiYaQEeSMzJufh3GDGA" line="1"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkDxioaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkDxi4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_bkDxjIaQEeSMzJufh3GDGA" name="" content=""/>
          <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkDxjYaQEeSMzJufh3GDGA" name="" content=""/>
          <action xmi:type="expression:Operation" xmi:id="_bkDxjoaQEeSMzJufh3GDGA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_bkDxj4aQEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_bkDxkIaQEeSMzJufh3GDGA" name="proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_bkDxkYaQEeSMzJufh3GDGA" content=""/>
              </referencedElements>
            </leftOperand>
            <operator xmi:type="expression:Operator" xmi:id="_bkDxkoaQEeSMzJufh3GDGA" type="ASSIGNMENT"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_bkDxk4aQEeSMzJufh3GDGA" name="field_proposal1" content="field_proposal1" type="TYPE_INPUT">
              <referencedElements xmi:type="form:TextFormField" xmi:id="_bkDxlIaQEeSMzJufh3GDGA" name="proposal1">
                <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkDxlYaQEeSMzJufh3GDGA"/>
                <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkDxloaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkDxl4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                <inputExpression xmi:type="expression:Expression" xmi:id="_bkDxmIaQEeSMzJufh3GDGA" name="" content=""/>
                <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkDxmYaQEeSMzJufh3GDGA" name="" content=""/>
                <action xmi:type="expression:Operation" xmi:id="_bkDxmoaQEeSMzJufh3GDGA">
                  <leftOperand xmi:type="expression:Expression" xmi:id="_bkDxm4aQEeSMzJufh3GDGA"/>
                  <operator xmi:type="expression:Operator" xmi:id="_bkDxnIaQEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                  <rightOperand xmi:type="expression:Expression" xmi:id="_bkDxnYaQEeSMzJufh3GDGA"/>
                </action>
                <tooltip xmi:type="expression:Expression" xmi:id="_bkDxnoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <helpMessage xmi:type="expression:Expression" xmi:id="_bkDxn4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <displayLabel xmi:type="expression:Expression" xmi:id="_bkDxoIaQEeSMzJufh3GDGA" name="proposal1" content="proposal1" returnTypeFixed="true"/>
                <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkDxoYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkDxooaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkDxo4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_bkDxpIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <tooltipForAdd xmi:type="expression:Expression" xmi:id="_bkDxpYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_bkDxpoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <tooltipForRemove xmi:type="expression:Expression" xmi:id="_bkDxp4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <exampleMessage xmi:type="expression:Expression" xmi:id="_bkDxqIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              </referencedElements>
            </rightOperand>
          </action>
          <tooltip xmi:type="expression:Expression" xmi:id="_bkDxqYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:type="expression:Expression" xmi:id="_bkDxqoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_bkDxq4aQEeSMzJufh3GDGA" name="Proposal" content="Proposal" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkDxrIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkDxrYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_bkDxroaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_bkDxr4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <tooltipForAdd xmi:type="expression:Expression" xmi:id="_bkDxsIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_bkDxsYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <tooltipForRemove xmi:type="expression:Expression" xmi:id="_bkDxsoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <exampleMessage xmi:type="expression:Expression" xmi:id="_bkDxs4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </widgets>
        <widgets xmi:type="form:SubmitFormButton" xmi:id="_bkDxtIaQEeSMzJufh3GDGA" name="Soumettre1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkDxtYaQEeSMzJufh3GDGA" line="2"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_bkDxtoaQEeSMzJufh3GDGA" name="OK" content="OK" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkDxt4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <widgets xmi:type="form:MessageInfo" xmi:id="_bkDxuIaQEeSMzJufh3GDGA" name="Enter proposal:">
          <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_bkDxuYaQEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_bkDxuoaQEeSMzJufh3GDGA"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_bkDxu4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_bkDxvIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_bkDxvYaQEeSMzJufh3GDGA" name="" content=""/>
          <afterEventExpression xmi:type="expression:Expression" xmi:id="_bkDxvoaQEeSMzJufh3GDGA" name="" content=""/>
          <action xmi:type="expression:Operation" xmi:id="_bkDxv4aQEeSMzJufh3GDGA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_bkDxwIaQEeSMzJufh3GDGA"/>
            <operator xmi:type="expression:Operator" xmi:id="_bkDxwYaQEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_bkDxwoaQEeSMzJufh3GDGA"/>
          </action>
          <tooltip xmi:type="expression:Expression" xmi:id="_bkDxw4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:type="expression:Expression" xmi:id="_bkDxxIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_bkDxxYaQEeSMzJufh3GDGA" name="Message1" content="Message1" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_bkDxxoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:type="expression:Expression" xmi:id="_bkDxx4aQEeSMzJufh3GDGA" name="Propose proposal" content="Propose proposal" returnTypeFixed="true"/>
      </form>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDxyIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_bkDxyYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDxyoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bkDxy4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDxzIaQEeSMzJufh3GDGA" source="_bkB8oIaQEeSMzJufh3GDGA" target="_bkB8U4aQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDxzYaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDxzoaQEeSMzJufh3GDGA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDxz4aQEeSMzJufh3GDGA" source="_bkDKwoaQEeSMzJufh3GDGA" target="_bkB8pYaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx0IaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx0YaQEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx0oaQEeSMzJufh3GDGA" source="_bkB8pYaQEeSMzJufh3GDGA" target="_bkCjyIaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx04aQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx1IaQEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx1YaQEeSMzJufh3GDGA" source="_bkDK4IaQEeSMzJufh3GDGA" target="_ebw-cIaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx1oaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx14aQEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx2IaQEeSMzJufh3GDGA" source="_ebw-cIaQEeSMzJufh3GDGA" target="_bkDK6oaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx2YaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx2oaQEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx24aQEeSMzJufh3GDGA" source="_bkDKzIaQEeSMzJufh3GDGA" target="_bkDKqYaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx3IaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx3YaQEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx3oaQEeSMzJufh3GDGA" source="_bkDK1oaQEeSMzJufh3GDGA" target="_bkDKs4aQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx34aQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx4IaQEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx4YaQEeSMzJufh3GDGA" source="_bkB8U4aQEeSMzJufh3GDGA" target="_bkDKvYaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx4oaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx44aQEeSMzJufh3GDGA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx5IaQEeSMzJufh3GDGA" name="Approved" source="_bkDKvYaQEeSMzJufh3GDGA" target="_bkDKwoaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx5YaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx5oaQEeSMzJufh3GDGA" name="proposalOK==true" content="proposalOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_bkDx54aQEeSMzJufh3GDGA" name="proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_bkDx6IaQEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx6YaQEeSMzJufh3GDGA" name="Not Approved" source="_bkDKvYaQEeSMzJufh3GDGA" target="_bkDKzIaQEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx6oaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx64aQEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx7IaQEeSMzJufh3GDGA" source="_bkCjyIaQEeSMzJufh3GDGA" target="_bkDKuIaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx7YaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx7oaQEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx74aQEeSMzJufh3GDGA" name="Approved" source="_bkDKuIaQEeSMzJufh3GDGA" target="_bkDK4IaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx8IaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx8YaQEeSMzJufh3GDGA" name="projectOK==true" content="projectOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_bkDx8oaQEeSMzJufh3GDGA" name="projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_bkDx84aQEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx9IaQEeSMzJufh3GDGA" name="Not approved" source="_bkDKuIaQEeSMzJufh3GDGA" target="_bkDK1oaQEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx9YaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx9oaQEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bkDx94aQEeSMzJufh3GDGA" source="_bkDK6oaQEeSMzJufh3GDGA" target="_bkDKroaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bkDx-IaQEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bkDx-YaQEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_bkDx-oaQEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_bkDx-4aQEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_bkDx_IaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_bkDx_YaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_bkDx_oaQEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_bkDx_4aQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_bkDyAIaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_bkDyAYaQEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_bkDyAoaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_bkDyA4aQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_bkDyBIaQEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_bkDyBYaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_bkDyBoaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_bkDyB4aQEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_bkDyCIaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_bkDyCYaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_eWxwwIaQEeSMzJufh3GDGA" name="Do_project_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Lane" xmi:id="_RUV_wIaREeSMzJufh3GDGA" name="Research and Development" actor="_edEmAIaQEeSMzJufh3GDGA">
        <elements xmi:type="process:Task" xmi:id="_edFNEIaQEeSMzJufh3GDGA" name="Deploy" outgoing="_HKrBEIaREeSMzJufh3GDGA" incoming="_Gi2MEIaREeSMzJufh3GDGA" actor="_edEmAIaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_edFNEYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_edFNEoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_edFNE4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_edFNFIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_edFNFYaQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_edFNFoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_edFNF4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_edFNGIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_edFNGYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_edFNLoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_edFNL4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_xZbiUIaQEeSMzJufh3GDGA" name="Start project" outgoing="_ECP3kIaREeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_xZcJY4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xZcJYYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xZcJYIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xZcJYoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_y0oVAIaQEeSMzJufh3GDGA" name="Project finished" incoming="_HKrBEIaREeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_y0o8E4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_y0o8EYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_y0o8EIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_y0o8EoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_3LfnkIaQEeSMzJufh3GDGA" name="Specify" outgoing="_FW7ykIaREeSMzJufh3GDGA" incoming="_ECP3kIaREeSMzJufh3GDGA" actor="_edEmAIaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_3LgOo4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3LgOoYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3LgOoIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3LgOooaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_3LgOqIaQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_3LgOqYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_3LgOqoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3LgOpIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3LgOpYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_3LgOpoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_3LgOp4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5ziA0IaQEeSMzJufh3GDGA" name="Implement" outgoing="_F-ndoIaREeSMzJufh3GDGA" incoming="_FW7ykIaREeSMzJufh3GDGA" actor="_edEmAIaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_5zrx04aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5zrx0YaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5zrx0IaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5zrx0oaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_5zrx2IaQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_5zrx2YaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_5zrx2oaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5zrx1IaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5zrx1YaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_5zrx1oaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_5zrx14aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_-5CiEIaQEeSMzJufh3GDGA" name="Test" outgoing="_Gi2MEIaREeSMzJufh3GDGA" incoming="_F-ndoIaREeSMzJufh3GDGA" actor="_edEmAIaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_-5NhM4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-5NhMYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-5NhMIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-5NhMoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_-5NhOIaQEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_-5NhOYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_-5NhOoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-5NhNIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-5NhNYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_-5NhNoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_-5NhN4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_ebn0gIaQEeSMzJufh3GDGA" path="_eWxwwIaQEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_eWzmAYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_eWzmAIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_ebn0g4aQEeSMzJufh3GDGA" path="_eWxwwIaQEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_ebn0gYaQEeSMzJufh3GDGA" path="_eWxwwIaQEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_ebn0hIaQEeSMzJufh3GDGA" path="_eWxwwIaQEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_ebn0goaQEeSMzJufh3GDGA" path="_eWxwwIaQEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_edHpUIaQEeSMzJufh3GDGA" name="sub_proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_97zoUIaREeSMzJufh3GDGA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_edI3cIaQEeSMzJufh3GDGA" name="sub_proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_-ZTcoIaREeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_edI3c4aQEeSMzJufh3GDGA" name="sub_projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_9aGCYIaREeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_edI3doaQEeSMzJufh3GDGA" name="sub_impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_3IPCwIaREeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_eWzmA4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_eWzmAoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_eWzmBIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_eWzl_4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ECP3kIaREeSMzJufh3GDGA" source="_xZbiUIaQEeSMzJufh3GDGA" target="_3LfnkIaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ECP3kYaREeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_ECQeoIaREeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FW7ykIaREeSMzJufh3GDGA" source="_3LfnkIaQEeSMzJufh3GDGA" target="_5ziA0IaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FW8ZoIaREeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_FW8ZoYaREeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_F-ndoIaREeSMzJufh3GDGA" source="_5ziA0IaQEeSMzJufh3GDGA" target="_-5CiEIaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_F-ndoYaREeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_F-oEsIaREeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Gi2MEIaREeSMzJufh3GDGA" source="_-5CiEIaQEeSMzJufh3GDGA" target="_edFNEIaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Gi2MEYaREeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Gi2MEoaREeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HKrBEIaREeSMzJufh3GDGA" source="_edFNEIaQEeSMzJufh3GDGA" target="_y0oVAIaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HKroIIaREeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_HKroIYaREeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_edEmAIaQEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eWzl8IaQEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_eWzl8YaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eWzl8oaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eWzl84aQEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_eWzl9IaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eWzl9YaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eWzl9oaQEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_eWzl94aQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eWzl-IaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eWzl-YaQEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_eWzl-oaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eWzl-4aQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eWzl_IaQEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_eWzl_YaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eWzl_oaQEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_bkDyCoaQEeSMzJufh3GDGA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_bkDyC4aQEeSMzJufh3GDGA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_bkDyDIaQEeSMzJufh3GDGA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_bkDyDYaQEeSMzJufh3GDGA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_bkDyDoaQEeSMzJufh3GDGA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_bkDyD4aQEeSMzJufh3GDGA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_bkDyEIaQEeSMzJufh3GDGA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_bkDyEYaQEeSMzJufh3GDGA" name="XML"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_bkEYkIaQEeSMzJufh3GDGA" type="Process" element="_bkB8UIaQEeSMzJufh3GDGA" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_bkEYkYaQEeSMzJufh3GDGA" type="2007" element="_bkB8UYaQEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkEYkoaQEeSMzJufh3GDGA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_bkEYk4aQEeSMzJufh3GDGA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_bkEYlIaQEeSMzJufh3GDGA" type="3007" element="_bkB8UoaQEeSMzJufh3GDGA">
          <children xmi:type="notation:DecorationNode" xmi:id="_bkEYlYaQEeSMzJufh3GDGA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_bkEYloaQEeSMzJufh3GDGA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_bkEYl4aQEeSMzJufh3GDGA" type="3005" element="_bkB8U4aQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYmIaQEeSMzJufh3GDGA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYmYaQEeSMzJufh3GDGA" x="119" y="165"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYmoaQEeSMzJufh3GDGA" type="3002" element="_bkB8oIaQEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYm4aQEeSMzJufh3GDGA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEYnIaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYnYaQEeSMzJufh3GDGA" x="40" y="179"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYnoaQEeSMzJufh3GDGA" type="3005" element="_bkB8pYaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYn4aQEeSMzJufh3GDGA" type="5005" element="_bkB8pYaQEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYoIaQEeSMzJufh3GDGA" x="421" y="102"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYpIaQEeSMzJufh3GDGA" type="3005" element="_bkCjyIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYpYaQEeSMzJufh3GDGA" type="5005" element="_bkCjyIaQEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYpoaQEeSMzJufh3GDGA" x="556" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYp4aQEeSMzJufh3GDGA" type="3062" element="_bkDKqYaQEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYqIaQEeSMzJufh3GDGA" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEYqYaQEeSMzJufh3GDGA" x="-1" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYqoaQEeSMzJufh3GDGA" x="537" y="197"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYq4aQEeSMzJufh3GDGA" type="3062" element="_bkDKroaQEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYrIaQEeSMzJufh3GDGA" type="5090" element="_bkDKroaQEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEYrYaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYroaQEeSMzJufh3GDGA" x="1221" y="136"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYr4aQEeSMzJufh3GDGA" type="3062" element="_bkDKs4aQEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYsIaQEeSMzJufh3GDGA" type="5090" element="_bkDKs4aQEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEYsYaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYsoaQEeSMzJufh3GDGA" x="1012" y="226"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYs4aQEeSMzJufh3GDGA" type="3008" element="_bkDKuIaQEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYtIaQEeSMzJufh3GDGA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEYtYaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYtoaQEeSMzJufh3GDGA" x="689" y="105" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYt4aQEeSMzJufh3GDGA" type="3008" element="_bkDKvYaQEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYuIaQEeSMzJufh3GDGA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEYuYaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYuoaQEeSMzJufh3GDGA" x="230" y="170" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYu4aQEeSMzJufh3GDGA" type="3027" element="_bkDKwoaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYvIaQEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYvYaQEeSMzJufh3GDGA" x="271" y="95" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYvoaQEeSMzJufh3GDGA" type="3027" element="_bkDKzIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYv4aQEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYwIaQEeSMzJufh3GDGA" x="347" y="187" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYwYaQEeSMzJufh3GDGA" type="3027" element="_bkDK1oaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYwoaQEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYw4aQEeSMzJufh3GDGA" x="765" y="192" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYxIaQEeSMzJufh3GDGA" type="3027" element="_bkDK4IaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYxYaQEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYxoaQEeSMzJufh3GDGA" x="762" y="96" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkEYx4aQEeSMzJufh3GDGA" type="3027" element="_bkDK6oaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkEYyIaQEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYyYaQEeSMzJufh3GDGA" x="1041" y="90" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ebyzoIaQEeSMzJufh3GDGA" type="3063" element="_ebw-cIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ebzasIaQEeSMzJufh3GDGA" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ebyzoYaQEeSMzJufh3GDGA" x="913" y="125"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_bkEYyoaQEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_bkEYy4aQEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_bkEYzIaQEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_bkEYzYaQEeSMzJufh3GDGA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEYzoaQEeSMzJufh3GDGA" x="45" y="10" width="1372" height="302"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_bkEYz4aQEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkEY0IaQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_bkEY0YaQEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_bkEY0oaQEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkEY04aQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_ebre4IaQEeSMzJufh3GDGA" type="2007" element="_eWxwwIaQEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_ebsF84aQEeSMzJufh3GDGA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_ebsF9IaQEeSMzJufh3GDGA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_RUWm0IaREeSMzJufh3GDGA" type="3007" element="_RUV_wIaREeSMzJufh3GDGA">
          <children xmi:type="notation:DecorationNode" xmi:id="_RUXN4IaREeSMzJufh3GDGA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_RUXN4YaREeSMzJufh3GDGA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_edF0IIaQEeSMzJufh3GDGA" type="3005" element="_edFNEIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_edF0IYaQEeSMzJufh3GDGA" type="5005" element="_edFNEIaQEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_edF0IoaQEeSMzJufh3GDGA" x="597" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xZcwcIaQEeSMzJufh3GDGA" type="3002" element="_xZbiUIaQEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_xZcwcoaQEeSMzJufh3GDGA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xZcwc4aQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xZcwcYaQEeSMzJufh3GDGA" x="84" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_y0o8FIaQEeSMzJufh3GDGA" type="3062" element="_y0oVAIaQEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_y0pjIIaQEeSMzJufh3GDGA" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_y0pjIYaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_y0o8FYaQEeSMzJufh3GDGA" x="753" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3LhcwIaQEeSMzJufh3GDGA" type="3005" element="_3LfnkIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3LhcwoaQEeSMzJufh3GDGA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3LhcwYaQEeSMzJufh3GDGA" x="160" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5zsY4IaQEeSMzJufh3GDGA" type="3005" element="_5ziA0IaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5z07wIaQEeSMzJufh3GDGA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5zsY4YaQEeSMzJufh3GDGA" x="294" y="91" width="134" height="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-5OvUIaQEeSMzJufh3GDGA" type="3005" element="_-5CiEIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-5OvUoaQEeSMzJufh3GDGA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-5OvUYaQEeSMzJufh3GDGA" x="464" y="100"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_RUWm0YaREeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_RUWm0oaREeSMzJufh3GDGA" fontName="Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_RUWm04aREeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_RUXN4oaREeSMzJufh3GDGA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RUWm1IaREeSMzJufh3GDGA" x="231" y="176"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_ebre4YaQEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_ebsF8IaQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_ebsF8YaQEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_ebsF9YaQEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ebsF8oaQEeSMzJufh3GDGA" width="1454" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_bkEY1IaQEeSMzJufh3GDGA"/>
    <edges xmi:type="notation:Connector" xmi:id="_bkEY1YaQEeSMzJufh3GDGA" type="4001" element="_bkDxzIaQEeSMzJufh3GDGA" source="_bkEYmoaQEeSMzJufh3GDGA" target="_bkEYl4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkEY1oaQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEY14aQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkEY2IaQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkEY2YaQEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkEY2oaQEeSMzJufh3GDGA" type="4001" element="_bkDxz4aQEeSMzJufh3GDGA" source="_bkEYu4aQEeSMzJufh3GDGA" target="_bkEYnoaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkEY24aQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEY3IaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkEY3YaQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkEY3oaQEeSMzJufh3GDGA" points="[0, 1, -66, -7]$[16, 1, -50, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkEY34aQEeSMzJufh3GDGA" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkEY4IaQEeSMzJufh3GDGA" type="4001" element="_bkDx0oaQEeSMzJufh3GDGA" source="_bkEYnoaQEeSMzJufh3GDGA" target="_bkEYpIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkEY4YaQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEY4oaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkEY44aQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkEY5IaQEeSMzJufh3GDGA" points="[0, 0, -41, 91]$[-9, -91, -50, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkEY5YaQEeSMzJufh3GDGA" id="(1.0,0.64)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkEY5oaQEeSMzJufh3GDGA" type="4001" element="_bkDx1YaQEeSMzJufh3GDGA" source="_bkEYxIaQEeSMzJufh3GDGA" target="_ebyzoIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkEY54aQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEY6IaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkEY6YaQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkEY6oaQEeSMzJufh3GDGA" points="[0, 0, -5, -60]$[55, 51, 50, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkEY64aQEeSMzJufh3GDGA" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkEY7IaQEeSMzJufh3GDGA" type="4001" element="_bkDx2IaQEeSMzJufh3GDGA" source="_ebyzoIaQEeSMzJufh3GDGA" target="_bkEYx4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkEY7YaQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEY7oaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkEY74aQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkEY8IaQEeSMzJufh3GDGA" points="[0, 0, -60, 48]$[65, -35, 5, 13]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkEY8oaQEeSMzJufh3GDGA" id="(0.5583333333333333,0.7833333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkEY84aQEeSMzJufh3GDGA" type="4001" element="_bkDx24aQEeSMzJufh3GDGA" source="_bkEYvoaQEeSMzJufh3GDGA" target="_bkEYp4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkEY9IaQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkEY9YaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkEY9oaQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkEY94aQEeSMzJufh3GDGA" points="[0, -8, -85, 2]$[78, 3, -7, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_oIaQEeSMzJufh3GDGA" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkE_oYaQEeSMzJufh3GDGA" type="4001" element="_bkDx3oaQEeSMzJufh3GDGA" source="_bkEYwYaQEeSMzJufh3GDGA" target="_bkEYr4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_ooaQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkE_o4aQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_pIaQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkE_pYaQEeSMzJufh3GDGA" points="[0, 0, -142, -15]$[135, 28, -7, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_poaQEeSMzJufh3GDGA" id="(1.0,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkE_p4aQEeSMzJufh3GDGA" type="4001" element="_bkDx4YaQEeSMzJufh3GDGA" source="_bkEYl4aQEeSMzJufh3GDGA" target="_bkEYt4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_qIaQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkE_qYaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_qoaQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkE_q4aQEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkE_rIaQEeSMzJufh3GDGA" type="4001" element="_bkDx5IaQEeSMzJufh3GDGA" source="_bkEYt4aQEeSMzJufh3GDGA" target="_bkEYu4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_rYaQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkE_roaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_r4aQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkE_sIaQEeSMzJufh3GDGA" points="[-11, -22, -51, 47]$[42, -57, 2, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_sYaQEeSMzJufh3GDGA" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_soaQEeSMzJufh3GDGA" id="(0.5333333333333333,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkE_s4aQEeSMzJufh3GDGA" type="4001" element="_bkDx6YaQEeSMzJufh3GDGA" source="_bkEYt4aQEeSMzJufh3GDGA" target="_bkEYvoaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_tIaQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkE_tYaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_toaQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkE_t4aQEeSMzJufh3GDGA" points="[-14, 1, -91, 0]$[52, -2, -25, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_uIaQEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_uYaQEeSMzJufh3GDGA" id="(0.20833333333333334,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkE_uoaQEeSMzJufh3GDGA" type="4001" element="_bkDx7IaQEeSMzJufh3GDGA" source="_bkEYpIaQEeSMzJufh3GDGA" target="_bkEYs4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_u4aQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkE_vIaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_vYaQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkE_voaQEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_v4aQEeSMzJufh3GDGA" id="(0.97,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkE_wIaQEeSMzJufh3GDGA" type="4001" element="_bkDx74aQEeSMzJufh3GDGA" source="_bkEYs4aQEeSMzJufh3GDGA" target="_bkEYxIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_wYaQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkE_woaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_w4aQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkE_xIaQEeSMzJufh3GDGA" points="[-11, -3, -65, 0]$[30, -1, -24, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_xYaQEeSMzJufh3GDGA" id="(1.0,0.813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_xoaQEeSMzJufh3GDGA" id="(0.025,0.18333333333333332)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkE_x4aQEeSMzJufh3GDGA" type="4001" element="_bkDx9IaQEeSMzJufh3GDGA" source="_bkEYs4aQEeSMzJufh3GDGA" target="_bkEYwYaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_yIaQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkE_yYaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_yoaQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkE_y4aQEeSMzJufh3GDGA" points="[-4, -10, -40, -95]$[33, 84, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_zIaQEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_zYaQEeSMzJufh3GDGA" id="(0.025,0.4166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bkE_zoaQEeSMzJufh3GDGA" type="4001" element="_bkDx94aQEeSMzJufh3GDGA" source="_bkEYx4aQEeSMzJufh3GDGA" target="_bkEYq4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_z4aQEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bkE_0IaQEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_0YaQEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bkE_0oaQEeSMzJufh3GDGA" points="[0, 0, -75, -29]$[72, 14, -3, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bkE_04aQEeSMzJufh3GDGA" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ECQeoYaREeSMzJufh3GDGA" type="4001" element="_ECP3kIaREeSMzJufh3GDGA" source="_xZcwcIaQEeSMzJufh3GDGA" target="_3LhcwIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ECbdwIaREeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ECbdwYaREeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ECQeooaREeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ECQeo4aREeSMzJufh3GDGA" points="[-7, -2, -57, 0]$[46, -1, -4, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ECcr4IaREeSMzJufh3GDGA" id="(0.9666666666666667,0.5333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ECcr4YaREeSMzJufh3GDGA" id="(0.05,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FW9AsIaREeSMzJufh3GDGA" type="4001" element="_FW7ykIaREeSMzJufh3GDGA" source="_3LhcwIaQEeSMzJufh3GDGA" target="_5zsY4IaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FW9As4aREeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FW9AtIaREeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FW9AsYaREeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FW9AsoaREeSMzJufh3GDGA" points="[0, -5, -35, 0]$[34, -6, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FXB5MIaREeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FXB5MYaREeSMzJufh3GDGA" id="(0.007462686567164179,0.4925373134328358)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_F-orwIaREeSMzJufh3GDGA" type="4001" element="_F-ndoIaREeSMzJufh3GDGA" source="_5zsY4IaQEeSMzJufh3GDGA" target="_-5OvUIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_F-orw4aREeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_F-orxIaREeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_F-orwYaREeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_F-orwoaREeSMzJufh3GDGA" points="[0, 1, -36, 0]$[36, 1, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_F-qg8IaREeSMzJufh3GDGA" id="(1.0,0.4626865671641791)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_F-qg8YaREeSMzJufh3GDGA" id="(0.0,0.46)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Gi2zIIaREeSMzJufh3GDGA" type="4001" element="_Gi2MEIaREeSMzJufh3GDGA" source="_-5OvUIaQEeSMzJufh3GDGA" target="_edF0IIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Gi3aMIaREeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Gi3aMYaREeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Gi2zIYaREeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Gi2zIoaREeSMzJufh3GDGA" points="[0, -6, -40, 0]$[33, -7, -7, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Gi4oUIaREeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Gi4oUYaREeSMzJufh3GDGA" id="(0.07,0.46)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HKsPMIaREeSMzJufh3GDGA" type="4001" element="_HKrBEIaREeSMzJufh3GDGA" source="_edF0IIaQEeSMzJufh3GDGA" target="_y0o8FIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HKsPM4aREeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HKsPNIaREeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HKsPMYaREeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HKsPMoaREeSMzJufh3GDGA" points="[0, -3, -59, 0]$[56, -3, -3, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HKuEYIaREeSMzJufh3GDGA" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HKuEYYaREeSMzJufh3GDGA" id="(0.1,0.5666666666666667)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_bkE_1IaQEeSMzJufh3GDGA" type="Form" element="_bkDxh4aQEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_bkE_1YaQEeSMzJufh3GDGA" type="2120" element="_bkDxiIaQEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_1oaQEeSMzJufh3GDGA" type="5157"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkE_14aQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_bkE_2IaQEeSMzJufh3GDGA" type="2126" element="_bkDxtIaQEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_2YaQEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_bkE_2oaQEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_24aQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_bkE_3IaQEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkE_3YaQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_bkE_3oaQEeSMzJufh3GDGA" type="2131" element="_bkDxuIaQEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_34aQEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkE_4IaQEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_bkE_4YaQEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_bkE_4oaQEeSMzJufh3GDGA" type="Form" element="_bkB8XYaQEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_bkE_44aQEeSMzJufh3GDGA" type="2130" element="_bkB8XoaQEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_5IaQEeSMzJufh3GDGA" type="5148"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkE_5YaQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_bkE_5oaQEeSMzJufh3GDGA" type="2126" element="_bkB8joaQEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_54aQEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_bkE_6IaQEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_6YaQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_bkE_6oaQEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkE_64aQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_bkE_7IaQEeSMzJufh3GDGA" type="2131" element="_bkB8koaQEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_7YaQEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkE_7oaQEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_bkE_74aQEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_bkE_8IaQEeSMzJufh3GDGA" type="Form" element="_bkCjY4aQEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_bkE_8YaQEeSMzJufh3GDGA" type="2120" element="_bkCjZIaQEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_8oaQEeSMzJufh3GDGA" type="5157"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkE_84aQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_bkE_9IaQEeSMzJufh3GDGA" type="2126" element="_bkCjlIaQEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_9YaQEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_bkE_9oaQEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkE_94aQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_bkE_-IaQEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkE_-YaQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_bkE_-oaQEeSMzJufh3GDGA" type="2131" element="_bkCjmIaQEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkE_-4aQEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkE__IaQEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_bkE__YaQEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_bkE__oaQEeSMzJufh3GDGA" type="Form" element="_bkCj0oaQEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_bkE__4aQEeSMzJufh3GDGA" type="2130" element="_bkCj04aQEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkFAAIaQEeSMzJufh3GDGA" type="5148"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkFAAYaQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_bkFAAoaQEeSMzJufh3GDGA" type="2126" element="_bkDKh4aQEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkFAA4aQEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_bkFABIaQEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkFABYaQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_bkFABoaQEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkFAB4aQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_bkFACIaQEeSMzJufh3GDGA" type="2131" element="_bkDKi4aQEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkFACYaQEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkFACoaQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_bkFAC4aQEeSMzJufh3GDGA" type="2131" element="_bkDKmYaQEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkFmsIaQEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkFmsYaQEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_bkFmsoaQEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_bkFms4aQEeSMzJufh3GDGA" type="Form" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_bkFmtIaQEeSMzJufh3GDGA" type="2126">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkFmtYaQEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_bkFmtoaQEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_bkFmt4aQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_bkFmuIaQEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkFmuYaQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_bkFmuoaQEeSMzJufh3GDGA" type="2131" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_bkFmu4aQEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkFmvIaQEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_bkFmvYaQEeSMzJufh3GDGA"/>
  </notation:Diagram>
</xmi:XMI>
