<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process">
  <process:MainProcess xmi:id="_bkB8UIaQEeSMzJufh3GDGA" name="Projet_Validation_Diagram_CORTES_MARTINEZ" version="3.0" author="corteshs" bonitaVersion="6.3.8" bonitaModelVersion="6.3.8-001" configId="ACED000574003750726F6A65745F56616C69646174696F6E5F4469616772616D5F434F525445535F4D415254494E455A362E332E382D303031362E332E38">
    <elements xsi:type="process:Pool" xmi:id="_bkB8UYaQEeSMzJufh3GDGA" name="Projet_Validation_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="3.0">
      <elements xsi:type="process:Lane" xmi:id="_bkB8UoaQEeSMzJufh3GDGA" name="Employé (lane)" actor="_bkDx-oaQEeSMzJufh3GDGA">
        <elements xsi:type="process:Task" xmi:id="_bkB8U4aQEeSMzJufh3GDGA" name="Approve proposal" outgoing="_bkDx4YaQEeSMzJufh3GDGA" incoming="_bkDxzIaQEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_bkB8VIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_bkB8VYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_bkB8VoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_bkB8V4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_bkB8WIaQEeSMzJufh3GDGA">
            <cardinality xmi:id="_fvU-MJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvU-MZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_bkB8W4aQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_bkB8XIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_bkB8XYaQEeSMzJufh3GDGA" name="ApproveProposal" nLine="3">
            <widgets xsi:type="form:CheckBoxSingleFormField" xmi:id="_bkB8XoaQEeSMzJufh3GDGA" name="proposalOK1">
              <widgetLayoutInfo xmi:id="_bkB8X4aQEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fvVlRJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fvVlRZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fvVlRpXdEeSroeU30tgKmw" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xsi:type="process:Data" xmi:id="_fvVlR5XdEeSroeU30tgKmw" name="proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fvVlSJXdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_bkB8ZoaQEeSMzJufh3GDGA">
                <leftOperand xmi:id="_fvWMUJXdEeSroeU30tgKmw" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="process:Data" xmi:id="_fvWMUZXdEeSroeU30tgKmw" name="proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_bkB8aoaQEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_fvWMUpXdEeSroeU30tgKmw" name="field_proposalOK1" content="field_proposalOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="form:CheckBoxSingleFormField" xmi:id="_fvWMU5XdEeSroeU30tgKmw" name="proposalOK1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_fvVlSZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fvVlSpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_fvVlS5XdEeSroeU30tgKmw" name="Approved?" content="Approved?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fvVlTJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_fvVlTpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_fvVlT5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_fvVlUJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_fvVlUZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_fvVlUpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_fvVlU5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_fvVlVJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_bkB8joaQEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_fvWMWpXdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:id="_fvWMW5XdEeSroeU30tgKmw" name="OK" content="OK" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fvWMXJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_bkB8koaQEeSMzJufh3GDGA" name="proposal1">
              <widgetLayoutInfo xmi:id="_fvWMZpXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fvWMZ5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fvWMaJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fvWMaZXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_fvWMapXdEeSroeU30tgKmw" name="proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fvWMa5XdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_fvWMbJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fvWMbZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fvWMbpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_fvU-QZXdEeSroeU30tgKmw" name="Approve proposal" content="Approve proposal" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_bkB8noaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_bkB8n4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:StartEvent" xmi:id="_bkB8oIaQEeSMzJufh3GDGA" name="Proposal made" outgoing="_bkDxzIaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvWzfJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvWzfZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvWzfpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvWzf5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_bkB8pYaQEeSMzJufh3GDGA" name="Analyze Impact" outgoing="_bkDx0oaQEeSMzJufh3GDGA" incoming="_bkDxz4aQEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_bkB8poaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_bkB8p4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_bkB8qIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_bkB8qYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_bkB8qoaQEeSMzJufh3GDGA">
            <cardinality xmi:id="_fvU-MpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvU-M5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_bkCjYYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_bkCjYoaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_bkCjY4aQEeSMzJufh3GDGA" name="AnalyzeImpact" nLine="3">
            <widgets xsi:type="form:TextFormField" xmi:id="_bkCjZIaQEeSMzJufh3GDGA" name="impacts1">
              <widgetLayoutInfo xmi:id="_fvWzhJXdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fvWzhZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fvWzhpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fvWzh5XdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_fvWziJXdEeSroeU30tgKmw" name="impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fvWziZXdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_fvWzjpXdEeSroeU30tgKmw">
                <leftOperand xmi:id="_fvWzj5XdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                  <referencedElements xsi:type="process:Data" xmi:id="_fvWzkJXdEeSroeU30tgKmw" name="impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_fvWzk5XdEeSroeU30tgKmw" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_fvWzkZXdEeSroeU30tgKmw" name="field_impacts1" content="field_impacts1" type="TYPE_INPUT">
                  <referencedElements xsi:type="form:TextFormField" xmi:id="_fvWzkpXdEeSroeU30tgKmw" name="impacts1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_fvWzipXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fvWzi5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_fvWzjJXdEeSroeU30tgKmw" name="Impact?" content="Impact?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fvWzjZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_fvWzlJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_fvWzlZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_fvWzlpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_fvWzl5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_fvWzmJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_fvWzmZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_fvWzmpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_bkCjlIaQEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_fvWMXZXdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:id="_fvWMXpXdEeSroeU30tgKmw" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fvWMX5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_bkCjmIaQEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:id="_bkCjmYaQEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <htmlAttributes xmi:id="_bkCjmoaQEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <widgetLayoutInfo xmi:id="_fvWMcZXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fvWMcpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fvWMc5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fvWMdJXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_fvWMdZXdEeSroeU30tgKmw" name="proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fvWMdpXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_fvWMd5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fvWMeJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fvWMeZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_fvU-RZXdEeSroeU30tgKmw" name="Analyze Impact" content="Analyze Impact" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_bkCjpoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_bkCjp4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_bkCjyIaQEeSMzJufh3GDGA" name="Validate project" outgoing="_bkDx7IaQEeSMzJufh3GDGA" incoming="_bkDx0oaQEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_bkCjyYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_bkCjyoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_bkCjy4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_bkCjzIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_bkCjzYaQEeSMzJufh3GDGA">
            <cardinality xmi:id="_fvU-NJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvU-NZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_bkCj0IaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_bkCj0YaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_bkCj0oaQEeSMzJufh3GDGA" name="ValidateProject">
            <widgets xsi:type="form:CheckBoxSingleFormField" xmi:id="_bkCj04aQEeSMzJufh3GDGA" name="projectOK1">
              <widgetLayoutInfo xmi:id="_bkCj1IaQEeSMzJufh3GDGA" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fvVlVpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fvVlV5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fvVlWJXdEeSroeU30tgKmw" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xsi:type="process:Data" xmi:id="_fvVlWZXdEeSroeU30tgKmw" name="projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fvVlWpXdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_bkCj24aQEeSMzJufh3GDGA">
                <leftOperand xmi:id="_fvWMVZXdEeSroeU30tgKmw" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="process:Data" xmi:id="_fvWMVpXdEeSroeU30tgKmw" name="projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_bkCj34aQEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_fvWMV5XdEeSroeU30tgKmw" name="field_projectOK1" content="field_projectOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="form:CheckBoxSingleFormField" xmi:id="_fvWMWJXdEeSroeU30tgKmw" name="projectOK1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_fvVlW5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fvVlXJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_fvVlXZXdEeSroeU30tgKmw" name="Approve project?" content="Approve project?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fvVlXpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_fvVlYJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_fvVlYZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_fvVlYpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_fvVlY5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_fvVlZJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_fvVlZZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_fvVlZpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_bkDKh4aQEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_fvWMYJXdEeSroeU30tgKmw" line="3"/>
              <displayLabel xmi:id="_fvWMYZXdEeSroeU30tgKmw" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fvWMYpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_bkDKi4aQEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:id="_bkDKjIaQEeSMzJufh3GDGA" key="input_css:color" value="purple"/>
              <htmlAttributes xmi:id="_bkDKjYaQEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <htmlAttributes xmi:id="_bkDKjoaQEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <widgetLayoutInfo xmi:id="_fvWMfZXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fvWMfpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fvWMf5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fvWMgJXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_fvWMgZXdEeSroeU30tgKmw" name="proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fvWMgpXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_fvWzYJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fvWzYZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fvWzYpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_bkDKmYaQEeSMzJufh3GDGA" name="impacts1">
              <htmlAttributes xmi:id="_bkDKmoaQEeSMzJufh3GDGA" key="input_css:color" value="red"/>
              <htmlAttributes xmi:id="_bkDKm4aQEeSMzJufh3GDGA" key="input_css:font-size" value="18px"/>
              <widgetLayoutInfo xmi:id="_fvWzZZXdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fvWzZpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fvWzZ5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fvWzaJXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_fvWzaZXdEeSroeU30tgKmw" name="impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fvWzapXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_fvWza5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fvWzbJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fvWzbZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_fvU-SpXdEeSroeU30tgKmw" name="Validate project" content="Validate project" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_bkDKp4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_bkDKqIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_bkDKqYaQEeSMzJufh3GDGA" name="Proposal refused" incoming="_bkDx24aQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvXaf5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvXagJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvXagZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvXagpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_bkDKroaQEeSMzJufh3GDGA" name="Project finished" incoming="_bkDx94aQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvXag5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvXahJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvXahZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvXahpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_bkDKs4aQEeSMzJufh3GDGA" name="Project refused" incoming="_bkDx3oaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvXah5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvXaiJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvXaiZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvXaipXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:XORGateway" xmi:id="_bkDKuIaQEeSMzJufh3GDGA" name="Project approval?" outgoing="_bkDx74aQEeSMzJufh3GDGA _bkDx9IaQEeSMzJufh3GDGA" incoming="_bkDx7IaQEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:id="_fvXaj5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvXakJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvXakZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvXakpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:XORGateway" xmi:id="_bkDKvYaQEeSMzJufh3GDGA" name="Proposal approval?" outgoing="_bkDx5IaQEeSMzJufh3GDGA _bkDx6YaQEeSMzJufh3GDGA" incoming="_bkDx4YaQEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:id="_fvXak5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvXalJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvXalZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvXalpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_bkDKwoaQEeSMzJufh3GDGA" name="Notify proposal aproved" outgoing="_bkDxz4aQEeSMzJufh3GDGA" incoming="_bkDx5IaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvXal5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvXamJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvXamZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvXampXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fvXam5XdEeSroeU30tgKmw">
            <cardinality xmi:id="_fvXanJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvXanZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fvXanpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fvXan5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_bkDKzIaQEeSMzJufh3GDGA" name="Notify proposal refusal" outgoing="_bkDx24aQEeSMzJufh3GDGA" incoming="_bkDx6YaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvXaoJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvXaoZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvXaopXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvXao5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fvXapJXdEeSroeU30tgKmw">
            <cardinality xmi:id="_fvXapZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvXappXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fvXap5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fvXaqJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_bkDK1oaQEeSMzJufh3GDGA" name="Notify project refused" outgoing="_bkDx3oaQEeSMzJufh3GDGA" incoming="_bkDx9IaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvXaqZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvXaqpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvXaq5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvXarJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fvXarZXdEeSroeU30tgKmw">
            <cardinality xmi:id="_fvXarpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvXar5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fvXasJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fvXasZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_bkDK4IaQEeSMzJufh3GDGA" name="Notify project accepted" outgoing="_bkDx1YaQEeSMzJufh3GDGA" incoming="_bkDx74aQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvYBgJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvYBgZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvYBgpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvYBg5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fvYBhJXdEeSroeU30tgKmw">
            <cardinality xmi:id="_fvYBhZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvYBhpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fvYBh5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fvYBiJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_bkDK6oaQEeSMzJufh3GDGA" name="Notify project delivery" outgoing="_bkDx94aQEeSMzJufh3GDGA" incoming="_bkDx2IaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvYBiZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvYBipXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvYBi5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvYBjJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fvYBjZXdEeSroeU30tgKmw">
            <cardinality xmi:id="_fvYBjpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvYBj5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fvYBkJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fvYBkZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:CallActivity" xmi:id="_ebw-cIaQEeSMzJufh3GDGA" name="Do project" outgoing="_bkDx2IaQEeSMzJufh3GDGA" incoming="_bkDx1YaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvYBkpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvYBk5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvYBlJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvYBlZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fvYBlpXdEeSroeU30tgKmw">
            <cardinality xmi:id="_fvYBl5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvYBmJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fvYBmZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fvYBmpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <inputMappings xmi:id="_edIQYIaQEeSMzJufh3GDGA" processSource="_bkDK-4aQEeSMzJufh3GDGA" subprocessTarget="sub_proposal"/>
          <inputMappings xmi:id="_edI3coaQEeSMzJufh3GDGA" processSource="_bkDxgYaQEeSMzJufh3GDGA" subprocessTarget="sub_proposalOK"/>
          <inputMappings xmi:id="_edI3dYaQEeSMzJufh3GDGA" processSource="_bkDxg4aQEeSMzJufh3GDGA" subprocessTarget="sub_projectOK"/>
          <inputMappings xmi:id="_edI3eIaQEeSMzJufh3GDGA" processSource="_bkDxhYaQEeSMzJufh3GDGA" subprocessTarget="sub_impacts"/>
          <outputMappings xmi:id="_Co8F0IaSEeSMzJufh3GDGA" subprocessSource="sub_proposal" processTarget="_bkDK-4aQEeSMzJufh3GDGA"/>
          <outputMappings xmi:id="_CsskcIaSEeSMzJufh3GDGA" subprocessSource="sub_proposalOK" processTarget="_bkDxgYaQEeSMzJufh3GDGA"/>
          <outputMappings xmi:id="_Cs0gQIaSEeSMzJufh3GDGA" subprocessSource="sub_projectOK" processTarget="_bkDxg4aQEeSMzJufh3GDGA"/>
          <outputMappings xmi:id="_Cs8cEIaSEeSMzJufh3GDGA" subprocessSource="sub_impacts" processTarget="_bkDxhYaQEeSMzJufh3GDGA"/>
          <calledActivityName xmi:id="_fvYBo5XdEeSroeU30tgKmw" name="Do_project_CORTES_MARTINEZ" content="Do_project_CORTES_MARTINEZ" returnTypeFixed="true"/>
          <calledActivityVersion xmi:id="_fvYBpJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:id="_boflkIaQEeSMzJufh3GDGA" path="_bkB8UYaQEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:id="_bkDK9YaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_bkDK9oaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_bkDK94aQEeSMzJufh3GDGA" path="_bkB8UYaQEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:id="_bkDK-IaQEeSMzJufh3GDGA" path="_bkB8UYaQEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:id="_bkDK-YaQEeSMzJufh3GDGA" path="_bkB8UYaQEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:id="_bkDK-oaQEeSMzJufh3GDGA" path="_bkB8UYaQEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:id="_bkDK-4aQEeSMzJufh3GDGA" name="proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fvVlZ5XdEeSroeU30tgKmw" content=""/>
      </data>
      <data xmi:id="_bkDxgYaQEeSMzJufh3GDGA" name="proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fvVlaJXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_bkDxg4aQEeSMzJufh3GDGA" name="projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fvVlaZXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_bkDxhYaQEeSMzJufh3GDGA" name="impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fvVlapXdEeSroeU30tgKmw" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <form xmi:id="_bkDxh4aQEeSMzJufh3GDGA" name="Project_Validation_CORTES_MARTINEZ" nLine="3">
        <widgets xsi:type="form:TextFormField" xmi:id="_bkDxiIaQEeSMzJufh3GDGA" name="proposal1">
          <widgetLayoutInfo xmi:id="_fvWzm5XdEeSroeU30tgKmw" line="1"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fvWznJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:id="_fvWznZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:id="_fvWznpXdEeSroeU30tgKmw" name="" content=""/>
          <afterEventExpression xmi:id="_fvWzn5XdEeSroeU30tgKmw" name="" content=""/>
          <action xmi:id="_fvXacpXdEeSroeU30tgKmw">
            <leftOperand xmi:id="_fvXac5XdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
              <referencedElements xsi:type="process:Data" xmi:id="_fvXadJXdEeSroeU30tgKmw" name="proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA"/>
            </leftOperand>
            <operator xmi:id="_fvXad5XdEeSroeU30tgKmw" type="ASSIGNMENT"/>
            <rightOperand xmi:id="_fvXadZXdEeSroeU30tgKmw" name="field_proposal1" content="field_proposal1" type="TYPE_INPUT">
              <referencedElements xsi:type="form:TextFormField" xmi:id="_fvXadpXdEeSroeU30tgKmw" name="proposal1"/>
            </rightOperand>
          </action>
          <tooltip xmi:id="_fvWzoJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:id="_fvWzoZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:id="_fvXacJXdEeSroeU30tgKmw" name="Proposal" content="Proposal" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_fvXacZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <maxNumberOfDuplication xmi:id="_fvXaeJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:id="_fvXaeZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <displayLabelForAdd xmi:id="_fvXaepXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <tooltipForAdd xmi:id="_fvXae5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabelForRemove xmi:id="_fvXafJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <tooltipForRemove xmi:id="_fvXafZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <exampleMessage xmi:id="_fvXafpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </widgets>
        <widgets xsi:type="form:SubmitFormButton" xmi:id="_bkDxtIaQEeSMzJufh3GDGA" name="Soumettre1">
          <widgetLayoutInfo xmi:id="_fvWMY5XdEeSroeU30tgKmw" line="2"/>
          <displayLabel xmi:id="_fvWMZJXdEeSroeU30tgKmw" name="OK" content="OK" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_fvWMZZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <widgets xsi:type="form:MessageInfo" xmi:id="_bkDxuIaQEeSMzJufh3GDGA" name="Enter proposal:">
          <htmlAttributes xmi:id="_bkDxuYaQEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
          <widgetLayoutInfo xmi:id="_fvWzb5XdEeSroeU30tgKmw"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fvWzcJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:id="_fvWzcZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:id="_fvWzcpXdEeSroeU30tgKmw" name="" content=""/>
          <afterEventExpression xmi:id="_fvWzc5XdEeSroeU30tgKmw" name="" content=""/>
          <action xmi:id="_fvWzeJXdEeSroeU30tgKmw">
            <leftOperand xmi:id="_fvWzeZXdEeSroeU30tgKmw"/>
            <operator xmi:id="_fvWze5XdEeSroeU30tgKmw" type="ASSIGNMENT" expression="="/>
            <rightOperand xmi:id="_fvWzepXdEeSroeU30tgKmw"/>
          </action>
          <tooltip xmi:id="_fvWzdJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:id="_fvWzdZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:id="_fvWzdpXdEeSroeU30tgKmw" name="Message1" content="Message1" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_fvWzd5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:id="_fvVlQpXdEeSroeU30tgKmw" name="Propose proposal" content="Propose proposal" returnTypeFixed="true"/>
      </form>
      <entryRedirectionURL xmi:id="_bkDxyIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_bkDxyYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_bkDxyoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_bkDxy4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDxzIaQEeSMzJufh3GDGA" source="_bkB8oIaQEeSMzJufh3GDGA" target="_bkB8U4aQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDxzYaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBppXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDxz4aQEeSMzJufh3GDGA" source="_bkDKwoaQEeSMzJufh3GDGA" target="_bkB8pYaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx0IaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBqJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx0oaQEeSMzJufh3GDGA" source="_bkB8pYaQEeSMzJufh3GDGA" target="_bkCjyIaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx04aQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBqpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx1YaQEeSMzJufh3GDGA" source="_bkDK4IaQEeSMzJufh3GDGA" target="_ebw-cIaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx1oaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBrJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx2IaQEeSMzJufh3GDGA" source="_ebw-cIaQEeSMzJufh3GDGA" target="_bkDK6oaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx2YaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBrpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx24aQEeSMzJufh3GDGA" source="_bkDKzIaQEeSMzJufh3GDGA" target="_bkDKqYaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx3IaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBsJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx3oaQEeSMzJufh3GDGA" source="_bkDK1oaQEeSMzJufh3GDGA" target="_bkDKs4aQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx34aQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBspXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx4YaQEeSMzJufh3GDGA" source="_bkB8U4aQEeSMzJufh3GDGA" target="_bkDKvYaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx4oaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBtJXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx5IaQEeSMzJufh3GDGA" name="Approved" source="_bkDKvYaQEeSMzJufh3GDGA" target="_bkDKwoaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx5YaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBtpXdEeSroeU30tgKmw" name="proposalOK==true" content="proposalOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xsi:type="process:Data" xmi:id="_fvYBt5XdEeSroeU30tgKmw" name="proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA"/>
        </condition>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx6YaQEeSMzJufh3GDGA" name="Not Approved" source="_bkDKvYaQEeSMzJufh3GDGA" target="_bkDKzIaQEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:id="_bkDx6oaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBuZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx7IaQEeSMzJufh3GDGA" source="_bkCjyIaQEeSMzJufh3GDGA" target="_bkDKuIaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx7YaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBu5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx74aQEeSMzJufh3GDGA" name="Approved" source="_bkDKuIaQEeSMzJufh3GDGA" target="_bkDK4IaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx8IaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYBvZXdEeSroeU30tgKmw" name="projectOK==true" content="projectOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xsi:type="process:Data" xmi:id="_fvYokJXdEeSroeU30tgKmw" name="projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA"/>
        </condition>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx9IaQEeSMzJufh3GDGA" name="Not approved" source="_bkDKuIaQEeSMzJufh3GDGA" target="_bkDK1oaQEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:id="_bkDx9YaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYokpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_bkDx94aQEeSMzJufh3GDGA" source="_bkDK6oaQEeSMzJufh3GDGA" target="_bkDKroaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_bkDx-IaQEeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYolJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:id="_bkDx-oaQEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:id="_bkDx-4aQEeSMzJufh3GDGA">
        <name xmi:id="_fvYon5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fvYooJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_bkDx_oaQEeSMzJufh3GDGA">
        <name xmi:id="_fvYooZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fvYoopXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_bkDyAYaQEeSMzJufh3GDGA">
        <name xmi:id="_fvYoo5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fvYopJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_bkDyBIaQEeSMzJufh3GDGA">
        <name xmi:id="_fvYopZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fvYoppXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_bkDyB4aQEeSMzJufh3GDGA">
        <name xmi:id="_fvYop5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fvYoqJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xsi:type="process:Pool" xmi:id="_eWxwwIaQEeSMzJufh3GDGA" name="Do_project_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xsi:type="process:Lane" xmi:id="_RUV_wIaREeSMzJufh3GDGA" name="Research and Development" actor="_edEmAIaQEeSMzJufh3GDGA">
        <elements xsi:type="process:Task" xmi:id="_edFNEIaQEeSMzJufh3GDGA" name="Deploy" outgoing="_HKrBEIaREeSMzJufh3GDGA" incoming="_Gi2MEIaREeSMzJufh3GDGA" actor="_edEmAIaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_edFNEYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_edFNEoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_edFNE4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_edFNFIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_edFNFYaQEeSMzJufh3GDGA">
            <cardinality xmi:id="_fvU-NpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvU-N5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_edFNGIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_edFNGYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_edFNLoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_edFNL4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:StartEvent" xmi:id="_xZbiUIaQEeSMzJufh3GDGA" name="Start project" outgoing="_ECP3kIaREeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvWzgJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvWzgZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvWzgpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvWzg5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_y0oVAIaQEeSMzJufh3GDGA" name="Project finished" incoming="_HKrBEIaREeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fvXai5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fvXajJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fvXajZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fvXajpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_3LfnkIaQEeSMzJufh3GDGA" name="Specify" outgoing="_FW7ykIaREeSMzJufh3GDGA" incoming="_ECP3kIaREeSMzJufh3GDGA" actor="_edEmAIaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_3LgOo4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_3LgOoYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_3LgOoIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_3LgOooaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_3LgOqIaQEeSMzJufh3GDGA">
            <cardinality xmi:id="_fvU-OJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvU-OZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_3LgOpIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_3LgOpYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_3LgOpoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_3LgOp4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_5ziA0IaQEeSMzJufh3GDGA" name="Implement" outgoing="_F-ndoIaREeSMzJufh3GDGA" incoming="_FW7ykIaREeSMzJufh3GDGA" actor="_edEmAIaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_5zrx04aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_5zrx0YaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_5zrx0IaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_5zrx0oaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_5zrx2IaQEeSMzJufh3GDGA">
            <cardinality xmi:id="_fvU-OpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvU-O5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_5zrx1IaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_5zrx1YaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_5zrx1oaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_5zrx14aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_-5CiEIaQEeSMzJufh3GDGA" name="Test" outgoing="_Gi2MEIaREeSMzJufh3GDGA" incoming="_F-ndoIaREeSMzJufh3GDGA" actor="_edEmAIaQEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_-5NhM4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_-5NhMYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_-5NhMIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_-5NhMoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_-5NhOIaQEeSMzJufh3GDGA">
            <cardinality xmi:id="_fvU-PJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fvU-PZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_-5NhNIaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_-5NhNYaQEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_-5NhNoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_-5NhN4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:id="_ebn0gIaQEeSMzJufh3GDGA" path="_eWxwwIaQEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:id="_eWzmAYaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_eWzmAIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_ebn0g4aQEeSMzJufh3GDGA" path="_eWxwwIaQEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:id="_ebn0gYaQEeSMzJufh3GDGA" path="_eWxwwIaQEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:id="_ebn0hIaQEeSMzJufh3GDGA" path="_eWxwwIaQEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:id="_ebn0goaQEeSMzJufh3GDGA" path="_eWxwwIaQEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:id="_edHpUIaQEeSMzJufh3GDGA" name="sub_proposal" dataType="_bkDyD4aQEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fvVla5XdEeSroeU30tgKmw" content=""/>
      </data>
      <data xmi:id="_edI3cIaQEeSMzJufh3GDGA" name="sub_proposalOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fvVlbJXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_edI3c4aQEeSMzJufh3GDGA" name="sub_projectOK" dataType="_bkDyCoaQEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fvVlbZXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_edI3doaQEeSMzJufh3GDGA" name="sub_impacts" dataType="_bkDyD4aQEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fvVlbpXdEeSroeU30tgKmw" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <entryRedirectionURL xmi:id="_eWzmA4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_eWzmAoaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_eWzmBIaQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_eWzl_4aQEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xsi:type="process:SequenceFlow" xmi:id="_ECP3kIaREeSMzJufh3GDGA" source="_xZbiUIaQEeSMzJufh3GDGA" target="_3LfnkIaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_ECP3kYaREeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYolpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_FW7ykIaREeSMzJufh3GDGA" source="_3LfnkIaQEeSMzJufh3GDGA" target="_5ziA0IaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_FW8ZoIaREeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYomJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_F-ndoIaREeSMzJufh3GDGA" source="_5ziA0IaQEeSMzJufh3GDGA" target="_-5CiEIaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_F-ndoYaREeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYompXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_Gi2MEIaREeSMzJufh3GDGA" source="_-5CiEIaQEeSMzJufh3GDGA" target="_edFNEIaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_Gi2MEYaREeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYonJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_HKrBEIaREeSMzJufh3GDGA" source="_edFNEIaQEeSMzJufh3GDGA" target="_y0oVAIaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_HKroIIaREeSMzJufh3GDGA"/>
        <condition xmi:id="_fvYonpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:id="_edEmAIaQEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:id="_eWzl8IaQEeSMzJufh3GDGA">
        <name xmi:id="_fvYoqZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fvYoqpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_eWzl84aQEeSMzJufh3GDGA">
        <name xmi:id="_fvYoq5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fvYorJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_eWzl9oaQEeSMzJufh3GDGA">
        <name xmi:id="_fvYorZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fvYorpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_eWzl-YaQEeSMzJufh3GDGA">
        <name xmi:id="_fvYor5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fvYosJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_eWzl_IaQEeSMzJufh3GDGA">
        <name xmi:id="_fvYosZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fvYospXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xsi:type="process:BooleanType" xmi:id="_bkDyCoaQEeSMzJufh3GDGA" name="Boolean"/>
    <datatypes xsi:type="process:DateType" xmi:id="_bkDyC4aQEeSMzJufh3GDGA" name="Date"/>
    <datatypes xsi:type="process:IntegerType" xmi:id="_bkDyDIaQEeSMzJufh3GDGA" name="Integer"/>
    <datatypes xsi:type="process:LongType" xmi:id="_bkDyDYaQEeSMzJufh3GDGA" name="Long"/>
    <datatypes xsi:type="process:DoubleType" xmi:id="_bkDyDoaQEeSMzJufh3GDGA" name="Double"/>
    <datatypes xsi:type="process:StringType" xmi:id="_bkDyD4aQEeSMzJufh3GDGA" name="Text"/>
    <datatypes xsi:type="process:JavaType" xmi:id="_bkDyEIaQEeSMzJufh3GDGA" name="Java_object"/>
    <datatypes xsi:type="process:XMLType" xmi:id="_bkDyEYaQEeSMzJufh3GDGA" name="XML"/>
    <datatypes xsi:type="process:BusinessObjectType" xmi:id="_fvPeqpXdEeSroeU30tgKmw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_bkEYkIaQEeSMzJufh3GDGA" type="Process" element="_bkB8UIaQEeSMzJufh3GDGA" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:id="_bkEYkYaQEeSMzJufh3GDGA" type="2007" element="_bkB8UYaQEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_bkEYkoaQEeSMzJufh3GDGA" type="5008" element="_bkB8UYaQEeSMzJufh3GDGA"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_bkEYk4aQEeSMzJufh3GDGA" type="7001" element="_bkB8UYaQEeSMzJufh3GDGA">
        <children xmi:id="_fvZ22pXdEeSroeU30tgKmw" type="3007" element="_bkB8UoaQEeSMzJufh3GDGA">
          <children xsi:type="notation:DecorationNode" xmi:id="_bkEYlYaQEeSMzJufh3GDGA" type="5007" element="_bkB8UoaQEeSMzJufh3GDGA"/>
          <children xsi:type="notation:DecorationNode" xmi:id="_bkEYloaQEeSMzJufh3GDGA" type="7002" element="_bkB8UoaQEeSMzJufh3GDGA">
            <children xsi:type="notation:Shape" xmi:id="_bkEYl4aQEeSMzJufh3GDGA" type="3005" element="_bkB8U4aQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE0JXdEeSroeU30tgKmw" type="5005" element="_bkB8U4aQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYmYaQEeSMzJufh3GDGA" x="119" y="165"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYmoaQEeSMzJufh3GDGA" type="3002" element="_bkB8oIaQEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE0pXdEeSroeU30tgKmw" type="5024" element="_bkB8oIaQEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_bkEYnIaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYnYaQEeSMzJufh3GDGA" x="40" y="179"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYnoaQEeSMzJufh3GDGA" type="3005" element="_bkB8pYaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE1ZXdEeSroeU30tgKmw" type="5005" element="_bkB8pYaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYoIaQEeSMzJufh3GDGA" x="421" y="102"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYpIaQEeSMzJufh3GDGA" type="3005" element="_bkCjyIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE15XdEeSroeU30tgKmw" type="5005" element="_bkCjyIaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYpoaQEeSMzJufh3GDGA" x="556" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYp4aQEeSMzJufh3GDGA" type="3062" element="_bkDKqYaQEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE2ZXdEeSroeU30tgKmw" type="5090" element="_bkDKqYaQEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_bkEYqYaQEeSMzJufh3GDGA" x="-1" y="18"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYqoaQEeSMzJufh3GDGA" x="537" y="197"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYq4aQEeSMzJufh3GDGA" type="3062" element="_bkDKroaQEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE3JXdEeSroeU30tgKmw" type="5090" element="_bkDKroaQEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_bkEYrYaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYroaQEeSMzJufh3GDGA" x="1221" y="136"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYr4aQEeSMzJufh3GDGA" type="3062" element="_bkDKs4aQEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE35XdEeSroeU30tgKmw" type="5090" element="_bkDKs4aQEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_bkEYsYaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYsoaQEeSMzJufh3GDGA" x="1012" y="226"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYs4aQEeSMzJufh3GDGA" type="3008" element="_bkDKuIaQEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE4pXdEeSroeU30tgKmw" type="5026" element="_bkDKuIaQEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_bkEYtYaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYtoaQEeSMzJufh3GDGA" x="689" y="105" width="43" height="43"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYt4aQEeSMzJufh3GDGA" type="3008" element="_bkDKvYaQEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE5ZXdEeSroeU30tgKmw" type="5026" element="_bkDKvYaQEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_bkEYuYaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYuoaQEeSMzJufh3GDGA" x="230" y="170" width="43" height="43"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYu4aQEeSMzJufh3GDGA" type="3027" element="_bkDKwoaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE6JXdEeSroeU30tgKmw" type="5017" element="_bkDKwoaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYvYaQEeSMzJufh3GDGA" x="271" y="95" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYvoaQEeSMzJufh3GDGA" type="3027" element="_bkDKzIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE6pXdEeSroeU30tgKmw" type="5017" element="_bkDKzIaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYwIaQEeSMzJufh3GDGA" x="347" y="187" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYwYaQEeSMzJufh3GDGA" type="3027" element="_bkDK1oaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE7JXdEeSroeU30tgKmw" type="5017" element="_bkDK1oaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYw4aQEeSMzJufh3GDGA" x="765" y="192" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYxIaQEeSMzJufh3GDGA" type="3027" element="_bkDK4IaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE7pXdEeSroeU30tgKmw" type="5017" element="_bkDK4IaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYxoaQEeSMzJufh3GDGA" x="762" y="96" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_bkEYx4aQEeSMzJufh3GDGA" type="3027" element="_bkDK6oaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE8JXdEeSroeU30tgKmw" type="5017" element="_bkDK6oaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYyYaQEeSMzJufh3GDGA" x="1041" y="90" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_ebyzoIaQEeSMzJufh3GDGA" type="3063" element="_ebw-cIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE8pXdEeSroeU30tgKmw" type="5093" element="_ebw-cIaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_ebyzoYaQEeSMzJufh3GDGA" x="913" y="125"/>
            </children>
          </children>
          <styles xsi:type="notation:DescriptionStyle" xmi:id="_bkEYyoaQEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FontStyle" xmi:id="_bkEYy4aQEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xsi:type="notation:LineStyle" xmi:id="_bkEYzIaQEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FillStyle" xmi:id="_bkEYzYaQEeSMzJufh3GDGA"/>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEYzoaQEeSMzJufh3GDGA" x="45" y="10" width="1372" height="302"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_bkEYz4aQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_bkEY0IaQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_bkEY0YaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_bkEY0oaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkEY04aQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_ebre4IaQEeSMzJufh3GDGA" type="2007" element="_eWxwwIaQEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_ebsF84aQEeSMzJufh3GDGA" type="5008" element="_eWxwwIaQEeSMzJufh3GDGA"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_ebsF9IaQEeSMzJufh3GDGA" type="7001" element="_eWxwwIaQEeSMzJufh3GDGA">
        <children xmi:id="_fvadzZXdEeSroeU30tgKmw" type="3007" element="_RUV_wIaREeSMzJufh3GDGA">
          <children xsi:type="notation:DecorationNode" xmi:id="_RUXN4IaREeSMzJufh3GDGA" type="5007" element="_RUV_wIaREeSMzJufh3GDGA"/>
          <children xsi:type="notation:DecorationNode" xmi:id="_RUXN4YaREeSMzJufh3GDGA" type="7002" element="_RUV_wIaREeSMzJufh3GDGA">
            <children xsi:type="notation:Shape" xmi:id="_edF0IIaQEeSMzJufh3GDGA" type="3005" element="_edFNEIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE9JXdEeSroeU30tgKmw" type="5005" element="_edFNEIaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_edF0IoaQEeSMzJufh3GDGA" x="597" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_xZcwcIaQEeSMzJufh3GDGA" type="3002" element="_xZbiUIaQEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE9pXdEeSroeU30tgKmw" type="5024" element="_xZbiUIaQEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_xZcwc4aQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_xZcwcYaQEeSMzJufh3GDGA" x="84" y="110"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_y0o8FIaQEeSMzJufh3GDGA" type="3062" element="_y0oVAIaQEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE-ZXdEeSroeU30tgKmw" type="5090" element="_y0oVAIaQEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_y0pjIYaQEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_y0o8FYaQEeSMzJufh3GDGA" x="753" y="110"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_3LhcwIaQEeSMzJufh3GDGA" type="3005" element="_3LfnkIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE_JXdEeSroeU30tgKmw" type="5005" element="_3LfnkIaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_3LhcwYaQEeSMzJufh3GDGA" x="160" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_5zsY4IaQEeSMzJufh3GDGA" type="3005" element="_5ziA0IaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbE_pXdEeSroeU30tgKmw" type="5005" element="_5ziA0IaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_5zsY4YaQEeSMzJufh3GDGA" x="294" y="91" width="134" height="67"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_-5OvUIaQEeSMzJufh3GDGA" type="3005" element="_-5CiEIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fvbFAJXdEeSroeU30tgKmw" type="5005" element="_-5CiEIaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_-5OvUYaQEeSMzJufh3GDGA" x="464" y="100"/>
            </children>
          </children>
          <styles xsi:type="notation:DescriptionStyle" xmi:id="_RUWm0YaREeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FontStyle" xmi:id="_RUWm0oaREeSMzJufh3GDGA" fontName="Sans"/>
          <styles xsi:type="notation:LineStyle" xmi:id="_RUWm04aREeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FillStyle" xmi:id="_RUXN4oaREeSMzJufh3GDGA"/>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_RUWm1IaREeSMzJufh3GDGA" x="231" y="176"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_ebre4YaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_ebsF8IaQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_ebsF8YaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_ebsF9YaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_ebsF8oaQEeSMzJufh3GDGA" width="1454" height="250"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_bkEY1IaQEeSMzJufh3GDGA"/>
    <edges xsi:type="notation:Connector" xmi:id="_bkEY1YaQEeSMzJufh3GDGA" type="4001" element="_bkDxzIaQEeSMzJufh3GDGA" source="_bkEYmoaQEeSMzJufh3GDGA" target="_bkEYl4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvcS8JXdEeSroeU30tgKmw" type="6001" element="_bkDxzIaQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvcS8ZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvcS8pXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkEY2YaQEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkEY2oaQEeSMzJufh3GDGA" type="4001" element="_bkDxz4aQEeSMzJufh3GDGA" source="_bkEYu4aQEeSMzJufh3GDGA" target="_bkEYnoaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvcS9JXdEeSroeU30tgKmw" type="6001" element="_bkDxz4aQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvcS9ZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvcS9pXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkEY3oaQEeSMzJufh3GDGA" points="[0, 1, -66, -7]$[16, 1, -50, -7]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkEY34aQEeSMzJufh3GDGA" id="(1.0,0.55)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkEY4IaQEeSMzJufh3GDGA" type="4001" element="_bkDx0oaQEeSMzJufh3GDGA" source="_bkEYnoaQEeSMzJufh3GDGA" target="_bkEYpIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvcS-ZXdEeSroeU30tgKmw" type="6001" element="_bkDx0oaQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvcS-pXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvcS-5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkEY5IaQEeSMzJufh3GDGA" points="[0, 0, -41, 91]$[-9, -91, -50, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkEY5YaQEeSMzJufh3GDGA" id="(1.0,0.64)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkEY5oaQEeSMzJufh3GDGA" type="4001" element="_bkDx1YaQEeSMzJufh3GDGA" source="_bkEYxIaQEeSMzJufh3GDGA" target="_ebyzoIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvcS_pXdEeSroeU30tgKmw" type="6001" element="_bkDx1YaQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvcS_5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvcTAJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkEY6oaQEeSMzJufh3GDGA" points="[0, 0, -5, -60]$[55, 51, 50, -9]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkEY64aQEeSMzJufh3GDGA" id="(1.0,0.5)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkEY7IaQEeSMzJufh3GDGA" type="4001" element="_bkDx2IaQEeSMzJufh3GDGA" source="_ebyzoIaQEeSMzJufh3GDGA" target="_bkEYx4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvcTA5XdEeSroeU30tgKmw" type="6001" element="_bkDx2IaQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvcTBJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvcTBZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkEY8IaQEeSMzJufh3GDGA" points="[0, 0, -60, 48]$[65, -35, 5, 13]"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkEY8oaQEeSMzJufh3GDGA" id="(0.5583333333333333,0.7833333333333333)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkEY84aQEeSMzJufh3GDGA" type="4001" element="_bkDx24aQEeSMzJufh3GDGA" source="_bkEYvoaQEeSMzJufh3GDGA" target="_bkEYp4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvcTCJXdEeSroeU30tgKmw" type="6001" element="_bkDx24aQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvcTCZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvcTCpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkEY94aQEeSMzJufh3GDGA" points="[0, -8, -85, 2]$[78, 3, -7, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_oIaQEeSMzJufh3GDGA" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkE_oYaQEeSMzJufh3GDGA" type="4001" element="_bkDx3oaQEeSMzJufh3GDGA" source="_bkEYwYaQEeSMzJufh3GDGA" target="_bkEYr4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvcTDZXdEeSroeU30tgKmw" type="6001" element="_bkDx3oaQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvcTDpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvcTD5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkE_pYaQEeSMzJufh3GDGA" points="[0, 0, -142, -15]$[135, 28, -7, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_poaQEeSMzJufh3GDGA" id="(1.0,0.5666666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkE_p4aQEeSMzJufh3GDGA" type="4001" element="_bkDx4YaQEeSMzJufh3GDGA" source="_bkEYl4aQEeSMzJufh3GDGA" target="_bkEYt4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvcTEpXdEeSroeU30tgKmw" type="6001" element="_bkDx4YaQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvcTE5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvcTFJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkE_q4aQEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkE_rIaQEeSMzJufh3GDGA" type="4001" element="_bkDx5IaQEeSMzJufh3GDGA" source="_bkEYt4aQEeSMzJufh3GDGA" target="_bkEYu4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvcTFpXdEeSroeU30tgKmw" type="6001" element="_bkDx5IaQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvcTF5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvcTGJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkE_sIaQEeSMzJufh3GDGA" points="[-11, -22, -51, 47]$[42, -57, 2, 12]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_sYaQEeSMzJufh3GDGA" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_soaQEeSMzJufh3GDGA" id="(0.5333333333333333,0.8)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkE_s4aQEeSMzJufh3GDGA" type="4001" element="_bkDx6YaQEeSMzJufh3GDGA" source="_bkEYt4aQEeSMzJufh3GDGA" target="_bkEYvoaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvcTHJXdEeSroeU30tgKmw" type="6001" element="_bkDx6YaQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvcTHZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvc6AJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkE_t4aQEeSMzJufh3GDGA" points="[-14, 1, -91, 0]$[52, -2, -25, -3]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_uIaQEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_uYaQEeSMzJufh3GDGA" id="(0.20833333333333334,0.45)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkE_uoaQEeSMzJufh3GDGA" type="4001" element="_bkDx7IaQEeSMzJufh3GDGA" source="_bkEYpIaQEeSMzJufh3GDGA" target="_bkEYs4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvc6BJXdEeSroeU30tgKmw" type="6001" element="_bkDx7IaQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvc6BZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvc6BpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkE_voaQEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_v4aQEeSMzJufh3GDGA" id="(0.97,0.54)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkE_wIaQEeSMzJufh3GDGA" type="4001" element="_bkDx74aQEeSMzJufh3GDGA" source="_bkEYs4aQEeSMzJufh3GDGA" target="_bkEYxIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvc6CZXdEeSroeU30tgKmw" type="6001" element="_bkDx74aQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvc6CpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvc6C5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkE_xIaQEeSMzJufh3GDGA" points="[-11, -3, -65, 0]$[30, -1, -24, 2]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_xYaQEeSMzJufh3GDGA" id="(1.0,0.813953488372093)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_xoaQEeSMzJufh3GDGA" id="(0.025,0.18333333333333332)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkE_x4aQEeSMzJufh3GDGA" type="4001" element="_bkDx9IaQEeSMzJufh3GDGA" source="_bkEYs4aQEeSMzJufh3GDGA" target="_bkEYwYaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvc6D5XdEeSroeU30tgKmw" type="6001" element="_bkDx9IaQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvc6EJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvc6EZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkE_y4aQEeSMzJufh3GDGA" points="[-4, -10, -40, -95]$[33, 84, -3, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_zIaQEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_zYaQEeSMzJufh3GDGA" id="(0.025,0.4166666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_bkE_zoaQEeSMzJufh3GDGA" type="4001" element="_bkDx94aQEeSMzJufh3GDGA" source="_bkEYx4aQEeSMzJufh3GDGA" target="_bkEYq4aQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvc6FZXdEeSroeU30tgKmw" type="6001" element="_bkDx94aQEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvc6FpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvc6F5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_bkE_0oaQEeSMzJufh3GDGA" points="[0, 0, -75, -29]$[72, 14, -3, -15]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_bkE_04aQEeSMzJufh3GDGA" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_ECQeoYaREeSMzJufh3GDGA" type="4001" element="_ECP3kIaREeSMzJufh3GDGA" source="_xZcwcIaQEeSMzJufh3GDGA" target="_3LhcwIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvc6GpXdEeSroeU30tgKmw" type="6001" element="_ECP3kIaREeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvc6G5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvc6HJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_ECQeo4aREeSMzJufh3GDGA" points="[-7, -2, -57, 0]$[46, -1, -4, 1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_ECcr4IaREeSMzJufh3GDGA" id="(0.9666666666666667,0.5333333333333333)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_ECcr4YaREeSMzJufh3GDGA" id="(0.05,0.5)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_FW9AsIaREeSMzJufh3GDGA" type="4001" element="_FW7ykIaREeSMzJufh3GDGA" source="_3LhcwIaQEeSMzJufh3GDGA" target="_5zsY4IaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvc6IJXdEeSroeU30tgKmw" type="6001" element="_FW7ykIaREeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvc6IZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvc6IpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_FW9AsoaREeSMzJufh3GDGA" points="[0, -5, -35, 0]$[34, -6, -1, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_FXB5MIaREeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_FXB5MYaREeSMzJufh3GDGA" id="(0.007462686567164179,0.4925373134328358)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_F-orwIaREeSMzJufh3GDGA" type="4001" element="_F-ndoIaREeSMzJufh3GDGA" source="_5zsY4IaQEeSMzJufh3GDGA" target="_-5OvUIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvc6JpXdEeSroeU30tgKmw" type="6001" element="_F-ndoIaREeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvc6J5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvc6KJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_F-orwoaREeSMzJufh3GDGA" points="[0, 1, -36, 0]$[36, 1, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_F-qg8IaREeSMzJufh3GDGA" id="(1.0,0.4626865671641791)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_F-qg8YaREeSMzJufh3GDGA" id="(0.0,0.46)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_Gi2zIIaREeSMzJufh3GDGA" type="4001" element="_Gi2MEIaREeSMzJufh3GDGA" source="_-5OvUIaQEeSMzJufh3GDGA" target="_edF0IIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvdhEJXdEeSroeU30tgKmw" type="6001" element="_Gi2MEIaREeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvdhEZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvdhEpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_Gi2zIoaREeSMzJufh3GDGA" points="[0, -6, -40, 0]$[33, -7, -7, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_Gi4oUIaREeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_Gi4oUYaREeSMzJufh3GDGA" id="(0.07,0.46)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_HKsPMIaREeSMzJufh3GDGA" type="4001" element="_HKrBEIaREeSMzJufh3GDGA" source="_edF0IIaQEeSMzJufh3GDGA" target="_y0o8FIaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvdhFpXdEeSroeU30tgKmw" type="6001" element="_HKrBEIaREeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fvdhF5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fvdhGJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_HKsPMoaREeSMzJufh3GDGA" points="[0, -3, -59, 0]$[56, -3, -3, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_HKuEYIaREeSMzJufh3GDGA" id="(1.0,0.6)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_HKuEYYaREeSMzJufh3GDGA" id="(0.1,0.5666666666666667)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_bkE_1IaQEeSMzJufh3GDGA" type="Form" element="_bkDxh4aQEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_bkE_1YaQEeSMzJufh3GDGA" type="2120" element="_bkDxiIaQEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvbFApXdEeSroeU30tgKmw" type="5157" element="_bkDxiIaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkE_14aQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_bkE_2IaQEeSMzJufh3GDGA" type="2126" element="_bkDxtIaQEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_bkE_2YaQEeSMzJufh3GDGA" type="5160" element="_bkDxtIaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_bkE_2oaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_bkE_24aQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_bkE_3IaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkE_3YaQEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_bkE_3oaQEeSMzJufh3GDGA" type="2131" element="_bkDxuIaQEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvbr4ZXdEeSroeU30tgKmw" type="5135" element="_bkDxuIaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkE_4IaQEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_bkE_4YaQEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_bkE_4oaQEeSMzJufh3GDGA" type="Form" element="_bkB8XYaQEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_bkE_44aQEeSMzJufh3GDGA" type="2130" element="_bkB8XoaQEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvbr45XdEeSroeU30tgKmw" type="5148" element="_bkB8XoaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkE_5YaQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_bkE_5oaQEeSMzJufh3GDGA" type="2126" element="_bkB8joaQEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_bkE_54aQEeSMzJufh3GDGA" type="5160" element="_bkB8joaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_bkE_6IaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_bkE_6YaQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_bkE_6oaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkE_64aQEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_bkE_7IaQEeSMzJufh3GDGA" type="2131" element="_bkB8koaQEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvbr5ZXdEeSroeU30tgKmw" type="5135" element="_bkB8koaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkE_7oaQEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_bkE_74aQEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_bkE_8IaQEeSMzJufh3GDGA" type="Form" element="_bkCjY4aQEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_bkE_8YaQEeSMzJufh3GDGA" type="2120" element="_bkCjZIaQEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvbr55XdEeSroeU30tgKmw" type="5157" element="_bkCjZIaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkE_84aQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_bkE_9IaQEeSMzJufh3GDGA" type="2126" element="_bkCjlIaQEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_bkE_9YaQEeSMzJufh3GDGA" type="5160" element="_bkCjlIaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_bkE_9oaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_bkE_94aQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_bkE_-IaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkE_-YaQEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_bkE_-oaQEeSMzJufh3GDGA" type="2131" element="_bkCjmIaQEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvbr6ZXdEeSroeU30tgKmw" type="5135" element="_bkCjmIaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkE__IaQEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_bkE__YaQEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_bkE__oaQEeSMzJufh3GDGA" type="Form" element="_bkCj0oaQEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_bkE__4aQEeSMzJufh3GDGA" type="2130" element="_bkCj04aQEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvbr65XdEeSroeU30tgKmw" type="5148" element="_bkCj04aQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkFAAYaQEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_bkFAAoaQEeSMzJufh3GDGA" type="2126" element="_bkDKh4aQEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_bkFAA4aQEeSMzJufh3GDGA" type="5160" element="_bkDKh4aQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_bkFABIaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_bkFABYaQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_bkFABoaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkFAB4aQEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_bkFACIaQEeSMzJufh3GDGA" type="2131" element="_bkDKi4aQEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvbr7ZXdEeSroeU30tgKmw" type="5135" element="_bkDKi4aQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkFACoaQEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_bkFAC4aQEeSMzJufh3GDGA" type="2131" element="_bkDKmYaQEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvbr75XdEeSroeU30tgKmw" type="5135" element="_bkDKmYaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkFmsYaQEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_bkFmsoaQEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_bkFms4aQEeSMzJufh3GDGA" type="Form" measurementUnit="Pixel">
    <children xmi:id="_bkFmtIaQEeSMzJufh3GDGA" type="2126">
      <children xsi:type="notation:DecorationNode" xmi:id="_bkFmtYaQEeSMzJufh3GDGA" type="5160"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_bkFmtoaQEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_bkFmt4aQEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_bkFmuIaQEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkFmuYaQEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_bkFmuoaQEeSMzJufh3GDGA" type="2131" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fvbr8ZXdEeSroeU30tgKmw" type="5135"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_bkFmvIaQEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_bkFmvYaQEeSMzJufh3GDGA"/>
  </notation:Diagram>
</xmi:XMI>
