<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process">
  <process:MainProcess xmi:id="_BeGHgIaLEeSMzJufh3GDGA" name="Projet_Validation_Diagram_CORTES_MARTINEZ" version="2.0" author="corteshs" bonitaVersion="6.3.8" bonitaModelVersion="6.3.8-001" configId="ACED000574003750726F6A65745F56616C69646174696F6E5F4469616772616D5F434F525445535F4D415254494E455A362E332E382D303031362E332E38">
    <elements xsi:type="process:Pool" xmi:id="_BeGHgYaLEeSMzJufh3GDGA" name="Projet_Validation_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="2.0">
      <elements xsi:type="process:Lane" xmi:id="_BeGHgoaLEeSMzJufh3GDGA" name="Employé (lane)" actor="_BeJyHYaLEeSMzJufh3GDGA">
        <elements xsi:type="process:Task" xmi:id="_BeGHg4aLEeSMzJufh3GDGA" name="Approve proposal" outgoing="_BeJyCIaLEeSMzJufh3GDGA" incoming="_BeJx84aLEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_BeGHhIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_BeGHhYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_BeGHhoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_BeGHh4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_BeGHiIaLEeSMzJufh3GDGA">
            <cardinality xmi:id="_fOvZoJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fOvZoZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_BeGHi4aLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_BeGHjIaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_Qn534IaOEeSMzJufh3GDGA" name="ApproveProposal" nLine="3">
            <widgets xsi:type="form:CheckBoxSingleFormField" xmi:id="_Qn54EYaOEeSMzJufh3GDGA" name="proposalOK1">
              <widgetLayoutInfo xmi:id="_Qn54EoaOEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fOwnxJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fOwnxZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fOwnxpXdEeSroeU30tgKmw" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xsi:type="process:Data" xmi:id="_fOwnx5XdEeSroeU30tgKmw" name="proposalOK" dataType="_BeJyLYaLEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fOwnyJXdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_Qn6e9YaOEeSMzJufh3GDGA">
                <leftOperand xmi:id="_fOx14JXdEeSroeU30tgKmw" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="process:Data" xmi:id="_fOx14ZXdEeSroeU30tgKmw" name="proposalOK" dataType="_BeJyLYaLEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_Qn6e-YaOEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_fOx14pXdEeSroeU30tgKmw" name="field_proposalOK1" content="field_proposalOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="form:CheckBoxSingleFormField" xmi:id="_fOx145XdEeSroeU30tgKmw" name="proposalOK1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_fOwnyZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fOwnypXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_fOwny5XdEeSroeU30tgKmw" name="Approved?" content="Approved?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOwnzJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_fOwnzpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_fOwnz5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_fOwn0JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_fOwn0ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_fOwn0pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_fOwn05XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_fOwn1JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_Qn6fHYaOEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_fOx16pXdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:id="_fOx165XdEeSroeU30tgKmw" name="OK" content="OK" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOx17JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_TMvMIIaOEeSMzJufh3GDGA" name="proposal1">
              <widgetLayoutInfo xmi:id="_fOyc9pXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fOyc95XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fOyc-JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fOyc-ZXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_fOyc-pXdEeSroeU30tgKmw" name="proposal" dataType="_BeJyMoaLEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fOyc-5XdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_fOyc_JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fOyc_ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOyc_pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_fOwAuJXdEeSroeU30tgKmw" name="Approve proposal" content="Approve proposal" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_BeGHjYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_BeGHjoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:StartEvent" xmi:id="_BeGHj4aLEeSMzJufh3GDGA" name="Proposal made" outgoing="_BeJx84aLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fOzrGpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fOzrG5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fOzrHJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fOzrHZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_BeGHoIaLEeSMzJufh3GDGA" name="Analyze Impact" outgoing="_BeJx-YaLEeSMzJufh3GDGA" incoming="_BeJx9oaLEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_BeGHoYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_BeGHooaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_BeGHo4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_BeGHpIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_BeGHpYaLEeSMzJufh3GDGA">
            <cardinality xmi:id="_fOvZopXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fOwAsJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_BeGHqIaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_BeGHqYaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_sUc3cIaOEeSMzJufh3GDGA" name="AnalyzeImpact" nLine="3">
            <widgets xsi:type="form:TextFormField" xmi:id="_sUc3cYaOEeSMzJufh3GDGA" name="impacts1">
              <widgetLayoutInfo xmi:id="_fOzrHpXdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fOzrH5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fOzrIJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fOzrIZXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_fOzrIpXdEeSroeU30tgKmw" name="impacts" dataType="_BeJyMoaLEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fOzrI5XdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_fOzrKJXdEeSroeU30tgKmw">
                <leftOperand xmi:id="_fOzrKZXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                  <referencedElements xsi:type="process:Data" xmi:id="_fOzrKpXdEeSroeU30tgKmw" name="impacts" dataType="_BeJyMoaLEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_fOzrLZXdEeSroeU30tgKmw" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_fOzrK5XdEeSroeU30tgKmw" name="field_impacts1" content="field_impacts1" type="TYPE_INPUT">
                  <referencedElements xsi:type="form:TextFormField" xmi:id="_fOzrLJXdEeSroeU30tgKmw" name="impacts1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_fOzrJJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fOzrJZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_fOzrJpXdEeSroeU30tgKmw" name="Impact?" content="Impact?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOzrJ5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_fOzrLpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_fOzrL5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_fOzrMJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_fOzrMZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_fOzrMpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_fOzrM5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_fOzrNJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_sUde0YaOEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_fOx17ZXdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:id="_fOx17pXdEeSroeU30tgKmw" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOx175XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_4oElMIaOEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:id="_6qd6wIaOEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <htmlAttributes xmi:id="_7WALEIaOEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <widgetLayoutInfo xmi:id="_fOydAZXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fOydApXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fOzEAJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fOzEAZXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_fOzEApXdEeSroeU30tgKmw" name="proposal" dataType="_BeJyMoaLEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fOzEA5XdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_fOzEBJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fOzEBZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOzEBpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_fOwAvJXdEeSroeU30tgKmw" name="Analyze Impact" content="Analyze Impact" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_BeGHqoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_BeGHq4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_BeJK1IaLEeSMzJufh3GDGA" name="Do the project" outgoing="_BeJx_4aLEeSMzJufh3GDGA" incoming="_BeJx_IaLEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_BeJK1YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_BeJK1oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_BeJK14aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_BeJK2IaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_BeJK2YaLEeSMzJufh3GDGA">
            <cardinality xmi:id="_fOwAsZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fOwAspXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_BeJK3IaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_BeJK3YaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_4FKP8IaPEeSMzJufh3GDGA" name="DoTheProject" nLine="3">
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_4FKP8YaPEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_fOx18JXdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:id="_fOx18ZXdEeSroeU30tgKmw" name="Project Finished" content="Project Finished" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOx18pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_8nnugIaPEeSMzJufh3GDGA" name="Message1">
              <widgetLayoutInfo xmi:id="_fOzEB5XdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fOzECJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fOzECZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fOzECpXdEeSroeU30tgKmw" name="Press the button Monkey!!!!" content="Press the button Monkey!!!!"/>
              <afterEventExpression xmi:id="_fOzEC5XdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_fOzEEJXdEeSroeU30tgKmw">
                <leftOperand xmi:id="_fOzEEZXdEeSroeU30tgKmw"/>
                <operator xmi:id="_fOzEE5XdEeSroeU30tgKmw" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:id="_fOzEEpXdEeSroeU30tgKmw"/>
              </action>
              <tooltip xmi:id="_fOzEDJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fOzEDZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_fOzEDpXdEeSroeU30tgKmw" name="Message1" content="Message1" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOzED5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_fOwAv5XdEeSroeU30tgKmw" name="Do the project" content="Do the project" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_BeJK3oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_BeJK34aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_BeJK7IaLEeSMzJufh3GDGA" name="Validate project" outgoing="_BeJyEYaLEeSMzJufh3GDGA" incoming="_BeJx-YaLEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_BeJK7YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_BeJK7oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_BeJK74aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_BeJK8IaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_BeJK8YaLEeSMzJufh3GDGA">
            <cardinality xmi:id="_fOwAs5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fOwAtJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_BeJK9IaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_BeJK9YaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_e474EIaPEeSMzJufh3GDGA" name="ValidateProject">
            <widgets xsi:type="form:CheckBoxSingleFormField" xmi:id="_e48fMoaPEeSMzJufh3GDGA" name="projectOK1">
              <widgetLayoutInfo xmi:id="_e48fM4aPEeSMzJufh3GDGA" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fOwn1pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fOwn15XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fOxO0JXdEeSroeU30tgKmw" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xsi:type="process:Data" xmi:id="_fOxO0ZXdEeSroeU30tgKmw" name="projectOK" dataType="_BeJyLYaLEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fOxO0pXdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_e48fOoaPEeSMzJufh3GDGA">
                <leftOperand xmi:id="_fOx15ZXdEeSroeU30tgKmw" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="process:Data" xmi:id="_fOx15pXdEeSroeU30tgKmw" name="projectOK" dataType="_BeJyLYaLEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_e48fPoaPEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_fOx155XdEeSroeU30tgKmw" name="field_projectOK1" content="field_projectOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="form:CheckBoxSingleFormField" xmi:id="_fOx16JXdEeSroeU30tgKmw" name="projectOK1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_fOxO05XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fOxO1JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_fOxO1ZXdEeSroeU30tgKmw" name="Approve project?" content="Approve project?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOxO1pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_fOxO2JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_fOxO2ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_fOxO2pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_fOxO25XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_fOxO3JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_fOxO3ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_fOxO3pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_e49GN4aPEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_fOyc8JXdEeSroeU30tgKmw" line="3"/>
              <displayLabel xmi:id="_fOyc8ZXdEeSroeU30tgKmw" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOyc8pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_gqqUYIaPEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:id="_iFbCMIaPEeSMzJufh3GDGA" key="input_css:color" value="purple"/>
              <htmlAttributes xmi:id="_iZaVMIaPEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <htmlAttributes xmi:id="_i3W1cIaPEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <widgetLayoutInfo xmi:id="_fOzEF5XdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fOzEGJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fOzEGZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fOzEGpXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_fOzEG5XdEeSroeU30tgKmw" name="proposal" dataType="_BeJyMoaLEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fOzEHJXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_fOzEHZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fOzEHpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOzEH5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_mKTM4IaPEeSMzJufh3GDGA" name="impacts1">
              <htmlAttributes xmi:id="_jtkEsIaPEeSMzJufh3GDGA" key="input_css:color" value="red"/>
              <htmlAttributes xmi:id="_kgEfsIaPEeSMzJufh3GDGA" key="input_css:font-size" value="18px"/>
              <widgetLayoutInfo xmi:id="_fOzEIpXdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fOzEI5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_fOzEJJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_fOzEJZXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_fOzEJpXdEeSroeU30tgKmw" name="impacts" dataType="_BeJyMoaLEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_fOzEJ5XdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_fOzEKJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_fOzEKZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_fOzEKpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_fOwAxJXdEeSroeU30tgKmw" name="Validate project" content="Validate project" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_BeJK9oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_BeJK94aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_BeJLEIaLEeSMzJufh3GDGA" name="Proposal refused" incoming="_BeJyAoaLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fO0SLJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fO0SLZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fO0SLpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fO0SL5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_BeJLFYaLEeSMzJufh3GDGA" name="Project finished" incoming="_BeJyGoaLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fO0SMJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fO0SMZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fO0SMpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fO0SM5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_BeJLGoaLEeSMzJufh3GDGA" name="Project refused" incoming="_BeJyBYaLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fO0SNJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fO0SNZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fO0SNpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fO0SN5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:XORGateway" xmi:id="_BeJx44aLEeSMzJufh3GDGA" name="Project approval?" outgoing="_BeJyFIaLEeSMzJufh3GDGA _BeJyF4aLEeSMzJufh3GDGA" incoming="_BeJyEYaLEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:id="_fO0SOJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fO05MJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fO05MZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fO05MpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:XORGateway" xmi:id="_utXW8IaLEeSMzJufh3GDGA" name="Proposal approval?" outgoing="_BeJyC4aLEeSMzJufh3GDGA _BeJyDoaLEeSMzJufh3GDGA" incoming="_BeJyCIaLEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:id="_fO05M5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fO05NJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fO05NZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fO05NpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_mD--8IaOEeSMzJufh3GDGA" name="Notify proposal aproved" outgoing="_BeJx9oaLEeSMzJufh3GDGA" incoming="_BeJyC4aLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fO05N5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fO05OJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fO05OZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fO05OpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fO05O5XdEeSroeU30tgKmw">
            <cardinality xmi:id="_fO05PJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fO05PZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fO05PpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fO05P5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_np8QIIaOEeSMzJufh3GDGA" name="Notify proposal refusal" outgoing="_BeJyAoaLEeSMzJufh3GDGA" incoming="_BeJyDoaLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fO05QJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fO05QZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fO05QpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fO05Q5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fO05RJXdEeSroeU30tgKmw">
            <cardinality xmi:id="_fO05RZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fO05RpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fO05R5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fO05SJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_0uz_MIaPEeSMzJufh3GDGA" name="Notify project refused" outgoing="_BeJyBYaLEeSMzJufh3GDGA" incoming="_BeJyF4aLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fO05SZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fO05SpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fO05S5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fO05TJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fO05TZXdEeSroeU30tgKmw">
            <cardinality xmi:id="_fO05TpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fO05T5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fO05UJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fO05UZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_1dRnsIaPEeSMzJufh3GDGA" name="Notify project accepted" outgoing="_BeJx_IaLEeSMzJufh3GDGA" incoming="_BeJyFIaLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fO1gQJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fO1gQZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fO1gQpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fO1gQ5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fO1gRJXdEeSroeU30tgKmw">
            <cardinality xmi:id="_fO1gRZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fO1gRpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fO1gR5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fO1gSJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_JfAQoIaQEeSMzJufh3GDGA" name="Notify project delivery" outgoing="_BeJyGoaLEeSMzJufh3GDGA" incoming="_BeJx_4aLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_fO1gSZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_fO1gSpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_fO1gS5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_fO1gTJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_fO1gTZXdEeSroeU30tgKmw">
            <cardinality xmi:id="_fO1gTpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_fO1gT5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_fO1gUJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_fO1gUZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:id="_Bj_UIIaLEeSMzJufh3GDGA" path="_BeGHgYaLEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:id="_BeJx6YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_BeJx6oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_BeJx64aLEeSMzJufh3GDGA" path="_BeGHgYaLEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:id="_BeJx7IaLEeSMzJufh3GDGA" path="_BeGHgYaLEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:id="_BeJx7YaLEeSMzJufh3GDGA" path="_BeGHgYaLEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:id="_BeJx7oaLEeSMzJufh3GDGA" path="_BeGHgYaLEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:id="_bok3YIaLEeSMzJufh3GDGA" name="proposal" dataType="_BeJyMoaLEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fOxO35XdEeSroeU30tgKmw" content=""/>
      </data>
      <data xmi:id="_fv210IaLEeSMzJufh3GDGA" name="proposalOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fOxO4JXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_inbf4IaLEeSMzJufh3GDGA" name="projectOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fOxO4ZXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_pSIdUIaLEeSMzJufh3GDGA" name="impacts" dataType="_BeJyMoaLEeSMzJufh3GDGA">
        <defaultValue xmi:id="_fOxO4pXdEeSroeU30tgKmw" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <form xmi:id="_iVjQQIaMEeSMzJufh3GDGA" name="Project_Validation_CORTES_MARTINEZ" nLine="3">
        <widgets xsi:type="form:TextFormField" xmi:id="_iVjQQYaMEeSMzJufh3GDGA" name="proposal1">
          <widgetLayoutInfo xmi:id="_fOzrNZXdEeSroeU30tgKmw" line="1"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fOzrNpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:id="_fOzrN5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:id="_fOzrOJXdEeSroeU30tgKmw" name="" content=""/>
          <afterEventExpression xmi:id="_fOzrOZXdEeSroeU30tgKmw" name="" content=""/>
          <action xmi:id="_fOzrPpXdEeSroeU30tgKmw">
            <leftOperand xmi:id="_fO0SIJXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
              <referencedElements xsi:type="process:Data" xmi:id="_fO0SIZXdEeSroeU30tgKmw" name="proposal" dataType="_BeJyMoaLEeSMzJufh3GDGA"/>
            </leftOperand>
            <operator xmi:id="_fO0SJJXdEeSroeU30tgKmw" type="ASSIGNMENT"/>
            <rightOperand xmi:id="_fO0SIpXdEeSroeU30tgKmw" name="field_proposal1" content="field_proposal1" type="TYPE_INPUT">
              <referencedElements xsi:type="form:TextFormField" xmi:id="_fO0SI5XdEeSroeU30tgKmw" name="proposal1"/>
            </rightOperand>
          </action>
          <tooltip xmi:id="_fOzrOpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:id="_fOzrO5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:id="_fOzrPJXdEeSroeU30tgKmw" name="Proposal" content="Proposal" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_fOzrPZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <maxNumberOfDuplication xmi:id="_fO0SJZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:id="_fO0SJpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <displayLabelForAdd xmi:id="_fO0SJ5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <tooltipForAdd xmi:id="_fO0SKJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabelForRemove xmi:id="_fO0SKZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <tooltipForRemove xmi:id="_fO0SKpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <exampleMessage xmi:id="_fO0SK5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </widgets>
        <widgets xsi:type="form:SubmitFormButton" xmi:id="_iVjQbYaMEeSMzJufh3GDGA" name="Soumettre1">
          <widgetLayoutInfo xmi:id="_fOyc85XdEeSroeU30tgKmw" line="2"/>
          <displayLabel xmi:id="_fOyc9JXdEeSroeU30tgKmw" name="OK" content="OK" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_fOyc9ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <widgets xsi:type="form:MessageInfo" xmi:id="_sdX00IaMEeSMzJufh3GDGA" name="Enter proposal:">
          <htmlAttributes xmi:id="_zDz9UIaMEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
          <widgetLayoutInfo xmi:id="_fOzELJXdEeSroeU30tgKmw"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_fOzELZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:id="_fOzELpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:id="_fOzrEJXdEeSroeU30tgKmw" name="" content=""/>
          <afterEventExpression xmi:id="_fOzrEZXdEeSroeU30tgKmw" name="" content=""/>
          <action xmi:id="_fOzrFpXdEeSroeU30tgKmw">
            <leftOperand xmi:id="_fOzrF5XdEeSroeU30tgKmw"/>
            <operator xmi:id="_fOzrGZXdEeSroeU30tgKmw" type="ASSIGNMENT" expression="="/>
            <rightOperand xmi:id="_fOzrGJXdEeSroeU30tgKmw"/>
          </action>
          <tooltip xmi:id="_fOzrEpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:id="_fOzrE5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:id="_fOzrFJXdEeSroeU30tgKmw" name="Message1" content="Message1" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_fOzrFZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:id="_fOwnwpXdEeSroeU30tgKmw" name="Propose proposal" content="Propose proposal" returnTypeFixed="true"/>
      </form>
      <entryRedirectionURL xmi:id="_BeJx74aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_BeJx8IaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_BeJx8YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_BeJx8oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJx84aLEeSMzJufh3GDGA" source="_BeGHj4aLEeSMzJufh3GDGA" target="_BeGHg4aLEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJx9IaLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO1gU5XdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJx9oaLEeSMzJufh3GDGA" source="_mD--8IaOEeSMzJufh3GDGA" target="_BeGHoIaLEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJx94aLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HUJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJx-YaLEeSMzJufh3GDGA" source="_BeGHoIaLEeSMzJufh3GDGA" target="_BeJK7IaLEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJx-oaLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HUpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJx_IaLEeSMzJufh3GDGA" source="_1dRnsIaPEeSMzJufh3GDGA" target="_BeJK1IaLEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJx_YaLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HVJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJx_4aLEeSMzJufh3GDGA" source="_BeJK1IaLEeSMzJufh3GDGA" target="_JfAQoIaQEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJyAIaLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HVpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJyAoaLEeSMzJufh3GDGA" source="_np8QIIaOEeSMzJufh3GDGA" target="_BeJLEIaLEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJyA4aLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HWJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJyBYaLEeSMzJufh3GDGA" source="_0uz_MIaPEeSMzJufh3GDGA" target="_BeJLGoaLEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJyBoaLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HWpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJyCIaLEeSMzJufh3GDGA" source="_BeGHg4aLEeSMzJufh3GDGA" target="_utXW8IaLEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJyCYaLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HXJXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJyC4aLEeSMzJufh3GDGA" name="Approved" source="_utXW8IaLEeSMzJufh3GDGA" target="_mD--8IaOEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJyDIaLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HXpXdEeSroeU30tgKmw" name="proposalOK==true" content="proposalOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xsi:type="process:Data" xmi:id="_fO2HX5XdEeSroeU30tgKmw" name="proposalOK" dataType="_BeJyLYaLEeSMzJufh3GDGA"/>
        </condition>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJyDoaLEeSMzJufh3GDGA" name="Not Approved" source="_utXW8IaLEeSMzJufh3GDGA" target="_np8QIIaOEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:id="_BeJyD4aLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HYZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJyEYaLEeSMzJufh3GDGA" source="_BeJK7IaLEeSMzJufh3GDGA" target="_BeJx44aLEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJyEoaLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HY5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJyFIaLEeSMzJufh3GDGA" name="Approved" source="_BeJx44aLEeSMzJufh3GDGA" target="_1dRnsIaPEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJyFYaLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HZZXdEeSroeU30tgKmw" name="projectOK==true" content="projectOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xsi:type="process:Data" xmi:id="_fO2HZpXdEeSroeU30tgKmw" name="projectOK" dataType="_BeJyLYaLEeSMzJufh3GDGA"/>
        </condition>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJyF4aLEeSMzJufh3GDGA" name="Not approved" source="_BeJx44aLEeSMzJufh3GDGA" target="_0uz_MIaPEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:id="_BeJyGIaLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2HaJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_BeJyGoaLEeSMzJufh3GDGA" source="_JfAQoIaQEeSMzJufh3GDGA" target="_BeJLFYaLEeSMzJufh3GDGA">
        <decisionTable xmi:id="_BeJyG4aLEeSMzJufh3GDGA"/>
        <condition xmi:id="_fO2uYZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:id="_BeJyHYaLEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:id="_BeJyHoaLEeSMzJufh3GDGA">
        <name xmi:id="_fO2uYpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fO2uY5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_BeJyIYaLEeSMzJufh3GDGA">
        <name xmi:id="_fO2uZJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fO2uZZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_BeJyJIaLEeSMzJufh3GDGA">
        <name xmi:id="_fO2uZpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fO2uZ5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_BeJyJ4aLEeSMzJufh3GDGA">
        <name xmi:id="_fO2uaJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fO2uaZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_BeJyKoaLEeSMzJufh3GDGA">
        <name xmi:id="_fO2uapXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_fO2ua5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xsi:type="process:BooleanType" xmi:id="_BeJyLYaLEeSMzJufh3GDGA" name="Boolean"/>
    <datatypes xsi:type="process:DateType" xmi:id="_BeJyLoaLEeSMzJufh3GDGA" name="Date"/>
    <datatypes xsi:type="process:IntegerType" xmi:id="_BeJyL4aLEeSMzJufh3GDGA" name="Integer"/>
    <datatypes xsi:type="process:LongType" xmi:id="_BeJyMIaLEeSMzJufh3GDGA" name="Long"/>
    <datatypes xsi:type="process:DoubleType" xmi:id="_BeJyMYaLEeSMzJufh3GDGA" name="Double"/>
    <datatypes xsi:type="process:StringType" xmi:id="_BeJyMoaLEeSMzJufh3GDGA" name="Text"/>
    <datatypes xsi:type="process:JavaType" xmi:id="_BeJyM4aLEeSMzJufh3GDGA" name="Java_object"/>
    <datatypes xsi:type="process:XMLType" xmi:id="_BeJyNIaLEeSMzJufh3GDGA" name="XML"/>
    <datatypes xsi:type="process:BusinessObjectType" xmi:id="_fOgwKZXdEeSroeU30tgKmw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_BeJyNYaLEeSMzJufh3GDGA" type="Process" element="_BeGHgIaLEeSMzJufh3GDGA" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:id="_BeKY8IaLEeSMzJufh3GDGA" type="2007" element="_BeGHgYaLEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_BeKY8YaLEeSMzJufh3GDGA" type="5008" element="_BeGHgYaLEeSMzJufh3GDGA"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_BeKY8oaLEeSMzJufh3GDGA" type="7001" element="_BeGHgYaLEeSMzJufh3GDGA">
        <children xmi:id="_fO81AJXdEeSroeU30tgKmw" type="3007" element="_BeGHgoaLEeSMzJufh3GDGA">
          <children xsi:type="notation:DecorationNode" xmi:id="_BeKY9IaLEeSMzJufh3GDGA" type="5007" element="_BeGHgoaLEeSMzJufh3GDGA"/>
          <children xsi:type="notation:DecorationNode" xmi:id="_BeKY9YaLEeSMzJufh3GDGA" type="7002" element="_BeGHgoaLEeSMzJufh3GDGA">
            <children xsi:type="notation:Shape" xmi:id="_BeKY9oaLEeSMzJufh3GDGA" type="3005" element="_BeGHg4aLEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO-qMJXdEeSroeU30tgKmw" type="5005" element="_BeGHg4aLEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeKY-IaLEeSMzJufh3GDGA" x="119" y="165"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_BeKY-YaLEeSMzJufh3GDGA" type="3002" element="_BeGHj4aLEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO-qMpXdEeSroeU30tgKmw" type="5024" element="_BeGHj4aLEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_BeKY-4aLEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeKY_IaLEeSMzJufh3GDGA" x="40" y="179"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_BeKZAIaLEeSMzJufh3GDGA" type="3005" element="_BeGHoIaLEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO-qNZXdEeSroeU30tgKmw" type="5005" element="_BeGHoIaLEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeKZAoaLEeSMzJufh3GDGA" x="421" y="102"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_BeKZBoaLEeSMzJufh3GDGA" type="3005" element="_BeJK1IaLEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO-qN5XdEeSroeU30tgKmw" type="5005" element="_BeJK1IaLEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeKZCIaLEeSMzJufh3GDGA" x="913" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_BeKZDIaLEeSMzJufh3GDGA" type="3005" element="_BeJK7IaLEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO-qOZXdEeSroeU30tgKmw" type="5005" element="_BeJK7IaLEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeKZDoaLEeSMzJufh3GDGA" x="556" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_BeKZFYaLEeSMzJufh3GDGA" type="3062" element="_BeJLEIaLEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO_RQZXdEeSroeU30tgKmw" type="5090" element="_BeJLEIaLEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_BeKZF4aLEeSMzJufh3GDGA" x="-1" y="18"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeKZGIaLEeSMzJufh3GDGA" x="537" y="197"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_BeKZGYaLEeSMzJufh3GDGA" type="3062" element="_BeJLFYaLEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO_RRJXdEeSroeU30tgKmw" type="5090" element="_BeJLFYaLEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_BeKZG4aLEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeKZHIaLEeSMzJufh3GDGA" x="1221" y="136"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_BeKZHYaLEeSMzJufh3GDGA" type="3062" element="_BeJLGoaLEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO_RR5XdEeSroeU30tgKmw" type="5090" element="_BeJLGoaLEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_BeKZH4aLEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeKZIIaLEeSMzJufh3GDGA" x="1012" y="226"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_BeKZJYaLEeSMzJufh3GDGA" type="3008" element="_BeJx44aLEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO_4UJXdEeSroeU30tgKmw" type="5026" element="_BeJx44aLEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_BeKZJ4aLEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeKZKIaLEeSMzJufh3GDGA" x="689" y="105" width="43" height="43"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_utYlEIaLEeSMzJufh3GDGA" type="3008" element="_utXW8IaLEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO_4U5XdEeSroeU30tgKmw" type="5026" element="_utXW8IaLEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_utYlE4aLEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_utYlEYaLEeSMzJufh3GDGA" x="230" y="170" width="43" height="43"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_mECpUIaOEeSMzJufh3GDGA" type="3027" element="_mD--8IaOEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO_4VpXdEeSroeU30tgKmw" type="5017" element="_mD--8IaOEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_mECpUYaOEeSMzJufh3GDGA" x="271" y="95" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_np9eQIaOEeSMzJufh3GDGA" type="3027" element="_np8QIIaOEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO_4WJXdEeSroeU30tgKmw" type="5017" element="_np8QIIaOEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_np9eQYaOEeSMzJufh3GDGA" x="347" y="187" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_0u4QoIaPEeSMzJufh3GDGA" type="3027" element="_0uz_MIaPEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO_4WpXdEeSroeU30tgKmw" type="5017" element="_0uz_MIaPEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_0u4QoYaPEeSMzJufh3GDGA" x="765" y="192" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_1dSOyIaPEeSMzJufh3GDGA" type="3027" element="_1dRnsIaPEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO_4XJXdEeSroeU30tgKmw" type="5017" element="_1dRnsIaPEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_1dSOyYaPEeSMzJufh3GDGA" x="762" y="96" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_JfA3uYaQEeSMzJufh3GDGA" type="3027" element="_JfAQoIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_fO_4XpXdEeSroeU30tgKmw" type="5017" element="_JfAQoIaQEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_JfA3uoaQEeSMzJufh3GDGA" x="1041" y="90" width="120" height="60"/>
            </children>
          </children>
          <styles xsi:type="notation:DescriptionStyle" xmi:id="_BeKZKYaLEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FontStyle" xmi:id="_BeKZKoaLEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xsi:type="notation:LineStyle" xmi:id="_BeLAAIaLEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FillStyle" xmi:id="_BeLAAYaLEeSMzJufh3GDGA"/>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeLAAoaLEeSMzJufh3GDGA" x="45" y="10" width="1372" height="302"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_BeLAA4aLEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_BeLABIaLEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_BeLABYaLEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_BeLABoaLEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BeLAB4aLEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_BeLACIaLEeSMzJufh3GDGA"/>
    <edges xsi:type="notation:Connector" xmi:id="_BeLACYaLEeSMzJufh3GDGA" type="4001" element="_BeJx84aLEeSMzJufh3GDGA" source="_BeKY-YaLEeSMzJufh3GDGA" target="_BeKY9oaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPK3cJXdEeSroeU30tgKmw" type="6001" element="_BeJx84aLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPK3cZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPK3cpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLADYaLEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLADoaLEeSMzJufh3GDGA" type="4001" element="_BeJx9oaLEeSMzJufh3GDGA" source="_mECpUIaOEeSMzJufh3GDGA" target="_BeKZAIaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPK3dJXdEeSroeU30tgKmw" type="6001" element="_BeJx9oaLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPK3dZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPK3dpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLAEoaLEeSMzJufh3GDGA" points="[0, 1, -66, -7]$[16, 1, -50, -7]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLAE4aLEeSMzJufh3GDGA" id="(1.0,0.55)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLAFIaLEeSMzJufh3GDGA" type="4001" element="_BeJx-YaLEeSMzJufh3GDGA" source="_BeKZAIaLEeSMzJufh3GDGA" target="_BeKZDIaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPLegJXdEeSroeU30tgKmw" type="6001" element="_BeJx-YaLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPLegZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPLegpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLAGIaLEeSMzJufh3GDGA" points="[0, 0, -41, 91]$[-9, -91, -50, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLAGYaLEeSMzJufh3GDGA" id="(1.0,0.64)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLAGoaLEeSMzJufh3GDGA" type="4001" element="_BeJx_IaLEeSMzJufh3GDGA" source="_1dSOyIaPEeSMzJufh3GDGA" target="_BeKZBoaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPLehZXdEeSroeU30tgKmw" type="6001" element="_BeJx_IaLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPLehpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPLeh5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLAHoaLEeSMzJufh3GDGA" points="[0, 0, -5, -60]$[55, 51, 50, -9]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLAH4aLEeSMzJufh3GDGA" id="(1.0,0.5)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLAIIaLEeSMzJufh3GDGA" type="4001" element="_BeJx_4aLEeSMzJufh3GDGA" source="_BeKZBoaLEeSMzJufh3GDGA" target="_JfA3uYaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPLeipXdEeSroeU30tgKmw" type="6001" element="_BeJx_4aLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPLei5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPLejJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLAJIaLEeSMzJufh3GDGA" points="[0, 0, -60, 48]$[65, -35, 5, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLAJYaLEeSMzJufh3GDGA" id="(1.0,0.6)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLAJoaLEeSMzJufh3GDGA" id="(0.5583333333333333,0.7833333333333333)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLAJ4aLEeSMzJufh3GDGA" type="4001" element="_BeJyAoaLEeSMzJufh3GDGA" source="_np9eQIaOEeSMzJufh3GDGA" target="_BeKZFYaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPLekJXdEeSroeU30tgKmw" type="6001" element="_BeJyAoaLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPLekZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPLekpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLAK4aLEeSMzJufh3GDGA" points="[0, -8, -85, 2]$[78, 3, -7, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLALIaLEeSMzJufh3GDGA" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLALYaLEeSMzJufh3GDGA" type="4001" element="_BeJyBYaLEeSMzJufh3GDGA" source="_0u4QoIaPEeSMzJufh3GDGA" target="_BeKZHYaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPMFkJXdEeSroeU30tgKmw" type="6001" element="_BeJyBYaLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPMFkZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPMFkpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLAMYaLEeSMzJufh3GDGA" points="[0, 0, -142, -15]$[135, 28, -7, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLAMoaLEeSMzJufh3GDGA" id="(1.0,0.5666666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLAM4aLEeSMzJufh3GDGA" type="4001" element="_BeJyCIaLEeSMzJufh3GDGA" source="_BeKY9oaLEeSMzJufh3GDGA" target="_utYlEIaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPMFlZXdEeSroeU30tgKmw" type="6001" element="_BeJyCIaLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPMFlpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPMFl5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLAN4aLEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLAOIaLEeSMzJufh3GDGA" type="4001" element="_BeJyC4aLEeSMzJufh3GDGA" source="_utYlEIaLEeSMzJufh3GDGA" target="_mECpUIaOEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPMFmZXdEeSroeU30tgKmw" type="6001" element="_BeJyC4aLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPMFmpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPMFm5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLAPIaLEeSMzJufh3GDGA" points="[-11, -22, -51, 47]$[42, -57, 2, 12]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLAPYaLEeSMzJufh3GDGA" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLAPoaLEeSMzJufh3GDGA" id="(0.5333333333333333,0.8)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLAP4aLEeSMzJufh3GDGA" type="4001" element="_BeJyDoaLEeSMzJufh3GDGA" source="_utYlEIaLEeSMzJufh3GDGA" target="_np9eQIaOEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPMFn5XdEeSroeU30tgKmw" type="6001" element="_BeJyDoaLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPMFoJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPMFoZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLnE4aLEeSMzJufh3GDGA" points="[-14, 1, -91, 0]$[52, -2, -25, -3]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLnFIaLEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLnFYaLEeSMzJufh3GDGA" id="(0.20833333333333334,0.45)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLnFoaLEeSMzJufh3GDGA" type="4001" element="_BeJyEYaLEeSMzJufh3GDGA" source="_BeKZDIaLEeSMzJufh3GDGA" target="_BeKZJYaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPMFpZXdEeSroeU30tgKmw" type="6001" element="_BeJyEYaLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPMFppXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPMFp5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLnGoaLEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLnG4aLEeSMzJufh3GDGA" id="(0.97,0.54)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLnHIaLEeSMzJufh3GDGA" type="4001" element="_BeJyFIaLEeSMzJufh3GDGA" source="_BeKZJYaLEeSMzJufh3GDGA" target="_1dSOyIaPEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPMFqpXdEeSroeU30tgKmw" type="6001" element="_BeJyFIaLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPMFq5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPMFrJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLnIIaLEeSMzJufh3GDGA" points="[-11, -3, -65, 0]$[30, -1, -24, 2]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLnIYaLEeSMzJufh3GDGA" id="(1.0,0.813953488372093)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLnIoaLEeSMzJufh3GDGA" id="(0.025,0.18333333333333332)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLnI4aLEeSMzJufh3GDGA" type="4001" element="_BeJyF4aLEeSMzJufh3GDGA" source="_BeKZJYaLEeSMzJufh3GDGA" target="_0u4QoIaPEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPMso5XdEeSroeU30tgKmw" type="6001" element="_BeJyF4aLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPMspJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPMspZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLnJ4aLEeSMzJufh3GDGA" points="[-4, -10, -40, -95]$[33, 84, -3, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLnKIaLEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLnKYaLEeSMzJufh3GDGA" id="(0.025,0.4166666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_BeLnKoaLEeSMzJufh3GDGA" type="4001" element="_BeJyGoaLEeSMzJufh3GDGA" source="_JfA3uYaQEeSMzJufh3GDGA" target="_BeKZGYaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPMsqZXdEeSroeU30tgKmw" type="6001" element="_BeJyGoaLEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_fPMsqpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_fPMsq5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_BeLnLoaLEeSMzJufh3GDGA" points="[0, 0, -75, -29]$[72, 14, -3, -15]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BeLnL4aLEeSMzJufh3GDGA" id="(1.0,0.5333333333333333)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_iVxSsIaMEeSMzJufh3GDGA" type="Form" element="_iVjQQIaMEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_iXVY8IaMEeSMzJufh3GDGA" type="2120" element="_iVjQQYaMEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fO_4YJXdEeSroeU30tgKmw" type="5157" element="_iVjQQYaMEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_iXVY8YaMEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_iXWAAYaMEeSMzJufh3GDGA" type="2126" element="_iVjQbYaMEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_iXWnEIaMEeSMzJufh3GDGA" type="5160" element="_iVjQbYaMEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_iXWAAoaMEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_iXWAA4aMEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_iXWABIaMEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_iXWABYaMEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_sdaREIaMEeSMzJufh3GDGA" type="2131" element="_sdX00IaMEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fO_4YpXdEeSroeU30tgKmw" type="5135" element="_sdX00IaMEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_sda4IIaMEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_iVxSsYaMEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_Qn9iQIaOEeSMzJufh3GDGA" type="Form" element="_Qn534IaOEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_QoNZ44aOEeSMzJufh3GDGA" type="2130" element="_Qn54EYaOEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPAfYJXdEeSroeU30tgKmw" type="5148" element="_Qn54EYaOEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_QoNZ5IaOEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_QoOA8YaOEeSMzJufh3GDGA" type="2126" element="_Qn6fHYaOEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_QoOA9oaOEeSMzJufh3GDGA" type="5160" element="_Qn6fHYaOEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_QoOA8oaOEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_QoOA84aOEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_QoOA9IaOEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_QoOA9YaOEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_TMwaQIaOEeSMzJufh3GDGA" type="2131" element="_TMvMIIaOEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPAfYpXdEeSroeU30tgKmw" type="5135" element="_TMvMIIaOEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_TMwaQYaOEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_Qn9iQYaOEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_sUgh0IaOEeSMzJufh3GDGA" type="Form" element="_sUc3cIaOEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_sUsIAIaOEeSMzJufh3GDGA" type="2120" element="_sUc3cYaOEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPAfZJXdEeSroeU30tgKmw" type="5157" element="_sUc3cYaOEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_sUsIAYaOEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_sUsvFIaOEeSMzJufh3GDGA" type="2126" element="_sUde0YaOEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_sUsvGYaOEeSMzJufh3GDGA" type="5160" element="_sUde0YaOEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_sUsvFYaOEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_sUsvFoaOEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_sUsvF4aOEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_sUsvGIaOEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_4oFMTIaOEeSMzJufh3GDGA" type="2131" element="_4oElMIaOEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPAfZpXdEeSroeU30tgKmw" type="5135" element="_4oElMIaOEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_4oFMTYaOEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_sUgh0YaOEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_e5BXoIaPEeSMzJufh3GDGA" type="Form" element="_e474EIaPEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_e5RPQ4aPEeSMzJufh3GDGA" type="2130" element="_e48fMoaPEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPAfaJXdEeSroeU30tgKmw" type="5148" element="_e48fMoaPEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_e5RPRIaPEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_e5R2U4aPEeSMzJufh3GDGA" type="2126" element="_e49GN4aPEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_e5R2WIaPEeSMzJufh3GDGA" type="5160" element="_e49GN4aPEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_e5R2VIaPEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_e5R2VYaPEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_e5R2VoaPEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_e5R2V4aPEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_gqrigIaPEeSMzJufh3GDGA" type="2131" element="_gqqUYIaPEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPAfapXdEeSroeU30tgKmw" type="5135" element="_gqqUYIaPEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_gqrigYaPEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_mKTz8IaPEeSMzJufh3GDGA" type="2131" element="_mKTM4IaPEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPBGcJXdEeSroeU30tgKmw" type="5135" element="_mKTM4IaPEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_mKTz8YaPEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_e5BXoYaPEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_4FLeEIaPEeSMzJufh3GDGA" type="Form" element="_4FKP8IaPEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:id="_4FXrUIaPEeSMzJufh3GDGA" type="2126" element="_4FKP8YaPEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_4FYSYIaPEeSMzJufh3GDGA" type="5160" element="_4FKP8YaPEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_4FXrUYaPEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_4FXrUoaPEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_4FXrU4aPEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_4FXrVIaPEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_8no8oIaPEeSMzJufh3GDGA" type="2131" element="_8nnugIaPEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_fPBGcpXdEeSroeU30tgKmw" type="5135" element="_8nnugIaPEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8no8oYaPEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_4FLeEYaPEeSMzJufh3GDGA"/>
  </notation:Diagram>
</xmi:XMI>
