<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process">
  <process:MainProcess xmi:id="_AOkqQIaUEeSMzJufh3GDGA" name="Projet_Validation_Diagram_CORTES_MARTINEZ" version="5.0" author="corteshs" bonitaVersion="6.3.8" bonitaModelVersion="6.3.8-001" configId="ACED000574003750726F6A65745F56616C69646174696F6E5F4469616772616D5F434F525445535F4D415254494E455A362E332E382D303031362E332E38">
    <elements xsi:type="process:Pool" xmi:id="_AOkqQYaUEeSMzJufh3GDGA" name="Projet_Validation_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="5.0">
      <elements xsi:type="process:Lane" xmi:id="_AOkqQoaUEeSMzJufh3GDGA" name="Employé (lane)" actor="_AOksKYaUEeSMzJufh3GDGA">
        <elements xsi:type="process:Task" xmi:id="_AOkqQ4aUEeSMzJufh3GDGA" name="Approve proposal" outgoing="_AOksDYaUEeSMzJufh3GDGA" incoming="_AOkr-IaUEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_AOkqRIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_AOkqRYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_AOkqRoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_AOkqR4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_AOkqSIaUEeSMzJufh3GDGA">
            <cardinality xmi:id="_gxSxgJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxSxgZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <BoundaryIntermediateEvents xsi:type="process:BoundaryTimerEvent" xmi:id="_AOkqS4aUEeSMzJufh3GDGA" name="BoundaryTimerEvent" outgoing="_AOksJoaUEeSMzJufh3GDGA">
            <condition xmi:id="_gxSxjpXdEeSroeU30tgKmw" name="5 Jours 00:00:00" content="432000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long">
              <referencedElements xsi:type="process:Data" xmi:id="_gxTYkJXdEeSroeU30tgKmw" name="proposalOK" dataType="_AOlRiYaUEeSMzJufh3GDGA"/>
            </condition>
          </BoundaryIntermediateEvents>
          <loopCondition xmi:id="_AOkqT4aUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_AOkqUIaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_AOkqUYaUEeSMzJufh3GDGA" name="ApproveProposal" nLine="3">
            <widgets xsi:type="form:CheckBoxSingleFormField" xmi:id="_AOkqUoaUEeSMzJufh3GDGA" name="proposalOK1">
              <widgetLayoutInfo xmi:id="_AOkqU4aUEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gxT_uZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gxT_upXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gxT_u5XdEeSroeU30tgKmw" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xsi:type="process:Data" xmi:id="_gxT_vJXdEeSroeU30tgKmw" name="proposalOK" dataType="_AOlRiYaUEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gxT_vZXdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_AOkqWoaUEeSMzJufh3GDGA">
                <leftOperand xmi:id="_gxUmt5XdEeSroeU30tgKmw" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="process:Data" xmi:id="_gxUmuJXdEeSroeU30tgKmw" name="proposalOK" dataType="_AOlRiYaUEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_AOkqXoaUEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_gxUmuZXdEeSroeU30tgKmw" name="field_proposalOK1" content="field_proposalOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="form:CheckBoxSingleFormField" xmi:id="_gxUmupXdEeSroeU30tgKmw" name="proposalOK1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_gxT_vpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gxT_v5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_gxT_wJXdEeSroeU30tgKmw" name="Approved?" content="Approved?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gxT_wZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_gxT_w5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_gxT_xJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_gxT_xZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_gxT_xpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_gxT_x5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_gxT_yJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_gxT_yZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_AOkqgoaUEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_gxUmwZXdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:id="_gxUmwpXdEeSroeU30tgKmw" name="OK" content="OK" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gxUmw5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_AOkqhoaUEeSMzJufh3GDGA" name="proposal1">
              <widgetLayoutInfo xmi:id="_gxUmzZXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gxUmzpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gxUmz5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gxUm0JXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_gxUm0ZXdEeSroeU30tgKmw" name="proposal" dataType="_AOlRjoaUEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gxUm0pXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_gxUm05XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gxUm1JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gxUm1ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_gxT_qpXdEeSroeU30tgKmw" name="Approve proposal" content="Approve proposal" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_AOkqkoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_AOkqk4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:StartEvent" xmi:id="_AOkqlIaUEeSMzJufh3GDGA" name="Proposal made" outgoing="_AOkr-IaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxUnBpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxUnB5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxVNwJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxVNwZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_AOkqmYaUEeSMzJufh3GDGA" name="Analyze Impact" outgoing="_AOkr_oaUEeSMzJufh3GDGA" incoming="_AOkr-4aUEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_AOkqmoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_AOkqm4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_AOkqnIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_AOkqnYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_AOkqnoaUEeSMzJufh3GDGA">
            <cardinality xmi:id="_gxSxgpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxSxg5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_AOkqoYaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_AOkqooaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_AOkqo4aUEeSMzJufh3GDGA" name="AnalyzeImpact" nLine="3">
            <widgets xsi:type="form:TextFormField" xmi:id="_AOkqpIaUEeSMzJufh3GDGA" name="impacts1">
              <widgetLayoutInfo xmi:id="_gxVNxpXdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gxVNx5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gxVNyJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gxVNyZXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_gxVNypXdEeSroeU30tgKmw" name="impacts" dataType="_AOlRjoaUEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gxVNy5XdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_gxVN0JXdEeSroeU30tgKmw">
                <leftOperand xmi:id="_gxVN0ZXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                  <referencedElements xsi:type="process:Data" xmi:id="_gxVN0pXdEeSroeU30tgKmw" name="impacts" dataType="_AOlRjoaUEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_gxVN1ZXdEeSroeU30tgKmw" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_gxVN05XdEeSroeU30tgKmw" name="field_impacts1" content="field_impacts1" type="TYPE_INPUT">
                  <referencedElements xsi:type="form:TextFormField" xmi:id="_gxVN1JXdEeSroeU30tgKmw" name="impacts1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_gxVNzJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gxVNzZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_gxVNzpXdEeSroeU30tgKmw" name="Impact?" content="Impact?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gxVNz5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_gxVN1pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_gxVN15XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_gxVN2JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_gxVN2ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_gxVN2pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_gxVN25XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_gxVN3JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_AOkq1IaUEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_gxUmxJXdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:id="_gxUmxZXdEeSroeU30tgKmw" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gxUmxpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_AOkq2IaUEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:id="_AOkq2YaUEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <htmlAttributes xmi:id="_AOkq2oaUEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <widgetLayoutInfo xmi:id="_gxUm2JXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gxUm2ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gxUm2pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gxUm25XdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_gxUm3JXdEeSroeU30tgKmw" name="proposal" dataType="_AOlRjoaUEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gxUm3ZXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_gxUm3pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gxUm35XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gxUm4JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_gxT_rpXdEeSroeU30tgKmw" name="Analyze Impact" content="Analyze Impact" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_AOkq5oaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_AOkq54aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_AOkq6IaUEeSMzJufh3GDGA" name="Validate project" outgoing="_AOksGIaUEeSMzJufh3GDGA" incoming="_AOkr_oaUEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_AOkq6YaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_AOkq6oaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_AOkq64aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_AOkq7IaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_AOkq7YaUEeSMzJufh3GDGA">
            <cardinality xmi:id="_gxSxhJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxSxhZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <BoundaryIntermediateEvents xsi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_HlPV0IaUEeSMzJufh3GDGA" documentation="&#x9;&#x9;&#x9;" name="NonInterruptingBoundaryTimerEvent" outgoing="_WwvPoIaUEeSMzJufh3GDGA">
            <condition xmi:id="_gxVN85XdEeSroeU30tgKmw" name="4 Jours 00:00:00" content="345600000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <loopCondition xmi:id="_AOkq8IaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_AOkq8YaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:id="_AOkq8oaUEeSMzJufh3GDGA" name="ValidateProject">
            <widgets xsi:type="form:CheckBoxSingleFormField" xmi:id="_AOkq84aUEeSMzJufh3GDGA" name="projectOK1">
              <widgetLayoutInfo xmi:id="_AOkq9IaUEeSMzJufh3GDGA" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gxT_y5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gxT_zJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gxT_zZXdEeSroeU30tgKmw" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xsi:type="process:Data" xmi:id="_gxT_zpXdEeSroeU30tgKmw" name="projectOK" dataType="_AOlRiYaUEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gxT_z5XdEeSroeU30tgKmw" name="" content=""/>
              <action xmi:id="_AOkq-4aUEeSMzJufh3GDGA">
                <leftOperand xmi:id="_gxUmvJXdEeSroeU30tgKmw" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="process:Data" xmi:id="_gxUmvZXdEeSroeU30tgKmw" name="projectOK" dataType="_AOlRiYaUEeSMzJufh3GDGA"/>
                </leftOperand>
                <operator xmi:id="_AOkq_4aUEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:id="_gxUmvpXdEeSroeU30tgKmw" name="field_projectOK1" content="field_projectOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xsi:type="form:CheckBoxSingleFormField" xmi:id="_gxUmv5XdEeSroeU30tgKmw" name="projectOK1"/>
                </rightOperand>
              </action>
              <tooltip xmi:id="_gxT_0JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gxT_0ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:id="_gxT_0pXdEeSroeU30tgKmw" name="Approve project?" content="Approve project?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gxT_05XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:id="_gxUmsJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:id="_gxUmsZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:id="_gxUmspXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:id="_gxUms5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:id="_gxUmtJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:id="_gxUmtZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:id="_gxUmtpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:SubmitFormButton" xmi:id="_AOkrI4aUEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:id="_gxUmx5XdEeSroeU30tgKmw" line="3"/>
              <displayLabel xmi:id="_gxUmyJXdEeSroeU30tgKmw" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gxUmyZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_AOkrJ4aUEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:id="_AOkrKIaUEeSMzJufh3GDGA" key="input_css:color" value="purple"/>
              <htmlAttributes xmi:id="_AOkrKYaUEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <htmlAttributes xmi:id="_AOkrKoaUEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <widgetLayoutInfo xmi:id="_gxUm5JXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gxUm5ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gxUm5pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gxUm55XdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_gxUm6JXdEeSroeU30tgKmw" name="proposal" dataType="_AOlRjoaUEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gxUm6ZXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_gxUm6pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gxUm65XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gxUm7JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xsi:type="form:MessageInfo" xmi:id="_AOkrNYaUEeSMzJufh3GDGA" name="impacts1">
              <htmlAttributes xmi:id="_AOkrNoaUEeSMzJufh3GDGA" key="input_css:color" value="red"/>
              <htmlAttributes xmi:id="_AOkrN4aUEeSMzJufh3GDGA" key="input_css:font-size" value="18px"/>
              <widgetLayoutInfo xmi:id="_gxUm75XdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gxUm8JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:id="_gxUm8ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:id="_gxUm8pXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xsi:type="process:Data" xmi:id="_gxUm85XdEeSroeU30tgKmw" name="impacts" dataType="_AOlRjoaUEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:id="_gxUm9JXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:id="_gxUm9ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:id="_gxUm9pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:id="_gxUm95XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:id="_gxT_s5XdEeSroeU30tgKmw" name="Validate project" content="Validate project" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:id="_AOkrQ4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_AOkrRIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_AOkrRYaUEeSMzJufh3GDGA" name="Proposal refused" incoming="_AOksB4aUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxVN9JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxVN9ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxVN9pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxVN95XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_AOkrSoaUEeSMzJufh3GDGA" name="Project finished" incoming="_AOksI4aUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxVN-JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxVN-ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxVN-pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxVN-5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_AOkrT4aUEeSMzJufh3GDGA" name="Project refused" incoming="_AOksCoaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxVN_JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxVN_ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxVN_pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxVN_5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:XORGateway" xmi:id="_AOkrVIaUEeSMzJufh3GDGA" name="Project approval?" outgoing="_AOksG4aUEeSMzJufh3GDGA _AOksIIaUEeSMzJufh3GDGA" incoming="_AOksGIaUEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:id="_gxVOBJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxVOBZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxVOBpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxVOB5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:XORGateway" xmi:id="_AOkrWYaUEeSMzJufh3GDGA" name="5 days?" outgoing="_AOksEIaUEeSMzJufh3GDGA _AOksFYaUEeSMzJufh3GDGA" incoming="_AOksDYaUEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:id="_gxVOCJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxVOCZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxVOCpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxVOC5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_AOkrXoaUEeSMzJufh3GDGA" name="Notify proposal aproved" outgoing="_AOkr-4aUEeSMzJufh3GDGA" incoming="_AOksEIaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxVODJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxVODZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxVODpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxVOD5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gxVOEJXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gxVOEZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxVOEpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gxVOE5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gxVOFJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_AOkraIaUEeSMzJufh3GDGA" name="Notify proposal refusal" outgoing="_AOksB4aUEeSMzJufh3GDGA" incoming="_AOksFYaUEeSMzJufh3GDGA _AOksJoaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxV00JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxV00ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxV00pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxV005XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gxV01JXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gxV01ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxV01pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gxV015XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gxV02JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_AOkrcoaUEeSMzJufh3GDGA" name="Notify project refused" outgoing="_AOksCoaUEeSMzJufh3GDGA" incoming="_AOksIIaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxV02ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxV02pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxV025XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxV03JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gxV03ZXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gxV03pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxV035XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gxV04JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gxV04ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_AOkrfIaUEeSMzJufh3GDGA" name="Notify project accepted" outgoing="_AOksAYaUEeSMzJufh3GDGA" incoming="_AOksG4aUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxV04pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxV045XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxV05JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxV05ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gxV05pXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gxV055XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxV06JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gxV06ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gxV06pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_AOkrhoaUEeSMzJufh3GDGA" name="Notify project delivery" outgoing="_AOksI4aUEeSMzJufh3GDGA" incoming="_AOksBIaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxV065XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxV07JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxV07ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxV07pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gxV075XdEeSroeU30tgKmw">
            <cardinality xmi:id="_gxV08JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxV08ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gxV08pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gxV085XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:CallActivity" xmi:id="_AOkrkIaUEeSMzJufh3GDGA" name="Do project" outgoing="_AOksBIaUEeSMzJufh3GDGA" incoming="_AOksAYaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxV0_pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxV0_5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxV1AJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxV1AZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_gxV1ApXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gxV1A5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxV1BJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gxV1BZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gxV1BpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <inputMappings xmi:id="_AOkrmoaUEeSMzJufh3GDGA" processSource="_AOkrq4aUEeSMzJufh3GDGA" subprocessTarget="sub_proposal"/>
          <inputMappings xmi:id="_AOkrm4aUEeSMzJufh3GDGA" processSource="_AOkrrYaUEeSMzJufh3GDGA" subprocessTarget="sub_proposalOK"/>
          <inputMappings xmi:id="_AOkrnIaUEeSMzJufh3GDGA" processSource="_AOkrr4aUEeSMzJufh3GDGA" subprocessTarget="sub_projectOK"/>
          <inputMappings xmi:id="_AOkrnYaUEeSMzJufh3GDGA" processSource="_AOkrsYaUEeSMzJufh3GDGA" subprocessTarget="sub_impacts"/>
          <outputMappings xmi:id="_AOkrnoaUEeSMzJufh3GDGA" subprocessSource="sub_proposal" processTarget="_AOkrq4aUEeSMzJufh3GDGA"/>
          <outputMappings xmi:id="_AOkrn4aUEeSMzJufh3GDGA" subprocessSource="sub_proposalOK" processTarget="_AOkrrYaUEeSMzJufh3GDGA"/>
          <outputMappings xmi:id="_AOkroIaUEeSMzJufh3GDGA" subprocessSource="sub_projectOK" processTarget="_AOkrr4aUEeSMzJufh3GDGA"/>
          <outputMappings xmi:id="_AOkroYaUEeSMzJufh3GDGA" subprocessSource="sub_impacts" processTarget="_AOkrsYaUEeSMzJufh3GDGA"/>
          <calledActivityName xmi:id="_gxV1D5XdEeSroeU30tgKmw" name="Do_project_CORTES_MARTINEZ" content="Do_project_CORTES_MARTINEZ" returnTypeFixed="true"/>
          <calledActivityVersion xmi:id="_gxV1EJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:ServiceTask" xmi:id="_Wwn64IaUEeSMzJufh3GDGA" name="Notify Delay" outgoing="_l1tDoIaUEeSMzJufh3GDGA" incoming="_WwvPoIaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxV09JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxV09ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxV09pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxV095XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:id="_53x_8IaWEeSMzJufh3GDGA" name="Connecteur Mail - Delay" definitionId="email" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.0.0">
            <configuration xmi:id="_53x_8YaWEeSMzJufh3GDGA" definitionId="email" version="1.0.0">
              <parameters xmi:id="_53x_8oaWEeSMzJufh3GDGA" key="smtpHost">
                <expression xsi:type="expression:Expression" xmi:id="_gxV1I5XdEeSroeU30tgKmw" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53x_9IaWEeSMzJufh3GDGA" key="smtpPort">
                <expression xsi:type="expression:Expression" xmi:id="_gxV1JJXdEeSroeU30tgKmw" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53x_9oaWEeSMzJufh3GDGA" key="sslSupport">
                <expression xsi:type="expression:Expression" xmi:id="_gxV1JZXdEeSroeU30tgKmw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53x_-IaWEeSMzJufh3GDGA" key="starttlsSupport">
                <expression xsi:type="expression:Expression" xmi:id="_gxV1JpXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53x_-oaWEeSMzJufh3GDGA" key="userName">
                <expression xsi:type="expression:Expression" xmi:id="_gxV1J5XdEeSroeU30tgKmw" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53x__IaWEeSMzJufh3GDGA" key="password">
                <expression xsi:type="expression:Expression" xmi:id="_gxV1KJXdEeSroeU30tgKmw" name="nbvcxwmlkj" content="nbvcxwmlkj" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53x__oaWEeSMzJufh3GDGA" key="from">
                <expression xsi:type="expression:Expression" xmi:id="_gxV1KZXdEeSroeU30tgKmw" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53yAAIaWEeSMzJufh3GDGA" key="to">
                <expression xsi:type="expression:Expression" xmi:id="_gxV1KpXdEeSroeU30tgKmw" name="sacortesh@gmail.com" content="sacortesh@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53yAAoaWEeSMzJufh3GDGA" key="bcc">
                <expression xsi:type="expression:Expression" xmi:id="_gxV1K5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53yABIaWEeSMzJufh3GDGA" key="cc">
                <expression xsi:type="expression:Expression" xmi:id="_gxV1LJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53yABoaWEeSMzJufh3GDGA" key="subject">
                <expression xsi:type="expression:Expression" xmi:id="_gxWb4JXdEeSroeU30tgKmw" name="Test" content="Test" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53yACIaWEeSMzJufh3GDGA" key="html">
                <expression xsi:type="expression:Expression" xmi:id="_gxWb4ZXdEeSroeU30tgKmw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53yACoaWEeSMzJufh3GDGA" key="message">
                <expression xsi:type="expression:Expression" xmi:id="_gxWb4pXdEeSroeU30tgKmw" name="&lt;pattern-expression>" content="${impacts}&#xA;${proposal}&#xA;Gracias" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xsi:type="process:Data" xmi:id="_gxWb45XdEeSroeU30tgKmw" name="impacts" dataType="_AOlRjoaUEeSMzJufh3GDGA"/>
                  <referencedElements xsi:type="process:Data" xmi:id="_gxWb5JXdEeSroeU30tgKmw" name="proposal" dataType="_AOlRjoaUEeSMzJufh3GDGA"/>
                </expression>
              </parameters>
              <parameters xmi:id="_53yAEIaWEeSMzJufh3GDGA" key="headers">
                <expression xsi:type="expression:TableExpression" xmi:id="_53yAEYaWEeSMzJufh3GDGA"/>
              </parameters>
              <parameters xmi:id="_53yAEoaWEeSMzJufh3GDGA" key="charset">
                <expression xsi:type="expression:Expression" xmi:id="_gxWb5pXdEeSroeU30tgKmw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53yAFIaWEeSMzJufh3GDGA" key="replyTo">
                <expression xsi:type="expression:Expression" xmi:id="_gxWb55XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:id="_53yAFoaWEeSMzJufh3GDGA" key="attachments">
                <expression xsi:type="expression:ListExpression" xmi:id="_53yAF4aWEeSMzJufh3GDGA"/>
              </parameters>
            </configuration>
          </connectors>
          <multiInstantiation xmi:id="_gxV0-ZXdEeSroeU30tgKmw">
            <cardinality xmi:id="_gxV0-pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxV0-5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_gxV0_JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_gxV0_ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndEvent" xmi:id="_l1m9AIaUEeSMzJufh3GDGA" name="Notification Done" incoming="_l1tDoIaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxWb6ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxWb6pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxWb65XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxWb7JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:id="_ASBm4IaUEeSMzJufh3GDGA" path="_AOkqQYaUEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:id="_AOkrpYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_AOkrpoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_AOkrp4aUEeSMzJufh3GDGA" path="_AOkqQYaUEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:id="_AOkrqIaUEeSMzJufh3GDGA" path="_AOkqQYaUEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:id="_AOkrqYaUEeSMzJufh3GDGA" path="_AOkqQYaUEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:id="_AOkrqoaUEeSMzJufh3GDGA" path="_AOkqQYaUEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:id="_AOkrq4aUEeSMzJufh3GDGA" name="proposal" dataType="_AOlRjoaUEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gxTYkZXdEeSroeU30tgKmw" content=""/>
      </data>
      <data xmi:id="_AOkrrYaUEeSMzJufh3GDGA" name="proposalOK" dataType="_AOlRiYaUEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gxT_oJXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_AOkrr4aUEeSMzJufh3GDGA" name="projectOK" dataType="_AOlRiYaUEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gxT_oZXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_AOkrsYaUEeSMzJufh3GDGA" name="impacts" dataType="_AOlRjoaUEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gxT_opXdEeSroeU30tgKmw" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <form xmi:id="_AOkrs4aUEeSMzJufh3GDGA" name="Project_Validation_CORTES_MARTINEZ" nLine="3">
        <widgets xsi:type="form:TextFormField" xmi:id="_AOkrtIaUEeSMzJufh3GDGA" name="proposal1">
          <widgetLayoutInfo xmi:id="_gxVN3ZXdEeSroeU30tgKmw" line="1"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gxVN3pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:id="_gxVN35XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:id="_gxVN4JXdEeSroeU30tgKmw" name="" content=""/>
          <afterEventExpression xmi:id="_gxVN4ZXdEeSroeU30tgKmw" name="" content=""/>
          <action xmi:id="_gxVN5pXdEeSroeU30tgKmw">
            <leftOperand xmi:id="_gxVN55XdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
              <referencedElements xsi:type="process:Data" xmi:id="_gxVN6JXdEeSroeU30tgKmw" name="proposal" dataType="_AOlRjoaUEeSMzJufh3GDGA"/>
            </leftOperand>
            <operator xmi:id="_gxVN65XdEeSroeU30tgKmw" type="ASSIGNMENT"/>
            <rightOperand xmi:id="_gxVN6ZXdEeSroeU30tgKmw" name="field_proposal1" content="field_proposal1" type="TYPE_INPUT">
              <referencedElements xsi:type="form:TextFormField" xmi:id="_gxVN6pXdEeSroeU30tgKmw" name="proposal1"/>
            </rightOperand>
          </action>
          <tooltip xmi:id="_gxVN4pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:id="_gxVN45XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:id="_gxVN5JXdEeSroeU30tgKmw" name="Proposal" content="Proposal" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_gxVN5ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <maxNumberOfDuplication xmi:id="_gxVN7JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:id="_gxVN7ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <displayLabelForAdd xmi:id="_gxVN7pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <tooltipForAdd xmi:id="_gxVN75XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabelForRemove xmi:id="_gxVN8JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <tooltipForRemove xmi:id="_gxVN8ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <exampleMessage xmi:id="_gxVN8pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </widgets>
        <widgets xsi:type="form:SubmitFormButton" xmi:id="_AOkr4IaUEeSMzJufh3GDGA" name="Soumettre1">
          <widgetLayoutInfo xmi:id="_gxUmypXdEeSroeU30tgKmw" line="2"/>
          <displayLabel xmi:id="_gxUmy5XdEeSroeU30tgKmw" name="OK" content="OK" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_gxUmzJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <widgets xsi:type="form:MessageInfo" xmi:id="_AOkr5IaUEeSMzJufh3GDGA" name="Enter proposal:">
          <htmlAttributes xmi:id="_AOkr5YaUEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
          <widgetLayoutInfo xmi:id="_gxUm-ZXdEeSroeU30tgKmw"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:id="_gxUm-pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:id="_gxUm-5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:id="_gxUm_JXdEeSroeU30tgKmw" name="" content=""/>
          <afterEventExpression xmi:id="_gxUm_ZXdEeSroeU30tgKmw" name="" content=""/>
          <action xmi:id="_gxUnApXdEeSroeU30tgKmw">
            <leftOperand xmi:id="_gxUnA5XdEeSroeU30tgKmw"/>
            <operator xmi:id="_gxUnBZXdEeSroeU30tgKmw" type="ASSIGNMENT" expression="="/>
            <rightOperand xmi:id="_gxUnBJXdEeSroeU30tgKmw"/>
          </action>
          <tooltip xmi:id="_gxUm_pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:id="_gxUm_5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:id="_gxUnAJXdEeSroeU30tgKmw" name="Message1" content="Message1" returnTypeFixed="true"/>
          <injectWidgetScript xmi:id="_gxUnAZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:id="_gxT_t5XdEeSroeU30tgKmw" name="Propose proposal" content="Propose proposal" returnTypeFixed="true"/>
      </form>
      <entryRedirectionURL xmi:id="_AOkr9IaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_AOkr9YaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_AOkr9oaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_AOkr94aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOkr-IaUEeSMzJufh3GDGA" source="_AOkqlIaUEeSMzJufh3GDGA" target="_AOkqQ4aUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOkr-YaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWb7pXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOkr-4aUEeSMzJufh3GDGA" source="_AOkrXoaUEeSMzJufh3GDGA" target="_AOkqmYaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOkr_IaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWb8JXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOkr_oaUEeSMzJufh3GDGA" source="_AOkqmYaUEeSMzJufh3GDGA" target="_AOkq6IaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOkr_4aUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWb8pXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksAYaUEeSMzJufh3GDGA" source="_AOkrfIaUEeSMzJufh3GDGA" target="_AOkrkIaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOksAoaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWb9JXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksBIaUEeSMzJufh3GDGA" source="_AOkrkIaUEeSMzJufh3GDGA" target="_AOkrhoaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOksBYaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWb9pXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksB4aUEeSMzJufh3GDGA" source="_AOkraIaUEeSMzJufh3GDGA" target="_AOkrRYaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOksCIaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWb-JXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksCoaUEeSMzJufh3GDGA" source="_AOkrcoaUEeSMzJufh3GDGA" target="_AOkrT4aUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOksC4aUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWb-pXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksDYaUEeSMzJufh3GDGA" source="_AOkqQ4aUEeSMzJufh3GDGA" target="_AOkrWYaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOksDoaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWb_JXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksEIaUEeSMzJufh3GDGA" name="Approved" source="_AOkrWYaUEeSMzJufh3GDGA" target="_AOkrXoaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOksEYaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWb_pXdEeSroeU30tgKmw" name="proposalOK==true" content="proposalOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xsi:type="process:Data" xmi:id="_gxWb_5XdEeSroeU30tgKmw" name="proposalOK" dataType="_AOlRiYaUEeSMzJufh3GDGA"/>
        </condition>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksFYaUEeSMzJufh3GDGA" name="Not Approved" source="_AOkrWYaUEeSMzJufh3GDGA" target="_AOkraIaUEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:id="_AOksFoaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcAZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksGIaUEeSMzJufh3GDGA" source="_AOkq6IaUEeSMzJufh3GDGA" target="_AOkrVIaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOksGYaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcA5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksG4aUEeSMzJufh3GDGA" name="Approved" source="_AOkrVIaUEeSMzJufh3GDGA" target="_AOkrfIaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOksHIaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcBZXdEeSroeU30tgKmw" name="projectOK==true" content="projectOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xsi:type="process:Data" xmi:id="_gxWcBpXdEeSroeU30tgKmw" name="projectOK" dataType="_AOlRiYaUEeSMzJufh3GDGA"/>
        </condition>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksIIaUEeSMzJufh3GDGA" name="Not approved" source="_AOkrVIaUEeSMzJufh3GDGA" target="_AOkrcoaUEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:id="_AOksIYaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcCJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksI4aUEeSMzJufh3GDGA" source="_AOkrhoaUEeSMzJufh3GDGA" target="_AOkrSoaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOksJIaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcCpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOksJoaUEeSMzJufh3GDGA" source="_AOkqS4aUEeSMzJufh3GDGA" target="_AOkraIaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOksJ4aUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcDJXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_WwvPoIaUEeSMzJufh3GDGA" source="_HlPV0IaUEeSMzJufh3GDGA" target="_Wwn64IaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_WwvPoYaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcDpXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_l1tDoIaUEeSMzJufh3GDGA" source="_Wwn64IaUEeSMzJufh3GDGA" target="_l1m9AIaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_l1tDoYaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcEJXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:id="_AOksKYaUEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:id="_AOksKoaUEeSMzJufh3GDGA">
        <name xmi:id="_gxWcG5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gxWcHJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_AOksLYaUEeSMzJufh3GDGA">
        <name xmi:id="_gxWcHZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gxWcHpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_AOksMIaUEeSMzJufh3GDGA">
        <name xmi:id="_gxWcH5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gxWcIJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_AOksM4aUEeSMzJufh3GDGA">
        <name xmi:id="_gxWcIZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gxWcIpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_AOksNoaUEeSMzJufh3GDGA">
        <name xmi:id="_gxWcI5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gxWcJJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xsi:type="process:Pool" xmi:id="_AOksOYaUEeSMzJufh3GDGA" name="Do_project_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="3.0">
      <elements xsi:type="process:Lane" xmi:id="_AOksOoaUEeSMzJufh3GDGA" name="Research and Development" actor="_AOlReYaUEeSMzJufh3GDGA">
        <elements xsi:type="process:Task" xmi:id="_AOksO4aUEeSMzJufh3GDGA" name="Deploy" outgoing="_AOlRdoaUEeSMzJufh3GDGA" incoming="_AOlRc4aUEeSMzJufh3GDGA" actor="_AOlReYaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_AOksPIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_AOksPYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_AOksPoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_AOksP4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_AOksQIaUEeSMzJufh3GDGA">
            <cardinality xmi:id="_gxSxhpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxSxh5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_AOksQ4aUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_AOksRIaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_AOksRYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_AOksRoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:StartEvent" xmi:id="_AOksR4aUEeSMzJufh3GDGA" name="Start project" outgoing="_AOlRaoaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxVNwpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxVNw5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxVNxJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxVNxZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_AOksTIaUEeSMzJufh3GDGA" name="Project finished" incoming="_AOlRdoaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_gxVOAJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_gxVOAZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_gxVOApXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_gxVOA5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_AOksUYaUEeSMzJufh3GDGA" name="Specify" outgoing="_AOlRbYaUEeSMzJufh3GDGA" incoming="_AOlRaoaUEeSMzJufh3GDGA" actor="_AOlReYaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_AOksUoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_AOksU4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_AOksVIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_AOksVYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_AOksVoaUEeSMzJufh3GDGA">
            <cardinality xmi:id="_gxSxiJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxSxiZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_AOksWYaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_AOksWoaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_AOksW4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_AOksXIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_AOksXYaUEeSMzJufh3GDGA" name="Implement" outgoing="_AOlRcIaUEeSMzJufh3GDGA" incoming="_AOlRbYaUEeSMzJufh3GDGA" actor="_AOlReYaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_AOksXoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_AOksX4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_AOksYIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_AOksYYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_AOksYoaUEeSMzJufh3GDGA">
            <cardinality xmi:id="_gxSxipXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxSxi5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_AOksZYaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_AOksZoaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_AOksZ4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_AOksaIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_AOksaYaUEeSMzJufh3GDGA" name="Test" outgoing="_AOlRc4aUEeSMzJufh3GDGA" incoming="_AOlRcIaUEeSMzJufh3GDGA" actor="_AOlReYaUEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_AOksaoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_AOksa4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_AOksbIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_AOksbYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_AOlRUIaUEeSMzJufh3GDGA">
            <cardinality xmi:id="_gxSxjJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_gxSxjZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_AOlRU4aUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_AOlRVIaUEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_AOlRVYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_AOlRVoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:id="_AVyFgIaUEeSMzJufh3GDGA" path="_AOksOYaUEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:id="_AOlRWIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_AOlRWYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_AOlRWoaUEeSMzJufh3GDGA" path="_AOksOYaUEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:id="_AOlRW4aUEeSMzJufh3GDGA" path="_AOksOYaUEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:id="_AOlRXIaUEeSMzJufh3GDGA" path="_AOksOYaUEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:id="_AOlRXYaUEeSMzJufh3GDGA" path="_AOksOYaUEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:id="_AOlRXoaUEeSMzJufh3GDGA" name="sub_proposal" dataType="_AOlRjoaUEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gxT_o5XdEeSroeU30tgKmw" content=""/>
      </data>
      <data xmi:id="_AOlRYIaUEeSMzJufh3GDGA" name="sub_proposalOK" dataType="_AOlRiYaUEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gxT_pJXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_AOlRYoaUEeSMzJufh3GDGA" name="sub_projectOK" dataType="_AOlRiYaUEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gxT_pZXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:id="_AOlRZIaUEeSMzJufh3GDGA" name="sub_impacts" dataType="_AOlRjoaUEeSMzJufh3GDGA">
        <defaultValue xmi:id="_gxT_ppXdEeSroeU30tgKmw" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <entryRedirectionURL xmi:id="_AOlRZoaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_AOlRZ4aUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_AOlRaIaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_AOlRaYaUEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOlRaoaUEeSMzJufh3GDGA" source="_AOksR4aUEeSMzJufh3GDGA" target="_AOksUYaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOlRa4aUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcEpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOlRbYaUEeSMzJufh3GDGA" source="_AOksUYaUEeSMzJufh3GDGA" target="_AOksXYaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOlRboaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcFJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOlRcIaUEeSMzJufh3GDGA" source="_AOksXYaUEeSMzJufh3GDGA" target="_AOksaYaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOlRcYaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcFpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOlRc4aUEeSMzJufh3GDGA" source="_AOksaYaUEeSMzJufh3GDGA" target="_AOksO4aUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOlRdIaUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcGJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_AOlRdoaUEeSMzJufh3GDGA" source="_AOksO4aUEeSMzJufh3GDGA" target="_AOksTIaUEeSMzJufh3GDGA">
        <decisionTable xmi:id="_AOlRd4aUEeSMzJufh3GDGA"/>
        <condition xmi:id="_gxWcGpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:id="_AOlReYaUEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:id="_AOlReoaUEeSMzJufh3GDGA">
        <name xmi:id="_gxWcJZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gxWcJpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_AOlRfYaUEeSMzJufh3GDGA">
        <name xmi:id="_gxWcJ5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gxWcKJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_AOlRgIaUEeSMzJufh3GDGA">
        <name xmi:id="_gxWcKZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gxWcKpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_AOlRg4aUEeSMzJufh3GDGA">
        <name xmi:id="_gxXC8JXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gxXC8ZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_AOlRhoaUEeSMzJufh3GDGA">
        <name xmi:id="_gxXC8pXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_gxXC85XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xsi:type="process:BooleanType" xmi:id="_AOlRiYaUEeSMzJufh3GDGA" name="Boolean"/>
    <datatypes xsi:type="process:DateType" xmi:id="_AOlRioaUEeSMzJufh3GDGA" name="Date"/>
    <datatypes xsi:type="process:IntegerType" xmi:id="_AOlRi4aUEeSMzJufh3GDGA" name="Integer"/>
    <datatypes xsi:type="process:LongType" xmi:id="_AOlRjIaUEeSMzJufh3GDGA" name="Long"/>
    <datatypes xsi:type="process:DoubleType" xmi:id="_AOlRjYaUEeSMzJufh3GDGA" name="Double"/>
    <datatypes xsi:type="process:StringType" xmi:id="_AOlRjoaUEeSMzJufh3GDGA" name="Text"/>
    <datatypes xsi:type="process:JavaType" xmi:id="_AOlRj4aUEeSMzJufh3GDGA" name="Java_object"/>
    <datatypes xsi:type="process:XMLType" xmi:id="_AOlRkIaUEeSMzJufh3GDGA" name="XML"/>
    <datatypes xsi:type="process:BusinessObjectType" xmi:id="_gxPHKZXdEeSroeU30tgKmw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_AOlRkYaUEeSMzJufh3GDGA" type="Process" element="_AOkqQIaUEeSMzJufh3GDGA" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:id="_AOlRkoaUEeSMzJufh3GDGA" type="2007" element="_AOkqQYaUEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_AOlRk4aUEeSMzJufh3GDGA" type="5008" element="_AOkqQYaUEeSMzJufh3GDGA"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_AOlRlIaUEeSMzJufh3GDGA" type="7001" element="_AOkqQYaUEeSMzJufh3GDGA">
        <children xmi:id="_gxXqK5XdEeSroeU30tgKmw" type="3007" element="_AOkqQoaUEeSMzJufh3GDGA">
          <children xsi:type="notation:DecorationNode" xmi:id="_AOlRloaUEeSMzJufh3GDGA" type="5007" element="_AOkqQoaUEeSMzJufh3GDGA"/>
          <children xsi:type="notation:DecorationNode" xmi:id="_AOlRl4aUEeSMzJufh3GDGA" type="7002" element="_AOkqQoaUEeSMzJufh3GDGA">
            <children xsi:type="notation:Shape" xmi:id="_AOlRmIaUEeSMzJufh3GDGA" type="3005" element="_AOkqQ4aUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxYRHpXdEeSroeU30tgKmw" type="5005" element="_AOkqQ4aUEeSMzJufh3GDGA"/>
              <children xsi:type="notation:Shape" xmi:id="_AOlRmoaUEeSMzJufh3GDGA" type="3043" element="_AOkqS4aUEeSMzJufh3GDGA" fontName="Sans">
                <children xsi:type="notation:DecorationNode" xmi:id="_gxYRIZXdEeSroeU30tgKmw" type="5055" element="_AOkqS4aUEeSMzJufh3GDGA">
                  <layoutConstraint xsi:type="notation:Location" xmi:id="_AOlRnIaUEeSMzJufh3GDGA" y="5"/>
                </children>
                <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRnYaUEeSMzJufh3GDGA"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRnoaUEeSMzJufh3GDGA" x="119" y="165"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRn4aUEeSMzJufh3GDGA" type="3002" element="_AOkqlIaUEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxYRJJXdEeSroeU30tgKmw" type="5024" element="_AOkqlIaUEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_AOlRoYaUEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRooaUEeSMzJufh3GDGA" x="40" y="179"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRo4aUEeSMzJufh3GDGA" type="3005" element="_AOkqmYaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxYRJ5XdEeSroeU30tgKmw" type="5005" element="_AOkqmYaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRpYaUEeSMzJufh3GDGA" x="421" y="102"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRpoaUEeSMzJufh3GDGA" type="3005" element="_AOkq6IaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxYRKZXdEeSroeU30tgKmw" type="5005" element="_AOkq6IaUEeSMzJufh3GDGA"/>
              <children xsi:type="notation:Shape" xmi:id="_HlSZIIaUEeSMzJufh3GDGA" type="3064" element="_HlPV0IaUEeSMzJufh3GDGA" fontName="Sans">
                <children xsi:type="notation:DecorationNode" xmi:id="_gxYRLJXdEeSroeU30tgKmw" type="5094" element="_HlPV0IaUEeSMzJufh3GDGA">
                  <layoutConstraint xsi:type="notation:Location" xmi:id="_HlTAMIaUEeSMzJufh3GDGA" y="5"/>
                </children>
                <layoutConstraint xsi:type="notation:Bounds" xmi:id="_HlSZIYaUEeSMzJufh3GDGA"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRqIaUEeSMzJufh3GDGA" x="556" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRqYaUEeSMzJufh3GDGA" type="3062" element="_AOkrRYaUEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxYRL5XdEeSroeU30tgKmw" type="5090" element="_AOkrRYaUEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_AOlRq4aUEeSMzJufh3GDGA" x="-1" y="18"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRrIaUEeSMzJufh3GDGA" x="508" y="227"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRrYaUEeSMzJufh3GDGA" type="3062" element="_AOkrSoaUEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxYRMpXdEeSroeU30tgKmw" type="5090" element="_AOkrSoaUEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_AOlRr4aUEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRsIaUEeSMzJufh3GDGA" x="1221" y="136"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRsYaUEeSMzJufh3GDGA" type="3062" element="_AOkrT4aUEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxY4IJXdEeSroeU30tgKmw" type="5090" element="_AOkrT4aUEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_AOlRs4aUEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRtIaUEeSMzJufh3GDGA" x="1012" y="226"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRtYaUEeSMzJufh3GDGA" type="3008" element="_AOkrVIaUEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxY4I5XdEeSroeU30tgKmw" type="5026" element="_AOkrVIaUEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_AOlRt4aUEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRuIaUEeSMzJufh3GDGA" x="689" y="105" width="43" height="43"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRuYaUEeSMzJufh3GDGA" type="3008" element="_AOkrWYaUEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxY4JpXdEeSroeU30tgKmw" type="5026" element="_AOkrWYaUEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_AOlRu4aUEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRvIaUEeSMzJufh3GDGA" x="230" y="170" width="43" height="43"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRvYaUEeSMzJufh3GDGA" type="3027" element="_AOkrXoaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxY4KZXdEeSroeU30tgKmw" type="5017" element="_AOkrXoaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRv4aUEeSMzJufh3GDGA" x="271" y="95" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRwIaUEeSMzJufh3GDGA" type="3027" element="_AOkraIaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfMJXdEeSroeU30tgKmw" type="5017" element="_AOkraIaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRwoaUEeSMzJufh3GDGA" x="347" y="187" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRw4aUEeSMzJufh3GDGA" type="3027" element="_AOkrcoaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfMpXdEeSroeU30tgKmw" type="5017" element="_AOkrcoaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRxYaUEeSMzJufh3GDGA" x="765" y="192" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRxoaUEeSMzJufh3GDGA" type="3027" element="_AOkrfIaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfNJXdEeSroeU30tgKmw" type="5017" element="_AOkrfIaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRyIaUEeSMzJufh3GDGA" x="762" y="96" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRyYaUEeSMzJufh3GDGA" type="3027" element="_AOkrhoaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfNpXdEeSroeU30tgKmw" type="5017" element="_AOkrhoaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRy4aUEeSMzJufh3GDGA" x="1041" y="90" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlRzIaUEeSMzJufh3GDGA" type="3063" element="_AOkrkIaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfOJXdEeSroeU30tgKmw" type="5093" element="_AOkrkIaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlRzoaUEeSMzJufh3GDGA" x="913" y="125"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_WwpwEIaUEeSMzJufh3GDGA" type="3027" element="_Wwn64IaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfOpXdEeSroeU30tgKmw" type="5017" element="_Wwn64IaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_WwpwEYaUEeSMzJufh3GDGA" x="590" y="192"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_l1oLIIaUEeSMzJufh3GDGA" type="3003" element="_l1m9AIaUEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfPJXdEeSroeU30tgKmw" type="5025" element="_l1m9AIaUEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_l1oyMYaUEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_l1oLIYaUEeSMzJufh3GDGA" x="714" y="227"/>
            </children>
          </children>
          <styles xsi:type="notation:DescriptionStyle" xmi:id="_AOlRz4aUEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FontStyle" xmi:id="_AOlR0IaUEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xsi:type="notation:LineStyle" xmi:id="_AOlR0YaUEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FillStyle" xmi:id="_AOlR0oaUEeSMzJufh3GDGA"/>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlR04aUEeSMzJufh3GDGA" x="45" y="10" width="1372" height="302"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_AOlR1IaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_AOlR1YaUEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_AOlR1oaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_AOlR14aUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlR2IaUEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_AOlR2YaUEeSMzJufh3GDGA" type="2007" element="_AOksOYaUEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_AOlR2oaUEeSMzJufh3GDGA" type="5008" element="_AOksOYaUEeSMzJufh3GDGA"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_AOlR24aUEeSMzJufh3GDGA" type="7001" element="_AOksOYaUEeSMzJufh3GDGA">
        <children xmi:id="_gxYREJXdEeSroeU30tgKmw" type="3007" element="_AOksOoaUEeSMzJufh3GDGA">
          <children xsi:type="notation:DecorationNode" xmi:id="_AOlR3YaUEeSMzJufh3GDGA" type="5007" element="_AOksOoaUEeSMzJufh3GDGA"/>
          <children xsi:type="notation:DecorationNode" xmi:id="_AOlR3oaUEeSMzJufh3GDGA" type="7002" element="_AOksOoaUEeSMzJufh3GDGA">
            <children xsi:type="notation:Shape" xmi:id="_AOlR34aUEeSMzJufh3GDGA" type="3005" element="_AOksO4aUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfP5XdEeSroeU30tgKmw" type="5005" element="_AOksO4aUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlR4YaUEeSMzJufh3GDGA" x="597" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlR4oaUEeSMzJufh3GDGA" type="3002" element="_AOksR4aUEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfQZXdEeSroeU30tgKmw" type="5024" element="_AOksR4aUEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_AOlR5IaUEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlR5YaUEeSMzJufh3GDGA" x="84" y="110"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlR5oaUEeSMzJufh3GDGA" type="3062" element="_AOksTIaUEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfRJXdEeSroeU30tgKmw" type="5090" element="_AOksTIaUEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_AOlR6IaUEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlR6YaUEeSMzJufh3GDGA" x="753" y="110"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlR6oaUEeSMzJufh3GDGA" type="3005" element="_AOksUYaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfR5XdEeSroeU30tgKmw" type="5005" element="_AOksUYaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlR7IaUEeSMzJufh3GDGA" x="160" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlR7YaUEeSMzJufh3GDGA" type="3005" element="_AOksXYaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfSZXdEeSroeU30tgKmw" type="5005" element="_AOksXYaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlR74aUEeSMzJufh3GDGA" x="294" y="91" width="134" height="67"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_AOlR8IaUEeSMzJufh3GDGA" type="3005" element="_AOksaYaUEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_gxZfS5XdEeSroeU30tgKmw" type="5005" element="_AOksaYaUEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlR8oaUEeSMzJufh3GDGA" x="464" y="100"/>
            </children>
          </children>
          <styles xsi:type="notation:DescriptionStyle" xmi:id="_AOlR84aUEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FontStyle" xmi:id="_AOlR9IaUEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xsi:type="notation:LineStyle" xmi:id="_AOlR9YaUEeSMzJufh3GDGA"/>
          <styles xsi:type="notation:FillStyle" xmi:id="_AOlR9oaUEeSMzJufh3GDGA"/>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlR94aUEeSMzJufh3GDGA" x="231" y="176"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_AOlR-IaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_AOlR-YaUEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_AOlR-oaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_AOlR-4aUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlR_IaUEeSMzJufh3GDGA" width="1454" height="250"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_AOlR_YaUEeSMzJufh3GDGA"/>
    <edges xsi:type="notation:Connector" xmi:id="_AOlR_oaUEeSMzJufh3GDGA" type="4001" element="_AOkr-IaUEeSMzJufh3GDGA" source="_AOlRn4aUEeSMzJufh3GDGA" target="_AOlRmIaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxaGQJXdEeSroeU30tgKmw" type="6001" element="_AOkr-IaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxaGQZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxaGQpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSAoaUEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSA4aUEeSMzJufh3GDGA" type="4001" element="_AOkr-4aUEeSMzJufh3GDGA" source="_AOlRvYaUEeSMzJufh3GDGA" target="_AOlRo4aUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxaGRJXdEeSroeU30tgKmw" type="6001" element="_AOkr-4aUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxaGRZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxatUJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSB4aUEeSMzJufh3GDGA" points="[0, 1, -66, -7]$[16, 1, -50, -7]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSCIaUEeSMzJufh3GDGA" id="(1.0,0.55)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSCYaUEeSMzJufh3GDGA" type="4001" element="_AOkr_oaUEeSMzJufh3GDGA" source="_AOlRo4aUEeSMzJufh3GDGA" target="_AOlRpoaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatU5XdEeSroeU30tgKmw" type="6001" element="_AOkr_oaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatVJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxatVZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSDYaUEeSMzJufh3GDGA" points="[0, 0, -41, 91]$[-9, -91, -50, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSDoaUEeSMzJufh3GDGA" id="(1.0,0.64)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSD4aUEeSMzJufh3GDGA" type="4001" element="_AOksAYaUEeSMzJufh3GDGA" source="_AOlRxoaUEeSMzJufh3GDGA" target="_AOlRzIaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatWJXdEeSroeU30tgKmw" type="6001" element="_AOksAYaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatWZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxatWpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSE4aUEeSMzJufh3GDGA" points="[0, 0, -5, -60]$[55, 51, 50, -9]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSFIaUEeSMzJufh3GDGA" id="(1.0,0.5)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSFYaUEeSMzJufh3GDGA" type="4001" element="_AOksBIaUEeSMzJufh3GDGA" source="_AOlRzIaUEeSMzJufh3GDGA" target="_AOlRyYaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatXZXdEeSroeU30tgKmw" type="6001" element="_AOksBIaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatXpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxatX5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSGYaUEeSMzJufh3GDGA" points="[0, 0, -60, 48]$[65, -35, 5, 13]"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSGoaUEeSMzJufh3GDGA" id="(0.5583333333333333,0.7833333333333333)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSG4aUEeSMzJufh3GDGA" type="4001" element="_AOksB4aUEeSMzJufh3GDGA" source="_AOlRwIaUEeSMzJufh3GDGA" target="_AOlRqYaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatYpXdEeSroeU30tgKmw" type="6001" element="_AOksB4aUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatY5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxatZJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSH4aUEeSMzJufh3GDGA" points="[0, -8, -85, 2]$[78, 3, -7, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSIIaUEeSMzJufh3GDGA" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSIYaUEeSMzJufh3GDGA" type="4001" element="_AOksCoaUEeSMzJufh3GDGA" source="_AOlRw4aUEeSMzJufh3GDGA" target="_AOlRsYaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatZ5XdEeSroeU30tgKmw" type="6001" element="_AOksCoaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxataJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxataZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSJYaUEeSMzJufh3GDGA" points="[0, 0, -142, -15]$[135, 28, -7, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSJoaUEeSMzJufh3GDGA" id="(1.0,0.5666666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSJ4aUEeSMzJufh3GDGA" type="4001" element="_AOksDYaUEeSMzJufh3GDGA" source="_AOlRmIaUEeSMzJufh3GDGA" target="_AOlRuYaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatbJXdEeSroeU30tgKmw" type="6001" element="_AOksDYaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatbZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxatbpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSK4aUEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSLIaUEeSMzJufh3GDGA" type="4001" element="_AOksEIaUEeSMzJufh3GDGA" source="_AOlRuYaUEeSMzJufh3GDGA" target="_AOlRvYaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatcJXdEeSroeU30tgKmw" type="6001" element="_AOksEIaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatcZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxatcpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSMIaUEeSMzJufh3GDGA" points="[-11, -22, -51, 47]$[42, -57, 2, 12]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSMYaUEeSMzJufh3GDGA" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSMoaUEeSMzJufh3GDGA" id="(0.5333333333333333,0.8)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSM4aUEeSMzJufh3GDGA" type="4001" element="_AOksFYaUEeSMzJufh3GDGA" source="_AOlRuYaUEeSMzJufh3GDGA" target="_AOlRwIaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatdpXdEeSroeU30tgKmw" type="6001" element="_AOksFYaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatd5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxateJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSN4aUEeSMzJufh3GDGA" points="[-14, 1, -91, 0]$[52, -2, -25, -3]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSOIaUEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSOYaUEeSMzJufh3GDGA" id="(0.20833333333333334,0.45)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSOoaUEeSMzJufh3GDGA" type="4001" element="_AOksGIaUEeSMzJufh3GDGA" source="_AOlRpoaUEeSMzJufh3GDGA" target="_AOlRtYaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatfJXdEeSroeU30tgKmw" type="6001" element="_AOksGIaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatfZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxatfpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSPoaUEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSP4aUEeSMzJufh3GDGA" id="(0.97,0.54)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSQIaUEeSMzJufh3GDGA" type="4001" element="_AOksG4aUEeSMzJufh3GDGA" source="_AOlRtYaUEeSMzJufh3GDGA" target="_AOlRxoaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatgZXdEeSroeU30tgKmw" type="6001" element="_AOksG4aUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatgpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxatg5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSRIaUEeSMzJufh3GDGA" points="[-11, -3, -65, 0]$[30, -1, -24, 2]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSRYaUEeSMzJufh3GDGA" id="(1.0,0.813953488372093)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSRoaUEeSMzJufh3GDGA" id="(0.025,0.18333333333333332)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSR4aUEeSMzJufh3GDGA" type="4001" element="_AOksIIaUEeSMzJufh3GDGA" source="_AOlRtYaUEeSMzJufh3GDGA" target="_AOlRw4aUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxath5XdEeSroeU30tgKmw" type="6001" element="_AOksIIaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatiJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxatiZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSS4aUEeSMzJufh3GDGA" points="[-4, -10, -40, -95]$[33, 84, -3, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSTIaUEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSTYaUEeSMzJufh3GDGA" id="(0.025,0.4166666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSToaUEeSMzJufh3GDGA" type="4001" element="_AOksI4aUEeSMzJufh3GDGA" source="_AOlRyYaUEeSMzJufh3GDGA" target="_AOlRrYaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxatjZXdEeSroeU30tgKmw" type="6001" element="_AOksI4aUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxatjpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxbUYJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSUoaUEeSMzJufh3GDGA" points="[0, 0, -75, -29]$[72, 14, -3, -15]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSU4aUEeSMzJufh3GDGA" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSVIaUEeSMzJufh3GDGA" type="4001" element="_AOlRaoaUEeSMzJufh3GDGA" source="_AOlR4oaUEeSMzJufh3GDGA" target="_AOlR6oaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxbUY5XdEeSroeU30tgKmw" type="6001" element="_AOlRaoaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxbUZJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxbUZZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSWIaUEeSMzJufh3GDGA" points="[-7, -2, -57, 0]$[46, -1, -4, 1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSWYaUEeSMzJufh3GDGA" id="(0.9666666666666667,0.5333333333333333)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSWoaUEeSMzJufh3GDGA" id="(0.05,0.5)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSW4aUEeSMzJufh3GDGA" type="4001" element="_AOlRbYaUEeSMzJufh3GDGA" source="_AOlR6oaUEeSMzJufh3GDGA" target="_AOlR7YaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxbUaZXdEeSroeU30tgKmw" type="6001" element="_AOlRbYaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxbUapXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxbUa5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSX4aUEeSMzJufh3GDGA" points="[0, -5, -35, 0]$[34, -6, -1, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSYIaUEeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSYYaUEeSMzJufh3GDGA" id="(0.007462686567164179,0.4925373134328358)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSYoaUEeSMzJufh3GDGA" type="4001" element="_AOlRcIaUEeSMzJufh3GDGA" source="_AOlR7YaUEeSMzJufh3GDGA" target="_AOlR8IaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxbUb5XdEeSroeU30tgKmw" type="6001" element="_AOlRcIaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxbUcJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxbUcZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSZoaUEeSMzJufh3GDGA" points="[0, 1, -36, 0]$[36, 1, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSZ4aUEeSMzJufh3GDGA" id="(1.0,0.4626865671641791)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSaIaUEeSMzJufh3GDGA" id="(0.0,0.46)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSaYaUEeSMzJufh3GDGA" type="4001" element="_AOlRc4aUEeSMzJufh3GDGA" source="_AOlR8IaUEeSMzJufh3GDGA" target="_AOlR34aUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxbUdZXdEeSroeU30tgKmw" type="6001" element="_AOlRc4aUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxbUdpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxbUd5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSbYaUEeSMzJufh3GDGA" points="[0, -6, -40, 0]$[33, -7, -7, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSboaUEeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSb4aUEeSMzJufh3GDGA" id="(0.07,0.46)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlScIaUEeSMzJufh3GDGA" type="4001" element="_AOlRdoaUEeSMzJufh3GDGA" source="_AOlR34aUEeSMzJufh3GDGA" target="_AOlR5oaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxbUe5XdEeSroeU30tgKmw" type="6001" element="_AOlRdoaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxbUfJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxbUfZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSdIaUEeSMzJufh3GDGA" points="[0, -3, -59, 0]$[56, -3, -3, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSdYaUEeSMzJufh3GDGA" id="(1.0,0.6)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSdoaUEeSMzJufh3GDGA" id="(0.1,0.5666666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_AOlSd4aUEeSMzJufh3GDGA" type="4001" element="_AOksJoaUEeSMzJufh3GDGA" source="_AOlRmoaUEeSMzJufh3GDGA" target="_AOlRwIaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxbUgZXdEeSroeU30tgKmw" type="6001" element="_AOksJoaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxbUgpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxbUg5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_AOlSe4aUEeSMzJufh3GDGA" points="[0, -1, -194, 0]$[187, 0, -7, 1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSfIaUEeSMzJufh3GDGA" id="(1.0,1.0)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_AOlSfYaUEeSMzJufh3GDGA" id="(0.058333333333333334,0.7333333333333333)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_WwxE0IaUEeSMzJufh3GDGA" type="4001" element="_WwvPoIaUEeSMzJufh3GDGA" source="_HlSZIIaUEeSMzJufh3GDGA" target="_WwpwEIaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxbUh5XdEeSroeU30tgKmw" type="6001" element="_WwvPoIaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxbUiJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxbUiZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_WwxE0oaUEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_l1tqsIaUEeSMzJufh3GDGA" type="4001" element="_l1tDoIaUEeSMzJufh3GDGA" source="_WwpwEIaUEeSMzJufh3GDGA" target="_l1oLIIaUEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxbUi5XdEeSroeU30tgKmw" type="6001" element="_l1tDoIaUEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_gxbUjJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_gxbUjZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_l1tqsoaUEeSMzJufh3GDGA" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_q8msAIaUEeSMzJufh3GDGA" id="(1.0,0.5)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_q8msAYaUEeSMzJufh3GDGA" id="(0.0,0.5)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AOlSfoaUEeSMzJufh3GDGA" type="Form" element="_AOkrs4aUEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_AOlSf4aUEeSMzJufh3GDGA" type="2120" element="_AOkrtIaUEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxZfTZXdEeSroeU30tgKmw" type="5157" element="_AOkrtIaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSgYaUEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_AOlSgoaUEeSMzJufh3GDGA" type="2126" element="_AOkr4IaUEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_AOlSg4aUEeSMzJufh3GDGA" type="5160" element="_AOkr4IaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_AOlShIaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_AOlShYaUEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_AOlShoaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSh4aUEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_AOlSiIaUEeSMzJufh3GDGA" type="2131" element="_AOkr5IaUEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxZfT5XdEeSroeU30tgKmw" type="5135" element="_AOkr5IaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSioaUEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_AOlSi4aUEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AOlSjIaUEeSMzJufh3GDGA" type="Form" element="_AOkqUYaUEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_AOlSjYaUEeSMzJufh3GDGA" type="2130" element="_AOkqUoaUEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxZfUZXdEeSroeU30tgKmw" type="5148" element="_AOkqUoaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSj4aUEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_AOlSkIaUEeSMzJufh3GDGA" type="2126" element="_AOkqgoaUEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_AOlSkYaUEeSMzJufh3GDGA" type="5160" element="_AOkqgoaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_AOlSkoaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_AOlSk4aUEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_AOlSlIaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSlYaUEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_AOlSloaUEeSMzJufh3GDGA" type="2131" element="_AOkqhoaUEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxZfU5XdEeSroeU30tgKmw" type="5135" element="_AOkqhoaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSmIaUEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_AOlSmYaUEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AOlSmoaUEeSMzJufh3GDGA" type="Form" element="_AOkqo4aUEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_AOlSm4aUEeSMzJufh3GDGA" type="2120" element="_AOkqpIaUEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxZfVZXdEeSroeU30tgKmw" type="5157" element="_AOkqpIaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSnYaUEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_AOlSnoaUEeSMzJufh3GDGA" type="2126" element="_AOkq1IaUEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_AOlSn4aUEeSMzJufh3GDGA" type="5160" element="_AOkq1IaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_AOlSoIaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_AOlSoYaUEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_AOlSooaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSo4aUEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_AOlSpIaUEeSMzJufh3GDGA" type="2131" element="_AOkq2IaUEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxZfV5XdEeSroeU30tgKmw" type="5135" element="_AOkq2IaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSpoaUEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_AOlSp4aUEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AOlSqIaUEeSMzJufh3GDGA" type="Form" element="_AOkq8oaUEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xsi:type="notation:Shape" xmi:id="_AOlSqYaUEeSMzJufh3GDGA" type="2130" element="_AOkq84aUEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxZfWZXdEeSroeU30tgKmw" type="5148" element="_AOkq84aUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSq4aUEeSMzJufh3GDGA"/>
    </children>
    <children xmi:id="_AOlSrIaUEeSMzJufh3GDGA" type="2126" element="_AOkrI4aUEeSMzJufh3GDGA">
      <children xsi:type="notation:DecorationNode" xmi:id="_AOlSrYaUEeSMzJufh3GDGA" type="5160" element="_AOkrI4aUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_AOlSroaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_AOlSr4aUEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_AOlSsIaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSsYaUEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_AOlSsoaUEeSMzJufh3GDGA" type="2131" element="_AOkrJ4aUEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxZfW5XdEeSroeU30tgKmw" type="5135" element="_AOkrJ4aUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlStIaUEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_AOlStYaUEeSMzJufh3GDGA" type="2131" element="_AOkrNYaUEeSMzJufh3GDGA" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxZfXZXdEeSroeU30tgKmw" type="5135" element="_AOkrNYaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSt4aUEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_AOlSuIaUEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AOlSuYaUEeSMzJufh3GDGA" type="Form" measurementUnit="Pixel">
    <children xmi:id="_AOlSuoaUEeSMzJufh3GDGA" type="2126">
      <children xsi:type="notation:DecorationNode" xmi:id="_AOlSu4aUEeSMzJufh3GDGA" type="5160"/>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_AOlSvIaUEeSMzJufh3GDGA"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_AOlSvYaUEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_AOlSvoaUEeSMzJufh3GDGA"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSv4aUEeSMzJufh3GDGA"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_AOlSwIaUEeSMzJufh3GDGA" type="2131" fontName="Sans">
      <children xsi:type="notation:DecorationNode" xmi:id="_gxZfX5XdEeSroeU30tgKmw" type="5135"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AOlSwoaUEeSMzJufh3GDGA"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_AOlSw4aUEeSMzJufh3GDGA"/>
  </notation:Diagram>
</xmi:XMI>
