<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process">
  <process:MainProcess xmi:id="_M4tGcIaHEeSvyIbfLayW-g" name="Projet_Validation_Diagram_CORTES_MARTINEZ" author="corteshs" bonitaVersion="6.3.8" bonitaModelVersion="6.3.8-001" configId="ACED000574003750726F6A65745F56616C69646174696F6E5F4469616772616D5F434F525445535F4D415254494E455A362E332E382D303031362E332E38">
    <elements xsi:type="process:Pool" xmi:id="_NASVIIaHEeSvyIbfLayW-g" name="Projet_Validation_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xsi:type="process:Lane" xmi:id="_ND8tIIaHEeSvyIbfLayW-g" name="Employé (lane)" actor="_ND2mgIaHEeSvyIbfLayW-g">
        <elements xsi:type="process:Task" xmi:id="_NEW80IaHEeSvyIbfLayW-g" name="Approve proposal" outgoing="_9jaQEIaJEeSMzJufh3GDGA" incoming="_NHqIcIaHEeSvyIbfLayW-g" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_NEZZEIaHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_NEYyAYaHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_NEYyAIaHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_NEYyAoaHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_NEaAIIaHEeSvyIbfLayW-g">
            <cardinality xmi:id="_dovFIJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_dovFIZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_NEZZEYaHEeSvyIbfLayW-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_NEZZEoaHEeSvyIbfLayW-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_NEZZE4aHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_NEZZFIaHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:StartEvent" xmi:id="_NHDEcIaHEeSvyIbfLayW-g" name="Proposal made" outgoing="_NHqIcIaHEeSvyIbfLayW-g">
          <viewPageFlowRedirectionURL xmi:id="_dovsMJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_dovsMZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_dovsMpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_dovsM5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_pj4RcYaHEeSMzJufh3GDGA" name="Notify proposal aproved" outgoing="_JzIAIIaIEeSMzJufh3GDGA" incoming="_B_FxMIaKEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_pj9J84aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_pj9J8YaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_pj9J8IaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_pj9J8oaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_pj9xAYaHEeSMzJufh3GDGA">
            <cardinality xmi:id="_dovFIpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_dovFI5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_pj9J9IaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_pj9J9YaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_pj9J9oaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_pj9xAIaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_sZPVAIaHEeSMzJufh3GDGA" name="Analyze Impact" outgoing="_KNN7IIaIEeSMzJufh3GDGA" incoming="_JzIAIIaIEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_sZPVAYaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_sZPVAoaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_sZPVA4aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_sZPVBIaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_sZPVBYaHEeSMzJufh3GDGA">
            <cardinality xmi:id="_dovFJJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_dovFJZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_sZPVCIaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_sZPVCYaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_sZPVCoaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_sZPVC4aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_sghowIaHEeSMzJufh3GDGA" name="Notify project accepted" outgoing="_LPl-IIaIEeSMzJufh3GDGA" incoming="_OnWSMIaKEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_sghowYaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_sghowoaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_sghow4aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_sghoxIaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_sghoxYaHEeSMzJufh3GDGA">
            <cardinality xmi:id="_dovFJpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_dovFJ5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_sghoyIaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_sghoyYaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_sghoyoaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_sghoy4aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_suRJ0IaHEeSMzJufh3GDGA" name="Do the project" outgoing="_LlpGoIaIEeSMzJufh3GDGA" incoming="_LPl-IIaIEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_suRJ0YaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_suRJ0oaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_suRJ04aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_suRJ1IaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_suRJ1YaHEeSMzJufh3GDGA">
            <cardinality xmi:id="_dovFKJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_dovFKZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_suRJ2IaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_suRJ2YaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_suRJ2oaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_suRJ24aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_s0hi0IaHEeSMzJufh3GDGA" name="Notify project delivery" outgoing="_7R0ygIaKEeSMzJufh3GDGA" incoming="_LlpGoIaIEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_s0hi0YaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_s0hi0oaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_s0hi04aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_s0hi1IaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_s0hi1YaHEeSMzJufh3GDGA">
            <cardinality xmi:id="_dovFKpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_dovFK5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_s0hi2IaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_s0hi2YaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_s0hi2oaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_s0hi24aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_s67s0IaHEeSMzJufh3GDGA" name="Validate project" outgoing="_Ibo94IaKEeSMzJufh3GDGA" incoming="_KNN7IIaIEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_s67s0YaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_s67s0oaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_s67s04aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_s67s1IaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_s67s1YaHEeSMzJufh3GDGA">
            <cardinality xmi:id="_dovFLJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_dovFLZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_s67s2IaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_s67s2YaHEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_s67s2oaHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_s67s24aHEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_dfwGUIaJEeSMzJufh3GDGA" name="Notify proposal refusal" outgoing="_4jA4UIaJEeSMzJufh3GDGA" incoming="_Ca8mwIaKEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_dfwtY4aJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_dfwtYYaJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_dfwtYIaJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_dfwtYoaJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_dfwtaIaJEeSMzJufh3GDGA">
            <cardinality xmi:id="_dovFLpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_dovFL5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_dfwtZIaJEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_dfwtZYaJEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_dfwtZoaJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_dfwtZ4aJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:Task" xmi:id="_hDkLUIaJEeSMzJufh3GDGA" name="Notify project refused" outgoing="_49jfQIaJEeSMzJufh3GDGA" incoming="_PQANoIaKEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_hDkyY4aJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_hDkyYYaJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_hDkyYIaJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_hDkyYoaJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_hDkyaIaJEeSMzJufh3GDGA">
            <cardinality xmi:id="_dovFMJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:id="_dovFMZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_hDkyZIaJEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_hDkyZYaJEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:id="_hDkyZoaJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:id="_hDkyZ4aJEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_p1kMcIaJEeSMzJufh3GDGA" name="Proposal refused" incoming="_4jA4UIaJEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_dovsNJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_dovsNZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_dovsNpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_dovsN5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_rh5LYIaJEeSMzJufh3GDGA" name="Project finished" incoming="_7R0ygIaKEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_dovsOJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_dovsOZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_dovsOpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_dovsO5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndTerminatedEvent" xmi:id="_r3j5YIaJEeSMzJufh3GDGA" name="Project refused" incoming="_49jfQIaJEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:id="_dovsPJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_dovsPZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_dovsPpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_dovsP5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:XORGateway" xmi:id="_-1MoEIaJEeSMzJufh3GDGA" name="Proposal approval?" outgoing="_B_FxMIaKEeSMzJufh3GDGA _Ca8mwIaKEeSMzJufh3GDGA" incoming="_9jaQEIaJEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:id="_dovsQJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_dovsQZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_dovsQpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_dovsQ5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:XORGateway" xmi:id="_I-3mwIaKEeSMzJufh3GDGA" name="Project approval?" outgoing="_OnWSMIaKEeSMzJufh3GDGA _PQANoIaKEeSMzJufh3GDGA" incoming="_Ibo94IaKEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:id="_dovsRJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_dovsRZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_dovsRpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_dovsR5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:id="_NM7C8IaHEeSvyIbfLayW-g" path="_NASVIIaHEeSvyIbfLayW-g/application/application"/>
      <mandatorySymbol xmi:id="_NAVYcoaHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_NAVYcYaHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_NM7C84aHEeSvyIbfLayW-g" path="_NASVIIaHEeSvyIbfLayW-g/html/error.html"/>
      <processTemplate xmi:id="_NM7C8YaHEeSvyIbfLayW-g" path="_NASVIIaHEeSvyIbfLayW-g/html/process.html"/>
      <pageTemplate xmi:id="_NM7C9IaHEeSvyIbfLayW-g" path="_NASVIIaHEeSvyIbfLayW-g/html/page.html"/>
      <consultationTemplate xmi:id="_NM7C8oaHEeSvyIbfLayW-g" path="_NASVIIaHEeSvyIbfLayW-g/html/consultation.html"/>
      <entryRedirectionURL xmi:id="_NAVYdIaHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_NAVYc4aHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_NAVYdYaHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_NAVYcIaHEeSvyIbfLayW-g" name="" content="" returnTypeFixed="true"/>
      <connections xsi:type="process:SequenceFlow" xmi:id="_NHqIcIaHEeSvyIbfLayW-g" source="_NHDEcIaHEeSvyIbfLayW-g" target="_NEW80IaHEeSvyIbfLayW-g">
        <decisionTable xmi:id="_NHqvgIaHEeSvyIbfLayW-g"/>
        <condition xmi:id="_dowTQZXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_JzIAIIaIEeSMzJufh3GDGA" source="_pj4RcYaHEeSMzJufh3GDGA" target="_sZPVAIaHEeSMzJufh3GDGA">
        <decisionTable xmi:id="_JzInMIaIEeSMzJufh3GDGA"/>
        <condition xmi:id="_dowTQ5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_KNN7IIaIEeSMzJufh3GDGA" source="_sZPVAIaHEeSMzJufh3GDGA" target="_s67s0IaHEeSMzJufh3GDGA">
        <decisionTable xmi:id="_KNN7IYaIEeSMzJufh3GDGA"/>
        <condition xmi:id="_dowTRZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_LPl-IIaIEeSMzJufh3GDGA" source="_sghowIaHEeSMzJufh3GDGA" target="_suRJ0IaHEeSMzJufh3GDGA">
        <decisionTable xmi:id="_LPl-IYaIEeSMzJufh3GDGA"/>
        <condition xmi:id="_dowTR5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_LlpGoIaIEeSMzJufh3GDGA" source="_suRJ0IaHEeSMzJufh3GDGA" target="_s0hi0IaHEeSMzJufh3GDGA">
        <decisionTable xmi:id="_LlpGoYaIEeSMzJufh3GDGA"/>
        <condition xmi:id="_dowTSZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_4jA4UIaJEeSMzJufh3GDGA" source="_dfwGUIaJEeSMzJufh3GDGA" target="_p1kMcIaJEeSMzJufh3GDGA">
        <decisionTable xmi:id="_4jA4UYaJEeSMzJufh3GDGA"/>
        <condition xmi:id="_dowTS5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_49jfQIaJEeSMzJufh3GDGA" source="_hDkLUIaJEeSMzJufh3GDGA" target="_r3j5YIaJEeSMzJufh3GDGA">
        <decisionTable xmi:id="_49kGUIaJEeSMzJufh3GDGA"/>
        <condition xmi:id="_dowTTZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_9jaQEIaJEeSMzJufh3GDGA" source="_NEW80IaHEeSvyIbfLayW-g" target="_-1MoEIaJEeSMzJufh3GDGA">
        <decisionTable xmi:id="_9ja3IIaJEeSMzJufh3GDGA"/>
        <condition xmi:id="_dowTT5XdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_B_FxMIaKEeSMzJufh3GDGA" source="_-1MoEIaJEeSMzJufh3GDGA" target="_pj4RcYaHEeSMzJufh3GDGA">
        <decisionTable xmi:id="_B_FxMYaKEeSMzJufh3GDGA"/>
        <condition xmi:id="_dowTUZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_Ca8mwIaKEeSMzJufh3GDGA" source="_-1MoEIaJEeSMzJufh3GDGA" target="_dfwGUIaJEeSMzJufh3GDGA">
        <decisionTable xmi:id="_Ca8mwYaKEeSMzJufh3GDGA"/>
        <condition xmi:id="_dowTU5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_Ibo94IaKEeSMzJufh3GDGA" source="_s67s0IaHEeSMzJufh3GDGA" target="_I-3mwIaKEeSMzJufh3GDGA">
        <decisionTable xmi:id="_Ibo94YaKEeSMzJufh3GDGA"/>
        <condition xmi:id="_dowTVZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_OnWSMIaKEeSMzJufh3GDGA" source="_I-3mwIaKEeSMzJufh3GDGA" target="_sghowIaHEeSMzJufh3GDGA">
        <decisionTable xmi:id="_OnWSMYaKEeSMzJufh3GDGA"/>
        <condition xmi:id="_dow6UZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_PQANoIaKEeSMzJufh3GDGA" source="_I-3mwIaKEeSMzJufh3GDGA" target="_hDkLUIaJEeSMzJufh3GDGA">
        <decisionTable xmi:id="_PQA0sIaKEeSMzJufh3GDGA"/>
        <condition xmi:id="_dow6U5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_7R0ygIaKEeSMzJufh3GDGA" source="_s0hi0IaHEeSMzJufh3GDGA" target="_rh5LYIaJEeSMzJufh3GDGA">
        <decisionTable xmi:id="_7R0ygYaKEeSMzJufh3GDGA"/>
        <condition xmi:id="_dow6VZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:id="_ND2mgIaHEeSvyIbfLayW-g" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:id="_NAUxYIaHEeSvyIbfLayW-g">
        <name xmi:id="_dow6VpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_dow6V5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_NAUxY4aHEeSvyIbfLayW-g">
        <name xmi:id="_dow6WJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_dow6WZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_NAUxZoaHEeSvyIbfLayW-g">
        <name xmi:id="_doxhYJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_doxhYZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_NAUxaYaHEeSvyIbfLayW-g">
        <name xmi:id="_doxhYpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_doxhY5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_NAUxbIaHEeSvyIbfLayW-g">
        <name xmi:id="_doxhZJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:id="_doxhZZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xsi:type="process:BooleanType" xmi:id="_M4tGcYaHEeSvyIbfLayW-g" name="Boolean"/>
    <datatypes xsi:type="process:DateType" xmi:id="_M4tGcoaHEeSvyIbfLayW-g" name="Date"/>
    <datatypes xsi:type="process:IntegerType" xmi:id="_M4tGc4aHEeSvyIbfLayW-g" name="Integer"/>
    <datatypes xsi:type="process:LongType" xmi:id="_M4tGdIaHEeSvyIbfLayW-g" name="Long"/>
    <datatypes xsi:type="process:DoubleType" xmi:id="_M4tGdYaHEeSvyIbfLayW-g" name="Double"/>
    <datatypes xsi:type="process:StringType" xmi:id="_M4tGdoaHEeSvyIbfLayW-g" name="Text"/>
    <datatypes xsi:type="process:JavaType" xmi:id="_M4tGd4aHEeSvyIbfLayW-g" name="Java_object"/>
    <datatypes xsi:type="process:XMLType" xmi:id="_M4tGeIaHEeSvyIbfLayW-g" name="XML"/>
    <datatypes xsi:type="process:BusinessObjectType" xmi:id="_dooXeJXdEeSroeU30tgKmw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_M4tGeYaHEeSvyIbfLayW-g" type="Process" element="_M4tGcIaHEeSvyIbfLayW-g" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:id="_NBRzoIaHEeSvyIbfLayW-g" type="2007" element="_NASVIIaHEeSvyIbfLayW-g">
      <children xsi:type="notation:DecorationNode" xmi:id="_NBUP4IaHEeSvyIbfLayW-g" type="5008" element="_NASVIIaHEeSvyIbfLayW-g"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_NBUP4YaHEeSvyIbfLayW-g" type="7001" element="_NASVIIaHEeSvyIbfLayW-g">
        <children xmi:id="_doyIe5XdEeSroeU30tgKmw" type="3007" element="_ND8tIIaHEeSvyIbfLayW-g">
          <children xsi:type="notation:DecorationNode" xmi:id="_ND_JZIaHEeSvyIbfLayW-g" type="5007" element="_ND8tIIaHEeSvyIbfLayW-g"/>
          <children xsi:type="notation:DecorationNode" xmi:id="_ND_JZYaHEeSvyIbfLayW-g" type="7002" element="_ND8tIIaHEeSvyIbfLayW-g">
            <children xsi:type="notation:Shape" xmi:id="_NEeRkIaHEeSvyIbfLayW-g" type="3005" element="_NEW80IaHEeSvyIbfLayW-g" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_dozWkJXdEeSroeU30tgKmw" type="5005" element="_NEW80IaHEeSvyIbfLayW-g"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_NEeRkYaHEeSvyIbfLayW-g" x="119" y="165"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_NHFgsIaHEeSvyIbfLayW-g" type="3002" element="_NHDEcIaHEeSvyIbfLayW-g" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_dozWkpXdEeSroeU30tgKmw" type="5024" element="_NHDEcIaHEeSvyIbfLayW-g">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_NHFgs4aHEeSvyIbfLayW-g" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_NHFgsYaHEeSvyIbfLayW-g" x="40" y="179"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_pklcEIaHEeSMzJufh3GDGA" type="3005" element="_pj4RcYaHEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_dozWlZXdEeSroeU30tgKmw" type="5005" element="_pj4RcYaHEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_pklcEYaHEeSMzJufh3GDGA" x="271" y="95" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_sZP8EIaHEeSMzJufh3GDGA" type="3005" element="_sZPVAIaHEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_dozWl5XdEeSroeU30tgKmw" type="5005" element="_sZPVAIaHEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_sZP8EoaHEeSMzJufh3GDGA" x="421" y="102"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_sgiP0IaHEeSMzJufh3GDGA" type="3005" element="_sghowIaHEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_dozWmZXdEeSroeU30tgKmw" type="5005" element="_sghowIaHEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_sgi24YaHEeSMzJufh3GDGA" x="762" y="96" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_suRw4IaHEeSMzJufh3GDGA" type="3005" element="_suRJ0IaHEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_dozWm5XdEeSroeU30tgKmw" type="5005" element="_suRJ0IaHEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_suRw4oaHEeSMzJufh3GDGA" x="913" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_s0iJ4IaHEeSMzJufh3GDGA" type="3005" element="_s0hi0IaHEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_dozWnZXdEeSroeU30tgKmw" type="5005" element="_s0hi0IaHEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_s0iJ4oaHEeSMzJufh3GDGA" x="1041" y="90" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_s68T4IaHEeSMzJufh3GDGA" type="3005" element="_s67s0IaHEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_dozWn5XdEeSroeU30tgKmw" type="5005" element="_s67s0IaHEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_s68T4oaHEeSMzJufh3GDGA" x="556" y="100"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_df0XwIaJEeSMzJufh3GDGA" type="3005" element="_dfwGUIaJEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_dozWoZXdEeSroeU30tgKmw" type="5005" element="_dfwGUIaJEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_df0XwYaJEeSMzJufh3GDGA" x="347" y="187" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_hDmnkIaJEeSMzJufh3GDGA" type="3005" element="_hDkLUIaJEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_doz9oJXdEeSroeU30tgKmw" type="5005" element="_hDkLUIaJEeSMzJufh3GDGA"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_hDmnkYaJEeSMzJufh3GDGA" x="765" y="192" width="120" height="60"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_p1nPwIaJEeSMzJufh3GDGA" type="3062" element="_p1kMcIaJEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_doz9opXdEeSroeU30tgKmw" type="5090" element="_p1kMcIaJEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_p1nPw4aJEeSMzJufh3GDGA" x="-1" y="18"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_p1nPwYaJEeSMzJufh3GDGA" x="537" y="197"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_rh5ycIaJEeSMzJufh3GDGA" type="3062" element="_rh5LYIaJEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_doz9pZXdEeSroeU30tgKmw" type="5090" element="_rh5LYIaJEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_rh5ycoaJEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_rh5yc4aJEeSMzJufh3GDGA" x="1221" y="136"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_r3kgcIaJEeSMzJufh3GDGA" type="3062" element="_r3j5YIaJEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_doz9qJXdEeSroeU30tgKmw" type="5090" element="_r3j5YIaJEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_r3kgcoaJEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_r3kgc4aJEeSMzJufh3GDGA" x="1012" y="226"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_-1N2MIaJEeSMzJufh3GDGA" type="3008" element="_-1MoEIaJEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_doz9q5XdEeSroeU30tgKmw" type="5026" element="_-1MoEIaJEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_-1N2M4aJEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_-1N2MYaJEeSMzJufh3GDGA" x="252" y="179" width="43" height="43"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_I-4N1IaKEeSMzJufh3GDGA" type="3008" element="_I-3mwIaKEeSMzJufh3GDGA" fontName="Sans">
              <children xsi:type="notation:DecorationNode" xmi:id="_doz9rpXdEeSroeU30tgKmw" type="5026" element="_I-3mwIaKEeSMzJufh3GDGA">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_I-404YaKEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_I-4N1YaKEeSMzJufh3GDGA" x="689" y="105" width="43" height="43"/>
            </children>
          </children>
          <styles xsi:type="notation:DescriptionStyle" xmi:id="_ND_JYIaHEeSvyIbfLayW-g"/>
          <styles xsi:type="notation:FontStyle" xmi:id="_ND_JYYaHEeSvyIbfLayW-g" fontName="Sans"/>
          <styles xsi:type="notation:LineStyle" xmi:id="_ND_JYoaHEeSvyIbfLayW-g"/>
          <styles xsi:type="notation:FillStyle" xmi:id="_ND_JZoaHEeSvyIbfLayW-g"/>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_ND_JY4aHEeSvyIbfLayW-g" x="45" y="10" width="1372" height="302"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_NBRzoYaHEeSvyIbfLayW-g"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_NBRzooaHEeSvyIbfLayW-g" fontName="Sans"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_NBRzo4aHEeSvyIbfLayW-g"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_NBUP4oaHEeSvyIbfLayW-g"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_NBRzpIaHEeSvyIbfLayW-g"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_M4tGeoaHEeSvyIbfLayW-g"/>
    <edges xsi:type="notation:Connector" xmi:id="_NHvA8IaHEeSvyIbfLayW-g" type="4001" element="_NHqIcIaHEeSvyIbfLayW-g" source="_NHFgsIaHEeSvyIbfLayW-g" target="_NEeRkIaHEeSvyIbfLayW-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do1LwJXdEeSroeU30tgKmw" type="6001" element="_NHqIcIaHEeSvyIbfLayW-g">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do1LwZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do1LwpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_NHvA8oaHEeSvyIbfLayW-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_JzJ1UIaIEeSMzJufh3GDGA" type="4001" element="_JzIAIIaIEeSMzJufh3GDGA" source="_pklcEIaHEeSMzJufh3GDGA" target="_sZP8EIaHEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do1LxJXdEeSroeU30tgKmw" type="6001" element="_JzIAIIaIEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do1y0JXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do1y0ZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_JzJ1UoaIEeSMzJufh3GDGA" points="[0, 1, -66, -7]$[16, 1, -50, -7]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_JzM4oIaIEeSMzJufh3GDGA" id="(1.0,0.55)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_KNOiMIaIEeSMzJufh3GDGA" type="4001" element="_KNN7IIaIEeSMzJufh3GDGA" source="_sZP8EIaHEeSMzJufh3GDGA" target="_s68T4IaHEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do1y1JXdEeSroeU30tgKmw" type="6001" element="_KNN7IIaIEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do1y1ZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do1y1pXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_KNOiMoaIEeSMzJufh3GDGA" points="[0, 0, -41, 91]$[-9, -91, -50, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_KNRlgIaIEeSMzJufh3GDGA" id="(1.0,0.64)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_LPmlMIaIEeSMzJufh3GDGA" type="4001" element="_LPl-IIaIEeSMzJufh3GDGA" source="_sgiP0IaHEeSMzJufh3GDGA" target="_suRw4IaHEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do1y2ZXdEeSroeU30tgKmw" type="6001" element="_LPl-IIaIEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do1y2pXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do1y25XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_LPmlMoaIEeSMzJufh3GDGA" points="[0, 0, -5, -60]$[55, 51, 50, -9]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_LPpogIaIEeSMzJufh3GDGA" id="(1.0,0.5)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_LlqUwIaIEeSMzJufh3GDGA" type="4001" element="_LlpGoIaIEeSMzJufh3GDGA" source="_suRw4IaHEeSMzJufh3GDGA" target="_s0iJ4IaHEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do1y3pXdEeSroeU30tgKmw" type="6001" element="_LlpGoIaIEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do1y35XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do1y4JXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_LlqUwoaIEeSMzJufh3GDGA" points="[0, 0, -60, 48]$[65, -35, 5, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_Llt_IIaIEeSMzJufh3GDGA" id="(1.0,0.6)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_Llt_IYaIEeSMzJufh3GDGA" id="(0.5583333333333333,0.7833333333333333)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_4jCGcIaJEeSMzJufh3GDGA" type="4001" element="_4jA4UIaJEeSMzJufh3GDGA" source="_df0XwIaJEeSMzJufh3GDGA" target="_p1nPwIaJEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do1y5JXdEeSroeU30tgKmw" type="6001" element="_4jA4UIaJEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do1y5ZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do1y5pXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_4jCGcoaJEeSMzJufh3GDGA" points="[0, -8, -85, 2]$[78, 3, -7, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_4jFJwIaJEeSMzJufh3GDGA" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_49ktYIaJEeSMzJufh3GDGA" type="4001" element="_49jfQIaJEeSMzJufh3GDGA" source="_hDmnkIaJEeSMzJufh3GDGA" target="_r3kgcIaJEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do1y6ZXdEeSroeU30tgKmw" type="6001" element="_49jfQIaJEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do1y6pXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do1y65XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_49ktYoaJEeSMzJufh3GDGA" points="[0, 0, -142, -15]$[135, 28, -7, 13]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_49nwsIaJEeSMzJufh3GDGA" id="(1.0,0.5666666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_9jbeMIaJEeSMzJufh3GDGA" type="4001" element="_9jaQEIaJEeSMzJufh3GDGA" source="_NEeRkIaHEeSvyIbfLayW-g" target="_-1N2MIaJEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do2Z4JXdEeSroeU30tgKmw" type="6001" element="_9jaQEIaJEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do2Z4ZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do2Z4pXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_9jbeMoaJEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_B_G_UIaKEeSMzJufh3GDGA" type="4001" element="_B_FxMIaKEeSMzJufh3GDGA" source="_-1N2MIaJEeSMzJufh3GDGA" target="_pklcEIaHEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do2Z5JXdEeSroeU30tgKmw" type="6001" element="_B_FxMIaKEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do2Z5ZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do2Z5pXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_B_G_UoaKEeSMzJufh3GDGA" points="[-11, -22, -51, 47]$[42, -57, 2, 12]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_B_KCoIaKEeSMzJufh3GDGA" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_B_KpsIaKEeSMzJufh3GDGA" id="(0.5333333333333333,0.8)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_CbFJoIaKEeSMzJufh3GDGA" type="4001" element="_Ca8mwIaKEeSMzJufh3GDGA" source="_-1N2MIaJEeSMzJufh3GDGA" target="_df0XwIaJEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do2Z6pXdEeSroeU30tgKmw" type="6001" element="_Ca8mwIaKEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do2Z65XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do2Z7JXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_CbFJooaKEeSMzJufh3GDGA" points="[-14, 1, -91, 0]$[52, -2, -25, -3]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_CbHl4IaKEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_CbHl4YaKEeSMzJufh3GDGA" id="(0.20833333333333334,0.45)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_IbqMAIaKEeSMzJufh3GDGA" type="4001" element="_Ibo94IaKEeSMzJufh3GDGA" source="_s68T4IaHEeSMzJufh3GDGA" target="_I-4N1IaKEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do2Z8JXdEeSroeU30tgKmw" type="6001" element="_Ibo94IaKEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do2Z8ZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do2Z8pXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_IbqMAoaKEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_NlMRoIaKEeSMzJufh3GDGA" id="(0.97,0.54)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_OnW5QIaKEeSMzJufh3GDGA" type="4001" element="_OnWSMIaKEeSMzJufh3GDGA" source="_I-4N1IaKEeSMzJufh3GDGA" target="_sgiP0IaHEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do2Z9ZXdEeSroeU30tgKmw" type="6001" element="_OnWSMIaKEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do2Z9pXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do2Z95XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_OnW5QoaKEeSMzJufh3GDGA" points="[-11, -3, -65, 0]$[30, -1, -24, 2]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_OnZVgIaKEeSMzJufh3GDGA" id="(1.0,0.813953488372093)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_OnZVgYaKEeSMzJufh3GDGA" id="(0.025,0.18333333333333332)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_PQGUQIaKEeSMzJufh3GDGA" type="4001" element="_PQANoIaKEeSMzJufh3GDGA" source="_I-4N1IaKEeSMzJufh3GDGA" target="_hDmnkIaJEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do2Z-5XdEeSroeU30tgKmw" type="6001" element="_PQANoIaKEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do2Z_JXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do2Z_ZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_PQGUQoaKEeSMzJufh3GDGA" points="[-4, -10, -40, -95]$[33, 84, -3, -1]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_PQJXkIaKEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_PQJ-oIaKEeSMzJufh3GDGA" id="(0.025,0.4166666666666667)"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_7R1ZkIaKEeSMzJufh3GDGA" type="4001" element="_7R0ygIaKEeSMzJufh3GDGA" source="_s0iJ4IaHEeSMzJufh3GDGA" target="_rh5ycIaJEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_do2aAZXdEeSroeU30tgKmw" type="6001" element="_7R0ygIaKEeSMzJufh3GDGA">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_do2aApXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_do2aA5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_7R2AoYaKEeSMzJufh3GDGA" points="[0, 0, -75, -29]$[72, 14, -3, -15]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_7R4c4IaKEeSMzJufh3GDGA" id="(1.0,0.5333333333333333)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
