<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_BeGHgIaLEeSMzJufh3GDGA" name="Projet_Validation_Diagram_CORTES_MARTINEZ" version="2.0" author="corteshs" bonitaVersion="6.1.1" bonitaModelVersion="6.1.1-001" configId="ACED000574003750726F6A65745F56616C69646174696F6E5F4469616772616D5F434F525445535F4D415254494E455A362E312E312D303031362E312E31">
    <elements xmi:type="process:Pool" xmi:id="_BeGHgYaLEeSMzJufh3GDGA" name="Projet_Validation_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="2.0">
      <elements xmi:type="process:Lane" xmi:id="_BeGHgoaLEeSMzJufh3GDGA" name="Employé (lane)" actor="_BeJyHYaLEeSMzJufh3GDGA">
        <elements xmi:type="process:Task" xmi:id="_BeGHg4aLEeSMzJufh3GDGA" name="Approve proposal" outgoing="_BeJyCIaLEeSMzJufh3GDGA" incoming="_BeJx84aLEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeGHhIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeGHhYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeGHhoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeGHh4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_BeGHiIaLEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_BeGHiYaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_BeGHioaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BeGHi4aLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BeGHjIaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_Qn534IaOEeSMzJufh3GDGA" name="ApproveProposal" nLine="3">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_Qn54EYaOEeSMzJufh3GDGA" name="proposalOK1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_Qn54EoaOEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_Qn54E4aOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_Qn6e8IaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_Qn6e8YaOEeSMzJufh3GDGA" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_Qn6e8oaOEeSMzJufh3GDGA" name="proposalOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_Qn6e84aOEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_Qn6e9IaOEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_Qn6e9YaOEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_Qn6e9oaOEeSMzJufh3GDGA" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="_Qn6e94aOEeSMzJufh3GDGA" name="proposalOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_Qn6e-IaOEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                  </referencedElements>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_Qn6e-YaOEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_Qn6e-oaOEeSMzJufh3GDGA" name="field_proposalOK1" content="field_proposalOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_Qn6e-4aOEeSMzJufh3GDGA" name="proposalOK1">
                    <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_Qn6e_IaOEeSMzJufh3GDGA" line="1"/>
                    <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_Qn6e_YaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_Qn6e_oaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <inputExpression xmi:type="expression:Expression" xmi:id="_Qn6e_4aOEeSMzJufh3GDGA" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                      <referencedElements xmi:type="process:Data" xmi:id="_Qn6fAIaOEeSMzJufh3GDGA" name="proposalOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
                        <defaultValue xmi:type="expression:Expression" xmi:id="_Qn6fAYaOEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                      </referencedElements>
                    </inputExpression>
                    <afterEventExpression xmi:type="expression:Expression" xmi:id="_Qn6fAoaOEeSMzJufh3GDGA" name="" content=""/>
                    <action xmi:type="expression:Operation" xmi:id="_Qn6fA4aOEeSMzJufh3GDGA">
                      <leftOperand xmi:type="expression:Expression" xmi:id="_Qn6fBIaOEeSMzJufh3GDGA"/>
                      <operator xmi:type="expression:Operator" xmi:id="_Qn6fBYaOEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                      <rightOperand xmi:type="expression:Expression" xmi:id="_Qn6fBoaOEeSMzJufh3GDGA"/>
                    </action>
                    <tooltip xmi:type="expression:Expression" xmi:id="_Qn6fB4aOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <helpMessage xmi:type="expression:Expression" xmi:id="_Qn6fCIaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabel xmi:type="expression:Expression" xmi:id="_Qn6fCYaOEeSMzJufh3GDGA" name="proposalOK1" content="proposalOK1" returnTypeFixed="true"/>
                    <injectWidgetScript xmi:type="expression:Expression" xmi:id="_Qn6fCoaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_Qn6fC4aOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_Qn6fDIaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_Qn6fDYaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForAdd xmi:type="expression:Expression" xmi:id="_Qn6fDoaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_Qn6fD4aOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForRemove xmi:type="expression:Expression" xmi:id="_Qn6fEIaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <exampleMessage xmi:type="expression:Expression" xmi:id="_Qn6fEYaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                  </referencedElements>
                </rightOperand>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_Qn6fEoaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_Qn6fE4aOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_Qn6fFIaOEeSMzJufh3GDGA" name="Approved?" content="Approved?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_Qn6fFYaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_Qn6fFoaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_Qn6fF4aOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_Qn6fGIaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_Qn6fGYaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_Qn6fGoaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_Qn6fG4aOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_Qn6fHIaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_Qn6fHYaOEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_Qn6fHoaOEeSMzJufh3GDGA" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_Qn6fH4aOEeSMzJufh3GDGA" name="OK" content="OK" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_Qn6fIIaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_TMvMIIaOEeSMzJufh3GDGA" name="proposal1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_Qn534oaOEeSMzJufh3GDGA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_Qn5344aOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_Qn535IaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_Qn535YaOEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_Qn535oaOEeSMzJufh3GDGA" name="proposal" dataType="_BeJyMoaLEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_Qn5354aOEeSMzJufh3GDGA" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_Qn536IaOEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_Qn54BoaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_Qn54B4aOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_Qn54CYaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_Qn6fIYaOEeSMzJufh3GDGA" name="Approve proposal" content="Approve proposal" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_BeGHjYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_BeGHjoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_BeGHj4aLEeSMzJufh3GDGA" name="Proposal made" outgoing="_BeJx84aLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeGHkIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeGHkYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeGHkoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeGHk4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BeGHoIaLEeSMzJufh3GDGA" name="Analyze Impact" outgoing="_BeJx-YaLEeSMzJufh3GDGA" incoming="_BeJx9oaLEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeGHoYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeGHooaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeGHo4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeGHpIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_BeGHpYaLEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_BeGHpoaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_BeGHp4aLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BeGHqIaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BeGHqYaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_sUc3cIaOEeSMzJufh3GDGA" name="AnalyzeImpact" nLine="3">
            <widgets xmi:type="form:TextFormField" xmi:id="_sUc3cYaOEeSMzJufh3GDGA" name="impacts1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_sUc3coaOEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_sUc3c4aOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_sUc3dIaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_sUc3dYaOEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_sUc3doaOEeSMzJufh3GDGA" name="impacts" dataType="_BeJyMoaLEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_sUc3d4aOEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_sUc3eIaOEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_sUc3eYaOEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_sUc3eoaOEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                  <referencedElements xmi:type="process:Data" xmi:id="_sUc3e4aOEeSMzJufh3GDGA" name="impacts" dataType="_BeJyMoaLEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_sUc3fIaOEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                  </referencedElements>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_sUc3fYaOEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_sUc3foaOEeSMzJufh3GDGA" name="field_impacts1" content="field_impacts1" type="TYPE_INPUT">
                  <referencedElements xmi:type="form:TextFormField" xmi:id="_sUc3f4aOEeSMzJufh3GDGA" name="impacts1">
                    <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_sUdegIaOEeSMzJufh3GDGA"/>
                    <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_sUdegYaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_sUdegoaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <inputExpression xmi:type="expression:Expression" xmi:id="_sUdeg4aOEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_sUdehIaOEeSMzJufh3GDGA" name="impacts" dataType="_BeJyMoaLEeSMzJufh3GDGA">
                        <defaultValue xmi:type="expression:Expression" xmi:id="_sUdehYaOEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                      </referencedElements>
                    </inputExpression>
                    <afterEventExpression xmi:type="expression:Expression" xmi:id="_sUdehoaOEeSMzJufh3GDGA" name="" content=""/>
                    <action xmi:type="expression:Operation" xmi:id="_sUdeh4aOEeSMzJufh3GDGA">
                      <leftOperand xmi:type="expression:Expression" xmi:id="_sUdeiIaOEeSMzJufh3GDGA"/>
                      <operator xmi:type="expression:Operator" xmi:id="_sUdeiYaOEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                      <rightOperand xmi:type="expression:Expression" xmi:id="_sUdeioaOEeSMzJufh3GDGA"/>
                    </action>
                    <tooltip xmi:type="expression:Expression" xmi:id="_sUdei4aOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <helpMessage xmi:type="expression:Expression" xmi:id="_sUdejIaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabel xmi:type="expression:Expression" xmi:id="_sUdejYaOEeSMzJufh3GDGA" name="impacts1" content="impacts1" returnTypeFixed="true"/>
                    <injectWidgetScript xmi:type="expression:Expression" xmi:id="_sUdejoaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_sUdej4aOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_sUdekIaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_sUdekYaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForAdd xmi:type="expression:Expression" xmi:id="_sUdekoaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_sUdek4aOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForRemove xmi:type="expression:Expression" xmi:id="_sUdelIaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <exampleMessage xmi:type="expression:Expression" xmi:id="_sUdelYaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                  </referencedElements>
                </rightOperand>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_sUdeloaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_sUdel4aOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_sUdemIaOEeSMzJufh3GDGA" name="Impact?" content="Impact?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_sUdemYaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_sUdemoaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_sUdem4aOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_sUdenIaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_sUdenYaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_sUdenoaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_sUden4aOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_sUdeoIaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_sUde0YaOEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_sUde0oaOEeSMzJufh3GDGA" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_sUde04aOEeSMzJufh3GDGA" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_sUeFkIaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_4oElMIaOEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_6qd6wIaOEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_7WALEIaOEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_sUdeooaOEeSMzJufh3GDGA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_sUdeo4aOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_sUdepIaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_sUdepYaOEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_sUdepoaOEeSMzJufh3GDGA" name="proposal" dataType="_BeJyMoaLEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_sUdep4aOEeSMzJufh3GDGA" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_sUdeqIaOEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_sUdexoaOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_sUdex4aOEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_sUdeyYaOEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_sUeFkYaOEeSMzJufh3GDGA" name="Analyze Impact" content="Analyze Impact" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_BeGHqoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_BeGHq4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BeJK1IaLEeSMzJufh3GDGA" name="Do the project" outgoing="_BeJx_4aLEeSMzJufh3GDGA" incoming="_BeJx_IaLEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJK1YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeJK1oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeJK14aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeJK2IaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_BeJK2YaLEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_BeJK2oaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_BeJK24aLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BeJK3IaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BeJK3YaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_4FKP8IaPEeSMzJufh3GDGA" name="DoTheProject" nLine="3">
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_4FKP8YaPEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_4FKP8oaPEeSMzJufh3GDGA" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_4FKP84aPEeSMzJufh3GDGA" name="Project Finished" content="Project Finished" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_4FKP9IaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_8nnugIaPEeSMzJufh3GDGA" name="Message1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_8npjsYaPEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_8nnuhoaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_8nnuh4aPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_8nnuhYaPEeSMzJufh3GDGA" name="Press the button Monkey!!!!" content="Press the button Monkey!!!!"/>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_8nnuiIaPEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_8noVkIaPEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_8noVkYaPEeSMzJufh3GDGA"/>
                <operator xmi:type="expression:Operator" xmi:id="_8noVkoaPEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_8noVk4aPEeSMzJufh3GDGA"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_8nnuhIaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_8nnug4aPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_8nnugYaPEeSMzJufh3GDGA" name="Message1" content="Message1" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_8nnugoaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_4FKP9YaPEeSMzJufh3GDGA" name="Do the project" content="Do the project" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJK3oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_BeJK34aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BeJK7IaLEeSMzJufh3GDGA" name="Validate project" outgoing="_BeJyEYaLEeSMzJufh3GDGA" incoming="_BeJx-YaLEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJK7YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeJK7oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeJK74aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeJK8IaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_BeJK8YaLEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_BeJK8oaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_BeJK84aLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BeJK9IaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BeJK9YaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_e474EIaPEeSMzJufh3GDGA" name="ValidateProject">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_e48fMoaPEeSMzJufh3GDGA" name="projectOK1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_e48fM4aPEeSMzJufh3GDGA" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_e48fNIaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_e48fNYaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_e48fNoaPEeSMzJufh3GDGA" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_e48fN4aPEeSMzJufh3GDGA" name="projectOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_e48fOIaPEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_e48fOYaPEeSMzJufh3GDGA" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_e48fOoaPEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_e48fO4aPEeSMzJufh3GDGA" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="_e48fPIaPEeSMzJufh3GDGA" name="projectOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_e48fPYaPEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                  </referencedElements>
                </leftOperand>
                <operator xmi:type="expression:Operator" xmi:id="_e48fPoaPEeSMzJufh3GDGA" type="ASSIGNMENT"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_e48fP4aPEeSMzJufh3GDGA" name="field_projectOK1" content="field_projectOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_e48fQIaPEeSMzJufh3GDGA" name="projectOK1">
                    <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_e48fQYaPEeSMzJufh3GDGA" line="1"/>
                    <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_e48fQoaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_e48fQ4aPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <inputExpression xmi:type="expression:Expression" xmi:id="_e48fRIaPEeSMzJufh3GDGA" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                      <referencedElements xmi:type="process:Data" xmi:id="_e48fRYaPEeSMzJufh3GDGA" name="projectOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
                        <defaultValue xmi:type="expression:Expression" xmi:id="_e48fRoaPEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
                      </referencedElements>
                    </inputExpression>
                    <afterEventExpression xmi:type="expression:Expression" xmi:id="_e48fR4aPEeSMzJufh3GDGA" name="" content=""/>
                    <action xmi:type="expression:Operation" xmi:id="_e48fSIaPEeSMzJufh3GDGA">
                      <leftOperand xmi:type="expression:Expression" xmi:id="_e48fSYaPEeSMzJufh3GDGA"/>
                      <operator xmi:type="expression:Operator" xmi:id="_e48fSoaPEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                      <rightOperand xmi:type="expression:Expression" xmi:id="_e48fS4aPEeSMzJufh3GDGA"/>
                    </action>
                    <tooltip xmi:type="expression:Expression" xmi:id="_e48fTIaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <helpMessage xmi:type="expression:Expression" xmi:id="_e48fTYaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabel xmi:type="expression:Expression" xmi:id="_e48fToaPEeSMzJufh3GDGA" name="projectOK1" content="projectOK1" returnTypeFixed="true"/>
                    <injectWidgetScript xmi:type="expression:Expression" xmi:id="_e48fT4aPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                    <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_e48fUIaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_e48fUYaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                    <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_e48fUoaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForAdd xmi:type="expression:Expression" xmi:id="_e48fU4aPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_e48fVIaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <tooltipForRemove xmi:type="expression:Expression" xmi:id="_e48fVYaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                    <exampleMessage xmi:type="expression:Expression" xmi:id="_e48fVoaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                  </referencedElements>
                </rightOperand>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_e48fV4aPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_e48fWIaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_e48fWYaPEeSMzJufh3GDGA" name="Approve project?" content="Approve project?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_e48fWoaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_e48fW4aPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_e48fXIaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_e48fXYaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_e48fXoaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_e48fX4aPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_e48fYIaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_e48fYYaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_e49GN4aPEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_e49GOIaPEeSMzJufh3GDGA" line="3"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_e49GOYaPEeSMzJufh3GDGA" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_e49GOoaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_gqqUYIaPEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_iFbCMIaPEeSMzJufh3GDGA" key="input_css:color" value="purple"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_iZaVMIaPEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_i3W1cIaPEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_e48fY4aPEeSMzJufh3GDGA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_e48fZIaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_e48fZYaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_e48fZoaPEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_e48fZ4aPEeSMzJufh3GDGA" name="proposal" dataType="_BeJyMoaLEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_e48faIaPEeSMzJufh3GDGA" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_e48faYaPEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_e48fh4aPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_e48fiIaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_e48fioaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_mKTM4IaPEeSMzJufh3GDGA" name="impacts1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_jtkEsIaPEeSMzJufh3GDGA" key="input_css:color" value="red"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_kgEfsIaPEeSMzJufh3GDGA" key="input_css:font-size" value="18px"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_e474EoaPEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_e474E4aPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_e474FIaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_e474FYaPEeSMzJufh3GDGA" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_e474FoaPEeSMzJufh3GDGA" name="impacts" dataType="_BeJyMoaLEeSMzJufh3GDGA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_e474F4aPEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_e474GIaPEeSMzJufh3GDGA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_e48fJ4aPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_e48fKIaPEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_e48fKoaPEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_e49GO4aPEeSMzJufh3GDGA" name="Validate project" content="Validate project" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJK9oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_BeJK94aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_BeJLEIaLEeSMzJufh3GDGA" name="Proposal refused" incoming="_BeJyAoaLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJLEYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeJLEoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeJLE4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeJLFIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_BeJLFYaLEeSMzJufh3GDGA" name="Project finished" incoming="_BeJyGoaLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJLFoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeJLF4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeJLGIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeJLGYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_BeJLGoaLEeSMzJufh3GDGA" name="Project refused" incoming="_BeJyBYaLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJLG4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeJLHIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeJLHYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeJLHoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_BeJx44aLEeSMzJufh3GDGA" name="Project approval?" outgoing="_BeJyFIaLEeSMzJufh3GDGA _BeJyF4aLEeSMzJufh3GDGA" incoming="_BeJyEYaLEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJx5IaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeJx5YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeJx5oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeJx54aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_utXW8IaLEeSMzJufh3GDGA" name="Proposal approval?" outgoing="_BeJyC4aLEeSMzJufh3GDGA _BeJyDoaLEeSMzJufh3GDGA" incoming="_BeJyCIaLEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJLIIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeJx4IaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeJx4YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeJx4oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_mD--8IaOEeSMzJufh3GDGA" name="Notify proposal aproved" outgoing="_BeJx9oaLEeSMzJufh3GDGA" incoming="_BeJyC4aLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeGHlYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeGHloaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeGHl4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeGHmIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_BeGHmYaLEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_BeGHmoaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_BeGHm4aLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BeGHnIaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BeGHnYaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_np8QIIaOEeSMzJufh3GDGA" name="Notify proposal refusal" outgoing="_BeJyAoaLEeSMzJufh3GDGA" incoming="_BeJyDoaLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJK-YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeJK-oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeJK-4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeJK_IaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_BeJK_YaLEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_BeJK_oaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_BeJK_4aLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BeJLAIaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BeJLAYaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_0uz_MIaPEeSMzJufh3GDGA" name="Notify project refused" outgoing="_BeJyBYaLEeSMzJufh3GDGA" incoming="_BeJyF4aLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJLBYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeJLBoaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeJLB4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeJLCIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_BeJLCYaLEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_BeJLCoaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_BeJLC4aLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BeJLDIaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BeJLDYaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_1dRnsIaPEeSMzJufh3GDGA" name="Notify project accepted" outgoing="_BeJx_IaLEeSMzJufh3GDGA" incoming="_BeJyFIaLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeGHrYaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeGHroaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeGHr4aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeGHsIaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_BeGHsYaLEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_BeGHsoaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_BeGHs4aLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BeJK0IaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BeJK0YaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_JfAQoIaQEeSMzJufh3GDGA" name="Notify project delivery" outgoing="_BeJyGoaLEeSMzJufh3GDGA" incoming="_BeJx_4aLEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJK4YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BeJK4oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BeJK44aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BeJK5IaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_BeJK5YaLEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_BeJK5oaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_BeJK54aLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BeJK6IaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BeJK6YaLEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_Bj_UIIaLEeSMzJufh3GDGA" path="_BeGHgYaLEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_BeJx6YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_BeJx6oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_BeJx64aLEeSMzJufh3GDGA" path="_BeGHgYaLEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_BeJx7IaLEeSMzJufh3GDGA" path="_BeGHgYaLEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_BeJx7YaLEeSMzJufh3GDGA" path="_BeGHgYaLEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_BeJx7oaLEeSMzJufh3GDGA" path="_BeGHgYaLEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_bok3YIaLEeSMzJufh3GDGA" name="proposal" dataType="_BeJyMoaLEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_bok3YYaLEeSMzJufh3GDGA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_fv210IaLEeSMzJufh3GDGA" name="proposalOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_fv210YaLEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_inbf4IaLEeSMzJufh3GDGA" name="projectOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_inbf4YaLEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_pSIdUIaLEeSMzJufh3GDGA" name="impacts" dataType="_BeJyMoaLEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pSIdUYaLEeSMzJufh3GDGA" content="" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <form xmi:type="form:Form" xmi:id="_iVjQQIaMEeSMzJufh3GDGA" name="Project_Validation_CORTES_MARTINEZ" nLine="3">
        <widgets xmi:type="form:TextFormField" xmi:id="_iVjQQYaMEeSMzJufh3GDGA" name="proposal1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_iVjQQoaMEeSMzJufh3GDGA" line="1"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_iVjQQ4aMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_iVjQRIaMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_iVjQRYaMEeSMzJufh3GDGA" name="" content=""/>
          <afterEventExpression xmi:type="expression:Expression" xmi:id="_iVjQRoaMEeSMzJufh3GDGA" name="" content=""/>
          <action xmi:type="expression:Operation" xmi:id="_iVjQR4aMEeSMzJufh3GDGA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iVjQSIaMEeSMzJufh3GDGA" name="proposal" content="proposal" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_iVjQSYaMEeSMzJufh3GDGA" name="proposal" dataType="_BeJyMoaLEeSMzJufh3GDGA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_iVjQSoaMEeSMzJufh3GDGA" content=""/>
              </referencedElements>
            </leftOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iVjQS4aMEeSMzJufh3GDGA" type="ASSIGNMENT"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iVjQTIaMEeSMzJufh3GDGA" name="field_proposal1" content="field_proposal1" type="TYPE_INPUT">
              <referencedElements xmi:type="form:TextFormField" xmi:id="_iVjQTYaMEeSMzJufh3GDGA" name="proposal1">
                <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_iVjQToaMEeSMzJufh3GDGA"/>
                <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_iVjQT4aMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_iVjQUIaMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                <inputExpression xmi:type="expression:Expression" xmi:id="_iVjQUYaMEeSMzJufh3GDGA" name="" content=""/>
                <afterEventExpression xmi:type="expression:Expression" xmi:id="_iVjQUoaMEeSMzJufh3GDGA" name="" content=""/>
                <action xmi:type="expression:Operation" xmi:id="_iVjQU4aMEeSMzJufh3GDGA">
                  <leftOperand xmi:type="expression:Expression" xmi:id="_iVjQVIaMEeSMzJufh3GDGA"/>
                  <operator xmi:type="expression:Operator" xmi:id="_iVjQVYaMEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
                  <rightOperand xmi:type="expression:Expression" xmi:id="_iVjQVoaMEeSMzJufh3GDGA"/>
                </action>
                <tooltip xmi:type="expression:Expression" xmi:id="_iVjQV4aMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <helpMessage xmi:type="expression:Expression" xmi:id="_iVjQWIaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <displayLabel xmi:type="expression:Expression" xmi:id="_iVjQWYaMEeSMzJufh3GDGA" name="proposal1" content="proposal1" returnTypeFixed="true"/>
                <injectWidgetScript xmi:type="expression:Expression" xmi:id="_iVjQWoaMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
                <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_iVjQW4aMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_iVjQXIaMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
                <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_iVjQXYaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <tooltipForAdd xmi:type="expression:Expression" xmi:id="_iVjQXoaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_iVjQX4aMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <tooltipForRemove xmi:type="expression:Expression" xmi:id="_iVjQYIaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
                <exampleMessage xmi:type="expression:Expression" xmi:id="_iVjQYYaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
              </referencedElements>
            </rightOperand>
          </action>
          <tooltip xmi:type="expression:Expression" xmi:id="_iVjQYoaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:type="expression:Expression" xmi:id="_iVjQY4aMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_iVjQZIaMEeSMzJufh3GDGA" name="Proposal" content="Proposal" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_iVjQZYaMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_iVjQZoaMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_iVjQZ4aMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_iVjQaIaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <tooltipForAdd xmi:type="expression:Expression" xmi:id="_iVjQaYaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_iVjQaoaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <tooltipForRemove xmi:type="expression:Expression" xmi:id="_iVjQa4aMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <exampleMessage xmi:type="expression:Expression" xmi:id="_iVjQbIaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
        </widgets>
        <widgets xmi:type="form:SubmitFormButton" xmi:id="_iVjQbYaMEeSMzJufh3GDGA" name="Soumettre1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_iVjQboaMEeSMzJufh3GDGA" line="2"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_iVjQb4aMEeSMzJufh3GDGA" name="OK" content="OK" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_iVjQcIaMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <widgets xmi:type="form:MessageInfo" xmi:id="_sdX00IaMEeSMzJufh3GDGA" name="Enter proposal:">
          <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_zDz9UIaMEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_sda4IoaMEeSMzJufh3GDGA"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_sdYb5YaMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_sdYb5oaMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_sdYb5IaMEeSMzJufh3GDGA" name="" content=""/>
          <afterEventExpression xmi:type="expression:Expression" xmi:id="_sdYb54aMEeSMzJufh3GDGA" name="" content=""/>
          <action xmi:type="expression:Operation" xmi:id="_sdYb6IaMEeSMzJufh3GDGA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_sdYb6YaMEeSMzJufh3GDGA"/>
            <operator xmi:type="expression:Operator" xmi:id="_sdYb6oaMEeSMzJufh3GDGA" type="ASSIGNMENT" expression="="/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_sdYb64aMEeSMzJufh3GDGA"/>
          </action>
          <tooltip xmi:type="expression:Expression" xmi:id="_sdYb44aMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:type="expression:Expression" xmi:id="_sdYb4oaMEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_sdYb4IaMEeSMzJufh3GDGA" name="Message1" content="Message1" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_sdYb4YaMEeSMzJufh3GDGA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:type="expression:Expression" xmi:id="_iVjQcYaMEeSMzJufh3GDGA" name="Propose proposal" content="Propose proposal" returnTypeFixed="true"/>
      </form>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJx74aLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_BeJx8IaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJx8YaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_BeJx8oaLEeSMzJufh3GDGA" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJx84aLEeSMzJufh3GDGA" source="_BeGHj4aLEeSMzJufh3GDGA" target="_BeGHg4aLEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJx9IaLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJx9YaLEeSMzJufh3GDGA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJx9oaLEeSMzJufh3GDGA" source="_mD--8IaOEeSMzJufh3GDGA" target="_BeGHoIaLEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJx94aLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJx-IaLEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJx-YaLEeSMzJufh3GDGA" source="_BeGHoIaLEeSMzJufh3GDGA" target="_BeJK7IaLEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJx-oaLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJx-4aLEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJx_IaLEeSMzJufh3GDGA" source="_1dRnsIaPEeSMzJufh3GDGA" target="_BeJK1IaLEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJx_YaLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJx_oaLEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJx_4aLEeSMzJufh3GDGA" source="_BeJK1IaLEeSMzJufh3GDGA" target="_JfAQoIaQEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJyAIaLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJyAYaLEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJyAoaLEeSMzJufh3GDGA" source="_np8QIIaOEeSMzJufh3GDGA" target="_BeJLEIaLEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJyA4aLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJyBIaLEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJyBYaLEeSMzJufh3GDGA" source="_0uz_MIaPEeSMzJufh3GDGA" target="_BeJLGoaLEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJyBoaLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJyB4aLEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJyCIaLEeSMzJufh3GDGA" source="_BeGHg4aLEeSMzJufh3GDGA" target="_utXW8IaLEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJyCYaLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJyCoaLEeSMzJufh3GDGA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJyC4aLEeSMzJufh3GDGA" name="Approved" source="_utXW8IaLEeSMzJufh3GDGA" target="_mD--8IaOEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJyDIaLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJyDYaLEeSMzJufh3GDGA" name="proposalOK==true" content="proposalOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_9qCxoIaLEeSMzJufh3GDGA" name="proposalOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_9qCxoYaLEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJyDoaLEeSMzJufh3GDGA" name="Not Approved" source="_utXW8IaLEeSMzJufh3GDGA" target="_np8QIIaOEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJyD4aLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJyEIaLEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJyEYaLEeSMzJufh3GDGA" source="_BeJK7IaLEeSMzJufh3GDGA" target="_BeJx44aLEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJyEoaLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJyE4aLEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJyFIaLEeSMzJufh3GDGA" name="Approved" source="_BeJx44aLEeSMzJufh3GDGA" target="_1dRnsIaPEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJyFYaLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJyFoaLEeSMzJufh3GDGA" name="projectOK==true" content="projectOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_Tb24IIaMEeSMzJufh3GDGA" name="projectOK" dataType="_BeJyLYaLEeSMzJufh3GDGA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_Tb24IYaMEeSMzJufh3GDGA" name="false" content="false" returnType="java.lang.Boolean"/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJyF4aLEeSMzJufh3GDGA" name="Not approved" source="_BeJx44aLEeSMzJufh3GDGA" target="_0uz_MIaPEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJyGIaLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJyGYaLEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BeJyGoaLEeSMzJufh3GDGA" source="_JfAQoIaQEeSMzJufh3GDGA" target="_BeJLFYaLEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BeJyG4aLEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BeJyHIaLEeSMzJufh3GDGA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_BeJyHYaLEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_BeJyHoaLEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_BeJyH4aLEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_BeJyIIaLEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_BeJyIYaLEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_BeJyIoaLEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_BeJyI4aLEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_BeJyJIaLEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_BeJyJYaLEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_BeJyJoaLEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_BeJyJ4aLEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_BeJyKIaLEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_BeJyKYaLEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_BeJyKoaLEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_BeJyK4aLEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_BeJyLIaLEeSMzJufh3GDGA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_BeJyLYaLEeSMzJufh3GDGA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_BeJyLoaLEeSMzJufh3GDGA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_BeJyL4aLEeSMzJufh3GDGA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_BeJyMIaLEeSMzJufh3GDGA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_BeJyMYaLEeSMzJufh3GDGA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_BeJyMoaLEeSMzJufh3GDGA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_BeJyM4aLEeSMzJufh3GDGA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_BeJyNIaLEeSMzJufh3GDGA" name="XML"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_BeJyNYaLEeSMzJufh3GDGA" type="Process" element="_BeGHgIaLEeSMzJufh3GDGA" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_BeKY8IaLEeSMzJufh3GDGA" type="2007" element="_BeGHgYaLEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeKY8YaLEeSMzJufh3GDGA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_BeKY8oaLEeSMzJufh3GDGA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_BeKY84aLEeSMzJufh3GDGA" type="3007" element="_BeGHgoaLEeSMzJufh3GDGA">
          <children xmi:type="notation:DecorationNode" xmi:id="_BeKY9IaLEeSMzJufh3GDGA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_BeKY9YaLEeSMzJufh3GDGA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_BeKY9oaLEeSMzJufh3GDGA" type="3005" element="_BeGHg4aLEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BeKY94aLEeSMzJufh3GDGA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeKY-IaLEeSMzJufh3GDGA" x="119" y="165"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BeKY-YaLEeSMzJufh3GDGA" type="3002" element="_BeGHj4aLEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_BeKY-oaLEeSMzJufh3GDGA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_BeKY-4aLEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeKY_IaLEeSMzJufh3GDGA" x="40" y="179"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BeKZAIaLEeSMzJufh3GDGA" type="3005" element="_BeGHoIaLEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BeKZAYaLEeSMzJufh3GDGA" type="5005" element="_BeGHoIaLEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeKZAoaLEeSMzJufh3GDGA" x="421" y="102"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BeKZBoaLEeSMzJufh3GDGA" type="3005" element="_BeJK1IaLEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BeKZB4aLEeSMzJufh3GDGA" type="5005" element="_BeJK1IaLEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeKZCIaLEeSMzJufh3GDGA" x="913" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BeKZDIaLEeSMzJufh3GDGA" type="3005" element="_BeJK7IaLEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BeKZDYaLEeSMzJufh3GDGA" type="5005" element="_BeJK7IaLEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeKZDoaLEeSMzJufh3GDGA" x="556" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BeKZFYaLEeSMzJufh3GDGA" type="3062" element="_BeJLEIaLEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_BeKZFoaLEeSMzJufh3GDGA" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_BeKZF4aLEeSMzJufh3GDGA" x="-1" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeKZGIaLEeSMzJufh3GDGA" x="537" y="197"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BeKZGYaLEeSMzJufh3GDGA" type="3062" element="_BeJLFYaLEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_BeKZGoaLEeSMzJufh3GDGA" type="5090" element="_BeJLFYaLEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_BeKZG4aLEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeKZHIaLEeSMzJufh3GDGA" x="1221" y="136"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BeKZHYaLEeSMzJufh3GDGA" type="3062" element="_BeJLGoaLEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_BeKZHoaLEeSMzJufh3GDGA" type="5090" element="_BeJLGoaLEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_BeKZH4aLEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeKZIIaLEeSMzJufh3GDGA" x="1012" y="226"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BeKZJYaLEeSMzJufh3GDGA" type="3008" element="_BeJx44aLEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_BeKZJoaLEeSMzJufh3GDGA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_BeKZJ4aLEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeKZKIaLEeSMzJufh3GDGA" x="689" y="105" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_utYlEIaLEeSMzJufh3GDGA" type="3008" element="_utXW8IaLEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_utYlEoaLEeSMzJufh3GDGA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_utYlE4aLEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_utYlEYaLEeSMzJufh3GDGA" x="230" y="170" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mECpUIaOEeSMzJufh3GDGA" type="3027" element="_mD--8IaOEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mECpUoaOEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mECpUYaOEeSMzJufh3GDGA" x="271" y="95" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_np9eQIaOEeSMzJufh3GDGA" type="3027" element="_np8QIIaOEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_np9eQoaOEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_np9eQYaOEeSMzJufh3GDGA" x="347" y="187" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0u4QoIaPEeSMzJufh3GDGA" type="3027" element="_0uz_MIaPEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0u4QooaPEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0u4QoYaPEeSMzJufh3GDGA" x="765" y="192" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1dSOyIaPEeSMzJufh3GDGA" type="3027" element="_1dRnsIaPEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1dSOyoaPEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1dSOyYaPEeSMzJufh3GDGA" x="762" y="96" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JfA3uYaQEeSMzJufh3GDGA" type="3027" element="_JfAQoIaQEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JfA3u4aQEeSMzJufh3GDGA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JfA3uoaQEeSMzJufh3GDGA" x="1041" y="90" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_BeKZKYaLEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_BeKZKoaLEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_BeLAAIaLEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_BeLAAYaLEeSMzJufh3GDGA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeLAAoaLEeSMzJufh3GDGA" x="45" y="10" width="1372" height="302"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_BeLAA4aLEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLABIaLEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_BeLABYaLEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_BeLABoaLEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BeLAB4aLEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_BeLACIaLEeSMzJufh3GDGA"/>
    <edges xmi:type="notation:Connector" xmi:id="_BeLACYaLEeSMzJufh3GDGA" type="4001" element="_BeJx84aLEeSMzJufh3GDGA" source="_BeKY-YaLEeSMzJufh3GDGA" target="_BeKY9oaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLACoaLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLAC4aLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLADIaLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLADYaLEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLADoaLEeSMzJufh3GDGA" type="4001" element="_BeJx9oaLEeSMzJufh3GDGA" source="_mECpUIaOEeSMzJufh3GDGA" target="_BeKZAIaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLAD4aLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLAEIaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLAEYaLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLAEoaLEeSMzJufh3GDGA" points="[0, 1, -66, -7]$[16, 1, -50, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLAE4aLEeSMzJufh3GDGA" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLAFIaLEeSMzJufh3GDGA" type="4001" element="_BeJx-YaLEeSMzJufh3GDGA" source="_BeKZAIaLEeSMzJufh3GDGA" target="_BeKZDIaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLAFYaLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLAFoaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLAF4aLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLAGIaLEeSMzJufh3GDGA" points="[0, 0, -41, 91]$[-9, -91, -50, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLAGYaLEeSMzJufh3GDGA" id="(1.0,0.64)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLAGoaLEeSMzJufh3GDGA" type="4001" element="_BeJx_IaLEeSMzJufh3GDGA" source="_1dSOyIaPEeSMzJufh3GDGA" target="_BeKZBoaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLAG4aLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLAHIaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLAHYaLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLAHoaLEeSMzJufh3GDGA" points="[0, 0, -5, -60]$[55, 51, 50, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLAH4aLEeSMzJufh3GDGA" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLAIIaLEeSMzJufh3GDGA" type="4001" element="_BeJx_4aLEeSMzJufh3GDGA" source="_BeKZBoaLEeSMzJufh3GDGA" target="_JfA3uYaQEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLAIYaLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLAIoaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLAI4aLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLAJIaLEeSMzJufh3GDGA" points="[0, 0, -60, 48]$[65, -35, 5, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLAJYaLEeSMzJufh3GDGA" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLAJoaLEeSMzJufh3GDGA" id="(0.5583333333333333,0.7833333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLAJ4aLEeSMzJufh3GDGA" type="4001" element="_BeJyAoaLEeSMzJufh3GDGA" source="_np9eQIaOEeSMzJufh3GDGA" target="_BeKZFYaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLAKIaLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLAKYaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLAKoaLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLAK4aLEeSMzJufh3GDGA" points="[0, -8, -85, 2]$[78, 3, -7, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLALIaLEeSMzJufh3GDGA" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLALYaLEeSMzJufh3GDGA" type="4001" element="_BeJyBYaLEeSMzJufh3GDGA" source="_0u4QoIaPEeSMzJufh3GDGA" target="_BeKZHYaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLALoaLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLAL4aLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLAMIaLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLAMYaLEeSMzJufh3GDGA" points="[0, 0, -142, -15]$[135, 28, -7, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLAMoaLEeSMzJufh3GDGA" id="(1.0,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLAM4aLEeSMzJufh3GDGA" type="4001" element="_BeJyCIaLEeSMzJufh3GDGA" source="_BeKY9oaLEeSMzJufh3GDGA" target="_utYlEIaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLANIaLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLANYaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLANoaLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLAN4aLEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLAOIaLEeSMzJufh3GDGA" type="4001" element="_BeJyC4aLEeSMzJufh3GDGA" source="_utYlEIaLEeSMzJufh3GDGA" target="_mECpUIaOEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLAOYaLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLAOoaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLAO4aLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLAPIaLEeSMzJufh3GDGA" points="[-11, -22, -51, 47]$[42, -57, 2, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLAPYaLEeSMzJufh3GDGA" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLAPoaLEeSMzJufh3GDGA" id="(0.5333333333333333,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLAP4aLEeSMzJufh3GDGA" type="4001" element="_BeJyDoaLEeSMzJufh3GDGA" source="_utYlEIaLEeSMzJufh3GDGA" target="_np9eQIaOEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLnEIaLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLnEYaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLnEoaLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLnE4aLEeSMzJufh3GDGA" points="[-14, 1, -91, 0]$[52, -2, -25, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLnFIaLEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLnFYaLEeSMzJufh3GDGA" id="(0.20833333333333334,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLnFoaLEeSMzJufh3GDGA" type="4001" element="_BeJyEYaLEeSMzJufh3GDGA" source="_BeKZDIaLEeSMzJufh3GDGA" target="_BeKZJYaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLnF4aLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLnGIaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLnGYaLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLnGoaLEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLnG4aLEeSMzJufh3GDGA" id="(0.97,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLnHIaLEeSMzJufh3GDGA" type="4001" element="_BeJyFIaLEeSMzJufh3GDGA" source="_BeKZJYaLEeSMzJufh3GDGA" target="_1dSOyIaPEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLnHYaLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLnHoaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLnH4aLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLnIIaLEeSMzJufh3GDGA" points="[-11, -3, -65, 0]$[30, -1, -24, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLnIYaLEeSMzJufh3GDGA" id="(1.0,0.813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLnIoaLEeSMzJufh3GDGA" id="(0.025,0.18333333333333332)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLnI4aLEeSMzJufh3GDGA" type="4001" element="_BeJyF4aLEeSMzJufh3GDGA" source="_BeKZJYaLEeSMzJufh3GDGA" target="_0u4QoIaPEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLnJIaLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLnJYaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLnJoaLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLnJ4aLEeSMzJufh3GDGA" points="[-4, -10, -40, -95]$[33, 84, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLnKIaLEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLnKYaLEeSMzJufh3GDGA" id="(0.025,0.4166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BeLnKoaLEeSMzJufh3GDGA" type="4001" element="_BeJyGoaLEeSMzJufh3GDGA" source="_JfA3uYaQEeSMzJufh3GDGA" target="_BeKZGYaLEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BeLnK4aLEeSMzJufh3GDGA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BeLnLIaLEeSMzJufh3GDGA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BeLnLYaLEeSMzJufh3GDGA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BeLnLoaLEeSMzJufh3GDGA" points="[0, 0, -75, -29]$[72, 14, -3, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BeLnL4aLEeSMzJufh3GDGA" id="(1.0,0.5333333333333333)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_iVxSsIaMEeSMzJufh3GDGA" type="Form" element="_iVjQQIaMEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_iXVY8IaMEeSMzJufh3GDGA" type="2120" element="_iVjQQYaMEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_iXWAAIaMEeSMzJufh3GDGA" type="5157"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iXVY8YaMEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_iXWAAYaMEeSMzJufh3GDGA" type="2126" element="_iVjQbYaMEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_iXWnEIaMEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_iXWAAoaMEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_iXWAA4aMEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_iXWABIaMEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iXWABYaMEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_sdaREIaMEeSMzJufh3GDGA" type="2131" element="_sdX00IaMEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_sda4IYaMEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sda4IIaMEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_iVxSsYaMEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_Qn9iQIaOEeSMzJufh3GDGA" type="Form" element="_Qn534IaOEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_QoNZ44aOEeSMzJufh3GDGA" type="2130" element="_Qn54EYaOEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_QoOA8IaOEeSMzJufh3GDGA" type="5148"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QoNZ5IaOEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_QoOA8YaOEeSMzJufh3GDGA" type="2126" element="_Qn6fHYaOEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_QoOA9oaOEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_QoOA8oaOEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_QoOA84aOEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_QoOA9IaOEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QoOA9YaOEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_TMwaQIaOEeSMzJufh3GDGA" type="2131" element="_TMvMIIaOEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_TMwaQoaOEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TMwaQYaOEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Qn9iQYaOEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_sUgh0IaOEeSMzJufh3GDGA" type="Form" element="_sUc3cIaOEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_sUsIAIaOEeSMzJufh3GDGA" type="2120" element="_sUc3cYaOEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_sUsvEIaOEeSMzJufh3GDGA" type="5157"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sUsIAYaOEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_sUsvFIaOEeSMzJufh3GDGA" type="2126" element="_sUde0YaOEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_sUsvGYaOEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_sUsvFYaOEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_sUsvFoaOEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_sUsvF4aOEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sUsvGIaOEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_4oFMTIaOEeSMzJufh3GDGA" type="2131" element="_4oElMIaOEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_4oFzUIaOEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4oFMTYaOEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_sUgh0YaOEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_e5BXoIaPEeSMzJufh3GDGA" type="Form" element="_e474EIaPEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_e5RPQ4aPEeSMzJufh3GDGA" type="2130" element="_e48fMoaPEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_e5RPRYaPEeSMzJufh3GDGA" type="5148"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_e5RPRIaPEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_e5R2U4aPEeSMzJufh3GDGA" type="2126" element="_e49GN4aPEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_e5R2WIaPEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_e5R2VIaPEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_e5R2VYaPEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_e5R2VoaPEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_e5R2V4aPEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_gqrigIaPEeSMzJufh3GDGA" type="2131" element="_gqqUYIaPEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_gqrigoaPEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gqrigYaPEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_mKTz8IaPEeSMzJufh3GDGA" type="2131" element="_mKTM4IaPEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_mKTz8oaPEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mKTz8YaPEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_e5BXoYaPEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_4FLeEIaPEeSMzJufh3GDGA" type="Form" element="_4FKP8IaPEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_4FXrUIaPEeSMzJufh3GDGA" type="2126" element="_4FKP8YaPEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_4FYSYIaPEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_4FXrUYaPEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_4FXrUoaPEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_4FXrU4aPEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4FXrVIaPEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_8no8oIaPEeSMzJufh3GDGA" type="2131" element="_8nnugIaPEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_8npjsIaPEeSMzJufh3GDGA" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8no8oYaPEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_4FLeEYaPEeSMzJufh3GDGA"/>
  </notation:Diagram>
</xmi:XMI>
