<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process">
  <process:MainProcess xmi:id="_AhxLsIaXEeSMzJufh3GDGA" name="Projet_Validation_Diagram_CORTES_MARTINEZ" version="6.0" author="corteshs" bonitaVersion="6.3.8" bonitaModelVersion="6.3.8-001" configId="ACED000574003750726F6A65745F56616C69646174696F6E5F4469616772616D5F434F525445535F4D415254494E455A362E332E382D303031362E332E38">
    <elements xmi:type="process:Pool" xmi:id="_AhxLsYaXEeSMzJufh3GDGA" name="Projet_Validation_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="6.0">
      <elements xmi:type="process:Lane" xmi:id="_AhxLsoaXEeSMzJufh3GDGA" name="Employé (lane)" actor="_AhxzfoaXEeSMzJufh3GDGA">
        <elements xmi:type="process:Task" xmi:id="_AhxLs4aXEeSMzJufh3GDGA" name="Approve proposal" outgoing="_AhxzXIaXEeSMzJufh3GDGA" incoming="_AhxzR4aXEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVhcY5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVhcZJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVhcZZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVhcZpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxLuIaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_pViqipXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pViqi5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_AhxLu4aXEeSMzJufh3GDGA" name="BoundaryTimerEvent" outgoing="_AhxzdYaXEeSMzJufh3GDGA">
            <condition xmi:type="expression:Expression" xmi:id="_pViqmpXdEeSroeU30tgKmw" name="5 Jours 00:00:00" content="432000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long">
              <referencedElements xmi:type="process:Data" xmi:id="_pViqm5XdEeSroeU30tgKmw" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA"/>
            </condition>
          </BoundaryIntermediateEvents>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pVhcaZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pVhcapXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_AhxLwYaXEeSMzJufh3GDGA" name="ApproveProposal" nLine="3">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_AhxLwoaXEeSMzJufh3GDGA" name="proposalOK1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxLw4aXEeSMzJufh3GDGA" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_pVjRo5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_pVjRpJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_pVjRpZXdEeSroeU30tgKmw" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_pVjRppXdEeSroeU30tgKmw" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_pVjRp5XdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_pVjRqJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_pVjRqZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_pVjRqpXdEeSroeU30tgKmw" name="Approved?" content="Approved?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVjRq5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_AhxLyoaXEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_pVj4qpXdEeSroeU30tgKmw" name="proposalOK" content="proposalOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="_pVkfsJXdEeSroeU30tgKmw" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_pVkfsZXdEeSroeU30tgKmw" name="field_proposalOK1" content="field_proposalOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_pVkfspXdEeSroeU30tgKmw" name="proposalOK1"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_AhxLzoaXEeSMzJufh3GDGA" type="ASSIGNMENT"/>
              </action>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_pVjRrZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_pVjRrpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_pVjRr5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_pVjRsJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_pVjRsZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_pVjRspXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_pVjRs5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_AhxL8oaXEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVmU4JXdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_pVmU4ZXdEeSroeU30tgKmw" name="OK" content="OK" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVmU4pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_AhxL9oaXEeSMzJufh3GDGA" name="proposal1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVp_QJXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_pVp_QZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_pVrNYJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_pVrNYZXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_pVrNYpXdEeSroeU30tgKmw" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_pVrNY5XdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_pVrNZJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_pVrNZZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVrNZpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_pVjRkZXdEeSroeU30tgKmw" name="Approve proposal" content="Approve proposal" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pVhcbJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_pVhcbZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_AhxMBIaXEeSMzJufh3GDGA" name="Proposal made" outgoing="_AhxzR4aXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVuQ05XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVuQ1JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVuQ1ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVuQ1pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AhxMCYaXEeSMzJufh3GDGA" name="Analyze Impact" outgoing="_AhxzTYaXEeSMzJufh3GDGA" incoming="_AhxzSoaXEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDcJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pViDcZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pViDcpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pViDc5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxMDoaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_pViqjJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pViqjZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pViDdZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pViDdpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_AhxME4aXEeSMzJufh3GDGA" name="AnalyzeImpact" nLine="3">
            <widgets xmi:type="form:TextFormField" xmi:id="_AhxMFIaXEeSMzJufh3GDGA" name="impacts1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVu3wZXdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_pVu3wpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_pVu3w5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_pVu3xJXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_pVu3xZXdEeSroeU30tgKmw" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_pVu3xpXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_pVu3x5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_pVu3yJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_pVu3yZXdEeSroeU30tgKmw" name="Impact?" content="Impact?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVu3ypXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_pVu3y5XdEeSroeU30tgKmw">
                <leftOperand xmi:type="expression:Expression" xmi:id="_pVu3zJXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                  <referencedElements xmi:type="process:Data" xmi:id="_pVu3zZXdEeSroeU30tgKmw" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_pVu3zpXdEeSroeU30tgKmw" name="field_impacts1" content="field_impacts1" type="TYPE_INPUT">
                  <referencedElements xmi:type="form:TextFormField" xmi:id="_hVIef5XdEeSroeU30tgKmw" name="impacts1"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_pVu30JXdEeSroeU30tgKmw" type="ASSIGNMENT"/>
              </action>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_pVu30ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_pVu30pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_pVve0JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_pVve0ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_pVve0pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_pVve05XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_pVve1JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_AhxMRIaXEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVmU45XdEeSroeU30tgKmw" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_pVmU5JXdEeSroeU30tgKmw" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVmU5ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_AhxMSIaXEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMSYaXEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMSoaXEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVtpopXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_pVtpo5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_pVtppJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_pVtppZXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_pVtpppXdEeSroeU30tgKmw" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_pVtpp5XdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_pVtpqJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_pVtpqZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVtpqpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_pVjRlZXdEeSroeU30tgKmw" name="Analyze Impact" content="Analyze Impact" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDeJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_pViDeZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AhxMWIaXEeSMzJufh3GDGA" name="Validate project" outgoing="_AhxzZ4aXEeSMzJufh3GDGA" incoming="_AhxzTYaXEeSMzJufh3GDGA" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDepXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pViDe5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pViDfJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pViDfZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxMXYaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_pViqjpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pViqj5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_AhxMYIaXEeSMzJufh3GDGA" documentation="&#x9;&#x9;&#x9;" name="NonInterruptingBoundaryTimerEvent" outgoing="_AhxzeIaXEeSMzJufh3GDGA">
            <condition xmi:type="expression:Expression" xmi:id="_pVve65XdEeSroeU30tgKmw" name="4 Jours 00:00:00" content="345600000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pViDgJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pViDgZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_AhxMZIaXEeSMzJufh3GDGA" name="ValidateProject">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_AhxMZYaXEeSMzJufh3GDGA" name="projectOK1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_AhxMZoaXEeSMzJufh3GDGA" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_pVjRtZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_pVjRtpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_pVjRt5XdEeSroeU30tgKmw" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_pVjRuJXdEeSroeU30tgKmw" name="projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_pVjRuZXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_pVjRupXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_pVjRu5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_pVj4oJXdEeSroeU30tgKmw" name="Approve project?" content="Approve project?" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVj4oZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_AhxMbYaXEeSMzJufh3GDGA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_pVkftJXdEeSroeU30tgKmw" name="projectOK" content="projectOK" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="_pVkftZXdEeSroeU30tgKmw" name="projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_pVkftpXdEeSroeU30tgKmw" name="field_projectOK1" content="field_projectOK1" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_pVkft5XdEeSroeU30tgKmw" name="projectOK1"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_AhxMcYaXEeSMzJufh3GDGA" type="ASSIGNMENT"/>
              </action>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_pVj4o5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_pVj4pJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_pVj4pZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_pVj4ppXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_pVj4p5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_pVj4qJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_pVj4qZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_AhxMlYaXEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVmU5pXdEeSroeU30tgKmw" line="3"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_pVmU55XdEeSroeU30tgKmw" name="Save" content="Save" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVmU6JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_AhxMmYaXEeSMzJufh3GDGA" name="proposal1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMmoaXEeSMzJufh3GDGA" key="input_css:color" value="purple"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMm4aXEeSMzJufh3GDGA" key="input_css:font-size" value="31px"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMnIaXEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVtprpXdEeSroeU30tgKmw"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_pVtpr5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_pVtpsJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_pVtpsZXdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_pVtpspXdEeSroeU30tgKmw" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_pVtps5XdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_pVtptJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_pVtptZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVtptpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_AhxMp4aXEeSMzJufh3GDGA" name="impacts1">
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMqIaXEeSMzJufh3GDGA" key="input_css:color" value="red"/>
              <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxMqYaXEeSMzJufh3GDGA" key="input_css:font-size" value="18px"/>
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVtpuZXdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_pVuQsJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_pVuQsZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_pVuQspXdEeSroeU30tgKmw" name="impacts" content="impacts" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_pVuQs5XdEeSroeU30tgKmw" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA"/>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_pVuQtJXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_pVuQtZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_pVuQtpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVuQt5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_pVjRmpXdEeSroeU30tgKmw" name="Validate project" content="Validate project" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDg5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_pViDhJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_AhxMt4aXEeSMzJufh3GDGA" name="Proposal refused" incoming="_AhxzVoaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVve7JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVve7ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVwF4JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVwF4ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_AhxMvIaXEeSMzJufh3GDGA" name="Project finished" incoming="_AhxzcoaXEeSMzJufh3GDGA _83WS8IaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVws8JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVws8ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVws8pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVws85XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_AhxMwYaXEeSMzJufh3GDGA" name="Project refused" incoming="_AhxzWYaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVws9JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVws9ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVws9pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVws95XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_AhxMxoaXEeSMzJufh3GDGA" name="Project approval?" outgoing="_AhxzaoaXEeSMzJufh3GDGA _Ahxzb4aXEeSMzJufh3GDGA" incoming="_AhxzZ4aXEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVws_JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVws_ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVws_pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVws_5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_AhxMy4aXEeSMzJufh3GDGA" name="5 days?" outgoing="_AhxzX4aXEeSMzJufh3GDGA _AhxzZIaXEeSMzJufh3GDGA" incoming="_AhxzXIaXEeSMzJufh3GDGA" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVwtAJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVwtAZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVwtApXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVwtA5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxM0IaXEeSMzJufh3GDGA" name="Notify proposal aproved" outgoing="_AhxzSoaXEeSMzJufh3GDGA" incoming="_AhxzX4aXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVwtBJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVwtBZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVwtBpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVwtB5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_pVwtCJXdEeSroeU30tgKmw">
            <cardinality xmi:type="expression:Expression" xmi:id="_pVwtCZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pVwtCpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pVwtC5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pVxUAJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxM2oaXEeSMzJufh3GDGA" name="Notify proposal refusal" outgoing="_AhxzVoaXEeSMzJufh3GDGA" incoming="_AhxzZIaXEeSMzJufh3GDGA _AhxzdYaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVxUAZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVxUApXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVxUA5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVxUBJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_pVxUBZXdEeSroeU30tgKmw">
            <cardinality xmi:type="expression:Expression" xmi:id="_pVxUBpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pVxUB5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pVxUCJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pVxUCZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxM5IaXEeSMzJufh3GDGA" name="Notify project refused" outgoing="_AhxzWYaXEeSMzJufh3GDGA" incoming="_Ahxzb4aXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVxUCpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVxUC5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVxUDJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVxUDZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_pVxUDpXdEeSroeU30tgKmw">
            <cardinality xmi:type="expression:Expression" xmi:id="_pVxUD5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pVxUEJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pVxUEZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pVxUEpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxM7oaXEeSMzJufh3GDGA" name="Notify project accepted" outgoing="_AhxzUIaXEeSMzJufh3GDGA" incoming="_AhxzaoaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVxUE5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVxUFJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVxUFZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVxUFpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_pVxUF5XdEeSroeU30tgKmw">
            <cardinality xmi:type="expression:Expression" xmi:id="_pVxUGJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pVxUGZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pVxUGpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pVxUG5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxM-IaXEeSMzJufh3GDGA" name="Notify project delivery" outgoing="_AhxzcoaXEeSMzJufh3GDGA" incoming="_AhxzU4aXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVxUHJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVxUHZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVxUHpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVxUH5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Ol28EIaYEeSMzJufh3GDGA" name="Send Email on Project Delivery" definitionId="email" event="ON_ENTER" throwErrorEvent="true" namedError="Send email error" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_pVx7IJXdEeSroeU30tgKmw" definitionId="email" version="1.0.0">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7IZXdEeSroeU30tgKmw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7IpXdEeSroeU30tgKmw" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7I5XdEeSroeU30tgKmw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7JJXdEeSroeU30tgKmw" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7JZXdEeSroeU30tgKmw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7JpXdEeSroeU30tgKmw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7J5XdEeSroeU30tgKmw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7KJXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7KZXdEeSroeU30tgKmw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7KpXdEeSroeU30tgKmw" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7K5XdEeSroeU30tgKmw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7LJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7LZXdEeSroeU30tgKmw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7LpXdEeSroeU30tgKmw" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7L5XdEeSroeU30tgKmw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7MJXdEeSroeU30tgKmw" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7MZXdEeSroeU30tgKmw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7MpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7M5XdEeSroeU30tgKmw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7NJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7NZXdEeSroeU30tgKmw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7NpXdEeSroeU30tgKmw" name="Project Delivered " content="Project Delivered " returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7N5XdEeSroeU30tgKmw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7OJXdEeSroeU30tgKmw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7OZXdEeSroeU30tgKmw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7OpXdEeSroeU30tgKmw" name="&lt;pattern-expression>" content="Bah oui, Project ${proposal} delivered&#xA;Thanks" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_pVx7O5XdEeSroeU30tgKmw" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7PJXdEeSroeU30tgKmw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_pVx7PZXdEeSroeU30tgKmw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7PpXdEeSroeU30tgKmw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7P5XdEeSroeU30tgKmw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7QJXdEeSroeU30tgKmw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7QZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7QpXdEeSroeU30tgKmw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_pVx7Q5XdEeSroeU30tgKmw"/>
              </parameters>
            </configuration>
          </connectors>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_pVx7EJXdEeSroeU30tgKmw">
            <cardinality xmi:type="expression:Expression" xmi:id="_pVx7EZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pVx7EpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <BoundaryIntermediateEvents xmi:type="process:IntermediateErrorCatchEvent" xmi:id="_uY4eQIaXEeSMzJufh3GDGA" name="Email Error" outgoing="_3s8qoIaXEeSMzJufh3GDGA" errorCode="Send email error"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pVx7FJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pVx7FZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_AhxNAoaXEeSMzJufh3GDGA" name="Do project" outgoing="_AhxzU4aXEeSMzJufh3GDGA" incoming="_AhxzUIaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVx7aZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVx7apXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVx7a5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVx7bJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_pVx7bZXdEeSroeU30tgKmw">
            <cardinality xmi:type="expression:Expression" xmi:id="_pVx7bpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pVx7b5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pVx7cJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pVx7cZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_AhxNDIaXEeSMzJufh3GDGA" processSource="_pVcj7ZXdEeSroeU30tgKmw" subprocessTarget="sub_proposal"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_AhxNDYaXEeSMzJufh3GDGA" processSource="_pVgOQZXdEeSroeU30tgKmw" subprocessTarget="sub_proposalOK"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_AhxNDoaXEeSMzJufh3GDGA" processSource="_pVgOQ5XdEeSroeU30tgKmw" subprocessTarget="sub_projectOK"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_AhxND4aXEeSMzJufh3GDGA" processSource="_pVgORZXdEeSroeU30tgKmw" subprocessTarget="sub_impacts"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_AhxNEIaXEeSMzJufh3GDGA" subprocessSource="sub_proposal" processTarget="_pVcj7ZXdEeSroeU30tgKmw"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_AhxNEYaXEeSMzJufh3GDGA" subprocessSource="sub_proposalOK" processTarget="_pVgOQZXdEeSroeU30tgKmw"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_AhxNEoaXEeSMzJufh3GDGA" subprocessSource="sub_projectOK" processTarget="_pVgOQ5XdEeSroeU30tgKmw"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_AhxNE4aXEeSMzJufh3GDGA" subprocessSource="sub_impacts" processTarget="_pVgORZXdEeSroeU30tgKmw"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_pVx7epXdEeSroeU30tgKmw" name="Do_project_CORTES_MARTINEZ" content="Do_project_CORTES_MARTINEZ" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_pVx7e5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AhxNFoaXEeSMzJufh3GDGA" name="Notify Delay" outgoing="_Ahxze4aXEeSMzJufh3GDGA" incoming="_AhxzeIaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVx7FpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVx7F5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVx7GJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVx7GZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_AhxywYaXEeSMzJufh3GDGA" name="Connecteur Mail - Delay" definitionId="email" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_pVx7RJXdEeSroeU30tgKmw" definitionId="email" version="1.0.0">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7RZXdEeSroeU30tgKmw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7RpXdEeSroeU30tgKmw" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7R5XdEeSroeU30tgKmw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7SJXdEeSroeU30tgKmw" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7SZXdEeSroeU30tgKmw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7SpXdEeSroeU30tgKmw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7S5XdEeSroeU30tgKmw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7TJXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7TZXdEeSroeU30tgKmw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7TpXdEeSroeU30tgKmw" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7T5XdEeSroeU30tgKmw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7UJXdEeSroeU30tgKmw" name="nbvcxwmlkj" content="nbvcxwmlkj" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7UZXdEeSroeU30tgKmw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7UpXdEeSroeU30tgKmw" name="sicpensimag@gmail.com" content="sicpensimag@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7U5XdEeSroeU30tgKmw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7VJXdEeSroeU30tgKmw" name="sacortesh@gmail.com" content="sacortesh@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7VZXdEeSroeU30tgKmw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7VpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7V5XdEeSroeU30tgKmw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7WJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7WZXdEeSroeU30tgKmw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7WpXdEeSroeU30tgKmw" name="Test" content="Test" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7W5XdEeSroeU30tgKmw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7XJXdEeSroeU30tgKmw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7XZXdEeSroeU30tgKmw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7XpXdEeSroeU30tgKmw" name="&lt;pattern-expression>" content="${impacts}&#xA;${proposal}&#xA;Gracias" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_pVx7X5XdEeSroeU30tgKmw" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA"/>
                  <referencedElements xmi:type="process:Data" xmi:id="_pVx7YJXdEeSroeU30tgKmw" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7YZXdEeSroeU30tgKmw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_pVx7YpXdEeSroeU30tgKmw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7Y5XdEeSroeU30tgKmw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7ZJXdEeSroeU30tgKmw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7ZZXdEeSroeU30tgKmw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_pVx7ZpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pVx7Z5XdEeSroeU30tgKmw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_pVx7aJXdEeSroeU30tgKmw"/>
              </parameters>
            </configuration>
          </connectors>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_pVx7G5XdEeSroeU30tgKmw">
            <cardinality xmi:type="expression:Expression" xmi:id="_pVx7HJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pVx7HZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pVx7HpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pVx7H5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Ahxy7oaXEeSMzJufh3GDGA" name="Notification Done" incoming="_Ahxze4aXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVyiIJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVyiIZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVyiIpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVyiI5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4_iT4IaXEeSMzJufh3GDGA" name="Notify project delivery by form" outgoing="_83WS8IaXEeSMzJufh3GDGA" incoming="_3s8qoIaXEeSMzJufh3GDGA" overrideActorsOfTheLane="false" priority="4">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDhZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pViDhpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pViDh5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pViDiJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_3s189oaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_pViqkJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pViqkZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pViDipXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pViDi5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_CO9Q0IaYEeSMzJufh3GDGA" name="NotifyProjectDeliveryByForm" nLine="3">
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_CO9Q0YaYEeSMzJufh3GDGA" name="Soumettre1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVmU6ZXdEeSroeU30tgKmw" line="2"/>
              <tooltip xmi:type="expression:Expression" xmi:id="_pVmU6pXdEeSroeU30tgKmw" content=""/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_pVm78JXdEeSroeU30tgKmw" name="Ok" content="Ok" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVm78ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_IIvHoIaYEeSMzJufh3GDGA" name="Message1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVuQuJXdEeSroeU30tgKmw" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_pVuQuZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_pVuQupXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_pVuQu5XdEeSroeU30tgKmw" name="Save Yoko Ono, Deliver the message" content="Save Yoko Ono, Deliver the message"/>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_pVuQvJXdEeSroeU30tgKmw" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_pVuQvZXdEeSroeU30tgKmw" name="Save Yoko Ono, Deliver the message" content="Save Yoko Ono, Deliver the message" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_pVuQvpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_pVuQv5XdEeSroeU30tgKmw" name="Message1" content="Message1" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVuQwJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_pVuQwZXdEeSroeU30tgKmw">
                <leftOperand xmi:type="expression:Expression" xmi:id="_pVuQwpXdEeSroeU30tgKmw"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_pVuQw5XdEeSroeU30tgKmw"/>
                <operator xmi:type="expression:Operator" xmi:id="_pVuQxJXdEeSroeU30tgKmw" type="ASSIGNMENT" expression="="/>
              </action>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_pVjRnZXdEeSroeU30tgKmw" name="Notify project delivery by form" content="Notify project delivery by form" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDjZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_pViDjpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_Al-9UIaXEeSMzJufh3GDGA" path="_AhxLsYaXEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_pVcj55XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_pVcj6JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxy9oaXEeSMzJufh3GDGA" path="_AhxLsYaXEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxy94aXEeSMzJufh3GDGA" path="_AhxLsYaXEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxy-IaXEeSMzJufh3GDGA" path="_AhxLsYaXEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxy-YaXEeSMzJufh3GDGA" path="_AhxLsYaXEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_pVcj7ZXdEeSroeU30tgKmw" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pVgOQJXdEeSroeU30tgKmw" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_pVgOQZXdEeSroeU30tgKmw" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pVgOQpXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_pVgOQ5XdEeSroeU30tgKmw" name="projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pVgORJXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_pVgORZXdEeSroeU30tgKmw" name="impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pVgORpXdEeSroeU30tgKmw" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <form xmi:type="form:Form" xmi:id="_AhxzAoaXEeSMzJufh3GDGA" name="Project_Validation_CORTES_MARTINEZ" nLine="3">
        <widgets xmi:type="form:TextFormField" xmi:id="_AhxzA4aXEeSMzJufh3GDGA" name="proposal1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVve1ZXdEeSroeU30tgKmw" line="1"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_pVve1pXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_pVve15XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_pVve2JXdEeSroeU30tgKmw" name="" content=""/>
          <afterEventExpression xmi:type="expression:Expression" xmi:id="_pVve2ZXdEeSroeU30tgKmw" name="" content=""/>
          <tooltip xmi:type="expression:Expression" xmi:id="_pVve2pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:type="expression:Expression" xmi:id="_pVve25XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_pVve3JXdEeSroeU30tgKmw" name="Proposal" content="Proposal" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVve3ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <action xmi:type="expression:Operation" xmi:id="_pVve3pXdEeSroeU30tgKmw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pVve35XdEeSroeU30tgKmw" name="proposal" content="proposal" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_pVve4JXdEeSroeU30tgKmw" name="proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pVve4ZXdEeSroeU30tgKmw" name="field_proposal1" content="field_proposal1" type="TYPE_INPUT">
              <referencedElements xmi:type="form:TextFormField" xmi:id="_hVJFgpXdEeSroeU30tgKmw" name="proposal1"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pVve45XdEeSroeU30tgKmw" type="ASSIGNMENT"/>
          </action>
          <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_pVve5JXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_pVve5ZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_pVve5pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <tooltipForAdd xmi:type="expression:Expression" xmi:id="_pVve55XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_pVve6JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <tooltipForRemove xmi:type="expression:Expression" xmi:id="_pVve6ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <exampleMessage xmi:type="expression:Expression" xmi:id="_pVve6pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </widgets>
        <widgets xmi:type="form:SubmitFormButton" xmi:id="_AhxzL4aXEeSMzJufh3GDGA" name="Soumettre1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVnjAJXdEeSroeU30tgKmw" line="2"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_pVnjAZXdEeSroeU30tgKmw" name="OK" content="OK" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVnjApXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <widgets xmi:type="form:MessageInfo" xmi:id="_AhxzM4aXEeSMzJufh3GDGA" name="Enter proposal:">
          <htmlAttributes xmi:type="ecore:EStringToStringMapEntry" xmi:id="_AhxzNIaXEeSMzJufh3GDGA" key="input_css:text-bold" value="enabled"/>
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_pVuQxpXdEeSroeU30tgKmw"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_pVuQx5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_pVuQyJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_pVuQyZXdEeSroeU30tgKmw" name="" content=""/>
          <afterEventExpression xmi:type="expression:Expression" xmi:id="_pVuQypXdEeSroeU30tgKmw" name="" content=""/>
          <tooltip xmi:type="expression:Expression" xmi:id="_pVuQy5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:type="expression:Expression" xmi:id="_pVuQzJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_pVuQzZXdEeSroeU30tgKmw" name="Message1" content="Message1" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_pVuQzpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <action xmi:type="expression:Operation" xmi:id="_pVuQz5XdEeSroeU30tgKmw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pVuQ0JXdEeSroeU30tgKmw"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pVuQ0ZXdEeSroeU30tgKmw"/>
            <operator xmi:type="expression:Operator" xmi:id="_pVuQ0pXdEeSroeU30tgKmw" type="ASSIGNMENT" expression="="/>
          </action>
        </widgets>
        <pageLabel xmi:type="expression:Expression" xmi:id="_pVjRoZXdEeSroeU30tgKmw" name="Propose proposal" content="Propose proposal" returnTypeFixed="true"/>
      </form>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pVgOSJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_pVgOSZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVgOSpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVgOS5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzR4aXEeSMzJufh3GDGA" target="_AhxLs4aXEeSMzJufh3GDGA" source="_AhxMBIaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzSIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiJZXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzSoaXEeSMzJufh3GDGA" target="_AhxMCYaXEeSMzJufh3GDGA" source="_AhxM0IaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzS4aXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiJ5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzTYaXEeSMzJufh3GDGA" target="_AhxMWIaXEeSMzJufh3GDGA" source="_AhxMCYaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzToaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiKZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzUIaXEeSMzJufh3GDGA" target="_AhxNAoaXEeSMzJufh3GDGA" source="_AhxM7oaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzUYaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiK5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzU4aXEeSMzJufh3GDGA" target="_AhxM-IaXEeSMzJufh3GDGA" source="_AhxNAoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzVIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiLZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzVoaXEeSMzJufh3GDGA" target="_AhxMt4aXEeSMzJufh3GDGA" source="_AhxM2oaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzV4aXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiL5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzWYaXEeSMzJufh3GDGA" target="_AhxMwYaXEeSMzJufh3GDGA" source="_AhxM5IaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzWoaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiMZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzXIaXEeSMzJufh3GDGA" target="_AhxMy4aXEeSMzJufh3GDGA" source="_AhxLs4aXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzXYaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiM5XdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzX4aXEeSMzJufh3GDGA" name="Approved" target="_AhxM0IaXEeSMzJufh3GDGA" source="_AhxMy4aXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzYIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiNZXdEeSroeU30tgKmw" name="proposalOK==true" content="proposalOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_pVyiNpXdEeSroeU30tgKmw" name="proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzZIaXEeSMzJufh3GDGA" name="Not Approved" target="_AhxM2oaXEeSMzJufh3GDGA" source="_AhxMy4aXEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzZYaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiOJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzZ4aXEeSMzJufh3GDGA" target="_AhxMxoaXEeSMzJufh3GDGA" source="_AhxMWIaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzaIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiOpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzaoaXEeSMzJufh3GDGA" name="Approved" target="_AhxM7oaXEeSMzJufh3GDGA" source="_AhxMxoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxza4aXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiPJXdEeSroeU30tgKmw" name="projectOK==true" content="projectOK==true" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_pVyiPZXdEeSroeU30tgKmw" name="projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxzb4aXEeSMzJufh3GDGA" name="Not approved" target="_AhxM5IaXEeSMzJufh3GDGA" source="_AhxMxoaXEeSMzJufh3GDGA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzcIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiP5XdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzcoaXEeSMzJufh3GDGA" target="_AhxMvIaXEeSMzJufh3GDGA" source="_AhxM-IaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxzc4aXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiQZXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzdYaXEeSMzJufh3GDGA" target="_AhxM2oaXEeSMzJufh3GDGA" source="_AhxLu4aXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzdoaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiQ5XdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AhxzeIaXEeSMzJufh3GDGA" target="_AhxNFoaXEeSMzJufh3GDGA" source="_AhxMYIaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzeYaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiRZXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxze4aXEeSMzJufh3GDGA" target="_Ahxy7oaXEeSMzJufh3GDGA" source="_AhxNFoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AhxzfIaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiR5XdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3s8qoIaXEeSMzJufh3GDGA" target="_4_iT4IaXEeSMzJufh3GDGA" source="_uY4eQIaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3s8qoYaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiSZXdEeSroeU30tgKmw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_83WS8IaXEeSMzJufh3GDGA" target="_AhxMvIaXEeSMzJufh3GDGA" source="_4_iT4IaXEeSMzJufh3GDGA">
        <expression xmi:type="expression:Expression" xmi:id="_pVyiSpXdEeSroeU30tgKmw" content=""/>
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_83WS8YaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiTJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_AhxzfoaXEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxzf4aXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_pVzJNZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pVzJNpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AhxzgoaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_pVzJN5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pVzwQJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AhxzhYaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_pV0XUJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pV0XUZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AhxziIaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_pV0XUpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pV0XU5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxzi4aXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_pV0XVJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pV0XVZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_AhxzjoaXEeSMzJufh3GDGA" name="Do_project_CORTES_MARTINEZ" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="4.0">
      <elements xmi:type="process:Lane" xmi:id="_Ahxzj4aXEeSMzJufh3GDGA" name="Research and Development" actor="_Ahxz7IaXEeSMzJufh3GDGA">
        <elements xmi:type="process:Task" xmi:id="_AhxzkIaXEeSMzJufh3GDGA" name="Deploy" outgoing="_Ahxz6YaXEeSMzJufh3GDGA" incoming="_Ahxz5oaXEeSMzJufh3GDGA" actor="_Ahxz7IaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDj5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pViDkJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pViDkZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pViDkpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_AhxzlYaXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_pViqkpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pViqk5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pViDlJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pViDlZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDlpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_pViDl5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_AhxznIaXEeSMzJufh3GDGA" name="Start project" outgoing="_Ahxz3YaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVuQ15XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVuQ2JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVuQ2ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVu3wJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_AhxzoYaXEeSMzJufh3GDGA" name="Project finished" incoming="_Ahxz6YaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVws-JXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVws-ZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVws-pXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVws-5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AhxzpoaXEeSMzJufh3GDGA" name="Specify" outgoing="_Ahxz4IaXEeSMzJufh3GDGA" incoming="_Ahxz3YaXEeSMzJufh3GDGA" actor="_Ahxz7IaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDmJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pViDmZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pViDmpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pViDm5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_Ahxzq4aXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_pViqlJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pViqlZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pViDnZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pViDnpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDn5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_pViDoJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AhxzsoaXEeSMzJufh3GDGA" name="Implement" outgoing="_Ahxz44aXEeSMzJufh3GDGA" incoming="_Ahxz4IaXEeSMzJufh3GDGA" actor="_Ahxz7IaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDoZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pViDopXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pViDo5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pViDpJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_Ahxzt4aXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_pViqlpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pViql5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pViDppXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pViDp5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pViDqJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_pViqgJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AhxzvoaXEeSMzJufh3GDGA" name="Test" outgoing="_Ahxz5oaXEeSMzJufh3GDGA" incoming="_Ahxz44aXEeSMzJufh3GDGA" actor="_Ahxz7IaXEeSMzJufh3GDGA">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pViqgZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pViqgpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pViqg5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pViqhJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_Ahxzw4aXEeSMzJufh3GDGA">
            <cardinality xmi:type="expression:Expression" xmi:id="_pViqmJXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_pViqmZXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pViqhpXdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pViqh5XdEeSroeU30tgKmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pViqiJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_pViqiZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_AqMu8IaXEeSMzJufh3GDGA" path="_AhxzjoaXEeSMzJufh3GDGA/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_pVg1V5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_pVg1WJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_AhxzzYaXEeSMzJufh3GDGA" path="_AhxzjoaXEeSMzJufh3GDGA/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_AhxzzoaXEeSMzJufh3GDGA" path="_AhxzjoaXEeSMzJufh3GDGA/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxzz4aXEeSMzJufh3GDGA" path="_AhxzjoaXEeSMzJufh3GDGA/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_Ahxz0IaXEeSMzJufh3GDGA" path="_AhxzjoaXEeSMzJufh3GDGA/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_pVg1XZXdEeSroeU30tgKmw" name="sub_proposal" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pVg1XpXdEeSroeU30tgKmw" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_pVg1X5XdEeSroeU30tgKmw" name="sub_proposalOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pVg1YJXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_pVg1YZXdEeSroeU30tgKmw" name="sub_projectOK" dataType="_Ahxz_IaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pVg1YpXdEeSroeU30tgKmw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_pVg1Y5XdEeSroeU30tgKmw" name="sub_impacts" dataType="_Ahx0AYaXEeSMzJufh3GDGA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pVg1ZJXdEeSroeU30tgKmw" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pVg1ZZXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_pVg1ZpXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVg1Z5XdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pVg1aJXdEeSroeU30tgKmw" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxz3YaXEeSMzJufh3GDGA" target="_AhxzpoaXEeSMzJufh3GDGA" source="_AhxznIaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxz3oaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiTpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxz4IaXEeSMzJufh3GDGA" target="_AhxzsoaXEeSMzJufh3GDGA" source="_AhxzpoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxz4YaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVyiUJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxz44aXEeSMzJufh3GDGA" target="_AhxzvoaXEeSMzJufh3GDGA" source="_AhxzsoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxz5IaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVzJMJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxz5oaXEeSMzJufh3GDGA" target="_AhxzkIaXEeSMzJufh3GDGA" source="_AhxzvoaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxz54aXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVzJMpXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ahxz6YaXEeSMzJufh3GDGA" target="_AhxzoYaXEeSMzJufh3GDGA" source="_AhxzkIaXEeSMzJufh3GDGA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ahxz6oaXEeSMzJufh3GDGA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pVzJNJXdEeSroeU30tgKmw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Ahxz7IaXEeSMzJufh3GDGA" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxz7YaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_pV0XVpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pV0XV5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxz8IaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_pV0XWJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pV0XWZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxz84aXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_pV0XWpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pV0XW5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxz9oaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_pV0XXJXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pV0XXZXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ahxz-YaXEeSMzJufh3GDGA">
        <name xmi:type="expression:Expression" xmi:id="_pV0XXpXdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pV0XX5XdEeSroeU30tgKmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Ahxz_IaXEeSMzJufh3GDGA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Ahxz_YaXEeSMzJufh3GDGA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Ahxz_oaXEeSMzJufh3GDGA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Ahxz_4aXEeSMzJufh3GDGA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Ahx0AIaXEeSMzJufh3GDGA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Ahx0AYaXEeSMzJufh3GDGA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Ahx0AoaXEeSMzJufh3GDGA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Ahx0A4aXEeSMzJufh3GDGA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_pVcj5JXdEeSroeU30tgKmw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Ahx0BIaXEeSMzJufh3GDGA" type="Process" element="_AhxLsIaXEeSMzJufh3GDGA" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Ahx0BYaXEeSMzJufh3GDGA" type="2007" element="_AhxLsYaXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0BoaXEeSMzJufh3GDGA" type="5008" element="_AhxLsYaXEeSMzJufh3GDGA"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0B4aXEeSMzJufh3GDGA" type="7001" element="_AhxLsYaXEeSMzJufh3GDGA">
        <children xmi:type="notation:Node" xmi:id="_pV5P25XdEeSroeU30tgKmw" type="3007" element="_AhxLsoaXEeSMzJufh3GDGA">
          <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0CYaXEeSMzJufh3GDGA" type="5007" element="_AhxLsoaXEeSMzJufh3GDGA"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0CoaXEeSMzJufh3GDGA" type="7002" element="_AhxLsoaXEeSMzJufh3GDGA">
            <children xmi:type="notation:Shape" xmi:id="_Ahx0C4aXEeSMzJufh3GDGA" type="3005" element="_AhxLs4aXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FAJXdEeSroeU30tgKmw" type="5005" element="_AhxLs4aXEeSMzJufh3GDGA"/>
              <children xmi:type="notation:Shape" xmi:id="_Ahx0DYaXEeSMzJufh3GDGA" type="3043" element="_AhxLu4aXEeSMzJufh3GDGA" fontName="Sans">
                <children xmi:type="notation:DecorationNode" xmi:id="_pV7FA5XdEeSroeU30tgKmw" type="5055" element="_AhxLu4aXEeSMzJufh3GDGA">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0D4aXEeSMzJufh3GDGA" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0EIaXEeSMzJufh3GDGA"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0EYaXEeSMzJufh3GDGA" x="119" y="165"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0EoaXEeSMzJufh3GDGA" type="3002" element="_AhxMBIaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FBpXdEeSroeU30tgKmw" type="5024" element="_AhxMBIaXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0FIaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0FYaXEeSMzJufh3GDGA" x="40" y="179"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0FoaXEeSMzJufh3GDGA" type="3005" element="_AhxMCYaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FCZXdEeSroeU30tgKmw" type="5005" element="_AhxMCYaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0GIaXEeSMzJufh3GDGA" x="421" y="102"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0GYaXEeSMzJufh3GDGA" type="3005" element="_AhxMWIaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FC5XdEeSroeU30tgKmw" type="5005" element="_AhxMWIaXEeSMzJufh3GDGA"/>
              <children xmi:type="notation:Shape" xmi:id="_Ahx0G4aXEeSMzJufh3GDGA" type="3064" element="_AhxMYIaXEeSMzJufh3GDGA" fontName="Sans">
                <children xmi:type="notation:DecorationNode" xmi:id="_pV7FDpXdEeSroeU30tgKmw" type="5094" element="_AhxMYIaXEeSMzJufh3GDGA">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0HYaXEeSMzJufh3GDGA" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0HoaXEeSMzJufh3GDGA"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0H4aXEeSMzJufh3GDGA" x="556" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0IIaXEeSMzJufh3GDGA" type="3062" element="_AhxMt4aXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FEZXdEeSroeU30tgKmw" type="5090" element="_AhxMt4aXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0IoaXEeSMzJufh3GDGA" x="-1" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0I4aXEeSMzJufh3GDGA" x="508" y="227"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0JIaXEeSMzJufh3GDGA" type="3062" element="_AhxMvIaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FFJXdEeSroeU30tgKmw" type="5090" element="_AhxMvIaXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0JoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0J4aXEeSMzJufh3GDGA" x="1221" y="136"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0KIaXEeSMzJufh3GDGA" type="3062" element="_AhxMwYaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FF5XdEeSroeU30tgKmw" type="5090" element="_AhxMwYaXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0KoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0K4aXEeSMzJufh3GDGA" x="1012" y="226"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0LIaXEeSMzJufh3GDGA" type="3008" element="_AhxMxoaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FGpXdEeSroeU30tgKmw" type="5026" element="_AhxMxoaXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0LoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0L4aXEeSMzJufh3GDGA" x="689" y="105" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0MIaXEeSMzJufh3GDGA" type="3008" element="_AhxMy4aXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FHZXdEeSroeU30tgKmw" type="5026" element="_AhxMy4aXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0MoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0M4aXEeSMzJufh3GDGA" x="230" y="170" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0NIaXEeSMzJufh3GDGA" type="3027" element="_AhxM0IaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FIJXdEeSroeU30tgKmw" type="5017" element="_AhxM0IaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0NoaXEeSMzJufh3GDGA" x="271" y="95" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0N4aXEeSMzJufh3GDGA" type="3027" element="_AhxM2oaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FIpXdEeSroeU30tgKmw" type="5017" element="_AhxM2oaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0OYaXEeSMzJufh3GDGA" x="347" y="187" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0OoaXEeSMzJufh3GDGA" type="3027" element="_AhxM5IaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FJJXdEeSroeU30tgKmw" type="5017" element="_AhxM5IaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0PIaXEeSMzJufh3GDGA" x="765" y="192" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0PYaXEeSMzJufh3GDGA" type="3027" element="_AhxM7oaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FJpXdEeSroeU30tgKmw" type="5017" element="_AhxM7oaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0P4aXEeSMzJufh3GDGA" x="762" y="96" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0QIaXEeSMzJufh3GDGA" type="3027" element="_AhxM-IaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7FKJXdEeSroeU30tgKmw" type="5017" element="_AhxM-IaXEeSMzJufh3GDGA"/>
              <children xmi:type="notation:Shape" xmi:id="_uY5sYIaXEeSMzJufh3GDGA" type="3032" element="_uY4eQIaXEeSMzJufh3GDGA" fontName="Sans">
                <children xmi:type="notation:DecorationNode" xmi:id="_pV7FK5XdEeSroeU30tgKmw" type="5062" element="_uY4eQIaXEeSMzJufh3GDGA">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_uY6TcYaXEeSMzJufh3GDGA" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uY5sYYaXEeSMzJufh3GDGA"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0QoaXEeSMzJufh3GDGA" x="1041" y="90" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0Q4aXEeSMzJufh3GDGA" type="3063" element="_AhxNAoaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7sEZXdEeSroeU30tgKmw" type="5093" element="_AhxNAoaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0RYaXEeSMzJufh3GDGA" x="913" y="125"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0RoaXEeSMzJufh3GDGA" type="3027" element="_AhxNFoaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7sE5XdEeSroeU30tgKmw" type="5017" element="_AhxNFoaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0SIaXEeSMzJufh3GDGA" x="590" y="192"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0SYaXEeSMzJufh3GDGA" type="3003" element="_Ahxy7oaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7sFZXdEeSroeU30tgKmw" type="5025" element="_Ahxy7oaXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0S4aXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0TIaXEeSMzJufh3GDGA" x="714" y="227"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4_i68IaXEeSMzJufh3GDGA" type="3005" element="_4_iT4IaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7sGJXdEeSroeU30tgKmw" type="5005" element="_4_iT4IaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4_i68YaXEeSMzJufh3GDGA" x="1107" y="227" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Ahx0TYaXEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Ahx0ToaXEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Ahx0T4aXEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Ahx0UIaXEeSMzJufh3GDGA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0UYaXEeSMzJufh3GDGA" x="45" y="10" width="1383" height="342"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Ahx0UoaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ahx0U4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Ahx0VIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Ahx0VYaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0VoaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_Ahx0V4aXEeSMzJufh3GDGA" type="2007" element="_AhxzjoaXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0WIaXEeSMzJufh3GDGA" type="5008" element="_AhxzjoaXEeSMzJufh3GDGA"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0WYaXEeSMzJufh3GDGA" type="7001" element="_AhxzjoaXEeSMzJufh3GDGA">
        <children xmi:type="notation:Node" xmi:id="_pV5265XdEeSroeU30tgKmw" type="3007" element="_Ahxzj4aXEeSMzJufh3GDGA">
          <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0W4aXEeSMzJufh3GDGA" type="5007" element="_Ahxzj4aXEeSMzJufh3GDGA"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Ahx0XIaXEeSMzJufh3GDGA" type="7002" element="_Ahxzj4aXEeSMzJufh3GDGA">
            <children xmi:type="notation:Shape" xmi:id="_Ahx0XYaXEeSMzJufh3GDGA" type="3005" element="_AhxzkIaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7sGpXdEeSroeU30tgKmw" type="5005" element="_AhxzkIaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0X4aXEeSMzJufh3GDGA" x="597" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0YIaXEeSMzJufh3GDGA" type="3002" element="_AhxznIaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7sHJXdEeSroeU30tgKmw" type="5024" element="_AhxznIaXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0YoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0Y4aXEeSMzJufh3GDGA" x="84" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0ZIaXEeSMzJufh3GDGA" type="3062" element="_AhxzoYaXEeSMzJufh3GDGA" fontName="Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7sH5XdEeSroeU30tgKmw" type="5090" element="_AhxzoYaXEeSMzJufh3GDGA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ahx0ZoaXEeSMzJufh3GDGA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0Z4aXEeSMzJufh3GDGA" x="753" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0aIaXEeSMzJufh3GDGA" type="3005" element="_AhxzpoaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7sIpXdEeSroeU30tgKmw" type="5005" element="_AhxzpoaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0aoaXEeSMzJufh3GDGA" x="160" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0a4aXEeSMzJufh3GDGA" type="3005" element="_AhxzsoaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7sJJXdEeSroeU30tgKmw" type="5005" element="_AhxzsoaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0bYaXEeSMzJufh3GDGA" x="294" y="91" width="134" height="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ahx0boaXEeSMzJufh3GDGA" type="3005" element="_AhxzvoaXEeSMzJufh3GDGA" fontName="Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pV7sJpXdEeSroeU30tgKmw" type="5005" element="_AhxzvoaXEeSMzJufh3GDGA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0cIaXEeSMzJufh3GDGA" x="464" y="100"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Ahx0cYaXEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Ahx0coaXEeSMzJufh3GDGA" fontName="Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Ahx0c4aXEeSMzJufh3GDGA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Ahx0dIaXEeSMzJufh3GDGA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0dYaXEeSMzJufh3GDGA" x="231" y="176"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Ahx0doaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ahx0d4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Ahx0eIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Ahx0eYaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahx0eoaXEeSMzJufh3GDGA" width="1454" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Ahx0e4aXEeSMzJufh3GDGA"/>
    <edges xmi:type="notation:Connector" xmi:id="_Ahx0fIaXEeSMzJufh3GDGA" type="4001" element="_AhxzR4aXEeSMzJufh3GDGA" source="_Ahx0EoaXEeSMzJufh3GDGA" target="_Ahx0C4aXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-IUJXdEeSroeU30tgKmw" type="6001" element="_AhxzR4aXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-IUZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-IUpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ0oaXEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ04aXEeSMzJufh3GDGA" type="4001" element="_AhxzSoaXEeSMzJufh3GDGA" source="_Ahx0NIaXEeSMzJufh3GDGA" target="_Ahx0FoaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-IVJXdEeSroeU30tgKmw" type="6001" element="_AhxzSoaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-IVZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-IVpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ14aXEeSMzJufh3GDGA" points="[0, 1, -66, -7]$[16, 1, -50, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ2IaXEeSMzJufh3GDGA" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ2YaXEeSMzJufh3GDGA" type="4001" element="_AhxzTYaXEeSMzJufh3GDGA" source="_Ahx0FoaXEeSMzJufh3GDGA" target="_Ahx0GYaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-IWZXdEeSroeU30tgKmw" type="6001" element="_AhxzTYaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-IWpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-IW5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ3YaXEeSMzJufh3GDGA" points="[0, 0, -41, 91]$[-9, -91, -50, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ3oaXEeSMzJufh3GDGA" id="(1.0,0.64)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ34aXEeSMzJufh3GDGA" type="4001" element="_AhxzUIaXEeSMzJufh3GDGA" source="_Ahx0PYaXEeSMzJufh3GDGA" target="_Ahx0Q4aXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-IXpXdEeSroeU30tgKmw" type="6001" element="_AhxzUIaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-vYJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-vYZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ44aXEeSMzJufh3GDGA" points="[0, 0, -5, -60]$[55, 51, 50, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ5IaXEeSMzJufh3GDGA" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ5YaXEeSMzJufh3GDGA" type="4001" element="_AhxzU4aXEeSMzJufh3GDGA" source="_Ahx0Q4aXEeSMzJufh3GDGA" target="_Ahx0QIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-vZJXdEeSroeU30tgKmw" type="6001" element="_AhxzU4aXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-vZZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-vZpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ6YaXEeSMzJufh3GDGA" points="[0, 0, -60, 48]$[65, -35, 5, 13]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ6oaXEeSMzJufh3GDGA" id="(0.5583333333333333,0.7833333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ64aXEeSMzJufh3GDGA" type="4001" element="_AhxzVoaXEeSMzJufh3GDGA" source="_Ahx0N4aXEeSMzJufh3GDGA" target="_Ahx0IIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-vaZXdEeSroeU30tgKmw" type="6001" element="_AhxzVoaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-vapXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-va5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ74aXEeSMzJufh3GDGA" points="[0, -8, -85, 2]$[78, 3, -7, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ8IaXEeSMzJufh3GDGA" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ8YaXEeSMzJufh3GDGA" type="4001" element="_AhxzWYaXEeSMzJufh3GDGA" source="_Ahx0OoaXEeSMzJufh3GDGA" target="_Ahx0KIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-vbpXdEeSroeU30tgKmw" type="6001" element="_AhxzWYaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-vb5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-vcJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ9YaXEeSMzJufh3GDGA" points="[0, 0, -142, -15]$[135, 28, -7, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyZ9oaXEeSMzJufh3GDGA" id="(1.0,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ94aXEeSMzJufh3GDGA" type="4001" element="_AhxzXIaXEeSMzJufh3GDGA" source="_Ahx0C4aXEeSMzJufh3GDGA" target="_Ahx0MIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-vc5XdEeSroeU30tgKmw" type="6001" element="_AhxzXIaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-vdJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-vdZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyZ-4aXEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyZ_IaXEeSMzJufh3GDGA" type="4001" element="_AhxzX4aXEeSMzJufh3GDGA" source="_Ahx0MIaXEeSMzJufh3GDGA" target="_Ahx0NIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-vd5XdEeSroeU30tgKmw" type="6001" element="_AhxzX4aXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-veJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-veZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaAIaXEeSMzJufh3GDGA" points="[-11, -22, -51, 47]$[42, -57, 2, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaAYaXEeSMzJufh3GDGA" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaAoaXEeSMzJufh3GDGA" id="(0.5333333333333333,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaA4aXEeSMzJufh3GDGA" type="4001" element="_AhxzZIaXEeSMzJufh3GDGA" source="_Ahx0MIaXEeSMzJufh3GDGA" target="_Ahx0N4aXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-vfZXdEeSroeU30tgKmw" type="6001" element="_AhxzZIaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-vfpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-vf5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaB4aXEeSMzJufh3GDGA" points="[-14, 1, -91, 0]$[52, -2, -25, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaCIaXEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaCYaXEeSMzJufh3GDGA" id="(0.20833333333333334,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaCoaXEeSMzJufh3GDGA" type="4001" element="_AhxzZ4aXEeSMzJufh3GDGA" source="_Ahx0GYaXEeSMzJufh3GDGA" target="_Ahx0LIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-vg5XdEeSroeU30tgKmw" type="6001" element="_AhxzZ4aXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-vhJXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-vhZXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaDoaXEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaD4aXEeSMzJufh3GDGA" id="(0.97,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaEIaXEeSMzJufh3GDGA" type="4001" element="_AhxzaoaXEeSMzJufh3GDGA" source="_Ahx0LIaXEeSMzJufh3GDGA" target="_Ahx0PYaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-viJXdEeSroeU30tgKmw" type="6001" element="_AhxzaoaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-viZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-vipXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaFIaXEeSMzJufh3GDGA" points="[-11, -3, -65, 0]$[30, -1, -24, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaFYaXEeSMzJufh3GDGA" id="(1.0,0.813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaFoaXEeSMzJufh3GDGA" id="(0.025,0.18333333333333332)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaF4aXEeSMzJufh3GDGA" type="4001" element="_Ahxzb4aXEeSMzJufh3GDGA" source="_Ahx0LIaXEeSMzJufh3GDGA" target="_Ahx0OoaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-vjpXdEeSroeU30tgKmw" type="6001" element="_Ahxzb4aXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-vj5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-vkJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaG4aXEeSMzJufh3GDGA" points="[-4, -10, -40, -95]$[33, 84, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaHIaXEeSMzJufh3GDGA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaHYaXEeSMzJufh3GDGA" id="(0.025,0.4166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaHoaXEeSMzJufh3GDGA" type="4001" element="_AhxzcoaXEeSMzJufh3GDGA" source="_Ahx0QIaXEeSMzJufh3GDGA" target="_Ahx0JIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-vlJXdEeSroeU30tgKmw" type="6001" element="_AhxzcoaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-vlZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-vlpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaIoaXEeSMzJufh3GDGA" points="[0, 0, -75, -29]$[72, 14, -3, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaI4aXEeSMzJufh3GDGA" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaJIaXEeSMzJufh3GDGA" type="4001" element="_Ahxz3YaXEeSMzJufh3GDGA" source="_Ahx0YIaXEeSMzJufh3GDGA" target="_Ahx0aIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV-vmZXdEeSroeU30tgKmw" type="6001" element="_Ahxz3YaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV-vmpXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV-vm5XdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaKIaXEeSMzJufh3GDGA" points="[-7, -2, -57, 0]$[46, -1, -4, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaKYaXEeSMzJufh3GDGA" id="(0.9666666666666667,0.5333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaKoaXEeSMzJufh3GDGA" id="(0.05,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaK4aXEeSMzJufh3GDGA" type="4001" element="_Ahxz4IaXEeSMzJufh3GDGA" source="_Ahx0aIaXEeSMzJufh3GDGA" target="_Ahx0a4aXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV_WcJXdEeSroeU30tgKmw" type="6001" element="_Ahxz4IaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV_WcZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV_WcpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaL4aXEeSMzJufh3GDGA" points="[0, -5, -35, 0]$[34, -6, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaMIaXEeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaMYaXEeSMzJufh3GDGA" id="(0.007462686567164179,0.4925373134328358)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaMoaXEeSMzJufh3GDGA" type="4001" element="_Ahxz44aXEeSMzJufh3GDGA" source="_Ahx0a4aXEeSMzJufh3GDGA" target="_Ahx0boaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV_WdpXdEeSroeU30tgKmw" type="6001" element="_Ahxz44aXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV_Wd5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV_WeJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaNoaXEeSMzJufh3GDGA" points="[0, 1, -36, 0]$[36, 1, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaN4aXEeSMzJufh3GDGA" id="(1.0,0.4626865671641791)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaOIaXEeSMzJufh3GDGA" id="(0.0,0.46)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaOYaXEeSMzJufh3GDGA" type="4001" element="_Ahxz5oaXEeSMzJufh3GDGA" source="_Ahx0boaXEeSMzJufh3GDGA" target="_Ahx0XYaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV_WfJXdEeSroeU30tgKmw" type="6001" element="_Ahxz5oaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV_WfZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV_WfpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaPYaXEeSMzJufh3GDGA" points="[0, -6, -40, 0]$[33, -7, -7, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaPoaXEeSMzJufh3GDGA" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaP4aXEeSMzJufh3GDGA" id="(0.07,0.46)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaQIaXEeSMzJufh3GDGA" type="4001" element="_Ahxz6YaXEeSMzJufh3GDGA" source="_Ahx0XYaXEeSMzJufh3GDGA" target="_Ahx0ZIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV_WgpXdEeSroeU30tgKmw" type="6001" element="_Ahxz6YaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV_Wg5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV_WhJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaRIaXEeSMzJufh3GDGA" points="[0, -3, -59, 0]$[56, -3, -3, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaRYaXEeSMzJufh3GDGA" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaRoaXEeSMzJufh3GDGA" id="(0.1,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaR4aXEeSMzJufh3GDGA" type="4001" element="_AhxzdYaXEeSMzJufh3GDGA" source="_Ahx0DYaXEeSMzJufh3GDGA" target="_Ahx0N4aXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV_WiJXdEeSroeU30tgKmw" type="6001" element="_AhxzdYaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV_WiZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV_WipXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaS4aXEeSMzJufh3GDGA" points="[0, -1, -194, 0]$[187, 0, -7, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaTIaXEeSMzJufh3GDGA" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaTYaXEeSMzJufh3GDGA" id="(0.058333333333333334,0.7333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaToaXEeSMzJufh3GDGA" type="4001" element="_AhxzeIaXEeSMzJufh3GDGA" source="_Ahx0G4aXEeSMzJufh3GDGA" target="_Ahx0RoaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV_WjpXdEeSroeU30tgKmw" type="6001" element="_AhxzeIaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV_Wj5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV_WkJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaUoaXEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AhyaU4aXEeSMzJufh3GDGA" type="4001" element="_Ahxze4aXEeSMzJufh3GDGA" source="_Ahx0RoaXEeSMzJufh3GDGA" target="_Ahx0SYaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV_WkpXdEeSroeU30tgKmw" type="6001" element="_Ahxze4aXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV_Wk5XdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV_WlJXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AhyaV4aXEeSMzJufh3GDGA" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaWIaXEeSMzJufh3GDGA" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AhyaWYaXEeSMzJufh3GDGA" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3tF0kIaXEeSMzJufh3GDGA" type="4001" element="_3s8qoIaXEeSMzJufh3GDGA" source="_uY5sYIaXEeSMzJufh3GDGA" target="_4_i68IaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV_WmJXdEeSroeU30tgKmw" type="6001" element="_3s8qoIaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV_WmZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV_WmpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3tF0koaXEeSMzJufh3GDGA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_83W6AIaXEeSMzJufh3GDGA" type="4001" element="_83WS8IaXEeSMzJufh3GDGA" source="_4_i68IaXEeSMzJufh3GDGA" target="_Ahx0JIaXEeSMzJufh3GDGA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV_WnJXdEeSroeU30tgKmw" type="6001" element="_83WS8IaXEeSMzJufh3GDGA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pV_WnZXdEeSroeU30tgKmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pV_WnpXdEeSroeU30tgKmw" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_83W6AoaXEeSMzJufh3GDGA" points="[-42, -29, -51, 76]$[2, -92, -7, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_83YvMIaXEeSMzJufh3GDGA" id="(1.0,0.48333333333333334)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AhyaWoaXEeSMzJufh3GDGA" type="Form" element="_AhxzAoaXEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_AhyaW4aXEeSMzJufh3GDGA" type="2120" element="_AhxzA4aXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sKJXdEeSroeU30tgKmw" type="5157" element="_AhxzA4aXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyaXYaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_AhyaXoaXEeSMzJufh3GDGA" type="2126" element="_AhxzL4aXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaX4aXEeSMzJufh3GDGA" type="5160" element="_AhxzL4aXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AhyaYIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyaYYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AhyaYoaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyaY4aXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyaZIaXEeSMzJufh3GDGA" type="2131" element="_AhxzM4aXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sKpXdEeSroeU30tgKmw" type="5135" element="_AhxzM4aXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyaZoaXEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_AhyaZ4aXEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AhyaaIaXEeSMzJufh3GDGA" type="Form" element="_AhxLwYaXEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_AhyaaYaXEeSMzJufh3GDGA" type="2130" element="_AhxLwoaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sLJXdEeSroeU30tgKmw" type="5148" element="_AhxLwoaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahyaa4aXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_AhyabIaXEeSMzJufh3GDGA" type="2126" element="_AhxL8oaXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyabYaXEeSMzJufh3GDGA" type="5160" element="_AhxL8oaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AhyaboaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ahyab4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AhyacIaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyacYaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyacoaXEeSMzJufh3GDGA" type="2131" element="_AhxL9oaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sLpXdEeSroeU30tgKmw" type="5135" element="_AhxL9oaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyadIaXEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_AhyadYaXEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AhyadoaXEeSMzJufh3GDGA" type="Form" element="_AhxME4aXEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_Ahyad4aXEeSMzJufh3GDGA" type="2120" element="_AhxMFIaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sMJXdEeSroeU30tgKmw" type="5157" element="_AhxMFIaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyaeYaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_AhyaeoaXEeSMzJufh3GDGA" type="2126" element="_AhxMRIaXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahyae4aXEeSMzJufh3GDGA" type="5160" element="_AhxMRIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AhyafIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyafYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AhyafoaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahyaf4aXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyagIaXEeSMzJufh3GDGA" type="2131" element="_AhxMSIaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sMpXdEeSroeU30tgKmw" type="5135" element="_AhxMSIaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyagoaXEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Ahyag4aXEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AhyahIaXEeSMzJufh3GDGA" type="Form" element="_AhxMZIaXEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_AhyahYaXEeSMzJufh3GDGA" type="2130" element="_AhxMZYaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sNJXdEeSroeU30tgKmw" type="5148" element="_AhxMZYaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahyah4aXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_AhyaiIaXEeSMzJufh3GDGA" type="2126" element="_AhxMlYaXEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_AhyaiYaXEeSMzJufh3GDGA" type="5160" element="_AhxMlYaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AhyaioaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ahyai4aXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AhyajIaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyajYaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyajoaXEeSMzJufh3GDGA" type="2131" element="_AhxMmYaXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sNpXdEeSroeU30tgKmw" type="5135" element="_AhxMmYaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyakIaXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyakYaXEeSMzJufh3GDGA" type="2131" element="_AhxMp4aXEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sOJXdEeSroeU30tgKmw" type="5135" element="_AhxMp4aXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahyak4aXEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_AhyalIaXEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_AhyalYaXEeSMzJufh3GDGA" type="Form" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_AhyaloaXEeSMzJufh3GDGA" type="2126">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ahyal4aXEeSMzJufh3GDGA" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AhyamIaXEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_AhyamYaXEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AhyamoaXEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ahyam4aXEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AhyanIaXEeSMzJufh3GDGA" type="2131" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sOpXdEeSroeU30tgKmw" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AhyanoaXEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Ahyan4aXEeSMzJufh3GDGA"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_CO_tEIaYEeSMzJufh3GDGA" type="Form" element="_CO9Q0IaYEeSMzJufh3GDGA" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_CPsQoIaYEeSMzJufh3GDGA" type="2126" element="_CO9Q0YaYEeSMzJufh3GDGA">
      <children xmi:type="notation:DecorationNode" xmi:id="_CPsQpYaYEeSMzJufh3GDGA" type="5160" element="_CO9Q0YaYEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_CPsQoYaYEeSMzJufh3GDGA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_CPsQooaYEeSMzJufh3GDGA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_CPsQo4aYEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CPsQpIaYEeSMzJufh3GDGA"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_IIwVwIaYEeSMzJufh3GDGA" type="2131" element="_IIvHoIaYEeSMzJufh3GDGA" fontName="Sans">
      <children xmi:type="notation:DecorationNode" xmi:id="_pV7sPJXdEeSroeU30tgKmw" type="5135" element="_IIvHoIaYEeSMzJufh3GDGA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IIwVwYaYEeSMzJufh3GDGA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_CO_tEYaYEeSMzJufh3GDGA"/>
  </notation:Diagram>
</xmi:XMI>
